import path from "node:path";

export type QualityCaseMode = "balanced" | "selective" | "paired" | "widespread";

export type QualityCaseSpec = {
  key: string;
  fixturePath: string;
  mode: QualityCaseMode;
  suite?: "professor-five";
  expectedGlobalLevel: "Tipik" | "Riskli" | "Atipik";
  expectedProfileIncludes: string[];
  requiredPhrases?: string[];
  forbiddenPhrases?: string[];
  requireAgeMismatchWarning?: boolean;
  minLiteratureParagraphs?: number;
  minApaReferences?: number;
  requireProfessorDecisionFrame?: boolean;
  expectedVisibleConfidence?: "yüksek" | "orta-yüksek" | "orta" | "sınırlı";
};

function fixture(name: string): string {
  return path.resolve(process.cwd(), "scripts", "fixtures", name);
}

export const QUALITY_CASE_SPECS: QualityCaseSpec[] = [
  {
    key: "fully-typical",
    fixturePath: fixture("dna-fully-typical-development.json"),
    mode: "balanced",
    expectedGlobalLevel: "Tipik",
    expectedProfileIncludes: ["Dengeli / Korunmuş Profil"],
    forbiddenPhrases: ["birincil kırılgan alan", "yaygın regülasyon yükü", "yüksek klinik yük", "öz-düzenleme"],
    minLiteratureParagraphs: 3,
    minApaReferences: 3,
  },
  {
    key: "selective-interoception",
    fixturePath: fixture("dna-global-typical-selective-interoception.json"),
    mode: "selective",
    expectedGlobalLevel: "Tipik",
    expectedProfileIncludes: ["İnterosepsiyon", "Seçici"],
    requiredPhrases: ["seçici"],
    forbiddenPhrases: ["yaygın regülasyon yükü", "öz-düzenleme"],
    minLiteratureParagraphs: 3,
    minApaReferences: 3,
  },
  {
    key: "paired-sensory-emotional",
    fixturePath: fixture("dna-dual-sensory-emotional-overload.json"),
    mode: "paired",
    expectedGlobalLevel: "Riskli",
    expectedProfileIncludes: ["Duyusal-Duygusal"],
    requiredPhrases: ["Duyusal Regülasyon", "Duygusal Regülasyon"],
    minLiteratureParagraphs: 3,
    minApaReferences: 4,
  },
  {
    key: "widespread-executive",
    fixturePath: fixture("dna-adhd-executive-load.json"),
    mode: "widespread",
    expectedGlobalLevel: "Riskli",
    expectedProfileIncludes: ["Yürütücü İşlev Öncelikli", "Regülasyon Profili"],
    forbiddenPhrases: ["seçici bir kırılganlık"],
    minLiteratureParagraphs: 3,
    minApaReferences: 4,
  },
  {
    key: "widespread-adaptive",
    fixturePath: fixture("dna-adaptive-daily-living.json"),
    mode: "widespread",
    expectedGlobalLevel: "Riskli",
    expectedProfileIncludes: ["Fizyolojik Toparlanma", "Regülasyon Güçlüğü"],
    forbiddenPhrases: ["seçici bir kırılganlık"],
    minLiteratureParagraphs: 3,
    minApaReferences: 4,
  },
  {
    key: "age-mismatch-warning",
    fixturePath: fixture("dna-age-mismatch-warning.json"),
    mode: "selective",
    expectedGlobalLevel: "Tipik",
    expectedProfileIncludes: ["Yürütücü İşlev", "Seçici"],
    requireAgeMismatchWarning: true,
    requiredPhrases: ["ana klinik değerlendirmeyi desteklemez"],
    minLiteratureParagraphs: 3,
    minApaReferences: 4,
  },
  {
    key: "item-linkage",
    fixturePath: fixture("dna-item-level-linkage.json"),
    mode: "paired",
    expectedGlobalLevel: "Atipik",
    expectedProfileIncludes: ["Duyusal"],
    requiredPhrases: ["Ölçek yanıt örüntüsü", "Ses ve arka plan gürültüsü"],
    minLiteratureParagraphs: 3,
    minApaReferences: 4,
  },
  {
    key: "motor-praxis-supported",
    fixturePath: fixture("dna-new-06-somatodyspraxia-motor-planning.json"),
    mode: "widespread",
    expectedGlobalLevel: "Riskli",
    expectedProfileIncludes: ["Motor Planlama", "Beden Organizasyonu", "Regülasyon Güçlüğü"],
    requiredPhrases: ["motor planlama", "görev"],
    minLiteratureParagraphs: 3,
    minApaReferences: 4,
  },
  {
    key: "multi-test-single-axis",
    fixturePath: fixture("dna-language-pragmatic-load.json"),
    mode: "widespread",
    expectedGlobalLevel: "Riskli",
    expectedProfileIncludes: ["Dilsel", "Sosyal-Pragmatik", "Regülasyon Güçlüğü"],
    requiredPhrases: ["dilsel", "sosyal"],
    minLiteratureParagraphs: 3,
    minApaReferences: 4,
  },
  {
    key: "format-tscore-briefp",
    fixturePath: fixture("dna-format-briefp-tscore-clinical.json"),
    mode: "widespread",
    expectedGlobalLevel: "Riskli",
    expectedProfileIncludes: ["Yürütücü", "Regülasyon Profili"],
    requiredPhrases: ["T skoru", "Ek test bulguları"],
    minLiteratureParagraphs: 3,
    minApaReferences: 4,
  },
  {
    key: "format-percentile-adaptive",
    fixturePath: fixture("dna-format-pedicat-percentile-adaptive.json"),
    mode: "widespread",
    expectedGlobalLevel: "Riskli",
    expectedProfileIncludes: ["Günlük Yaşam", "Öz Bakım", "Regülasyon Güçlüğü"],
    requiredPhrases: ["percentil", "PEDI-CAT", "Ek test bulguları"],
    minLiteratureParagraphs: 3,
    minApaReferences: 4,
  },
  {
    key: "format-standard-score-motor",
    fixturePath: fixture("dna-format-pdms3-standard-score-motor.json"),
    mode: "widespread",
    expectedGlobalLevel: "Riskli",
    expectedProfileIncludes: ["Motor", "Regülasyon Güçlüğü"],
    requiredPhrases: ["standart skoru", "PDMS-3", "motor planlama"],
    minLiteratureParagraphs: 3,
    minApaReferences: 4,
  },
  {
    key: "format-age-equivalent-language",
    fixturePath: fixture("dna-format-pls-age-equivalent-language.json"),
    mode: "paired",
    expectedGlobalLevel: "Riskli",
    expectedProfileIncludes: ["Dilsel", "Regülasyon Güçlüğü"],
    requiredPhrases: ["yaş eşdeğeri", "PLS-5", "sözel talep"],
    minLiteratureParagraphs: 3,
    minApaReferences: 4,
  },
  {
    key: "format-preserved-adaptive",
    fixturePath: fixture("dna-format-preserved-vineland-abas.json"),
    mode: "balanced",
    expectedGlobalLevel: "Tipik",
    expectedProfileIncludes: ["Dengeli / Korunmuş Profil"],
    requiredPhrases: ["korunmuş", "Vineland-3", "ABAS-3"],
    forbiddenPhrases: ["yüksek klinik yük", "yaygın regülasyon yükü", "öz-düzenleme"],
    minLiteratureParagraphs: 3,
    minApaReferences: 3,
  },
  {
    key: "evidence-limited-mixed-raw-preserved",
    fixturePath: fixture("dna-evidence-limited-mixed-raw-preserved.json"),
    mode: "paired",
    expectedGlobalLevel: "Riskli",
    expectedProfileIncludes: ["Geçiş", "Ko-Regülasyon"],
    requiredPhrases: [
      "bağlama göre değişen",
      "Aileden gelen bilgiye göre",
      "Terapist gözleminde",
      "Ham puan tek başına yorum gücünü sınırlar",
      "Korunmuş/yaş uyumlu sonuç"
    ],
    forbiddenPhrases: ["Beden-temelli toparlanma ve interoseptif düzenleme yükü", "Günlük yaşam ve öz bakım akışını sürdürme yükü", "öz-düzenleme"],
    minLiteratureParagraphs: 3,
    minApaReferences: 4,
  },
  {
    key: "format-mixed-language-social",
    fixturePath: fixture("dna-format-mixed-multi-test.json"),
    mode: "widespread",
    expectedGlobalLevel: "Riskli",
    expectedProfileIncludes: ["Dilsel", "Sosyal-Pragmatik", "Regülasyon Güçlüğü"],
    requiredPhrases: ["standart skoru", "T skoru", "ölçek puanı"],
    minLiteratureParagraphs: 3,
    minApaReferences: 4,
  },
  {
    key: "prof-01-selective-sensory-context",
    fixturePath: fixture("dna-prof-01-selective-sensory-context.json"),
    suite: "professor-five",
    mode: "selective",
    expectedGlobalLevel: "Tipik",
    expectedProfileIncludes: ["Duyusal", "Seçici"],
    requiredPhrases: ["uyaran", "korunmuş"],
    forbiddenPhrases: ["yaygın regülasyon yükü", "genellenmiş kapasite düşüklüğü"],
    minLiteratureParagraphs: 3,
    minApaReferences: 3,
    requireProfessorDecisionFrame: true,
    expectedVisibleConfidence: "orta-yüksek",
  },
  {
    key: "prof-02-cross-source-conflict",
    fixturePath: fixture("dna-prof-02-cross-source-conflict.json"),
    suite: "professor-five",
    mode: "widespread",
    expectedGlobalLevel: "Riskli",
    expectedProfileIncludes: ["Bağlama Duyarlı", "Regülasyon Profili"],
    requiredPhrases: ["kaynaklar arası", "bağlam"],
    forbiddenPhrases: ["kesin olarak", "tek başına kanıtlar"],
    minLiteratureParagraphs: 3,
    minApaReferences: 4,
    requireProfessorDecisionFrame: true,
    expectedVisibleConfidence: "orta",
  },
  {
    key: "prof-03-severe-sparse-evidence",
    fixturePath: fixture("dna-prof-03-severe-sparse-evidence.json"),
    suite: "professor-five",
    mode: "widespread",
    expectedGlobalLevel: "Atipik",
    expectedProfileIncludes: ["Yaygın", "Çok Alanlı"],
    requiredPhrases: ["sınırlı", "genellenebilir"],
    forbiddenPhrases: ["yüksek veri güveni", "kesin olarak"],
    minLiteratureParagraphs: 3,
    minApaReferences: 4,
    requireProfessorDecisionFrame: true,
    expectedVisibleConfidence: "sınırlı",
  },
  {
    key: "prof-04-executive-context-contrast",
    fixturePath: fixture("dna-prof-04-executive-context-contrast.json"),
    suite: "professor-five",
    mode: "widespread",
    expectedGlobalLevel: "Riskli",
    expectedProfileIncludes: ["Yürütücü İşlev Öncelikli", "Regülasyon Profili"],
    requiredPhrases: ["çalışma belleği", "görsel"],
    forbiddenPhrases: ["genel öğrenme kapasitesi düşüklüğü", "itaat eksikliği"],
    minLiteratureParagraphs: 3,
    minApaReferences: 4,
    requireProfessorDecisionFrame: true,
    expectedVisibleConfidence: "orta-yüksek",
  },
  {
    key: "prof-05-preserved-scale-external-concern",
    fixturePath: fixture("dna-prof-05-preserved-scale-external-concern.json"),
    suite: "professor-five",
    mode: "balanced",
    expectedGlobalLevel: "Tipik",
    expectedProfileIncludes: ["Dengeli", "Korunmuş"],
    requiredPhrases: ["ayrış", "hedefli"],
    forbiddenPhrases: ["belirgin bir sorun yoktur", "tanıyı doğrular"],
    minLiteratureParagraphs: 3,
    minApaReferences: 3,
    requireProfessorDecisionFrame: true,
    expectedVisibleConfidence: "orta",
  },
];
