import {
  DNA_CHAT_CATALOG_VERSION,
  type DnaChatCatalogClaim,
} from "./types"

function claim(
  input: Omit<
    DnaChatCatalogClaim,
    "version" | "safetyStatus" | "sourceVerified"
  >,
): DnaChatCatalogClaim {
  return Object.freeze({
    version: DNA_CHAT_CATALOG_VERSION,
    safetyStatus: "safe" as const,
    sourceVerified: true as const,
    ...input,
  })
}

export const DNA_CHAT_CATALOG_CLAIMS: readonly DnaChatCatalogClaim[] = Object.freeze([
  claim({
    id: "claim.selfreg.multicomponent",
    topicId: "selfreg.core",
    text: "Self-regülasyon tek bir beceri değil; hedefe ve bağlama göre işleyen çok bileşenli bir süreç ailesidir.",
    detail: "Dikkat, duygu, davranış, bilişsel kontrol ve bedensel uyarılma süreçleri farklı ölçüm düzeylerinde incelenebilir; tek puan bunların tümünü açıklamaz.",
    sourceIds: ["NIGG_2017", "INZLICHT_ET_AL_2021", "BLAIR_RAVER_2015"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.selfreg.contextual",
    topicId: "selfreg.core",
    text: "Self-regülasyon performansı talep, çevresel yapı, yorgunluk, motivasyon ve sosyal destekle değişebilir.",
    detail: "Gözlenen davranış değişmez bir iç kapasite olarak değil, kişi ile bağlamın etkileşimi içinde değerlendirilir.",
    sourceIds: ["BLAIR_RAVER_2015", "INZLICHT_ET_AL_2021"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "association",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.selfcontrol.distinction",
    topicId: "selfreg.self_control",
    text: "Self-kontrol, self-regülasyonun tamamı değil; dürtü veya kısa vadeli tepkiyi daha uzun vadeli amaç doğrultusunda yönetmeye odaklanan daha dar bir kavramdır.",
    detail: "Terimler bazı literatürlerde farklı kullanılsa da katalog self-regülasyonu üst şemsiye, self-kontrolü onun daha dar bir bileşeni olarak tanımlar.",
    sourceIds: ["NIGG_2017", "INZLICHT_ET_AL_2021"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.ef.components",
    topicId: "selfreg.executive_functions",
    text: "Yürütücü işlevler ketleyici kontrol, çalışma belleği ve bilişsel esneklik gibi birbiriyle ilişkili kontrol süreçlerini kapsar.",
    detail: "Bu bileşenler günlük görevlerde birlikte çalışabilir; ancak yürütücü işlev, self-regülasyonun tüm sosyal, duygusal ve fizyolojik yönleriyle aynı değildir.",
    sourceIds: ["DIAMOND_2013", "NIGG_2017"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.coregulation.support",
    topicId: "selfreg.coregulation",
    text: "Ko-regülasyon, kişinin düzenlemesinin başka bir kişi ve çevresel yapı tarafından desteklenmesini anlatır.",
    detail: "Özellikle erken gelişimde bakımveren desteği önemlidir; ilişki karşılıklıdır ve tek yönlü biyolojik neden olarak sunulamaz.",
    sourceIds: ["ROSANBALM_MURRAY_2017", "BLAIR_RAVER_2015"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "development",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.reactivity.recovery",
    topicId: "selfreg.reactivity_recovery",
    text: "Reaktivite ilk tepkinin hız ve yoğunluğunu, toparlanma ise zorlanma sonrasında daha dengeli işleyişe dönüş sürecini betimler.",
    detail: "İki boyut aynı değildir; güçlü ilk tepki her zaman uzun toparlanma anlamına gelmez ve her ikisi bağlama duyarlıdır.",
    sourceIds: ["BLAIR_RAVER_2015"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.selfreg.development",
    topicId: "selfreg.development",
    text: "Self-regülasyon erken çocukluk boyunca gelişir; gelişim hızı ve görünümü kişiler ve görevler arasında değişir.",
    detail: "Uzunlamasına grup eğilimleri tek çocuk için kesin gelişim çizgisi veya prognoz oluşturmaz.",
    sourceIds: ["MONTROY_ET_AL_2016", "BLAIR_RAVER_2015"],
    evidenceLevel: "strong",
    ageScope: "early_childhood",
    claimType: "development",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.selfreg.outcomes",
    topicId: "selfreg.development",
    text: "Çocukluk self-regülasyonu sonraki işlevsel sonuçlarla grup düzeyinde ilişkilidir, fakat bireysel kaderi belirlemez.",
    detail: "Meta-analitik ilişkiler ölçüm ve bağlam açısından heterojendir; korelasyon nedensellik veya DNA geçerliği değildir.",
    sourceIds: ["ROBSON_ET_AL_2020"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "association",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.cns.overview",
    topicId: "cns.overview",
    text: "Merkezi sinir sistemi beyin ve omurilikten oluşur; duyusal, motor, bilişsel ve düzenleyici süreçlerin geniş anatomik zeminidir.",
    detail: "Self-regülasyon merkezi sinir sistemindeki tek bir yapı veya merkezle açıklanamaz.",
    sourceIds: ["FRIEDMAN_ROBBINS_2022", "SAPER_2002"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.cns.distributed",
    topicId: "cns.distributed_networks",
    text: "Bilişsel, duygusal, interoseptif ve otonom düzenleme dağıtık ve etkileşen ağların katkısıyla yürür.",
    detail: "Bir bölgenin çok sayıda sürece, bir sürecin de çok sayıda bölge ve ağa bağlı olması bireysel lokalizasyonu sınırlar.",
    sourceIds: ["FRIEDMAN_ROBBINS_2022", "QUADT_ET_AL_2022", "FERRARO_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimType: "mechanism",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.insula.multifunction",
    topicId: "cns.insula",
    text: "İnsular korteks içsel beden sinyalleri, duygulanım, önem belirleme ve ağlar arası geçişle ilişkili çok işlevli bir kortikal bölgedir.",
    detail: "İnsula tek bir interosepsiyon veya duygu merkezi değildir; alt bölgeleri ve bağlantıları farklı işlevlere katkı verir.",
    sourceIds: ["MENON_UDDIN_2010", "FERRARO_ET_AL_2022", "CRITCHLEY_HARRISON_2013"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.insula.boundary",
    topicId: "cns.insula",
    text: "Davranışsal veya ölçek temelli bir profilden 'insula zayıf çalışıyor' sonucu çıkarılamaz.",
    detail: "Bu sonuç tersine çıkarım olur; beyin bölgesi işlevi için uygun nörogörüntüleme tasarımı gerekir ve o durumda bile bireysel yorum sınırlıdır.",
    sourceIds: ["POLDRAK_2006", "MENON_UDDIN_2010"],
    evidenceLevel: "boundary",
    ageScope: "all_ages",
    claimType: "measurement_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.salience.network",
    topicId: "cns.salience_network",
    text: "Salience ağı, iç veya dış olayların davranışsal önemini ağırlıklandırma ve diğer ağlar arasındaki geçişe katkı veren dağıtık bir ağdır.",
    detail: "Ön insula ve singulat bölgeler önemli düğümlerdir; ağ tek bir işlev veya sabit alarm durumu olarak yorumlanamaz.",
    sourceIds: ["SEELEY_2019", "MENON_UDDIN_2010"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.can.network",
    topicId: "cns.central_autonomic_network",
    text: "Merkezi otonom ağ, visseral bilgiyi bütünleştiren ve otonom çıktının bağlama göre düzenlenmesine katkı veren dağıtık merkezi devreleri anlatır.",
    detail: "İnsula, singulat, hipotalamik, amigdalar ve beyin sapı bölgeleri ağın farklı tanımlarında yer alabilir.",
    sourceIds: ["SAPER_2002", "LAMOTTE_ET_AL_2021", "FERRARO_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.can.boundary",
    topicId: "cns.central_autonomic_network",
    text: "DNA veya davranış gözlemi merkezi otonom ağ etkinliğini doğrudan ölçmez.",
    detail: "CAN açıklaması yalnız genel teori bağlamıdır; kişiye özgü ağ işlevi, hasar veya mekanizma sonucu üretilemez.",
    sourceIds: ["POLDRAK_2006", "FERRARO_ET_AL_2022"],
    evidenceLevel: "boundary",
    ageScope: "all_ages",
    claimType: "product_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.pfc.control",
    topicId: "cns.prefrontal_control",
    text: "Prefrontal bölgeler yürütücü kontrol ve hedefe yönelik davranışta önemli katkılar sağlar, ancak bu işlevleri tek başına yürütmez.",
    detail: "Kontrol performansı prefrontal, parietal, striatal ve diğer ağların etkileşimiyle ilişkilidir.",
    sourceIds: ["FRIEDMAN_ROBBINS_2022", "DIAMOND_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "mechanism",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.reverse_inference",
    topicId: "cns.reverse_inference",
    text: "Tersine çıkarım, gözlenen davranış veya beyin etkinliğinden tek ve özgül bir bilişsel süreç ya da patoloji sonucu üretme hatasıdır.",
    detail: "Aynı bölgenin farklı süreçlere katılması ve aynı sürecin dağıtık ağlara dayanması bu çıkarımı sınırlar.",
    sourceIds: ["POLDRAK_2006"],
    evidenceLevel: "boundary",
    ageScope: "all_ages",
    claimType: "misconception_correction",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.ans.overview",
    topicId: "ans.overview",
    text: "Otonom sinir sistemi kalp, damar, terleme, pupil, sindirim ve diğer iç organ süreçlerinin koşullara göre ayarlanmasına katılır.",
    detail: "Merkezi ve periferik devreler, visseral geri bildirim ve organ-özgül mekanizmalar birlikte çalışır.",
    sourceIds: ["WEHRWEIN_ET_AL_2016", "SAPER_2002"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.ans.not_personality",
    topicId: "ans.overview",
    text: "Bir kişiyi bütün olarak 'sempatik' veya 'parasempatik' diye sınıflamak fizyolojik olarak aşırı basitleştiricidir.",
    detail: "Otonom örüntüler organ, bağlam ve zaman ölçeğine göre değişir.",
    sourceIds: ["BERNTSON_ET_AL_1991", "WEHRWEIN_ET_AL_2016"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "misconception_correction",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.homeostasis.definition",
    topicId: "ans.homeostasis",
    text: "Homeostaz, iç değişkenlerin geri bildirim süreçleriyle işlevsel aralıklarda tutulmasını anlatır.",
    detail: "Sabit ve hareketsiz bir denge değil, sürekli düzenlenen dinamik bir süreçtir.",
    sourceIds: ["RAMSAY_WOODS_2014"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.allostasis.definition",
    topicId: "ans.allostasis",
    text: "Allostaz, değişen taleplere uyum için fizyolojik düzenlemenin bağlama ve beklenen ihtiyaca göre ayarlanmasını vurgulayan kuramsal çerçevedir.",
    detail: "Allostaz bir DNA skoru veya tek bir laboratuvar ölçümü değildir; allostatik yük de tek davranıştan çıkarılamaz.",
    sourceIds: ["RAMSAY_WOODS_2014", "MCEWEN_1998"],
    evidenceLevel: "theoretical",
    ageScope: "mixed",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.hrv.definition",
    topicId: "ans.hrv",
    text: "Kalp hızı değişkenliği, ardışık kalp atımları arasındaki zaman aralıklarının değişkenliğidir.",
    detail: "HRV doğrudan kaydedilen kardiyak zaman serisinden hesaplanır; ANS'nin tamamı, beyin işlevi veya self-regülasyonun doğrudan ölçümü değildir.",
    sourceIds: ["TASK_FORCE_HRV_1996", "LABORDE_ET_AL_2017"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "definition",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.hrv.association",
    topicId: "ans.hrv",
    text: "Bazı HRV ölçütleri ile self-regülasyon veya adaptif işlev arasında grup düzeyinde ilişkiler bildirilmiştir.",
    detail: "İlişkiler yöntem, yaş ve göreve göre heterojendir; düşük HRV tek kişide bozukluk, neden veya düşük DNA alanı anlamına gelmez.",
    sourceIds: ["GRAZIANO_DEREFINKO_2013", "LABORDE_ET_AL_2017"],
    evidenceLevel: "moderate",
    ageScope: "mixed",
    claimType: "association",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.hrv.measurement_boundary",
    topicId: "ans.hrv",
    text: "HRV, doğrudan kaydedilen kardiyak atımlar arası zaman serisinden hesaplanır; ANS'nin tamamını veya self-regülasyonu doğrudan ölçmez.",
    detail: "Solunum, kalp hızı, kayıt süresi, postür, hareket ve analiz yöntemi yorumu etkileyebilir; DNA puanı HRV yerine geçmez.",
    sourceIds: ["TASK_FORCE_HRV_1996", "LABORDE_ET_AL_2017"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.hrv.lfhf",
    topicId: "ans.hrv",
    text: "LF/HF oranı küresel bir sempatik-parasempatik denge göstergesi olarak güvenle yorumlanamaz.",
    detail: "HRV bileşenleri solunum, kalp hızı, kayıt süresi ve başka fizyolojik etkenlere duyarlıdır.",
    sourceIds: ["BILLMAN_2013", "LABORDE_ET_AL_2017"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "measurement_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.eda.definition",
    topicId: "ans.eda",
    text: "Elektrodermal aktivite, ter bezlerinin sempatik sinirsel kontrolüyle ilişkili deri iletkenliği değişimlerinin ölçümüdür.",
    detail: "EDA uyarılma ve dikkatle değişebilir; tek başına belirli bir duygu, neden veya tanı göstermez.",
    sourceIds: ["BOUCSEIN_ET_AL_2012"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "definition",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.eda.sensory",
    topicId: "ans.eda",
    text: "Çocuklarda duyusal uyaranlara verilen EDA örüntüleri üzerine kanıt sınırlı ve heterojendir.",
    detail: "Küçük veya seçilmiş örneklemlerden duyusal davranışın otonom nedeni ya da tanısal sınıfı çıkarılamaz.",
    sourceIds: ["CHRISTENSEN_ET_AL_2020", "MCINTOSH_ET_AL_1999"],
    evidenceLevel: "limited",
    ageScope: "childhood",
    claimType: "association",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.interoception.multidimensional",
    topicId: "ans.interoception",
    text: "İnterosepsiyon, iç beden sinyallerinin algılanması, bütünleştirilmesi, yorumlanması ve düzenleyici kullanımıyla ilgili çok boyutlu süreçlerdir.",
    detail: "Görev performansı, öz-bildirim eğilimi ve metabilişsel farkındalık aynı şey değildir.",
    sourceIds: ["KHALSA_ET_AL_2018", "GARFINKEL_ET_AL_2015"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.interoception.emotion",
    topicId: "ans.interoception",
    text: "İnterosepsiyon ve duygu düzenleme arasında ilişki adayları vardır, ancak yön ve mekanizma kişiye özgü olarak belirlenemez.",
    detail: "Kanıt yetişkin ağırlıklı ve yöntemsel olarak heterojendir; ilişki nedensellik değildir.",
    sourceIds: ["PINNA_EDWARDS_2020", "KHALSA_ET_AL_2018"],
    evidenceLevel: "moderate",
    ageScope: "adult_weighted",
    claimType: "association",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.ans.development",
    topicId: "ans.development",
    text: "Otonom göstergeler çocukluk boyunca yaş, büyüme, solunum, aktivite ve ölçüm protokolüyle değişebilir.",
    detail: "Yaşa özgü grup değerleri başka protokollere veya DNA puanlarına doğrudan çevrilemez.",
    sourceIds: ["GASIOR_ET_AL_2018", "WHEDON_ET_AL_2018"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "development",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.sympathetic.parasympathetic",
    topicId: "ans.sympathetic_parasympathetic",
    text: "Sempatik ve parasempatik süreçler günlük uyum için birlikte çalışan otonom bileşenlerdir; biri evrensel olarak kötü, diğeri iyi değildir.",
    detail: "Etkileri hedef organa, zamana ve bağlama göre değişir; 'savaş/kaç' ile 'dinlen/sindir' yalnız kaba öğretici kısaltmalardır.",
    sourceIds: ["WEHRWEIN_ET_AL_2016", "BERNTSON_ET_AL_1991"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "misconception_correction",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.autonomic.space",
    topicId: "ans.autonomic_space",
    text: "Sempatik ve parasempatik etkinlik karşılıklı değişim, eşzamanlı etkinleşme, eşzamanlı baskılanma veya bağımsız değişim örüntüleri gösterebilir.",
    detail: "Bu otonom uzam çerçevesi küresel bir tahterevalli modelinin yetersizliğini açıklar; kişiye özgü organ örüntüsünü davranıştan belirlemez.",
    sourceIds: ["BERNTSON_ET_AL_1991", "DAMPNEY_2016"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "mechanism",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.ans.measurement",
    topicId: "ans.measurement_limits",
    text: "Kalp hızı, HRV, EDA, pupil ve diğer ölçümler otonom işlevin farklı parçalarına ilişkin bilgi verir; hiçbiri tek başına bütün ANS'yi ölçmez.",
    detail: "Her sinyalin kayıt protokolü, artefaktları ve fizyolojik özgüllüğü farklıdır; davranış gözlemi bu ölçümlerin yerine geçmez.",
    sourceIds: ["TASK_FORCE_HRV_1996", "BOUCSEIN_ET_AL_2012", "MATHOT_2018"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "measurement_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.polyvagal.status",
    topicId: "ans.polyvagal",
    text: "Polivagal teori etkili bir kuramsal çerçevedir, ancak bazı anatomik ve fizyolojik öncülleri bilimsel tartışma konusudur.",
    detail: "Teori savunucu ve eleştirel kaynaklarla birlikte sunulmalı; yerleşik ve tartışmasız fizyoloji gibi anlatılmamalıdır.",
    sourceIds: ["PORGES_2021", "GROSSMAN_2023"],
    evidenceLevel: "theoretical",
    ageScope: "mixed",
    claimType: "misconception_correction",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.polyvagal.boundary",
    topicId: "ans.polyvagal",
    text: "Davranış gözleminden 'dorsal vagal kapanma', 'ventral vagal durum' veya kişisel vagal ton atanamaz.",
    detail: "Bu etiketler DNA raporu veya sohbet yanıtında biyolojik ölçüm gibi kullanılmamalıdır.",
    sourceIds: ["GROSSMAN_2023", "LABORDE_ET_AL_2017"],
    evidenceLevel: "boundary",
    ageScope: "all_ages",
    claimType: "product_boundary",
    dnaRelation: "none",
  }),
])

export const DNA_CHAT_CATALOG_CLAIM_BY_ID = new Map(
  DNA_CHAT_CATALOG_CLAIMS.map((entry) => [entry.id, entry]),
)
