import {
  DNA_CHAT_CATALOG_VERSION,
  type DnaChatCatalogClaim,
} from "./types"
import { V5_CASE_BOUNDARY_CLAIMS } from "./v5CaseBoundariesCatalog"
import { V5_COREGULATION_CLAIMS } from "./v5CoregulationCatalog"
import { V5_DEVELOPMENT_CLAIMS } from "./v5DevelopmentCatalog"
import { V5_SIX_DOMAINS_CLAIMS } from "./v5SixDomainsCatalog"

function claim(
  input: Omit<
    DnaChatCatalogClaim,
    "version" | "safetyStatus" | "sourceVerified"
  >,
): DnaChatCatalogClaim {
  return Object.freeze({
    version: DNA_CHAT_CATALOG_VERSION,
    safetyStatus: "safe" as const,
    sourceVerified: true as const,
    ...input,
  })
}

export const DNA_CHAT_CATALOG_CLAIMS: readonly DnaChatCatalogClaim[] = Object.freeze([
  claim({
    id: "claim.selfreg.multicomponent",
    topicId: "selfreg.core",
    text: "Self-regülasyon tek bir beceri değil; hedefe ve bağlama göre işleyen çok bileşenli bir süreç ailesidir.",
    detail: "Dikkat, duygu, davranış, bilişsel kontrol ve bedensel uyarılma süreçleri farklı ölçüm düzeylerinde incelenebilir; tek puan bunların tümünü açıklamaz.",
    sourceIds: ["NIGG_2017", "INZLICHT_ET_AL_2021", "BLAIR_RAVER_2015"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.selfreg.contextual",
    topicId: "selfreg.core",
    text: "Self-regülasyon performansı talep, çevresel yapı, yorgunluk, motivasyon ve sosyal destekle değişebilir.",
    detail: "Gözlenen davranış değişmez bir iç kapasite olarak değil, kişi ile bağlamın etkileşimi içinde değerlendirilir.",
    sourceIds: ["BLAIR_RAVER_2015", "INZLICHT_ET_AL_2021"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "association",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.selfreg.not_fixed_trait",
    topicId: "selfreg.core",
    text: "Self-regülasyon yetişkinlikte de bağlamdan bağımsız, tamamen sabit bir özellik değildir.",
    detail: "Talep, çevresel yapı, yorgunluk, motivasyon ve sosyal destek aynı kişide gözlenen performansı değiştirebilir.",
    sourceIds: ["BLAIR_RAVER_2015", "INZLICHT_ET_AL_2021"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "misconception_correction",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.selfcontrol.distinction",
    topicId: "selfreg.self_control",
    text: "Self-kontrol, self-regülasyonun tamamı değil; dürtü veya kısa vadeli tepkiyi daha uzun vadeli amaç doğrultusunda yönetmeye odaklanan daha dar bir kavramdır.",
    detail: "Terimler bazı literatürlerde farklı kullanılsa da katalog self-regülasyonu üst şemsiye, self-kontrolü onun daha dar bir bileşeni olarak tanımlar.",
    sourceIds: ["NIGG_2017", "INZLICHT_ET_AL_2021"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.ef.components",
    topicId: "selfreg.executive_functions",
    text: "Yürütücü işlevler ketleyici kontrol, çalışma belleği ve bilişsel esneklik gibi birbiriyle ilişkili kontrol süreçlerini kapsar.",
    detail: "Bu bileşenler günlük görevlerde birlikte çalışabilir; ancak yürütücü işlev, self-regülasyonun tüm sosyal, duygusal ve fizyolojik yönleriyle aynı değildir.",
    sourceIds: ["DIAMOND_2013", "NIGG_2017"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.ef.development",
    topicId: "selfreg.executive_functions",
    text: "Ketleyici kontrol, çalışma belleği ve bilişsel esneklik çocukluk boyunca gelişir; bileşenler aynı hızda veya tek bir yaşta olgunlaşmaz.",
    detail: "Okul çağındaki görev talepleri bu süreçleri daha görünür kılabilir, ancak yaş tek başına bireysel kapasite veya olgunluk ölçüsü değildir.",
    sourceIds: ["DIAMOND_2013", "NIGG_2017"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "development",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.coregulation.support",
    topicId: "selfreg.coregulation",
    text: "Ko-regülasyon, kişinin düzenlemesinin başka bir kişi ve çevresel yapı tarafından desteklenmesini anlatır.",
    detail: "Özellikle erken gelişimde bakımveren desteği önemlidir; ilişki karşılıklıdır ve tek yönlü biyolojik neden olarak sunulamaz.",
    sourceIds: ["ROSANBALM_MURRAY_2017", "BLAIR_RAVER_2015"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "development",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.reactivity.recovery",
    topicId: "selfreg.reactivity_recovery",
    text: "Reaktivite ilk tepkinin hız ve yoğunluğunu, toparlanma ise zorlanma sonrasında daha dengeli işleyişe dönüş sürecini betimler.",
    detail: "İki boyut aynı değildir; güçlü ilk tepki her zaman uzun toparlanma anlamına gelmez ve her ikisi bağlama duyarlıdır.",
    sourceIds: ["BLAIR_RAVER_2015"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.arousal.multicomponent",
    topicId: "selfreg.arousal",
    text: "Uyarılma tek bir iç seviye değil; uyanıklık, dikkat hazırlığı, motor etkinlik ve fizyolojik değişimler gibi kısmen ayrışabilen bileşenleri olan durum ailesidir.",
    detail: "Farklı yöntemler uyarılmanın farklı katmanlarına duyarlıdır; tek davranış veya tek sinyal bütün uyarılmayı temsil etmez.",
    sourceIds: ["ASTON_JONES_COHEN_2005", "BURT_OBRADOVIC_2013", "BATES_ET_AL_2022"],
    evidenceLevel: "moderate",
    ageScope: "mixed",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.arousal.contextual",
    topicId: "selfreg.arousal",
    text: "Uyarılmanın işlevsel etkisi görev, zamanlama, kişi ve çevresel talebe göre değişir; herkes için geçerli tek bir ideal düzey yoktur.",
    detail: "Yetişkin ve hayvan ağırlıklı optimal performans modelleri çocukta davranıştan kişisel eşik veya mekanizma belirlemek için kullanılamaz.",
    sourceIds: ["ASTON_JONES_COHEN_2005", "BATES_ET_AL_2022"],
    evidenceLevel: "moderate",
    ageScope: "mixed",
    claimType: "misconception_correction",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.reactivity.components",
    topicId: "selfreg.reactivity_recovery",
    text: "Reaktivite değerlendirmesinde taban düzeyi, değişim büyüklüğü, tepkinin başlama gecikmesi, zirvesi ve süresi ayrı bileşenlerdir.",
    detail: "Aynı büyüklükte görünen iki tepki farklı başlangıç düzeyi veya zaman seyrine sahip olabilir.",
    sourceIds: ["BURT_OBRADOVIC_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "measurement_boundary",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.reactivity.measurement_layers",
    topicId: "selfreg.reactivity_recovery",
    text: "Davranışsal, öz-bildirimli ve fizyolojik reaktivite göstergeleri farklı ölçüm katmanlarıdır ve bire bir örtüşmeleri beklenmez.",
    detail: "Özellikle erken çocukluk çalışmalarında yöntemler ve davranış-fizyoloji ilişkileri heterojendir.",
    sourceIds: ["BURT_OBRADOVIC_2013", "SACREY_ET_AL_2021", "BATES_ET_AL_2022"],
    evidenceLevel: "moderate",
    ageScope: "early_childhood",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.reactivity.recovery_distinction",
    topicId: "selfreg.reactivity_recovery",
    text: "Reaktivite ile toparlanma ayrıdır: güçlü veya hızlı bir ilk tepki tek başına uzun ya da yetersiz toparlanma anlamına gelmez.",
    detail: "İlk değişim ile zaman içindeki dönüş farklı parametreler ve zaman pencereleriyle değerlendirilmelidir.",
    sourceIds: ["BURT_OBRADOVIC_2013", "COLE_ET_AL_2004", "COLE_ET_AL_2020"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.recovery.trajectory",
    topicId: "selfreg.reactivity_recovery",
    text: "Toparlanma tek bir son durum değil; tepkinin zirvesinden sonra zaman içinde değişen bir yörüngedir.",
    detail: "Başlangıç düzeyi, dönüş eğimi, süre, görevin devamı ve dış destek yorumun parçasıdır.",
    sourceIds: ["BURT_OBRADOVIC_2013", "COLE_ET_AL_2020", "JONES_MASON_ET_AL_2018"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.recovery.no_universal_duration",
    topicId: "selfreg.recovery_measurement",
    text: "Bütün yaşlar, görevler ve göstergeler için geçerli tek bir normal toparlanma süresi yoktur.",
    detail: "Toparlanma süresi başlangıç düzeyi, stresörün sürmesi, ölçülen sistem, örnekleme aralığı ve bağlama göre değişir.",
    sourceIds: ["BURT_OBRADOVIC_2013", "JONES_MASON_ET_AL_2018", "COLE_ET_AL_2020"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "measurement_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.recovery.system_divergence",
    topicId: "selfreg.recovery_measurement",
    text: "Davranış, kalp hızı, HRV/RSA, EDA ve hormonal göstergeler aynı hızda veya aynı yönde toparlanmayabilir.",
    detail: "Bir katmandaki bazale dönüş başka bir sistemin toparlandığını kanıtlamaz.",
    sourceIds: ["SACREY_ET_AL_2021", "JONES_MASON_ET_AL_2018", "BATES_ET_AL_2022"],
    evidenceLevel: "moderate",
    ageScope: "early_childhood",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.recovery.no_single_biomarker",
    topicId: "selfreg.recovery_measurement",
    text: "Toparlanmayı bütün bağlamlarda temsil eden tek bir biyobelirteç yoktur.",
    detail: "Yorum seçilen göstergenin fizyolojik kapsamı, kayıt protokolü ve zaman penceresiyle sınırlıdır; DNA puanı biyobelirteç yerine geçmez.",
    sourceIds: ["BURT_OBRADOVIC_2013", "SACREY_ET_AL_2021", "FISHER_ET_AL_2018"],
    evidenceLevel: "boundary",
    ageScope: "mixed",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.selforganization.definition",
    topicId: "selfreg.self_organization",
    text: "Öz-örgütlenme, düzenli davranış ve gelişim örüntülerinin çok sayıda bileşenin zaman içindeki etkileşiminden ortaya çıkmasını anlatır.",
    detail: "Dinamik sistem çerçevesi tek bir merkezi yönetici veya tek yönlü neden varsaymadan kişi, görev ve çevre etkileşimini inceler.",
    sourceIds: ["SMITH_THELEN_2003", "COLE_ET_AL_2020"],
    evidenceLevel: "theoretical",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.selforganization.boundary",
    topicId: "selfreg.self_organization",
    text: "Öz-örgütlenme doğrudan ölçülen tek bir beyin süreci, tanı veya sabit kişilik özelliği değildir.",
    detail: "Kuramsal kavram tek vakada gizli mekanizma, bozukluk veya prognoz olarak kullanılamaz.",
    sourceIds: ["SMITH_THELEN_2003", "FISHER_ET_AL_2018"],
    evidenceLevel: "boundary",
    ageScope: "all_ages",
    claimType: "misconception_correction",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.habituation.definition",
    topicId: "selfreg.habituation",
    text: "Habituasyon, yinelenen bir uyarana verilen tepkinin belirli davranışsal ölçütlere göre azalmasıdır.",
    detail: "Tepkinin kendiliğinden geri gelmesi, uyarana özgüllük ve başka klasik ölçütler tepki azalmasının basit yorgunluktan ayrılmasına yardım eder.",
    sourceIds: ["RANKIN_ET_AL_2009"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.habituation.distinction",
    topicId: "selfreg.habituation",
    text: "Habituasyon; reseptör düzeyindeki duyusal adaptasyon, motor yorgunluk ve bütün sistemlerin toparlanmasıyla aynı değildir.",
    detail: "Gözlenen tepki azalması genel duyusal kapasite, sorunun sona ermesi veya her bağlama genellenen alışma anlamına gelmez.",
    sourceIds: ["RANKIN_ET_AL_2009"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "misconception_correction",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.sensory.definition",
    topicId: "selfreg.sensory_modulation",
    text: "Duyusal modülasyon, duyusal girdiye verilen davranışsal yanıtın yoğunluk, süre ve bağlam açısından günlük işleve uyarlanmasını betimleyen işlevsel şemsiye kavramdır.",
    detail: "Terim kaynaklar ve araçlar arasında farklı operasyonelleştirilebilir; tek, doğrudan ölçülen nörolojik filtre değildir.",
    sourceIds: ["DUNN_2001", "WATKYNS_ET_AL_2024"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.sensory.patterns",
    topicId: "selfreg.sensory_modulation",
    text: "Duyusal aşırı yanıtlılık, düşük yanıtlılık ve duyusal arayış günlük davranışı betimleyen örüntülerdir; tek başlarına tanı değildir.",
    detail: "Aynı davranış dikkat, duyu kaybı, yorgunluk, motor kapasite, anlama veya bağlam gibi farklı etkenlerle ilişkili olabilir.",
    sourceIds: ["DUNN_2001", "WATKYNS_ET_AL_2024"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "misconception_correction",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.sensory.dunn_boundary",
    topicId: "selfreg.sensory_modulation",
    text: "Dunn modelindeki düşük kayıt, arayış, hassasiyet ve kaçınma kadranları kuramsal eşik ile yanıt stratejisini birleştirir.",
    detail: "Davranış anketinden hesaplanan kuramsal eşik, psikofizik veya sinir sistemindeki biyolojik eşik değildir.",
    sourceIds: ["DUNN_2001"],
    evidenceLevel: "moderate",
    ageScope: "mixed",
    claimType: "measurement_boundary",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.sensory.multimethod",
    topicId: "selfreg.sensory_measurement",
    text: "Bakımveren bildirimi, yapılandırılmış gözlem ve performans temelli duyusal yöntemler farklı veri katmanları sağlar.",
    detail: "Araçların yapı ve psikometrik destekleri heterojendir; farklı yöntemlerin ayrışması otomatik olarak birinin yanlış olduğu anlamına gelmez.",
    sourceIds: ["WATKYNS_ET_AL_2024"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.sensory.physiology_boundary",
    topicId: "selfreg.sensory_measurement",
    text: "Çocuklarda duyusal davranış ile otonom ölçümler arasındaki kanıt heterojen ve sonuçsuzdur; birinden diğeri çıkarılamaz.",
    detail: "Duyusal kaçınma sempatik aktivasyon, düşük kayıt vagal yetersizlik veya bir ölçek puanı sinir sistemi durumu anlamına gelmez.",
    sourceIds: ["GOMEZ_ET_AL_2017", "WATKYNS_ET_AL_2024"],
    evidenceLevel: "limited",
    ageScope: "childhood",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.emotion.definition",
    topicId: "selfreg.emotion_regulation",
    text: "Duygu düzenleme, duygunun ortaya çıkışını, yoğunluğunu, süresini, ifadesini veya hedefle ilişkili kullanımını etkileyen çok aşamalı süreçlerdir.",
    detail: "Düzenleme kişiler arası destek, dikkat, bilişsel değerlendirme, davranış ve çevre düzenlemesi gibi farklı yollar içerebilir.",
    sourceIds: ["COLE_ET_AL_2004", "GROSS_2015"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.emotion.reactivity_distinction",
    topicId: "selfreg.emotion_regulation",
    text: "Duygusal reaktivite ile duygu düzenleme ilişkili fakat ayrı yapılardır.",
    detail: "İlk tepkinin yoğunluğu veya hızı, tepkinin hedef ve bağlama göre zaman içinde nasıl değiştirildiğini tek başına göstermez.",
    sourceIds: ["COLE_ET_AL_2004", "REITSEMA_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.emotion.not_calmness",
    topicId: "selfreg.emotion_regulation",
    text: "Duygu düzenleme yalnızca duyguyu azaltmak veya dışarıdan sakin görünmek değildir.",
    detail: "Bazı hedeflerde duyguyu sürdürmek, artırmak, ifade etmek veya destek istemek işlevsel olabilir; yorum bağlama dayanmalıdır.",
    sourceIds: ["GROSS_2015", "COLE_ET_AL_2004"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "misconception_correction",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.emotion.strategy_context",
    topicId: "selfreg.emotion_strategies",
    text: "Bir duygu düzenleme stratejisinin işlevi hedef, zamanlama, gelişim düzeyi ve bağlama göre değişir; evrensel iyi veya kötü tek strateji yoktur.",
    detail: "Aynı strateji farklı durumlarda farklı sonuçlarla ilişkili olabilir; esneklik repertuar, seçim ve geri bildirimle güncellemeyi içerir.",
    sourceIds: ["GROSS_2015", "BONANNO_BURTON_2013"],
    evidenceLevel: "moderate",
    ageScope: "adult_weighted",
    claimType: "misconception_correction",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.emotion.flexibility_boundary",
    topicId: "selfreg.emotion_strategies",
    text: "Düzenleme esnekliği tek bir stratejinin sık kullanılması değil, bağlamı okuyup yanıtı gerektiğinde değiştirebilme çerçevesidir.",
    detail: "Yetişkin ağırlıklı bulgular çocuk için kişiselleştirilmiş strateji veya müdahale reçetesi değildir.",
    sourceIds: ["BONANNO_BURTON_2013", "GROSS_2015"],
    evidenceLevel: "moderate",
    ageScope: "adult_weighted",
    claimType: "measurement_boundary",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.emotion.multimethod",
    topicId: "selfreg.emotion_measurement",
    text: "Duygu düzenleme anket, gözlem, deneysel görev ve günlük yaşamda tekrarlı ölçümle farklı bileşenler üzerinden incelenir.",
    detail: "Yöntemler aynı yapıyı aynı zaman ölçeğinde ölçmez; evrensel tek bir altın standart yoktur.",
    sourceIds: ["COLE_ET_AL_2004", "MAZEFSKY_ET_AL_2021", "REITSEMA_ET_AL_2022"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.emotion.measurement_boundary",
    topicId: "selfreg.emotion_measurement",
    text: "Duygu düzenleme ölçek puanı tanı, düzenleyici niyet, beyin bölgesi veya fizyolojik mekanizmayı doğrudan ölçmez.",
    detail: "Yoğunluk, değişkenlik, atalet ve reaktivite gibi ölçütler ayrıdır; örnekleme ve bağlam sonucu etkiler.",
    sourceIds: ["MAZEFSKY_ET_AL_2021", "REITSEMA_ET_AL_2022", "POLDRAK_2006"],
    evidenceLevel: "boundary",
    ageScope: "developmental",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.selfreg.development",
    topicId: "selfreg.development",
    text: "Self-regülasyon erken çocukluk boyunca gelişir; gelişim hızı ve görünümü kişiler ve görevler arasında değişir.",
    detail: "Uzunlamasına grup eğilimleri tek çocuk için kesin gelişim çizgisi veya prognoz oluşturmaz.",
    sourceIds: ["MONTROY_ET_AL_2016", "BLAIR_RAVER_2015"],
    evidenceLevel: "strong",
    ageScope: "early_childhood",
    claimType: "development",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.selfreg.outcomes",
    topicId: "selfreg.development",
    text: "Çocukluk self-regülasyonu sonraki işlevsel sonuçlarla grup düzeyinde ilişkilidir, fakat bireysel kaderi belirlemez.",
    detail: "Meta-analitik ilişkiler ölçüm ve bağlam açısından heterojendir; korelasyon nedensellik veya DNA geçerliği değildir.",
    sourceIds: ["ROBSON_ET_AL_2020"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "association",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.cns.overview",
    topicId: "cns.overview",
    text: "Merkezi sinir sistemi beyin ve omurilikten oluşur; duyusal, motor, bilişsel ve düzenleyici süreçlerin geniş anatomik zeminidir.",
    detail: "Self-regülasyon merkezi sinir sistemindeki tek bir yapı veya merkezle açıklanamaz.",
    sourceIds: ["FRIEDMAN_ROBBINS_2022", "SAPER_2002"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.cns.distributed",
    topicId: "cns.distributed_networks",
    text: "Bilişsel, duygusal, interoseptif ve otonom düzenleme dağıtık ve etkileşen ağların katkısıyla yürür.",
    detail: "Bir bölgenin çok sayıda sürece, bir sürecin de çok sayıda bölge ve ağa bağlı olması bireysel lokalizasyonu sınırlar.",
    sourceIds: ["FRIEDMAN_ROBBINS_2022", "QUADT_ET_AL_2022", "FERRARO_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimType: "mechanism",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.cns.not_single_center",
    topicId: "cns.distributed_networks",
    text: "Merkezi sinir sisteminde self-regülasyonu tek başına yöneten tek bir merkez yoktur.",
    detail: "Bilişsel, duygusal, interoseptif ve otonom katkılar dağıtık ağlar ve beden-çevre etkileşimi içinde birlikte işler.",
    sourceIds: ["FRIEDMAN_ROBBINS_2022", "QUADT_ET_AL_2022", "FERRARO_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimType: "misconception_correction",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.insula.multifunction",
    topicId: "cns.insula",
    text: "İnsular korteks iç beden sinyalleri, duygulanım, önem belirleme, duyusal bütünleştirme ve ağlar arası geçişle ilişkili çok işlevli bir kortikal bölgedir.",
    detail: "İnsula tek bir interosepsiyon, duygu, tat veya ağrı merkezi değildir; alt bölgeleri ve bağlantıları farklı işlevlere katkı verir.",
    sourceIds: ["UDDIN_ET_AL_2017", "KURTH_ET_AL_2010", "MENON_UDDIN_2010", "CRITCHLEY_HARRISON_2013"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.insula.anatomical_gradients",
    topicId: "cns.insula",
    text: "İnsulada ön-arka ve bağlantısallık temelli işlevsel eğilimler vardır; bunlar keskin ve tek işlevli bölmeler değildir.",
    detail: "Alt bölge sınırları atlas, görev ve yöntemle değişebilir; aynı alt bölge birden fazla sürece katılabilir.",
    sourceIds: ["UDDIN_ET_AL_2017", "KURTH_ET_AL_2010"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimType: "mechanism",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.insula.boundary",
    topicId: "cns.insula",
    text: "Davranışsal veya ölçek temelli bir profilden 'insula zayıf çalışıyor' sonucu çıkarılamaz.",
    detail: "Bu sonuç tersine çıkarım olur; beyin bölgesi işlevi için uygun nörogörüntüleme tasarımı gerekir ve o durumda bile bireysel yorum sınırlıdır.",
    sourceIds: ["POLDRAK_2006", "MENON_UDDIN_2010"],
    evidenceLevel: "boundary",
    ageScope: "all_ages",
    claimType: "measurement_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.insula.subregions",
    topicId: "cns.insula_subregions",
    text: "Arka insula somatoduyusal-visseral temsil, ön insula ise çoklu bilgiyi bütünleştirme ve önem işleme ağlarıyla daha sık ilişkilendirilir.",
    detail: "Bu ifade grup düzeyi işlevsel eğilimdir; anterior ve posterior bölümler birbirinden yalıtılmış modüller değildir.",
    sourceIds: ["UDDIN_ET_AL_2017", "KURTH_ET_AL_2010"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimType: "association",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.insula.subregion_boundary",
    topicId: "cns.insula_subregions",
    text: "Bir davranışın veya öz-bildirimin belirli bir insula alt bölgesini gösterdiği söylenemez.",
    detail: "Böyle bir sonuç, çok işlevli ve dağıtık ağ bulgularından bireysel bölgesel işlev çıkarmaya yönelik tersine çıkarım olur.",
    sourceIds: ["POLDRAK_2006", "UDDIN_ET_AL_2017"],
    evidenceLevel: "boundary",
    ageScope: "all_ages",
    claimType: "measurement_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.insula.measurement_methods",
    topicId: "cns.insula_measurement",
    text: "İnsulanın yapısal ve işlevsel özellikleri, nörogörüntüleme derlemeleri ve görev tabanlı fMRI meta-analizleriyle incelenir.",
    detail: "Bu çalışmalar grup düzeyinde yapı, BOLD etkinliği veya aktivasyon örüntüleri sağlar; doğrudan nöral çıktı, tekil işlev ya da bireysel kapasite ölçümü değildir.",
    sourceIds: ["UDDIN_ET_AL_2017", "KURTH_ET_AL_2010", "SCHULZ_2016"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.insula.measurement_boundary",
    topicId: "cns.insula_measurement",
    text: "BOLD aktivasyonu, davranış veya öz-bildirim insulanın bütün işlevlerinin doğrudan ölçümü değildir.",
    detail: "Görev, karşılaştırma koşulu, atlas ve analiz seçimi yorumu sınırlar; DNA insula aktivitesi, hacmi veya bağlantısallığı ölçmez.",
    sourceIds: ["POLDRAK_2006", "SCHULZ_2016"],
    evidenceLevel: "boundary",
    ageScope: "all_ages",
    claimType: "measurement_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.insula.development_boundary",
    topicId: "cns.insula_development",
    text: "Mevcut pediatrik interosepsiyon ölçümleri ve yetişkin-ağırlıklı insula bulguları, bir çocuk için insula olgunluk normu sağlamaz.",
    detail: "Pediatrik interosepsiyon ölçümleri doğrudan insula gelişim ölçümü değildir; günlük davranıştan olgunluk, gecikme veya bölgesel zayıflık sonucu üretilemez.",
    sourceIds: ["ADDABBO_MILANI_2025", "UDDIN_ET_AL_2017", "POLDRAK_2006"],
    evidenceLevel: "boundary",
    ageScope: "childhood",
    claimType: "development",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.salience.network",
    topicId: "cns.salience_network",
    text: "Salience ağı, iç veya dış olayların davranışsal önemini ağırlıklandırma ve diğer ağlar arasındaki geçişe katkı veren dağıtık bir ağdır.",
    detail: "Ön insula ve singulat bölgeler önemli düğümlerdir; ağ tek bir işlev veya sabit alarm durumu olarak yorumlanamaz.",
    sourceIds: ["SEELEY_2019", "MENON_UDDIN_2010"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.can.network",
    topicId: "cns.central_autonomic_network",
    text: "Merkezi otonom ağ, visseral bilgiyi bütünleştiren ve otonom çıktının bağlama göre düzenlenmesine katkı veren dağıtık merkezi devreleri anlatır.",
    detail: "İnsula, singulat, hipotalamik, amigdalar ve beyin sapı bölgeleri ağın farklı tanımlarında yer alabilir.",
    sourceIds: ["SAPER_2002", "LAMOTTE_ET_AL_2021", "FERRARO_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.can.boundary",
    topicId: "cns.central_autonomic_network",
    text: "DNA veya davranış gözlemi merkezi otonom ağ etkinliğini doğrudan ölçmez.",
    detail: "CAN açıklaması yalnız genel teori bağlamıdır; kişiye özgü ağ işlevi, hasar veya mekanizma sonucu üretilemez.",
    sourceIds: ["POLDRAK_2006", "FERRARO_ET_AL_2022"],
    evidenceLevel: "boundary",
    ageScope: "all_ages",
    claimType: "product_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.pfc.control",
    topicId: "cns.prefrontal_control",
    text: "Prefrontal bölgeler yürütücü kontrol ve hedefe yönelik davranışta önemli katkılar sağlar, ancak bu işlevleri tek başına yürütmez.",
    detail: "Kontrol performansı prefrontal, parietal, striatal ve diğer ağların etkileşimiyle ilişkilidir; prefrontal korteks tek bir yönetici merkez değildir.",
    sourceIds: ["MILLER_COHEN_2001", "FRIEDMAN_ROBBINS_2022", "DIAMOND_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "mechanism",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.pfc.heterogeneity",
    topicId: "cns.prefrontal_control",
    text: "Prefrontal korteks anatomik ve bağlantısal açıdan heterojendir; alt bölgeler farklı görevlerde farklı ağırlıklarla katkı verir.",
    detail: "Dorsolateral, ventrolateral, medial ve orbital etiketler yararlı anatomik çerçevelerdir, ancak tek işlevli kutular değildir.",
    sourceIds: ["KOLK_RAKIC_2022", "MILLER_COHEN_2001"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.pfc.boundary",
    topicId: "cns.prefrontal_control",
    text: "Günlük yürütücü davranıştan prefrontal korteksin zayıf, hasarlı veya gelişmemiş olduğu sonucu çıkarılamaz.",
    detail: "Davranış çok sayıda ağ, görev ve bağlam etkeninin ortak ürünüdür; DNA bir beyin görüntüleme veya nöropsikolojik tanı aracı değildir.",
    sourceIds: ["POLDRAK_2006", "FRIEDMAN_ROBBINS_2022"],
    evidenceLevel: "boundary",
    ageScope: "all_ages",
    claimType: "product_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.pfc.development",
    topicId: "cns.prefrontal_development",
    text: "Prefrontal yapılar ve bağlantılar çocukluk ile ergenlik boyunca değişir; gelişim tekdüze değildir ve tek yaşta tamamlanmaz.",
    detail: "Alt bölgeler, bağlantılar ve farklı kontrol görevleri birbirinden farklı gelişim çizgileri gösterebilir.",
    sourceIds: ["KOLK_RAKIC_2022", "FISKE_HOLMBOE_2019"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "development",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.pfc.development_boundary",
    topicId: "cns.prefrontal_development",
    text: "Grup düzeyi prefrontal gelişim bulguları bir çocuğun olgunluk düzeyi veya geleceği için bireysel ölçüm değildir.",
    detail: "Gözlenen davranıştan prefrontal olgunluk yaşı, gelişimsel gecikme veya prognoz çıkarılamaz.",
    sourceIds: ["KOLK_RAKIC_2022", "POLDRAK_2006"],
    evidenceLevel: "boundary",
    ageScope: "developmental",
    claimType: "product_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.working_memory.definition",
    topicId: "cns.working_memory",
    text: "Çalışma belleği amaçla ilgili bilgiyi kısa süre etkin tutma ve gerektiğinde bu bilgi üzerinde işlem yapma süreçlerini kapsar.",
    detail: "Çalışma belleği dikkat ve bilişsel kontrolle birlikte çalışan dağıtık bir süreçtir; tek bir depo veya tek bölge değildir.",
    sourceIds: ["MILLER_COHEN_2001", "DIAMOND_2013", "FRIEDMAN_ROBBINS_2022"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.working_memory.boundary",
    topicId: "cns.working_memory",
    text: "Tek görevde düşük performans veya günlük unutkanlık sabit çalışma belleği kapasitesi ya da prefrontal sorun göstermez.",
    detail: "Talimatı anlama, dil, dikkat, motivasyon, yorgunluk ve görev yapısı performansı etkileyebilir.",
    sourceIds: ["DIAMOND_2013", "TOPLAK_ET_AL_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.inhibitory_control.definition",
    topicId: "cns.inhibitory_control",
    text: "Ketleyici kontrol baskın veya otomatik bir tepkiyi bağlamsal hedef doğrultusunda durdurma, erteleme ya da değiştirme süreçlerini kapsar.",
    detail: "Tepki ketleme ve dikkat dağıtıcıyı bastırma ilişkili fakat özdeş olmayan görev talepleridir.",
    sourceIds: ["DIAMOND_2013", "FISKE_HOLMBOE_2019"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.inhibitory_control.development",
    topicId: "cns.inhibitory_control",
    text: "Ketleyici kontrol çocukluk boyunca gelişir ve görev zorluğu ile çevresel desteğe duyarlıdır.",
    detail: "Grup düzeyi gelişim eğilimleri bir çocuğun tek davranışından değişmez kapasite veya biyolojik olgunluk sonucu üretmez.",
    sourceIds: ["FISKE_HOLMBOE_2019", "DIAMOND_2013"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "development",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.cognitive_flexibility.definition",
    topicId: "cns.cognitive_flexibility",
    text: "Bilişsel esneklik kural, strateji, dikkat odağı veya bakış açısını değişen talebe göre güncelleyebilme süreçlerini kapsar.",
    detail: "Çalışma belleği ve ketleyici kontrolle ilişkilidir fakat bu süreçlerle aynı değildir.",
    sourceIds: ["DIAMOND_2013", "FRIEDMAN_ROBBINS_2022"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.cognitive_flexibility.context",
    topicId: "cns.cognitive_flexibility",
    text: "Bilişsel esneklik performansı görev, dil, belirsizlik, motivasyon ve bağlama göre değişebilir.",
    detail: "Bir bağlamdaki katılık tüm ortamlara, tanıya veya tek bir beyin mekanizmasına genellenemez.",
    sourceIds: ["DIAMOND_2013"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "association",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.ef.measurement_distinction",
    topicId: "cns.executive_measurement",
    text: "Yürütücü işlev performans görevleri ile günlük davranış derecelendirmeleri ilişkili fakat aynı olmayan bilgi düzeyleri sağlar.",
    detail: "Görevler yapılandırılmış koşuldaki en iyi performansı, derecelendirmeler ise günlük bağlamlardaki tipik davranışı farklı hata kaynaklarıyla örnekleyebilir.",
    sourceIds: ["TOPLAK_ET_AL_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "measurement_boundary",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.ef.measurement_boundary",
    topicId: "cns.executive_measurement",
    text: "Tek test, ölçek veya DNA alanı yürütücü işlevlerin tamamını ya da prefrontal beyin işlevini ölçmez.",
    detail: "Sonuçlar ölçüm yöntemi, görev koşulu, değerlendirici ve günlük bağlamla birlikte yorumlanmalıdır.",
    sourceIds: ["TOPLAK_ET_AL_2013", "POLDRAK_2006"],
    evidenceLevel: "boundary",
    ageScope: "all_ages",
    claimType: "product_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.acc.heterogeneity",
    topicId: "cns.anterior_cingulate",
    text: "Anterior singulat korteks tek bir kontrol veya duygu merkezi değil, alt bölge ve bağlantıları farklı süreçlere katılan heterojen bir bölge ailesidir.",
    detail: "Performans izleme, önem değerlendirme, duygulanım ve bedensel ayarlama bulguları görev ve ağ bağlamına göre farklılaşır.",
    sourceIds: ["BUSH_ET_AL_2000", "HEILBRONNER_HAYDEN_2016"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.acc.naming_boundary",
    topicId: "cns.anterior_cingulate",
    text: "Dorsal ACC ve anterior midcingulate terimleri literatürde her zaman aynı anatomik sınırla kullanılmaz.",
    detail: "Kaynakların atlası ve terminolojisi açıkça belirtilmeden iki etiket tam eş anlamlı kabul edilmemelidir.",
    sourceIds: ["HEILBRONNER_HAYDEN_2016", "BUSH_ET_AL_2000"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimType: "misconception_correction",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.acc.not_single_center",
    topicId: "cns.anterior_cingulate",
    text: "ACC tek bir hata, duygu, ağrı veya self-regülasyon merkezi değildir.",
    detail: "ACC alt bölgeleri performans izleme, önem değerlendirme, duygulanım ve bedensel ayarlamalara dağıtık ağlar içinde farklı ağırlıklarla katılır.",
    sourceIds: ["BUSH_ET_AL_2000", "HEILBRONNER_HAYDEN_2016", "CARTER_VAN_VEEN_2007"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimType: "misconception_correction",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.acc.profile_boundary",
    topicId: "cns.anterior_cingulate",
    text: "Davranışsal veya ölçek temelli profilden ACC etkinliği, hasarı ya da zayıflığı çıkarılamaz.",
    detail: "ACC çok işlevli ağlara katılır; bireysel bölgesel sonuç üretmek tersine çıkarım olur.",
    sourceIds: ["POLDRAK_2006", "HEILBRONNER_HAYDEN_2016"],
    evidenceLevel: "boundary",
    ageScope: "all_ages",
    claimType: "product_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.midcingulate.anatomy",
    topicId: "cns.midcingulate",
    text: "Orta singulat korteks bazı modern anatomik sınıflamalarda ACC'den ayrılan ve anterior ile posterior alt bölümlere ayrılabilen singulat bölgedir.",
    detail: "Eylem, performans izleme, ağrı ve duygulanım literatürleri bu bölgede kısmen örtüşen fakat özdeş olmayan örüntüler bildirir.",
    sourceIds: ["HEILBRONNER_HAYDEN_2016"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.midcingulate.naming",
    topicId: "cns.midcingulate",
    text: "MCC, aMCC ve dACC etiketleri kaynaklar arasında tam olarak aynı bölgeyi göstermeyebilir.",
    detail: "Bu nedenle işlevsel iddia, kullanılan anatomik tanım ve yöntemle birlikte okunmalıdır.",
    sourceIds: ["HEILBRONNER_HAYDEN_2016", "BUSH_ET_AL_2000"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimType: "misconception_correction",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.performance_monitoring.process",
    topicId: "cns.performance_monitoring",
    text: "Performans izleme hata, çatışma ve sonuç sinyallerinin değerlendirilip sonraki kontrolün ayarlanmasına katkı veren süreçler bütünüdür.",
    detail: "Hata fark etme, çatışma saptama ve kontrol ayarlama ilişkili fakat tek bir hesaplamaya indirgenemeyen düzeylerdir.",
    sourceIds: ["CARTER_VAN_VEEN_2007", "HEILBRONNER_HAYDEN_2016"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.performance_monitoring.distributed",
    topicId: "cns.performance_monitoring",
    text: "Performans izleme ACC veya tek bir EEG bileşeniyle eş anlamlı değildir; dağıtık kontrol ağlarının katkısını içerir.",
    detail: "Görev talebi, geri bildirim ve motivasyon sinyalleri hem davranışı hem nöral göstergeleri değiştirebilir.",
    sourceIds: ["CARTER_VAN_VEEN_2007", "FRIEDMAN_ROBBINS_2022"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "mechanism",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.ern.definition",
    topicId: "cns.error_related_negativity",
    text: "Hata ilişkili negatiflik, hata yanıtının hemen ardından kafa derisi EEG'sinde gözlenen yanıt-kilitli bir ERP bileşenidir.",
    detail: "ERN/Ne performans izleme araştırmalarında kullanılır; ACC'nin doğrudan ölçümü değildir.",
    sourceIds: ["WIERSEMA_ET_AL_2007", "CARTER_VAN_VEEN_2007"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.ern.development_measurement",
    topicId: "cns.error_related_negativity",
    text: "ERN özellikleri çocukluktan yetişkinliğe değişebilir ve görev ile analiz koşullarına duyarlıdır.",
    detail: "Yaş grubu ortalamaları tek çocukta tanı, kaygı, ACC işlevi veya gelecek sonucu sağlamaz.",
    sourceIds: ["WIERSEMA_ET_AL_2007"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "development",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.cingulo_opercular.definition",
    topicId: "cns.cingulo_opercular_network",
    text: "Bazı ağ parselasyonları anterior insula/frontal operkulum ile dorsal singulat veya midcingulate düğümlerini singulo-operküler ağ etiketi altında gruplar.",
    detail: "Bu ağ kontrol sürdürme, önem işleme ve performans izleme literatürlerinde tanımlanır; tek bir işlev merkezi değildir.",
    sourceIds: ["MENON_UDDIN_2010", "UDDIN_ET_AL_2017", "SEELEY_2019"],
    evidenceLevel: "moderate",
    ageScope: "adult_weighted",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.cingulo_opercular.naming_boundary",
    topicId: "cns.cingulo_opercular_network",
    text: "Singulo-operküler ağ ve salience ağı önemli düğümleri paylaşabilir, ancak her çalışmada tam eş anlamlı değildir.",
    detail: "Ağ adı ve sınırları parselasyon, görev ve kuramsal çerçeveye göre değişebilir.",
    sourceIds: ["MENON_UDDIN_2010", "UDDIN_ET_AL_2017", "SEELEY_2019"],
    evidenceLevel: "moderate",
    ageScope: "adult_weighted",
    claimType: "misconception_correction",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.reverse_inference",
    topicId: "cns.reverse_inference",
    text: "Tersine çıkarım, gözlenen davranış veya beyin etkinliğinden tek ve özgül bir bilişsel süreç ya da patoloji sonucu üretme hatasıdır.",
    detail: "Aynı bölgenin farklı süreçlere katılması ve aynı sürecin dağıtık ağlara dayanması bu çıkarımı sınırlar.",
    sourceIds: ["POLDRAK_2006"],
    evidenceLevel: "boundary",
    ageScope: "all_ages",
    claimType: "misconception_correction",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.ans.overview",
    topicId: "ans.overview",
    text: "Otonom sinir sistemi kalp, damar, terleme, pupil, sindirim ve diğer iç organ süreçlerinin koşullara göre ayarlanmasına katılır.",
    detail: "Merkezi ve periferik devreler, visseral geri bildirim ve organ-özgül mekanizmalar birlikte çalışır.",
    sourceIds: ["WEHRWEIN_ET_AL_2016", "SAPER_2002"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.ans.not_personality",
    topicId: "ans.overview",
    text: "Bir kişiyi bütün olarak 'sempatik' veya 'parasempatik' diye sınıflamak fizyolojik olarak aşırı basitleştiricidir.",
    detail: "Otonom örüntüler organ, bağlam ve zaman ölçeğine göre değişir.",
    sourceIds: ["BERNTSON_ET_AL_1991", "WEHRWEIN_ET_AL_2016"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "misconception_correction",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.ans.behavior_not_disorder",
    topicId: "ans.overview",
    text: "Davranışsal regülasyon güçlüğü ile otonom sinir sistemi bozukluğu aynı sonuç değildir.",
    detail: "Gözlemsel veya ölçek temelli profil fizyolojik ölçümün yerini tutmaz; ANS işlevi organ, bağlam ve uygun protokolle değerlendirilir.",
    sourceIds: ["WEHRWEIN_ET_AL_2016", "BERNTSON_ET_AL_1991"],
    evidenceLevel: "boundary",
    ageScope: "all_ages",
    claimType: "product_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.homeostasis.definition",
    topicId: "ans.homeostasis",
    text: "Homeostaz, iç değişkenlerin geri bildirim süreçleriyle işlevsel aralıklarda tutulmasını anlatır.",
    detail: "Sabit ve hareketsiz bir denge değil, sürekli düzenlenen dinamik bir süreçtir.",
    sourceIds: ["RAMSAY_WOODS_2014"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.allostasis.definition",
    topicId: "ans.allostasis",
    text: "Allostaz, değişen taleplere uyum için fizyolojik düzenlemenin bağlama ve beklenen ihtiyaca göre ayarlanmasını vurgulayan kuramsal çerçevedir.",
    detail: "Allostaz bir DNA skoru veya tek bir laboratuvar ölçümü değildir; allostatik yük de tek davranıştan çıkarılamaz.",
    sourceIds: ["RAMSAY_WOODS_2014", "MCEWEN_1998"],
    evidenceLevel: "theoretical",
    ageScope: "mixed",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.hrv.definition",
    topicId: "ans.hrv",
    text: "Kalp hızı değişkenliği, ardışık kalp atımları arasındaki zaman aralıklarının değişkenliğidir.",
    detail: "HRV doğrudan kaydedilen kardiyak zaman serisinden hesaplanır; ANS'nin tamamı, beyin işlevi veya self-regülasyonun doğrudan ölçümü değildir.",
    sourceIds: ["TASK_FORCE_HRV_1996", "LABORDE_ET_AL_2017"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "definition",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.hrv.association",
    topicId: "ans.hrv",
    text: "Bazı HRV ölçütleri ile self-regülasyon veya adaptif işlev arasında grup düzeyinde ilişkiler bildirilmiştir.",
    detail: "İlişkiler yöntem, yaş ve göreve göre heterojendir; düşük HRV tek kişide bozukluk, neden veya düşük DNA alanı anlamına gelmez.",
    sourceIds: ["GRAZIANO_DEREFINKO_2013", "LABORDE_ET_AL_2017"],
    evidenceLevel: "moderate",
    ageScope: "mixed",
    claimType: "association",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.hrv.measurement_boundary",
    topicId: "ans.hrv",
    text: "HRV, doğrudan kaydedilen kardiyak atımlar arası zaman serisinden hesaplanır; ANS'nin tamamını veya self-regülasyonu doğrudan ölçmez.",
    detail: "Solunum, kalp hızı, kayıt süresi, postür, hareket ve analiz yöntemi yorumu etkileyebilir; DNA puanı HRV yerine geçmez.",
    sourceIds: ["TASK_FORCE_HRV_1996", "LABORDE_ET_AL_2017"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.hrv.development_boundary",
    topicId: "ans.hrv",
    text: "Çocuklarda HRV yaş, kalp hızı, solunum, büyüme göstergeleri ve kayıt protokolüne göre değişebilir; bu kaynaklar tek bir evrensel olgunlaşma yaşı tanımlamaz.",
    detail: "Yaşa özgü grup değerleri ancak benzer kayıt ve analiz koşullarında yorumlanabilir; bireysel klinik eşik veya DNA karşılığı değildir.",
    sourceIds: ["GASIOR_ET_AL_2018", "LABORDE_ET_AL_2017"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "development",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.hrv.lfhf",
    topicId: "ans.hrv",
    text: "LF/HF oranı küresel bir sempatik-parasempatik denge göstergesi olarak güvenle yorumlanamaz.",
    detail: "HRV bileşenleri solunum, kalp hızı, kayıt süresi ve başka fizyolojik etkenlere duyarlıdır.",
    sourceIds: ["BILLMAN_2013", "LABORDE_ET_AL_2017"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "measurement_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.eda.definition",
    topicId: "ans.eda",
    text: "Elektrodermal aktivite, ter bezlerinin sempatik sinirsel kontrolüyle ilişkili deri iletkenliği değişimlerinin ölçümüdür.",
    detail: "EDA uyarılma ve dikkatle değişebilir; tek başına belirli bir duygu, neden veya tanı göstermez.",
    sourceIds: ["BOUCSEIN_ET_AL_2012"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "definition",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.eda.sensory",
    topicId: "ans.eda",
    text: "Çocuklarda duyusal uyaranlara verilen EDA örüntüleri üzerine kanıt sınırlı ve heterojendir.",
    detail: "Küçük veya seçilmiş örneklemlerden duyusal davranışın otonom nedeni ya da tanısal sınıfı çıkarılamaz.",
    sourceIds: ["CHRISTENSEN_ET_AL_2020", "MCINTOSH_ET_AL_1999"],
    evidenceLevel: "limited",
    ageScope: "childhood",
    claimType: "association",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.interoception.multidimensional",
    topicId: "ans.interoception",
    text: "İnterosepsiyon, iç beden sinyallerinin algılanması, bütünleştirilmesi, yorumlanması ve düzenleyici kullanımıyla ilgili çok boyutlu süreçlerdir.",
    detail: "Görev performansı, öz-bildirim eğilimi ve metabilişsel farkındalık aynı şey değildir.",
    sourceIds: ["CHEN_ET_AL_2021", "QUIGLEY_ET_AL_2021", "KHALSA_ET_AL_2018", "GARFINKEL_ET_AL_2015"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.interoception.consciousness_boundary",
    topicId: "ans.interoception",
    text: "İnteroseptif işlemenin önemli bir bölümü bilinçli farkındalık dışında gerçekleşebilir.",
    detail: "İç sinyale davranışsal veya fizyolojik duyarlılık, kişinin sinyali bilinçli biçimde tanıdığı ya da adlandırdığı anlamına gelmez.",
    sourceIds: ["CHEN_ET_AL_2021", "QUIGLEY_ET_AL_2021"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "misconception_correction",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.interoception.emotion",
    topicId: "ans.interoception",
    text: "İnterosepsiyon ve duygu düzenleme arasında ilişki adayları vardır, ancak yön ve mekanizma kişiye özgü olarak belirlenemez.",
    detail: "Kanıt yetişkin ağırlıklı ve yöntemsel olarak heterojendir; ilişki nedensellik değildir.",
    sourceIds: ["PINNA_EDWARDS_2020", "KHALSA_ET_AL_2018"],
    evidenceLevel: "moderate",
    ageScope: "adult_weighted",
    claimType: "association",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.interoception.dimensions_distinct",
    topicId: "ans.interoception_dimensions",
    text: "İnteroseptif görev performansı, öz-bildirimli eğilim ve performansa ilişkin metabilişsel isabet birbirinden ayrılmalıdır.",
    detail: "Bir boyuttaki yüksek veya düşük sonuç diğer boyutları ya da genel interoseptif kapasiteyi otomatik olarak göstermez.",
    sourceIds: ["GARFINKEL_ET_AL_2015", "DESMEDT_ET_AL_2023", "KHALSA_ET_AL_2018"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.interoception.terminology_boundary",
    topicId: "ans.interoception_dimensions",
    text: "İnteroseptif doğruluk, duyarlılık ve farkındalık terimleri kaynaklar arasında her zaman aynı anlamda kullanılmaz.",
    detail: "Yanıt, çalışmanın operasyonel tanımını ve kullandığı ölçüm türünü açıkça belirtmelidir.",
    sourceIds: ["DESMEDT_ET_AL_2023", "GARFINKEL_ET_AL_2015"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "misconception_correction",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.interoception.no_gold_standard",
    topicId: "ans.interoception_measurement",
    text: "İnterosepsiyonun bütün boyut ve modalitelerini tüm yaşlarda ölçen evrensel tek bir altın standart yoktur.",
    detail: "Performans görevleri, öz-bildirimler, güven değerlendirmeleri ve nörofizyolojik yöntemler farklı veri düzeyleri sağlar.",
    sourceIds: ["DESMEDT_ET_AL_2023", "DONAGHY_ET_AL_2025", "ADDABBO_MILANI_2025"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.interoception.tasks_not_equivalent",
    topicId: "ans.interoception_measurement",
    text: "Kalp atımı sayma, ayırt etme ve sinyal tespit görevleri aynı ölçüm değildir ve birbirinin yerine kullanılamaz.",
    detail: "Kalp bilgisi, zaman tahmini, dikkat, talimat ve fizyolojik sinyal gücü görev sonucunu farklı biçimlerde etkileyebilir.",
    sourceIds: ["DESMEDT_ET_AL_2023", "DONAGHY_ET_AL_2025"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.interoception.infant_sensitivity",
    topicId: "ans.interoception_development",
    text: "Bebeklerin bedenle eşzamanlı uyaranlara farklı yanıt vermesi erken interoseptif duyarlılık için grup düzeyi kanıt adayıdır.",
    detail: "Bu bulgu bilinçli farkındalık, genel interoseptif kapasite veya bireysel gelişim düzeyi anlamına gelmez.",
    sourceIds: ["MAISTER_ET_AL_2017"],
    evidenceLevel: "limited",
    ageScope: "early_childhood",
    claimType: "development",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.interoception.development_gap",
    topicId: "ans.interoception_development",
    text: "0–12 yaş için tüm interoseptif modalitelere uyan tek ve normatif bir gelişim eğrisi bulunmaz.",
    detail: "Pediatrik çalışmalar az sayıda ve görev, yaş aralığı ile bilgi kaynağı bakımından heterojendir; yetişkin bulguları çocuk normu değildir.",
    sourceIds: ["ADDABBO_MILANI_2025"],
    evidenceLevel: "limited",
    ageScope: "childhood",
    claimType: "development",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.interoception.multimodal",
    topicId: "ans.interoception_modalities",
    text: "İnterosepsiyon kardiyak, solunumsal, gastrointestinal, mesane-bağırsak, termal, ağrı ve efor gibi çok sayıda beden sinyali alanını kapsar.",
    detail: "Bu modaliteler farklı reseptör, iletim yolu, görev ve bağlamsal etkenler içerir.",
    sourceIds: ["CHEN_ET_AL_2021", "QUIGLEY_ET_AL_2021"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.interoception.modality_specificity",
    topicId: "ans.interoception_modalities",
    text: "Bir interoseptif modalitedeki performans diğer modalitelere veya genel interoseptif kapasiteye otomatik genellenemez.",
    detail: "Kardiyak görev sonucu gastrointestinal, solunumsal veya başka bir beden kanalını doğrudan temsil etmez.",
    sourceIds: ["CHEN_ET_AL_2021", "QUIGLEY_ET_AL_2021"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.ans.development",
    topicId: "ans.development",
    text: "Otonom göstergeler çocukluk boyunca yaş, büyüme, solunum, aktivite ve ölçüm protokolüyle değişebilir.",
    detail: "Yaşa özgü grup değerleri başka protokollere veya DNA puanlarına doğrudan çevrilemez.",
    sourceIds: ["GASIOR_ET_AL_2018", "WHEDON_ET_AL_2018"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "development",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.sympathetic.parasympathetic",
    topicId: "ans.sympathetic_parasympathetic",
    text: "Sempatik ve parasempatik süreçler günlük uyum için birlikte çalışan otonom bileşenlerdir; biri evrensel olarak kötü, diğeri iyi değildir.",
    detail: "Etkileri hedef organa, zamana ve bağlama göre değişir; 'savaş/kaç' ile 'dinlen/sindir' yalnız kaba öğretici kısaltmalardır.",
    sourceIds: ["WEHRWEIN_ET_AL_2016", "BERNTSON_ET_AL_1991"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "misconception_correction",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.sympathetic.measurement_boundary",
    topicId: "ans.sympathetic_parasympathetic",
    text: "Sempatik etkinliğin bütününü çocukta veya yetişkinde gösteren tek ve evrensel bir ölçüm yoktur.",
    detail: "EDA, kardiyak, pupiller ve diğer sinyaller organ ve protokole özgü farklı bilgi sağlar; biri bütün sempatik sistemi temsil etmez.",
    sourceIds: [
      "WEHRWEIN_ET_AL_2016",
      "BERNTSON_ET_AL_1991",
      "BOUCSEIN_ET_AL_2012",
      "TASK_FORCE_HRV_1996",
      "MATHOT_2018",
    ],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.autonomic.space",
    topicId: "ans.autonomic_space",
    text: "Sempatik ve parasempatik etkinlik karşılıklı değişim, eşzamanlı etkinleşme, eşzamanlı baskılanma veya bağımsız değişim örüntüleri gösterebilir.",
    detail: "Bu otonom uzam çerçevesi küresel bir tahterevalli modelinin yetersizliğini açıklar; kişiye özgü organ örüntüsünü davranıştan belirlemez.",
    sourceIds: ["BERNTSON_ET_AL_1991", "DAMPNEY_2016"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "mechanism",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.ans.measurement",
    topicId: "ans.measurement_limits",
    text: "Kalp hızı, HRV, EDA, pupil ve diğer ölçümler otonom işlevin farklı parçalarına ilişkin bilgi verir; hiçbiri tek başına bütün ANS'yi ölçmez.",
    detail: "Her sinyalin kayıt protokolü, artefaktları ve fizyolojik özgüllüğü farklıdır; davranış gözlemi bu ölçümlerin yerine geçmez.",
    sourceIds: ["TASK_FORCE_HRV_1996", "BOUCSEIN_ET_AL_2012", "MATHOT_2018"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "measurement_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.polyvagal.status",
    topicId: "ans.polyvagal",
    text: "Polivagal teori etkili bir kuramsal çerçevedir, ancak bazı anatomik ve fizyolojik öncülleri bilimsel tartışma konusudur.",
    detail: "Teori savunucu ve eleştirel kaynaklarla birlikte sunulmalı; yerleşik ve tartışmasız fizyoloji gibi anlatılmamalıdır.",
    sourceIds: ["PORGES_2021", "GROSSMAN_2023"],
    evidenceLevel: "theoretical",
    ageScope: "mixed",
    claimType: "misconception_correction",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.polyvagal.boundary",
    topicId: "ans.polyvagal",
    text: "Davranış gözleminden 'dorsal vagal kapanma', 'ventral vagal durum' veya kişisel vagal ton atanamaz.",
    detail: "Bu etiketler DNA raporu veya sohbet yanıtında biyolojik ölçüm gibi kullanılmamalıdır.",
    sourceIds: ["GROSSMAN_2023", "LABORDE_ET_AL_2017"],
    evidenceLevel: "boundary",
    ageScope: "all_ages",
    claimType: "product_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.stress.multisystem",
    topicId: "selfreg.stress_systems",
    text: "Stres yanıtı sinir sistemi, HPA ekseni, otonom, bağışıklık ve metabolik süreçlerin bağlama göre koordine olabildiği çok sistemli bir süreçtir.",
    detail: "Bu sistemler ortak bir uyum bağlamında incelenebilir; ancak tek bir belirti, davranış veya biyobelirteç bütün stres yanıtını temsil etmez.",
    sourceIds: ["CHROUSOS_2009", "MCEWEN_2007", "GUNNAR_QUEVEDO_2007"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.stress.systems_not_interchangeable",
    topicId: "selfreg.stress_systems",
    text: "Öznel stres, gözlenen davranış ve fizyolojik stres göstergeleri birbiriyle ilişkili olabilse de birbirinin yerine geçmez.",
    detail: "Farklı stres sistemleri aynı olayda aynı anda, aynı yönde veya aynı büyüklükte değişmek zorunda değildir; DNA profili de bu sistemlerin doğrudan ölçümü değildir.",
    sourceIds: ["DEJOSEPH_ET_AL_2024", "CHROUSOS_2009"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.hpa.axis_definition",
    topicId: "selfreg.hpa_axis",
    text: "HPA ekseni, hipotalamus, hipofiz ve adrenal korteks arasındaki hormon sinyalleri ile geri bildirim döngülerini içeren nöroendokrin bir stres sistemidir.",
    detail: "Hipotalamik sinyaller ACTH salımını, ACTH ise adrenal kortizol üretimini etkiler; sistem bazal ritim, reaktivite ve toparlanma gibi farklı zaman özellikleri taşır.",
    sourceIds: ["CHROUSOS_2009", "MCEWEN_2007", "GUNNAR_QUEVEDO_2007"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "mechanism",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.hpa.behavior_boundary",
    topicId: "selfreg.hpa_axis",
    text: "HPA ekseni işlevi, hormon örneklemesi olmadan davranıştan veya DNA puanından belirlenemez.",
    detail: "Aynı davranış farklı biyolojik ve bağlamsal yollarla ortaya çıkabilir; gözlem CRH, ACTH, kortizol düzeyi ya da HPA bozukluğu göstermez.",
    sourceIds: ["CHROUSOS_2009", "GUNNAR_QUEVEDO_2007"],
    evidenceLevel: "boundary",
    ageScope: "developmental",
    claimType: "product_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.cortisol.time_scales",
    topicId: "selfreg.cortisol_measurement",
    text: "Kan, tükürük, idrar ve saç kortizolü farklı örnekleme pencereleri ve zaman ölçekleri hakkında bilgi verir.",
    detail: "Günün saati, uyanma zamanı, örnekleme aralığı, sağlık durumu ve protokol yorumu etkiler; farklı örnek türleri birbirinin yerine kullanılamaz.",
    sourceIds: ["STALDER_ET_AL_2016", "CHROUSOS_2009", "GUNNAR_QUEVEDO_2007"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "measurement_boundary",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.cortisol.measurement_boundary",
    topicId: "selfreg.cortisol_measurement",
    text: "Tek bir kortizol değeri bütün stres yanıtını, yaşanmış travmayı veya kişisel regülasyon kapasitesini göstermez.",
    detail: "Kortizol sonucu örnekleme koşulları ve uygun referans bağlamıyla yorumlanmalıdır; davranış veya DNA skoru kortizol ölçümü yerine geçmez.",
    sourceIds: ["STALDER_ET_AL_2016", "CHROUSOS_2009"],
    evidenceLevel: "boundary",
    ageScope: "mixed",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.toxic_stress.framework",
    topicId: "selfreg.toxic_stress",
    text: "Toksik stres, güçlü veya uzun süreli güçlüklerin yeterli koruyucu ilişkisel destek olmadan gelişim sistemlerini zorlayabilmesini anlatan bir halk sağlığı çerçevesidir.",
    detail: "Kavram klinik tanı değildir ve tek bir ACE puanı, kortizol değeri, davranış ya da DNA profiliyle belirli çocukta doğrulanamaz.",
    sourceIds: ["SHONKOFF_ET_AL_2012", "GUNNAR_QUEVEDO_2007"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.allostatic_load.multisystem",
    topicId: "ans.allostatic_load",
    text: "Allostatik yük, uzun süreli uyum talepleriyle ilişkili çoklu fizyolojik sistem göstergelerini bir arada inceleyen bir araştırma çerçevesidir.",
    detail: "Çalışmalar nöroendokrin, kardiyovasküler, metabolik ve bağışıklık göstergelerinden farklı bileşimler kullanabilir; tek belirti allostatik yük değildir.",
    sourceIds: ["LUCENTE_GUIDI_2023", "MCEWEN_1998", "MCEWEN_2007"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.allostatic_load.no_universal_threshold",
    topicId: "ans.allostatic_load",
    text: "Allostatik yük için çocuklar dahil bütün yaş ve bağlamlarda geçerli tek bir biyobelirteç seti veya evrensel klinik eşik yoktur.",
    detail: "Biyobelirteç seçimi ve puanlama çalışmadan çalışmaya değişir; davranıştan ya da DNA puanından bireysel allostatik yük hesaplanamaz.",
    sourceIds: ["LUCENTE_GUIDI_2023", "MCEWEN_2007"],
    evidenceLevel: "boundary",
    ageScope: "developmental",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.sleep.multidimensional",
    topicId: "selfreg.sleep_health",
    text: "Uyku sağlığı süre, zamanlama, düzenlilik, süreklilik, gündüz uyanıklığı ve uykuya ilişkin davranışlar gibi birden çok boyut içerir.",
    detail: "Tek bir süre, yatış saati veya anket puanı uyku sağlığının bütününü temsil etmez; yöntemler farklı boyutlara duyarlıdır.",
    sourceIds: ["INHULSEN_ET_AL_2022", "GALLAND_ET_AL_2012"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.sleep.function_association",
    topicId: "selfreg.sleep_health",
    text: "Çocuklukta uyku örüntüleri ile bilişsel, duygusal ve davranışsal işlevler arasında grup düzeyinde ilişkiler bildirilmiştir.",
    detail: "Bu ilişkiler çoğu zaman çift yönlüdür ve tek çocukta uyku nedenini, tanıyı veya gelecekteki sonucu belirlemez.",
    sourceIds: ["ASTILL_ET_AL_2012", "GREGORY_SADEH_2012"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "association",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.daily_circadian.distinction",
    topicId: "selfreg.daily_rhythm",
    text: "Gözlenebilir günlük uyku-etkinlik örüntüsü ile içsel sirkadiyen zamanlama aynı kavram değildir.",
    detail: "Rutin, yatış saati veya hareketsizlik günlük örüntüyü betimleyebilir; bunlar melatonin başlangıcı, kortizol ritmi veya SCN işlevini doğrudan ölçmez.",
    sourceIds: ["BORBELY_ET_AL_2016", "HASTINGS_ET_AL_2018"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "misconception_correction",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.circadian.definition",
    topicId: "selfreg.circadian_rhythm",
    text: "Sirkadiyen ritimler yaklaşık 24 saatlik biyolojik zamanlama süreçleridir ve ışık gibi zamanlayıcılarla çevreye ayarlanır.",
    detail: "Sirkadiyen zamanlama uyku ile etkileşir; fakat uyku, günlük rutin ve sirkadiyen sistem birbirinin eş anlamlısı değildir.",
    sourceIds: ["HASTINGS_ET_AL_2018", "BORBELY_ET_AL_2016"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.circadian.behavior_boundary",
    topicId: "selfreg.circadian_rhythm",
    text: "Davranışsal yatış saati, DNA profili veya tüketici cihazı kişisel sirkadiyen fazı ya da SCN işlevini doğrudan göstermez.",
    detail: "İçsel faza ilişkin iddialar uygun biyolojik işaretleyici ve protokol gerektirir; günlük rutin biyolojik saat ölçümü değildir.",
    sourceIds: ["HASTINGS_ET_AL_2018", "BORBELY_ET_AL_2016"],
    evidenceLevel: "boundary",
    ageScope: "all_ages",
    claimType: "product_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.sleep.two_process",
    topicId: "selfreg.sleep_regulation",
    text: "İki süreçli uyku modeli, biriken homeostatik uyku basıncı ile sirkadiyen zamanlamanın etkileşimini kuramsal olarak açıklar.",
    detail: "Modelin süreçleri günlük davranıştan doğrudan ölçülen kişisel değerler değildir ve tek çocuk için tanı ya da tedavi kararı üretmez.",
    sourceIds: ["BORBELY_ET_AL_2016"],
    evidenceLevel: "theoretical",
    ageScope: "mixed",
    claimType: "mechanism",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.sleep.measurement_multimethod",
    topicId: "selfreg.sleep_measurement",
    text: "Uyku günlüğü, bakımveren anketi, aktigrafi ve polisomnografi çocuk uykusunun farklı yönleri hakkında bilgi verir.",
    detail: "Yöntemlerin veri kaynağı, zaman çözünürlüğü ve sınırlılıkları farklıdır; hiçbiri her uyku sorusunu tek başına yanıtlamaz.",
    sourceIds: ["MELTZER_ET_AL_2012_SLEEP", "INHULSEN_ET_AL_2022", "SADEH_2004"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "measurement_boundary",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.sleep.device_boundary",
    topicId: "selfreg.sleep_measurement",
    text: "Aktigrafi ve tüketici cihazları hareketten uyku-uyanıklık tahmini yapabilir; uyku evresini, biyolojik saati veya uyku bozukluğunu tek başına belirlemez.",
    detail: "Cihaz çıktısı kullanılan algoritma ve protokole bağlıdır; anket, akıllı saat veya DNA profili polisomnografi ya da klinik değerlendirme yerine geçmez.",
    sourceIds: ["MELTZER_ET_AL_2012_SLEEP", "SADEH_2004"],
    evidenceLevel: "boundary",
    ageScope: "childhood",
    claimType: "product_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.sleep.development",
    topicId: "selfreg.sleep_development",
    text: "Uyku süresi, gün içindeki dağılımı, gündüz uykuları ve zamanlama çocukluk boyunca ortalama olarak değişir.",
    detail: "Gelişimsel grup eğilimlerinin çevresinde geniş bireysel farklılık vardır; ölçüm yöntemi, kültür ve rutin gözlenen örüntüyü etkileyebilir.",
    sourceIds: ["GALLAND_ET_AL_2012", "PARUTHI_ET_AL_2016"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "development",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.sleep.guidance_boundary",
    topicId: "selfreg.sleep_development",
    text: "Yaşa göre önerilen uyku süresi aralıkları toplum düzeyi rehberidir; tek çocuk için tanı veya değişmez zorunlu miktar değildir.",
    detail: "Aralığın dışında bir gözlem tek başına bozukluk ya da gelişimsel gecikme göstermez; yorum süre dışındaki uyku boyutlarını ve bağlamı da gerektirir.",
    sourceIds: ["PARUTHI_ET_AL_2016", "GALLAND_ET_AL_2012"],
    evidenceLevel: "boundary",
    ageScope: "developmental",
    claimType: "measurement_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.ef.unity_diversity",
    topicId: "cns.executive_models",
    text: "Yürütücü işlevler ortak kontrol özellikleri taşıyan fakat çalışma belleği, ketleyici kontrol ve bilişsel esneklik gibi kısmen ayrışan süreçler ailesidir.",
    detail: "Bileşenlerin ayrışma derecesi örnekleme, yaş, görevler ve istatistiksel modele göre değişebilir; tek faktör tek biyolojik mekanizma demek değildir.",
    sourceIds: ["MIYAKE_ET_AL_2000", "KARR_ET_AL_2018", "DOEBEL_2020", "DIAMOND_2013"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.ef.contextual_performance",
    topicId: "cns.executive_models",
    text: "Yürütücü görev performansı görev talebi, strateji, motivasyon, yorgunluk ve bağlama duyarlıdır.",
    detail: "Tek görev sonucu değişmez genel kapasiteyi, frontal-lob işlevini veya bütün günlük self-regülasyonu doğrudan göstermez.",
    sourceIds: ["DOEBEL_2020", "TOPLAK_ET_AL_2013", "DIAMOND_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.ef.development_not_uniform",
    topicId: "cns.executive_development",
    text: "Yürütücü işlev bileşenleri erken çocukluktan itibaren gelişir; aynı hızda, doğrusal biçimde veya tek bir yaşta tamamlanmaz.",
    detail: "Yaşa ilişkin grup eğilimleri tek çocukta olgunluk, gecikme ya da yaşam boyu sonucu belirlemez.",
    sourceIds: ["GARON_ET_AL_2008", "HENDRY_ET_AL_2016", "DIAMOND_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "development",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.ef.task_impurity",
    topicId: "cns.executive_development",
    text: "Yürütücü işlev görevleri hedeflenen sürecin yanında dikkat, dil, motor yanıt, bellek, hız ve motivasyon gibi ek talepler içerir.",
    detail: "Bu görev saflığı sorunu özellikle gelişimsel karşılaştırmalarda önemlidir; düşük performans tek bir yürütücü bileşenin yetersizliğine atanamaz.",
    sourceIds: ["GARON_ET_AL_2008", "HENDRY_ET_AL_2016", "TOPLAK_ET_AL_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.working_memory.development",
    topicId: "cns.working_memory_development",
    text: "Çalışma belleğiyle ilişkili depolama, güncelleme ve kontrol performansı çocukluk boyunca ortalama olarak değişir.",
    detail: "Gelişim sözel ve görsel-uzamsal alanlarda, görev taleplerinde ve bireyler arasında farklı örüntüler gösterebilir; yaş tek başına kapasite eşiği değildir.",
    sourceIds: ["COWAN_2014", "GATHERCOLE_ET_AL_2004", "BADDELEY_2000"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "development",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.working_memory.short_term_distinction",
    topicId: "cns.working_memory_development",
    text: "Çalışma belleği yalnız kısa süreli depolama değil, bilginin hedef doğrultusunda sürdürülmesi ve işlenmesine ilişkin kontrol taleplerini de kapsar.",
    detail: "Basit kısa süreli bellek ile çalışma belleği görevleri örtüşebilir; ancak terimler ve görev talepleri otomatik olarak eşdeğer değildir.",
    sourceIds: ["BADDELEY_2000", "COWAN_2014"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "misconception_correction",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.working_memory.multimethod",
    topicId: "cns.working_memory_measurement",
    text: "Basit span, karmaşık span, güncelleme ve sözel ya da görsel-uzamsal görevler çalışma belleğinin farklı taleplerini örnekler.",
    detail: "Tek görev bütün çalışma belleğini veya sabit bireysel kapasiteyi temsil etmez; görev etkisinin büyük olması bireysel fark güvenirliğini garanti etmez.",
    sourceIds: ["ANDERSON_REIDY_2012", "HEDGE_ET_AL_2018", "TOPLAK_ET_AL_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.attention.multicomponent",
    topicId: "cns.attention",
    text: "Dikkat uyarılma, yöneltme, seçme, sürdürme ve hedefle ilgili kontrol gibi kısmen ayrışan süreçler ailesidir.",
    detail: "Dikkat tek bir enerji, değişmez özellik veya tek beyin bölgesi değildir; farklı görevler farklı bileşenleri örnekler.",
    sourceIds: ["PETERSEN_POSNER_2012", "RUEDA_ET_AL_2004"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.attention.no_behavior_proxy",
    topicId: "cns.attention",
    text: "Göz teması, yerinde oturma, tek görev süresi veya tek bir puan genel dikkatin doğrudan ölçümü değildir.",
    detail: "Gözlenen davranış dikkat dışında görev yapısı, motivasyon, dil, motor yanıt ve çevresel taleplerden etkilenebilir; beyin ağı veya tanı çıkarımı yapılamaz.",
    sourceIds: ["PETERSEN_POSNER_2012", "FISHER_ET_AL_2013_ATTENTION", "TOPLAK_ET_AL_2013"],
    evidenceLevel: "boundary",
    ageScope: "developmental",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.attention.networks_interact",
    topicId: "cns.attention_networks",
    text: "Dikkat ağı modelleri uyarılma, yöneltme ve yürütücü kontrol işlevlerini analitik olarak ayırır; gerçek görevlerde bu süreçler etkileşebilir.",
    detail: "Ağlar tamamen bağımsız kutular değildir ve işlevler tek bir anatomik düğüme indirgenemez.",
    sourceIds: ["PETERSEN_POSNER_2012", "RUEDA_ET_AL_2004"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "mechanism",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.attention.networks_boundary",
    topicId: "cns.attention_networks",
    text: "Davranıştan, Attention Network Test skorundan veya DNA profilinden kişisel dikkat ağı etkinliği belirlenemez.",
    detail: "Görev puanı belirli koşullardaki performansı örnekler; tek bir beyin bölgesinin işlevi, hasarı veya biyolojik mekanizması değildir.",
    sourceIds: ["PETERSEN_POSNER_2012", "RUEDA_ET_AL_2004"],
    evidenceLevel: "boundary",
    ageScope: "mixed",
    claimType: "product_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.sustained_attention.development",
    topicId: "cns.sustained_attention",
    text: "Sürdürülen dikkat performansı çocukluk boyunca ortalama olarak değişir ve farklı performans bileşenleri aynı hızda gelişmeyebilir.",
    detail: "Kaçırma, yanlış alarm, tepki süresi ve tepki değişkenliği ayrı ölçümlerdir; yaş eğilimi tek çocukta sabit kapasite değildir.",
    sourceIds: ["BETTS_ET_AL_2006", "FISHER_ET_AL_2013_ATTENTION"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "development",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.sustained_attention.task_load",
    topicId: "cns.sustained_attention",
    text: "Sürdürülen dikkat performansı görev süresi, hedef sıklığı, zorluk, motivasyon ve test koşullarına duyarlıdır.",
    detail: "Tek oturumdaki performans değişmez dikkat kapasitesini, isteksizliği, tanıyı veya kişisel beyin ağı işlevini göstermez.",
    sourceIds: ["BETTS_ET_AL_2006", "FISHER_ET_AL_2013_ATTENTION"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.selective_attention.definition",
    topicId: "cns.selective_attention",
    text: "Seçici dikkat, hedefle ilgili bilgiyi önceliklendirirken ilgisiz girdinin etkisini bağlama göre yönetme süreçlerini kapsar.",
    detail: "Bu süreç mutlak bir filtre değildir; hedef, uyaran belirginliği ve görev talebi hangi bilginin önceliklendirildiğini değiştirir.",
    sourceIds: ["FISHER_ET_AL_2013_ATTENTION", "PETERSEN_POSNER_2012"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.selective_attention.context",
    topicId: "cns.selective_attention",
    text: "Dikkat dağıtıcıya yönelmek her bağlamda seçici dikkat yetersizliği anlamına gelmez.",
    detail: "Uyaranın çekiciliği, yönerge, motivasyon, önceki deneyim ve görev yapısı sonucu etkileyebilir; tek davranıştan tanı ya da biyolojik neden çıkarılamaz.",
    sourceIds: ["FISHER_ET_AL_2013_ATTENTION", "PETERSEN_POSNER_2012"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "misconception_correction",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.attention.measurement_multimethod",
    topicId: "cns.attention_measurement",
    text: "Dikkat görevleri, davranış derecelendirmeleri ve doğal ortam gözlemleri farklı ve tamamlayıcı bilgi düzeyleri sağlar.",
    detail: "Tek bir altın standart yoktur; görevler belirli koşuldaki performansı, derecelendirmeler ise günlük bağlamlardaki gözlemleri örnekler ve birbirinin yerine geçmez.",
    sourceIds: ["HEDGE_ET_AL_2018", "TOPLAK_ET_AL_2013", "FISHER_ET_AL_2013_ATTENTION"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.attention.development",
    topicId: "cns.attention_development",
    text: "Yöneltme, sürdürme, seçme ve yürütücü dikkat performansı çocukluk boyunca farklı hızlarda ve göreve duyarlı biçimde değişir.",
    detail: "Bebeklikte bakış süresi yetişkin tipi dikkat kapasitesi değildir; yaş grubu eğilimleri tek çocuk için olgunluk, tanı veya prognoz vermez.",
    sourceIds: ["RUEDA_ET_AL_2004", "BETTS_ET_AL_2006", "FISHER_ET_AL_2013_ATTENTION"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "development",
    dnaRelation: "conceptual_proximity",
  }),
  ...V5_CASE_BOUNDARY_CLAIMS,
  ...V5_SIX_DOMAINS_CLAIMS,
  ...V5_DEVELOPMENT_CLAIMS,
  ...V5_COREGULATION_CLAIMS,
])

export const DNA_CHAT_CATALOG_CLAIM_BY_ID = new Map(
  DNA_CHAT_CATALOG_CLAIMS.map((entry) => [entry.id, entry]),
)
