import {
  DNA_CHAT_CATALOG_VERSION,
  type DnaChatCatalogProvenance,
} from "./types"

export const DNA_CHAT_CATALOG_PROVENANCE: readonly DnaChatCatalogProvenance[] = Object.freeze([
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.self-regulation.v1",
    sourcePackId: "self_regulation",
    category: "self_regulation",
    canonicalFile: "docs/dna-knowledge/research-packs/v1/self-regulation.md",
    sha256: "5424b29899da8c63d2884701c59a4f62da826c34c370d2985d967f2bef2fb4a9",
    importedAt: "2026-07-16",
    sourceFormat: "markdown",
    originalPackage: "self_regulasyon_arastirma_paketi_DNA.zip",
    rawCounts: { claims: 28, conceptCards: 26, questions: 84, sources: 45 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.central-nervous-system.v1",
    sourcePackId: "central_nervous_system",
    category: "central_nervous_system",
    canonicalFile: "docs/dna-knowledge/research-packs/v1/central-nervous-system.md",
    sha256: "1d6d484285fe36be15b0cae8837b87391bab21138cfd795171cd2209d6faa277",
    importedAt: "2026-07-16",
    sourceFormat: "markdown",
    originalPackage: "CNS_DNA_Arastirma_Paketi.zip",
    rawCounts: { claims: 16, conceptCards: 22, questions: 60, sources: 33 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.autonomic-nervous-system.v1",
    sourcePackId: "autonomic_nervous_system",
    category: "autonomic_nervous_system",
    canonicalFile: "docs/dna-knowledge/research-packs/v1/autonomic-nervous-system.md",
    sha256: "a8f870c214d3a5db99ebeaff1b6b40bb0bba930aae6ad26573ca002e8c8220f4",
    importedAt: "2026-07-16",
    sourceFormat: "markdown",
    originalPackage: "deep-research-report (1).md; DOCX duplicate intentionally omitted",
    rawCounts: { claims: 22, conceptCards: 20, questions: 70, sources: 31 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.sympathetic-parasympathetic.v1",
    sourcePackId: "sympathetic_parasympathetic",
    category: "sympathetic_parasympathetic",
    canonicalFile: "docs/dna-knowledge/research-packs/v1/sympathetic-parasympathetic-processes.md",
    sha256: "17afcc401554ac0d5d2765db0244ea64b3dbdb76c8ce8ddaa00e40b9e4a63b79",
    importedAt: "2026-07-16",
    sourceFormat: "markdown",
    originalPackage: "sempatik_parasempatik_surecler_dna_arastirma_paketi.zip",
    rawCounts: { claims: 36, conceptCards: 46, questions: 100, sources: 42 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.prefrontal-processes.v2",
    sourcePackId: "prefrontal_processes",
    category: "central_nervous_system",
    canonicalFile: "docs/dna-knowledge/research-packs/v2/prefrontal-processes.md",
    sha256: "fd3a2959344ae648a277bbb6d3cc10192af141a11ea4ce4e58af4da8ebae7c91",
    importedAt: "2026-07-17",
    sourceFormat: "markdown",
    originalPackage: "Prefrontal_Surecler_DNA_Arastirma_Paketi_Teslim.zip",
    rawCounts: { claims: 20, conceptCards: 24, questions: 70, sources: 32 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.anterior-cingulate-cortex.v2",
    sourcePackId: "anterior_cingulate_cortex",
    category: "central_nervous_system",
    canonicalFile: "docs/dna-knowledge/research-packs/v2/anterior-cingulate-cortex.md",
    sha256: "f20dca60867450fa55a7d1e78a5523208eed9632a3481dbb6cfbaea19bf281ef",
    importedAt: "2026-07-17",
    sourceFormat: "markdown",
    originalPackage: "DNA_Anterior_Singulat_Korteks_Arastirma_Paketi.zip",
    rawCounts: { claims: 30, conceptCards: 32, questions: 80, sources: 45 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.insular-cortex.v2",
    sourcePackId: "insular_cortex",
    category: "central_nervous_system",
    canonicalFile: "docs/dna-knowledge/research-packs/v2/insular-cortex.md",
    sha256: "0e05e9a9a611c725db6f4cf45eaaba11fa3a700642ab719518f9d16680681c54",
    importedAt: "2026-07-17",
    sourceFormat: "markdown",
    originalPackage: "insular_korteks_DNA_bilimsel_arastirma_paketi.zip",
    rawCounts: { claims: 40, conceptCards: 42, questions: 72, sources: 40 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.interoception.v2",
    sourcePackId: "interoception",
    category: "autonomic_nervous_system",
    canonicalFile: "docs/dna-knowledge/research-packs/v2/interoception.md",
    sha256: "e6f5b2789d0ec62848aa6d6347c56a7a48045f42bef3e647d0851746fb7da21d",
    importedAt: "2026-07-17",
    sourceFormat: "markdown",
    originalPackage: "interosepsiyon_dna_arastirma_paketi(1).zip",
    rawCounts: { claims: 40, conceptCards: 48, questions: 96, sources: 51 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.arousal-reactivity.v3",
    sourcePackId: "arousal_reactivity",
    category: "self_regulation",
    canonicalFile: "docs/dna-knowledge/research-packs/v3/arousal-reactivity.md",
    sha256: "07078c3e8f58d3745941f75a1659aaedd3ca632f23a79899edc2e0a5c767e426",
    importedAt: "2026-07-17",
    sourceFormat: "markdown",
    originalPackage: "Uyarilma_ve_Reaktivite_DNA_Arastirma_Paketi_Teslim.zip",
    rawCounts: { claims: 28, conceptCards: 42, questions: 80, sources: 39 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.recovery-self-organization.v3",
    sourcePackId: "recovery_self_organization",
    category: "self_regulation",
    canonicalFile: "docs/dna-knowledge/research-packs/v3/recovery-self-organization.md",
    sha256: "be6e9b52c710c6bdf0caced8a49f1476271851e70f058a6745adc788ca12d386",
    importedAt: "2026-07-17",
    sourceFormat: "markdown",
    originalPackage: "DNA_Toparlanma_Oz_Orgutlenme_Arastirma_Paketi.zip",
    rawCounts: { claims: 42, conceptCards: 44, questions: 96, sources: 57 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.sensory-modulation.v3",
    sourcePackId: "sensory_modulation",
    category: "self_regulation",
    canonicalFile: "docs/dna-knowledge/research-packs/v3/sensory-modulation.md",
    sha256: "78283a8d35559425019f5e07a478b1582bb9a9a3b612533f1d7d2057feb29dfc",
    importedAt: "2026-07-17",
    sourceFormat: "markdown",
    originalPackage: "duyusal_modulasyon_DNA_bilimsel_arastirma_paketi.zip",
    rawCounts: { claims: 44, conceptCards: 43, questions: 80, sources: 40 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.emotion-regulation.v3",
    sourcePackId: "emotion_regulation",
    category: "self_regulation",
    canonicalFile: "docs/dna-knowledge/research-packs/v3/emotion-regulation.md",
    sha256: "8834a5728b161f96bf8e42a0d9886e6cde45fdfb4d15da9979baa95885604d00",
    importedAt: "2026-07-17",
    sourceFormat: "markdown",
    originalPackage: "duygusal_duzenleme_dna_arastirma_paketi.zip",
    rawCounts: { claims: 40, conceptCards: 60, questions: 110, sources: 55 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.stress-systems.v4",
    sourcePackId: "stress_systems",
    category: "self_regulation",
    canonicalFile: "docs/dna-knowledge/research-packs/v4/stress-systems.md",
    sha256: "523dfc3ae756c911c0d99cf05920066916d2e2d06896254c643a2288eeb97fcb",
    importedAt: "2026-07-17",
    sourceFormat: "markdown",
    originalPackage: "Stres_Sistemleri_DNA_Arastirma_Paketi_Teslim.zip",
    rawCounts: { claims: 40, conceptCards: 50, questions: 119, sources: 47 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.sleep-daily-rhythm.v4",
    sourcePackId: "sleep_daily_rhythm",
    category: "self_regulation",
    canonicalFile: "docs/dna-knowledge/research-packs/v4/sleep-daily-rhythm.md",
    sha256: "12face8da1c7440307a366806b8364962ec296d028baebfb1df13bffec471801",
    importedAt: "2026-07-17",
    sourceFormat: "markdown",
    originalPackage: "DNA_Uyku_Gunluk_Ritim_Arastirma_Paketi.zip",
    rawCounts: { claims: 54, conceptCards: 58, questions: 111, sources: 64 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.executive-functions.v4",
    sourcePackId: "executive_functions",
    category: "central_nervous_system",
    canonicalFile: "docs/dna-knowledge/research-packs/v4/executive-functions.md",
    sha256: "42d1e37f380cf5e7a7714a3c1c7ab3e93ecbc3cbe4061560733920b6b15a6caf",
    importedAt: "2026-07-17",
    sourceFormat: "markdown",
    originalPackage: "yurutucu_islevler_DNA_bilimsel_arastirma_paketi.zip",
    rawCounts: { claims: 48, conceptCards: 45, questions: 80, sources: 50 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.attention-working-memory.v4",
    sourcePackId: "attention_working_memory",
    category: "central_nervous_system",
    canonicalFile: "docs/dna-knowledge/research-packs/v4/attention-working-memory.md",
    sha256: "a27304ba16dec580e9927d4ca53698cb1b6c353d2137fda7e0ad1b5e4bdda4cf",
    importedAt: "2026-07-17",
    sourceFormat: "markdown",
    originalPackage: "dikkat_calisma_bellegi_dna_arastirma_paketi.zip",
    rawCounts: { claims: 51, conceptCards: 73, questions: 110, sources: 68 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.case-report-boundaries.v5",
    sourcePackId: "case_report_boundaries",
    category: "self_regulation",
    canonicalFile: "docs/dna-knowledge/research-packs/v5/case-report-interpretation-boundaries.md",
    sha256: "1c9bddb5601139dac7196ef47eea03dd2cfed706e99f3cca66cf42e039761347",
    importedAt: "2026-07-17",
    sourceFormat: "markdown",
    originalPackage: "Vaka_ve_Rapor_Yorum_Sinirlari_DNA_Arastirma_Paketi_Teslim.zip",
    rawCounts: { claims: 48, conceptCards: 51, questions: 110, sources: 50 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.dna-six-domains.v5",
    sourcePackId: "dna_six_domains",
    category: "self_regulation",
    canonicalFile: "docs/dna-knowledge/research-packs/v5/dna-six-domains.md",
    sha256: "2ece669d1d0dc87421c11b94705d10e942e5d094b946f90e8077ad9a2f19d374",
    importedAt: "2026-07-17",
    sourceFormat: "markdown",
    originalPackage: "DNA_Alti_Alan_Arastirma_Paketi.zip",
    rawCounts: { claims: 66, conceptCards: 63, questions: 132, sources: 91 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.developmental-differences.v5",
    sourcePackId: "developmental_differences",
    category: "self_regulation",
    canonicalFile: "docs/dna-knowledge/research-packs/v5/developmental-differences.md",
    sha256: "f68d707ab32434cc2b72e0c52c328ae1a8dd7015759ae45c55acc1d144928492",
    importedAt: "2026-07-17",
    sourceFormat: "markdown",
    originalPackage: "gelisimsel_farkliliklar_DNA_bilimsel_arastirma_paketi.zip",
    rawCounts: { claims: 54, conceptCards: 48, questions: 80, sources: 54 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.coregulation.v5",
    sourcePackId: "coregulation",
    category: "self_regulation",
    canonicalFile: "docs/dna-knowledge/research-packs/v5/coregulation.md",
    sha256: "d0fe25b3a2c9eb6817cc9d6baaf12244c11d9a8c11cafaeb4ba3af08747c55e5",
    importedAt: "2026-07-17",
    sourceFormat: "markdown",
    originalPackage: "es_regulasyon_dna_arastirma_paketi.zip",
    rawCounts: { claims: 50, conceptCards: 75, questions: 116, sources: 60 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
])
