import {
  DNA_CHAT_CATALOG_VERSION,
  type DnaChatCatalogProvenance,
} from "./types"

export const DNA_CHAT_CATALOG_PROVENANCE: readonly DnaChatCatalogProvenance[] = Object.freeze([
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.self-regulation.v1",
    category: "self_regulation",
    canonicalFile: "docs/dna-knowledge/research-packs/v1/self-regulation.md",
    sha256: "5424b29899da8c63d2884701c59a4f62da826c34c370d2985d967f2bef2fb4a9",
    importedAt: "2026-07-16",
    sourceFormat: "markdown",
    originalPackage: "self_regulasyon_arastirma_paketi_DNA.zip",
    rawCounts: { claims: 28, conceptCards: 26, questions: 84, sources: 45 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.central-nervous-system.v1",
    category: "central_nervous_system",
    canonicalFile: "docs/dna-knowledge/research-packs/v1/central-nervous-system.md",
    sha256: "1d6d484285fe36be15b0cae8837b87391bab21138cfd795171cd2209d6faa277",
    importedAt: "2026-07-16",
    sourceFormat: "markdown",
    originalPackage: "CNS_DNA_Arastirma_Paketi.zip",
    rawCounts: { claims: 16, conceptCards: 22, questions: 60, sources: 33 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.autonomic-nervous-system.v1",
    category: "autonomic_nervous_system",
    canonicalFile: "docs/dna-knowledge/research-packs/v1/autonomic-nervous-system.md",
    sha256: "a8f870c214d3a5db99ebeaff1b6b40bb0bba930aae6ad26573ca002e8c8220f4",
    importedAt: "2026-07-16",
    sourceFormat: "markdown",
    originalPackage: "deep-research-report (1).md; DOCX duplicate intentionally omitted",
    rawCounts: { claims: 22, conceptCards: 20, questions: 70, sources: 31 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "provenance.sympathetic-parasympathetic.v1",
    category: "sympathetic_parasympathetic",
    canonicalFile: "docs/dna-knowledge/research-packs/v1/sympathetic-parasympathetic-processes.md",
    sha256: "17afcc401554ac0d5d2765db0244ea64b3dbdb76c8ce8ddaa00e40b9e4a63b79",
    importedAt: "2026-07-16",
    sourceFormat: "markdown",
    originalPackage: "sempatik_parasempatik_surecler_dna_arastirma_paketi.zip",
    rawCounts: { claims: 36, conceptCards: 46, questions: 100, sources: 42 },
    expertReview: "pending",
    runtimePolicy: "verified_safe_subset_only",
  },
])
