import {
  DNA_CHAT_CATALOG_VERSION,
  type DnaChatCatalogRelation,
} from "./types"

function relation(
  input: Omit<DnaChatCatalogRelation, "version" | "maxHops">,
): DnaChatCatalogRelation {
  return Object.freeze({
    version: DNA_CHAT_CATALOG_VERSION,
    maxHops: 1 as const,
    ...input,
  })
}

export const DNA_CHAT_CATALOG_RELATIONS: readonly DnaChatCatalogRelation[] = Object.freeze([
  relation({
    id: "relation.selfcontrol.selfreg",
    fromTopicId: "selfreg.self_control",
    toTopicId: "selfreg.core",
    predicate: "part_of",
    summary: "Self-kontrol, self-regülasyonun tamamı değil daha dar bir bileşenidir.",
    sourceIds: ["NIGG_2017", "INZLICHT_ET_AL_2021"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Terimlerin kullanımı literatürler arasında kısmen değişebilir.",
  }),
  relation({
    id: "relation.ef.selfreg",
    fromTopicId: "selfreg.executive_functions",
    toTopicId: "selfreg.core",
    predicate: "supports",
    summary: "Yürütücü işlevler hedefe yönelik self-regülasyonun bazı bilişsel bileşenlerini destekler.",
    sourceIds: ["DIAMOND_2013", "NIGG_2017"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Yürütücü işlev self-regülasyonun tüm duygusal, sosyal ve fizyolojik yönleriyle aynı değildir.",
  }),
  relation({
    id: "relation.coregulation.selfreg",
    fromTopicId: "selfreg.coregulation",
    toTopicId: "selfreg.core",
    predicate: "supports",
    summary: "Ko-regülasyon özellikle gelişimin erken dönemlerinde self-regülasyon için ilişkisel ve çevresel destek sağlar.",
    sourceIds: ["ROSANBALM_MURRAY_2017", "BLAIR_RAVER_2015"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "İlişki tek yönlü neden veya biyolojik mekanizma değildir.",
  }),
  relation({
    id: "relation.reactivity.selfreg",
    fromTopicId: "selfreg.reactivity_recovery",
    toTopicId: "selfreg.core",
    predicate: "conceptually_related_to",
    summary: "Reaktivite ve toparlanma, regülasyonun zaman içindeki davranışsal-fizyolojik görünümünü betimleyen iki ayrı boyuttur.",
    sourceIds: ["BLAIR_RAVER_2015"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Davranışsal görünüm otonom dal etkinliği ölçümü değildir.",
  }),
  relation({
    id: "relation.pfc.ef",
    fromTopicId: "cns.prefrontal_control",
    toTopicId: "selfreg.executive_functions",
    predicate: "supports",
    summary: "Prefrontal bölgeler dağıtık ağlarla birlikte yürütücü kontrol süreçlerine katkı verir.",
    sourceIds: ["FRIEDMAN_ROBBINS_2022", "DIAMOND_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Yürütücü davranıştan prefrontal bölge işlevi veya hasarı çıkarılamaz.",
  }),
  relation({
    id: "relation.insula.salience",
    fromTopicId: "cns.insula",
    toTopicId: "cns.salience_network",
    predicate: "part_of",
    summary: "Ön insula salience ağının önemli düğümlerinden biridir.",
    sourceIds: ["MENON_UDDIN_2010", "SEELEY_2019"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "İnsula veya salience ağı tek işlevli bir alarm merkezi değildir.",
  }),
  relation({
    id: "relation.insula.can",
    fromTopicId: "cns.insula",
    toTopicId: "cns.central_autonomic_network",
    predicate: "part_of",
    summary: "İnsular bölgeler merkezi otonom ağın visseral bütünleştirmeyle ilişkili düğümleri arasında sayılır.",
    sourceIds: ["SAPER_2002", "FERRARO_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "Davranıştan insula veya CAN etkinliği çıkarılamaz.",
  }),
  relation({
    id: "relation.can.ans",
    fromTopicId: "cns.central_autonomic_network",
    toTopicId: "ans.overview",
    predicate: "supports",
    summary: "Merkezi otonom ağ, otonom çıktının merkezi düzeyde bütünleştirilmesine katkı verir.",
    sourceIds: ["SAPER_2002", "LAMOTTE_ET_AL_2021"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "ANS yalnız merkezi ağdan oluşmaz; periferik ve organ içi düzenleme de önemlidir.",
  }),
  relation({
    id: "relation.interoception.insula",
    fromTopicId: "ans.interoception",
    toTopicId: "cns.insula",
    predicate: "associated_with",
    summary: "İnteroseptif işlemede insular bölgeler önemli fakat tek olmayan katkılar sağlar.",
    sourceIds: ["KHALSA_ET_AL_2018", "CRITCHLEY_HARRISON_2013"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "İnteroseptif davranıştan insula işlevi veya patolojisi çıkarılamaz.",
  }),
  relation({
    id: "relation.homeostasis.allostasis",
    fromTopicId: "ans.homeostasis",
    toTopicId: "ans.allostasis",
    predicate: "distinguished_from",
    summary: "Homeostaz geri bildirimle işlevsel aralığı korumayı, allostaz değişen ve beklenen taleplere göre ayarlamayı vurgular.",
    sourceIds: ["RAMSAY_WOODS_2014"],
    evidenceLevel: "theoretical",
    ageScope: "mixed",
    claimBoundary: "İki kavram klinik ölçüm, DNA skoru veya birbirini dışlayan tanılar değildir.",
  }),
  relation({
    id: "relation.hrv.ans",
    fromTopicId: "ans.hrv",
    toTopicId: "ans.overview",
    predicate: "measured_indirectly_by",
    summary: "HRV, kardiyak otonom modülasyonun bazı yönleri hakkında dolaylı ve protokole duyarlı bilgi sağlayabilir.",
    sourceIds: ["TASK_FORCE_HRV_1996", "LABORDE_ET_AL_2017"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "HRV ANS'nin tamamını, self-regülasyonu veya beyni doğrudan ölçmez.",
  }),
  relation({
    id: "relation.hrv.selfreg",
    fromTopicId: "ans.hrv",
    toTopicId: "selfreg.core",
    predicate: "associated_with",
    summary: "Bazı HRV ölçütleri ile self-regülasyon ve adaptif işlev arasında grup düzeyinde ilişkiler bildirilmiştir.",
    sourceIds: ["GRAZIANO_DEREFINKO_2013", "LABORDE_ET_AL_2017"],
    evidenceLevel: "moderate",
    ageScope: "mixed",
    claimBoundary: "İlişki nedensellik veya bireysel sınıflama değildir; DNA puanından HRV çıkarılamaz.",
  }),
  relation({
    id: "relation.eda.ans",
    fromTopicId: "ans.eda",
    toTopicId: "ans.overview",
    predicate: "measured_indirectly_by",
    summary: "EDA, sudomotor sempatik kontrolle ilişkili deri iletkenliği değişimini ölçer.",
    sourceIds: ["BOUCSEIN_ET_AL_2012"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "EDA belirli duyguya, tanıya veya ANS'nin tamamına özgü değildir.",
  }),
  relation({
    id: "relation.interoception.selfreg",
    fromTopicId: "ans.interoception",
    toTopicId: "selfreg.core",
    predicate: "conceptually_related_to",
    summary: "İç beden sinyallerinin işlenmesi, duygu ve davranışın bağlamsal düzenlenmesine katkı verebilecek süreçlerden biridir.",
    sourceIds: ["KHALSA_ET_AL_2018", "PINNA_EDWARDS_2020"],
    evidenceLevel: "moderate",
    ageScope: "adult_weighted",
    claimBoundary: "İlişki çok etkenlidir; tek yönlü neden veya DNA alan geçerliği değildir.",
  }),
  relation({
    id: "relation.sympathetic.ans",
    fromTopicId: "ans.sympathetic_parasympathetic",
    toTopicId: "ans.overview",
    predicate: "part_of",
    summary: "Sempatik ve parasempatik süreçler otonom sinir sisteminin başlıca efferent düzenleme bileşenleridir.",
    sourceIds: ["WEHRWEIN_ET_AL_2016"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "ANS ayrıca enterik, merkezi ve visseral afferent süreçleri kapsayan daha geniş bir sistemdir.",
  }),
  relation({
    id: "relation.space.sympathetic",
    fromTopicId: "ans.autonomic_space",
    toTopicId: "ans.sympathetic_parasympathetic",
    predicate: "supports",
    summary: "Otonom uzam modeli sempatik ve parasempatik etkinliğin basit bir tahterevalli olmadığını açıklar.",
    sourceIds: ["BERNTSON_ET_AL_1991"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Model kişiye özgü organ durumunu gözlemden belirlemez.",
  }),
  relation({
    id: "relation.measurement.hrv",
    fromTopicId: "ans.measurement_limits",
    toTopicId: "ans.hrv",
    predicate: "includes",
    summary: "HRV, otonom araştırmalarda kullanılan fakat kapsamı ve protokolü açıkça belirtilmesi gereken ölçümlerden biridir.",
    sourceIds: ["TASK_FORCE_HRV_1996", "LABORDE_ET_AL_2017"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "HRV'den küresel sempatovagal denge veya DNA alanı çıkarılamaz.",
  }),
  relation({
    id: "relation.measurement.eda",
    fromTopicId: "ans.measurement_limits",
    toTopicId: "ans.eda",
    predicate: "includes",
    summary: "EDA, sempatik sudomotor süreçlere duyarlı fakat psikolojik neden açısından özgül olmayan bir ölçümdür.",
    sourceIds: ["BOUCSEIN_ET_AL_2012"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "EDA duyusal davranış veya belirli duygu için tekil biyobelirteç değildir.",
  }),
  relation({
    id: "relation.polyvagal.ans",
    fromTopicId: "ans.polyvagal",
    toTopicId: "ans.overview",
    predicate: "conceptually_related_to",
    summary: "Polivagal teori otonom işlevi sosyal davranışla ilişkilendiren tartışmalı bir kuramsal çerçevedir.",
    sourceIds: ["PORGES_2021", "GROSSMAN_2023"],
    evidenceLevel: "theoretical",
    ageScope: "mixed",
    claimBoundary: "Yerleşik ANS anatomisiyle veya davranıştan ölçülen vagal durumla eşitlenemez.",
  }),
  relation({
    id: "relation.reverse.all-topics",
    fromTopicId: "cns.reverse_inference",
    toTopicId: "cns.distributed_networks",
    predicate: "supports",
    summary: "Dağıtık ağ yapısı, davranıştan tek beyin bölgesi çıkarımının neden güvenli olmadığını açıklar.",
    sourceIds: ["POLDRAK_2006", "FRIEDMAN_ROBBINS_2022"],
    evidenceLevel: "boundary",
    ageScope: "all_ages",
    claimBoundary: "Bu yöntem sınırı bir kişinin beyin durumu hakkında alternatif bir çıkarım sağlamaz.",
  }),
])
