import {
  DNA_CHAT_CATALOG_VERSION,
  type DnaChatCatalogRelation,
} from "./types"
import { V5_CASE_BOUNDARY_RELATIONS } from "./v5CaseBoundariesCatalog"
import { V5_COREGULATION_RELATIONS } from "./v5CoregulationCatalog"
import { V5_DEVELOPMENT_RELATIONS } from "./v5DevelopmentCatalog"
import { V5_SIX_DOMAINS_RELATIONS } from "./v5SixDomainsCatalog"

function relation(
  input: Omit<DnaChatCatalogRelation, "version" | "maxHops">,
): DnaChatCatalogRelation {
  return Object.freeze({
    version: DNA_CHAT_CATALOG_VERSION,
    maxHops: 1 as const,
    ...input,
  })
}

export const DNA_CHAT_CATALOG_RELATIONS: readonly DnaChatCatalogRelation[] = Object.freeze([
  relation({
    id: "relation.selfcontrol.selfreg",
    fromTopicId: "selfreg.self_control",
    toTopicId: "selfreg.core",
    predicate: "part_of",
    summary: "Self-kontrol, self-regülasyonun tamamı değil daha dar bir bileşenidir.",
    sourceIds: ["NIGG_2017", "INZLICHT_ET_AL_2021"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Terimlerin kullanımı literatürler arasında kısmen değişebilir.",
  }),
  relation({
    id: "relation.ef.selfreg",
    fromTopicId: "selfreg.executive_functions",
    toTopicId: "selfreg.core",
    predicate: "supports",
    summary: "Yürütücü işlevler hedefe yönelik self-regülasyonun bazı bilişsel bileşenlerini destekler.",
    sourceIds: ["DIAMOND_2013", "NIGG_2017"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Yürütücü işlev self-regülasyonun tüm duygusal, sosyal ve fizyolojik yönleriyle aynı değildir.",
  }),
  relation({
    id: "relation.coregulation.selfreg",
    fromTopicId: "selfreg.coregulation",
    toTopicId: "selfreg.core",
    predicate: "supports",
    summary: "Ko-regülasyon özellikle gelişimin erken dönemlerinde self-regülasyon için ilişkisel ve çevresel destek sağlar.",
    sourceIds: ["ROSANBALM_MURRAY_2017", "BLAIR_RAVER_2015"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "İlişki tek yönlü neden veya biyolojik mekanizma değildir.",
  }),
  relation({
    id: "relation.reactivity.selfreg",
    fromTopicId: "selfreg.reactivity_recovery",
    toTopicId: "selfreg.core",
    predicate: "conceptually_related_to",
    summary: "Reaktivite ve toparlanma, regülasyonun zaman içindeki davranışsal-fizyolojik görünümünü betimleyen iki ayrı boyuttur.",
    sourceIds: ["BLAIR_RAVER_2015"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Davranışsal görünüm otonom dal etkinliği ölçümü değildir.",
  }),
  relation({
    id: "relation.pfc.ef",
    fromTopicId: "cns.prefrontal_control",
    toTopicId: "selfreg.executive_functions",
    predicate: "supports",
    summary: "Prefrontal bölgeler dağıtık ağlarla birlikte yürütücü kontrol süreçlerine katkı verir.",
    sourceIds: ["MILLER_COHEN_2001", "FRIEDMAN_ROBBINS_2022", "DIAMOND_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Yürütücü davranıştan prefrontal bölge işlevi veya hasarı çıkarılamaz.",
  }),
  relation({
    id: "relation.pfc-development.pfc",
    fromTopicId: "cns.prefrontal_development",
    toTopicId: "cns.prefrontal_control",
    predicate: "conceptually_related_to",
    summary: "Prefrontal yapı ve bağlantıların gelişimi, kontrol süreçlerinin gelişen ağ zeminlerinden biridir.",
    sourceIds: ["KOLK_RAKIC_2022", "FISKE_HOLMBOE_2019"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Gelişimsel grup bulguları bireysel prefrontal olgunluk veya prognoz ölçmez.",
  }),
  relation({
    id: "relation.working-memory.ef",
    fromTopicId: "cns.working_memory",
    toTopicId: "selfreg.executive_functions",
    predicate: "part_of",
    summary: "Çalışma belleği yürütücü işlevler şemsiyesi altında ele alınan temel kontrol süreçlerinden biridir.",
    sourceIds: ["DIAMOND_2013", "FRIEDMAN_ROBBINS_2022"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Çalışma belleği yürütücü işlevlerin veya self-regülasyonun tamamı değildir.",
  }),
  relation({
    id: "relation.inhibitory-control.ef",
    fromTopicId: "cns.inhibitory_control",
    toTopicId: "selfreg.executive_functions",
    predicate: "part_of",
    summary: "Ketleyici kontrol yürütücü işlevlerin ilişkili fakat ayrı değerlendirilen temel bileşenlerinden biridir.",
    sourceIds: ["DIAMOND_2013", "FISKE_HOLMBOE_2019"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Tek davranış veya görev genel yürütücü kapasiteyi göstermez.",
  }),
  relation({
    id: "relation.cognitive-flexibility.ef",
    fromTopicId: "cns.cognitive_flexibility",
    toTopicId: "selfreg.executive_functions",
    predicate: "part_of",
    summary: "Bilişsel esneklik yürütücü işlevlerin çalışma belleği ve ketlemeyle etkileşen temel bileşenlerinden biridir.",
    sourceIds: ["DIAMOND_2013", "FRIEDMAN_ROBBINS_2022"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Bir bağlamdaki katılık bütün yürütücü işlevlere genellenemez.",
  }),
  relation({
    id: "relation.ef-measurement.ef",
    fromTopicId: "cns.executive_measurement",
    toTopicId: "selfreg.executive_functions",
    predicate: "conceptually_related_to",
    summary: "Performans görevleri ve günlük davranış derecelendirmeleri yürütücü işlevlere ilişkin farklı ve tamamlayıcı bilgi düzeyleri sağlar.",
    sourceIds: ["TOPLAK_ET_AL_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Bu ölçüm türleri birbirinin veya doğrudan beyin ölçümünün yerine geçmez.",
  }),
  relation({
    id: "relation.acc.midcingulate",
    fromTopicId: "cns.anterior_cingulate",
    toTopicId: "cns.midcingulate",
    predicate: "distinguished_from",
    summary: "Bazı modern anatomik sınıflamalar orta singulatı ACC'den ayırır; dACC ile aMCC etiketleri yine de kaynaklar arasında kısmen örtüşebilir.",
    sourceIds: ["HEILBRONNER_HAYDEN_2016", "BUSH_ET_AL_2000"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "Terimler atlas belirtilmeden tam eş anlamlı veya tamamen ayrık kabul edilmemelidir.",
  }),
  relation({
    id: "relation.performance-monitoring.acc",
    fromTopicId: "cns.performance_monitoring",
    toTopicId: "cns.anterior_cingulate",
    predicate: "associated_with",
    summary: "ACC ve komşu medial frontal bölgeler performans izleme görevlerinde sık bildirilir; süreç tek bir bölgeye indirgenemez.",
    sourceIds: ["CARTER_VAN_VEEN_2007", "HEILBRONNER_HAYDEN_2016"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "Hata davranışından ACC etkinliği veya hasarı çıkarılamaz.",
  }),
  relation({
    id: "relation.acc.prefrontal-control",
    fromTopicId: "cns.anterior_cingulate",
    toTopicId: "cns.prefrontal_control",
    predicate: "distinguished_from",
    summary: "ACC ve prefrontal kontrol bölgeleri birebir eş anlamlı etiketler değildir; sınırları kullanılan anatomi ve parselasyon tanımına göre değişebilir. Bilişsel kontrol ve performans izleme modellerinde etkileşen düğümler olarak ele alınırlar.",
    sourceIds: ["BUSH_ET_AL_2000", "HEILBRONNER_HAYDEN_2016", "CARTER_VAN_VEEN_2007", "MILLER_COHEN_2001"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "Anatomik ayrım veya grup düzeyi ilişki ACC'yi tek kontrol merkezi yapmaz ve davranıştan bireysel bölge işlevi çıkarmaz.",
  }),
  relation({
    id: "relation.performance-monitoring.ef",
    fromTopicId: "cns.performance_monitoring",
    toTopicId: "selfreg.executive_functions",
    predicate: "supports",
    summary: "Performans izleme, kontrol gereksinimini belirleyerek yürütücü ayarlamalara katkı verebilir.",
    sourceIds: ["CARTER_VAN_VEEN_2007", "FRIEDMAN_ROBBINS_2022"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "İzleme ile kontrol aynı süreç değildir ve ilişki bireysel neden göstermez.",
  }),
  relation({
    id: "relation.performance-monitoring.ern",
    fromTopicId: "cns.performance_monitoring",
    toTopicId: "cns.error_related_negativity",
    predicate: "measured_indirectly_by",
    summary: "ERN, performans izlemenin hata sonrasındaki elektrofizyolojik yönlerinden birini dolaylı olarak araştırmak için kullanılır.",
    sourceIds: ["WIERSEMA_ET_AL_2007", "CARTER_VAN_VEEN_2007"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "ERN performans izlemenin tamamı veya ACC'nin doğrudan ölçümü değildir.",
  }),
  relation({
    id: "relation.cingulo-opercular.insula",
    fromTopicId: "cns.cingulo_opercular_network",
    toTopicId: "cns.insula",
    predicate: "includes",
    summary: "Singulo-operküler ağ tanımlarında anterior insula veya frontal operkulum temel düğümler arasında yer alır.",
    sourceIds: ["MENON_UDDIN_2010", "UDDIN_ET_AL_2017"],
    evidenceLevel: "moderate",
    ageScope: "adult_weighted",
    claimBoundary: "Ağ düğümü üyeliği insulanın tek işlevini veya bireysel aktivitesini göstermez.",
  }),
  relation({
    id: "relation.cingulo-opercular.salience",
    fromTopicId: "cns.cingulo_opercular_network",
    toTopicId: "cns.salience_network",
    predicate: "distinguished_from",
    summary: "Singulo-operküler ve salience ağı etiketleri düğüm örtüşmesi gösterebilir, ancak her atlas ve kuramda tam eş anlamlı değildir.",
    sourceIds: ["MENON_UDDIN_2010", "UDDIN_ET_AL_2017", "SEELEY_2019"],
    evidenceLevel: "moderate",
    ageScope: "adult_weighted",
    claimBoundary: "Ağ adları yöntem ve parselasyon belirtilmeden birbirinin yerine kullanılmamalıdır.",
  }),
  relation({
    id: "relation.insula.salience",
    fromTopicId: "cns.insula",
    toTopicId: "cns.salience_network",
    predicate: "part_of",
    summary: "Ön insula salience ağının önemli düğümlerinden biridir.",
    sourceIds: ["MENON_UDDIN_2010", "SEELEY_2019"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "İnsula veya salience ağı tek işlevli bir alarm merkezi değildir.",
  }),
  relation({
    id: "relation.insula-subregions.insula",
    fromTopicId: "cns.insula_subregions",
    toTopicId: "cns.insula",
    predicate: "part_of",
    summary: "Anterior, posterior ve bağlantısallık temelli alt bölgeler insular korteks içindeki işlevsel-anatomik eğilimleri açıklar.",
    sourceIds: ["UDDIN_ET_AL_2017", "KURTH_ET_AL_2010"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "Alt bölgeler keskin veya tek işlevli modüller değildir.",
  }),
  relation({
    id: "relation.insula-measurement.insula",
    fromTopicId: "cns.insula_measurement",
    toTopicId: "cns.insula",
    predicate: "conceptually_related_to",
    summary: "Yapısal ve işlevsel nörogörüntüleme yöntemleri insula hakkında farklı veri düzeyleri sağlar.",
    sourceIds: ["UDDIN_ET_AL_2017", "KURTH_ET_AL_2010", "SCHULZ_2016", "POLDRAK_2006"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "Hiçbir tek yöntem, görev veya davranış insulanın bütün işlevlerini ölçmez.",
  }),
  relation({
    id: "relation.insula.can",
    fromTopicId: "cns.insula",
    toTopicId: "cns.central_autonomic_network",
    predicate: "part_of",
    summary: "İnsular bölgeler merkezi otonom ağın visseral bütünleştirmeyle ilişkili düğümleri arasında sayılır.",
    sourceIds: ["SAPER_2002", "FERRARO_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "Davranıştan insula veya CAN etkinliği çıkarılamaz.",
  }),
  relation({
    id: "relation.can.ans",
    fromTopicId: "cns.central_autonomic_network",
    toTopicId: "ans.overview",
    predicate: "supports",
    summary: "Merkezi otonom ağ, otonom çıktının merkezi düzeyde bütünleştirilmesine katkı verir.",
    sourceIds: ["SAPER_2002", "LAMOTTE_ET_AL_2021"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "ANS yalnız merkezi ağdan oluşmaz; periferik ve organ içi düzenleme de önemlidir.",
  }),
  relation({
    id: "relation.interoception.insula",
    fromTopicId: "ans.interoception",
    toTopicId: "cns.insula",
    predicate: "associated_with",
    summary: "İnteroseptif işlemede insular bölgeler önemli fakat tek olmayan katkılar sağlar.",
    sourceIds: ["KHALSA_ET_AL_2018", "CRITCHLEY_HARRISON_2013"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "İnteroseptif davranıştan insula işlevi veya patolojisi çıkarılamaz.",
  }),
  relation({
    id: "relation.interoception.dimensions",
    fromTopicId: "ans.interoception",
    toTopicId: "ans.interoception_dimensions",
    predicate: "includes",
    summary: "İnterosepsiyon görev performansı, öz-bildirim eğilimi ve metabilişsel farkındalık gibi ayrılması gereken boyutlar içerir.",
    sourceIds: ["GARFINKEL_ET_AL_2015", "DESMEDT_ET_AL_2023", "KHALSA_ET_AL_2018"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Bir boyut diğerlerinin veya genel kapasitenin doğrudan ölçümü değildir.",
  }),
  relation({
    id: "relation.interoception.measurement",
    fromTopicId: "ans.interoception",
    toTopicId: "ans.interoception_measurement",
    predicate: "measured_indirectly_by",
    summary: "İnterosepsiyon farklı görev ve öz-bildirim yöntemleriyle kısmi ve yönteme özgü biçimde incelenir.",
    sourceIds: ["DESMEDT_ET_AL_2023", "DONAGHY_ET_AL_2025", "ADDABBO_MILANI_2025"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Evrensel tek altın standart yoktur ve DNA bu ölçümlerin yerine geçmez.",
  }),
  relation({
    id: "relation.interoception.development",
    fromTopicId: "ans.interoception_development",
    toTopicId: "ans.interoception",
    predicate: "conceptually_related_to",
    summary: "İnteroseptif duyarlılık erken yaşamda incelenebilir; yaşa özgü görev ve yorum sınırları gerektirir.",
    sourceIds: ["MAISTER_ET_AL_2017", "ADDABBO_MILANI_2025"],
    evidenceLevel: "limited",
    ageScope: "childhood",
    claimBoundary: "Bebek duyarlılığı bilinçli farkındalık, norm veya bireysel prognoz değildir.",
  }),
  relation({
    id: "relation.interoception.modalities",
    fromTopicId: "ans.interoception",
    toTopicId: "ans.interoception_modalities",
    predicate: "includes",
    summary: "İnterosepsiyon kardiyak, solunumsal, gastrointestinal ve başka beden sinyali modalitelerini kapsar.",
    sourceIds: ["CHEN_ET_AL_2021", "QUIGLEY_ET_AL_2021"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Bir modalitedeki sonuç diğer modalitelere otomatik genellenemez.",
  }),
  relation({
    id: "relation.homeostasis.allostasis",
    fromTopicId: "ans.homeostasis",
    toTopicId: "ans.allostasis",
    predicate: "distinguished_from",
    summary: "Homeostaz geri bildirimle işlevsel aralığı korumayı, allostaz değişen ve beklenen taleplere göre ayarlamayı vurgular.",
    sourceIds: ["RAMSAY_WOODS_2014"],
    evidenceLevel: "theoretical",
    ageScope: "mixed",
    claimBoundary: "İki kavram klinik ölçüm, DNA skoru veya birbirini dışlayan tanılar değildir.",
  }),
  relation({
    id: "relation.hrv.ans",
    fromTopicId: "ans.hrv",
    toTopicId: "ans.overview",
    predicate: "measured_indirectly_by",
    summary: "HRV, kardiyak otonom modülasyonun bazı yönleri hakkında dolaylı ve protokole duyarlı bilgi sağlayabilir.",
    sourceIds: ["TASK_FORCE_HRV_1996", "LABORDE_ET_AL_2017"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "HRV ANS'nin tamamını, self-regülasyonu veya beyni doğrudan ölçmez.",
  }),
  relation({
    id: "relation.hrv.selfreg",
    fromTopicId: "ans.hrv",
    toTopicId: "selfreg.core",
    predicate: "associated_with",
    summary: "Bazı HRV ölçütleri ile self-regülasyon ve adaptif işlev arasında grup düzeyinde ilişkiler bildirilmiştir.",
    sourceIds: ["GRAZIANO_DEREFINKO_2013", "LABORDE_ET_AL_2017"],
    evidenceLevel: "moderate",
    ageScope: "mixed",
    claimBoundary: "İlişki nedensellik veya bireysel sınıflama değildir; DNA puanından HRV çıkarılamaz.",
  }),
  relation({
    id: "relation.eda.ans",
    fromTopicId: "ans.eda",
    toTopicId: "ans.overview",
    predicate: "measured_indirectly_by",
    summary: "EDA, sudomotor sempatik kontrolle ilişkili deri iletkenliği değişimini ölçer.",
    sourceIds: ["BOUCSEIN_ET_AL_2012"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "EDA belirli duyguya, tanıya veya ANS'nin tamamına özgü değildir.",
  }),
  relation({
    id: "relation.interoception.selfreg",
    fromTopicId: "ans.interoception",
    toTopicId: "selfreg.core",
    predicate: "conceptually_related_to",
    summary: "İç beden sinyallerinin işlenmesi, duygu ve davranışın bağlamsal düzenlenmesine katkı verebilecek süreçlerden biridir.",
    sourceIds: ["KHALSA_ET_AL_2018", "PINNA_EDWARDS_2020"],
    evidenceLevel: "moderate",
    ageScope: "adult_weighted",
    claimBoundary: "İlişki çok etkenlidir; tek yönlü neden veya DNA alan geçerliği değildir.",
  }),
  relation({
    id: "relation.sympathetic.ans",
    fromTopicId: "ans.sympathetic_parasympathetic",
    toTopicId: "ans.overview",
    predicate: "part_of",
    summary: "Sempatik ve parasempatik süreçler otonom sinir sisteminin başlıca efferent düzenleme bileşenleridir.",
    sourceIds: ["WEHRWEIN_ET_AL_2016"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "ANS ayrıca enterik, merkezi ve visseral afferent süreçleri kapsayan daha geniş bir sistemdir.",
  }),
  relation({
    id: "relation.space.sympathetic",
    fromTopicId: "ans.autonomic_space",
    toTopicId: "ans.sympathetic_parasympathetic",
    predicate: "supports",
    summary: "Otonom uzam modeli sempatik ve parasempatik etkinliğin basit bir tahterevalli olmadığını açıklar.",
    sourceIds: ["BERNTSON_ET_AL_1991"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Model kişiye özgü organ durumunu gözlemden belirlemez.",
  }),
  relation({
    id: "relation.measurement.hrv",
    fromTopicId: "ans.measurement_limits",
    toTopicId: "ans.hrv",
    predicate: "includes",
    summary: "HRV, otonom araştırmalarda kullanılan fakat kapsamı ve protokolü açıkça belirtilmesi gereken ölçümlerden biridir.",
    sourceIds: ["TASK_FORCE_HRV_1996", "LABORDE_ET_AL_2017"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "HRV'den küresel sempatovagal denge veya DNA alanı çıkarılamaz.",
  }),
  relation({
    id: "relation.measurement.eda",
    fromTopicId: "ans.measurement_limits",
    toTopicId: "ans.eda",
    predicate: "includes",
    summary: "EDA, sempatik sudomotor süreçlere duyarlı fakat psikolojik neden açısından özgül olmayan bir ölçümdür.",
    sourceIds: ["BOUCSEIN_ET_AL_2012"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "EDA duyusal davranış veya belirli duygu için tekil biyobelirteç değildir.",
  }),
  relation({
    id: "relation.polyvagal.ans",
    fromTopicId: "ans.polyvagal",
    toTopicId: "ans.overview",
    predicate: "conceptually_related_to",
    summary: "Polivagal teori otonom işlevi sosyal davranışla ilişkilendiren tartışmalı bir kuramsal çerçevedir.",
    sourceIds: ["PORGES_2021", "GROSSMAN_2023"],
    evidenceLevel: "theoretical",
    ageScope: "mixed",
    claimBoundary: "Yerleşik ANS anatomisiyle veya davranıştan ölçülen vagal durumla eşitlenemez.",
  }),
  relation({
    id: "relation.reverse.all-topics",
    fromTopicId: "cns.reverse_inference",
    toTopicId: "cns.distributed_networks",
    predicate: "supports",
    summary: "Dağıtık ağ yapısı, davranıştan tek beyin bölgesi çıkarımının neden güvenli olmadığını açıklar.",
    sourceIds: ["POLDRAK_2006", "FRIEDMAN_ROBBINS_2022"],
    evidenceLevel: "boundary",
    ageScope: "all_ages",
    claimBoundary: "Bu yöntem sınırı bir kişinin beyin durumu hakkında alternatif bir çıkarım sağlamaz.",
  }),
  relation({
    id: "relation.arousal.reactivity",
    fromTopicId: "selfreg.arousal",
    toTopicId: "selfreg.reactivity_recovery",
    predicate: "conceptually_related_to",
    summary: "Uyarılma düzeyindeki bağlamsal değişimler reaktivite örüntüsünün bileşenlerinden biri olabilir; kavramlar özdeş değildir.",
    sourceIds: ["BURT_OBRADOVIC_2013", "BATES_ET_AL_2022"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Davranıştan biyolojik uyarılma sistemi, ANS dalı veya kişisel mekanizma çıkarılamaz.",
  }),
  relation({
    id: "relation.recovery.measurement",
    fromTopicId: "selfreg.reactivity_recovery",
    toTopicId: "selfreg.recovery_measurement",
    predicate: "measured_indirectly_by",
    summary: "Toparlanma, seçilen davranışsal veya fizyolojik göstergenin zaman içindeki değişimiyle kısmi ve yönteme özgü biçimde değerlendirilir.",
    sourceIds: ["BURT_OBRADOVIC_2013", "JONES_MASON_ET_AL_2018", "SACREY_ET_AL_2021"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Tek gösterge bütün sistemlerin toparlanmasını veya DNA alanını ölçmez.",
  }),
  relation({
    id: "relation.recovery.selfreg",
    fromTopicId: "selfreg.reactivity_recovery",
    toTopicId: "selfreg.core",
    predicate: "conceptually_related_to",
    summary: "Tepkinin bağlama uygun biçimde zaman içinde değişmesi self-regülasyonun gözlenebilen yönlerinden biridir.",
    sourceIds: ["COLE_ET_AL_2004", "COLE_ET_AL_2020", "BLAIR_RAVER_2015"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Toparlanma tek başına genel self-regülasyon kapasitesi, neden veya prognoz değildir.",
  }),
  relation({
    id: "relation.selforganization.recovery",
    fromTopicId: "selfreg.self_organization",
    toTopicId: "selfreg.reactivity_recovery",
    predicate: "distinguished_from",
    summary: "Öz-örgütlenme örüntünün çok bileşenli ortaya çıkışını; toparlanma belirli bir değişimden sonraki zaman seyrini anlatır.",
    sourceIds: ["SMITH_THELEN_2003", "COLE_ET_AL_2020"],
    evidenceLevel: "theoretical",
    ageScope: "developmental",
    claimBoundary: "İki kuramsal kavram tek vakada doğrudan ölçülen mekanizma veya klinik etiket değildir.",
  }),
  relation({
    id: "relation.habituation.recovery",
    fromTopicId: "selfreg.habituation",
    toTopicId: "selfreg.reactivity_recovery",
    predicate: "distinguished_from",
    summary: "Habituasyon tekrarlanan özgül uyarana yanıt azalmasıdır; toparlanma ise değişim sonrası zaman içindeki dönüş örüntüsüdür.",
    sourceIds: ["RANKIN_ET_AL_2009", "BURT_OBRADOVIC_2013"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "Tepki azalması bütün sistemlerin toparlandığını veya sorunun sona erdiğini göstermez.",
  }),
  relation({
    id: "relation.sensory.selfreg",
    fromTopicId: "selfreg.sensory_modulation",
    toTopicId: "selfreg.core",
    predicate: "conceptually_related_to",
    summary: "Duyusal girdiye yanıtın günlük hedef ve bağlama uyarlanması self-regülasyonun işlevsel bağlamlarından biri olarak ele alınabilir.",
    sourceIds: ["DUNN_2001", "WATKYNS_ET_AL_2024", "NIGG_2017"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Kavramsal yakınlık DNA alan geçerliği, tanı veya tek biyolojik mekanizma kanıtı değildir.",
  }),
  relation({
    id: "relation.sensory.measurement",
    fromTopicId: "selfreg.sensory_modulation",
    toTopicId: "selfreg.sensory_measurement",
    predicate: "measured_indirectly_by",
    summary: "Duyusal yanıt örüntüleri bildirim, gözlem ve performans yöntemleriyle kısmi ve yönteme özgü biçimde değerlendirilir.",
    sourceIds: ["WATKYNS_ET_AL_2024"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Tek yöntem biyolojik eşik, tüm bağlamlardaki kapasite veya tanı sağlamaz.",
  }),
  relation({
    id: "relation.sensory.arousal",
    fromTopicId: "selfreg.sensory_modulation",
    toTopicId: "selfreg.arousal",
    predicate: "conceptually_related_to",
    summary: "Duyusal girdiye yanıt ile uyarılma süreçleri bazı bağlamlarda ilişkili olabilir; davranışsal örüntü biyolojik uyarılma ölçümü değildir.",
    sourceIds: ["GOMEZ_ET_AL_2017", "WATKYNS_ET_AL_2024"],
    evidenceLevel: "limited",
    ageScope: "childhood",
    claimBoundary: "Duyusal aşırı veya düşük yanıtlılıktan ANS durumu, vagal ton ya da beyin bölgesi çıkarılamaz.",
  }),
  relation({
    id: "relation.emotion.reactivity",
    fromTopicId: "selfreg.emotion_regulation",
    toTopicId: "selfreg.reactivity_recovery",
    predicate: "distinguished_from",
    summary: "Duygusal reaktivite ilk tepkinin özelliklerini; düzenleme ise tepkinin hedef ve bağlama göre zaman içinde nasıl değiştiğini anlatır.",
    sourceIds: ["COLE_ET_AL_2004", "REITSEMA_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Güçlü duygu tek başına düzenleme güçlüğü, biyolojik mekanizma veya tanı değildir.",
  }),
  relation({
    id: "relation.emotion.selfreg",
    fromTopicId: "selfreg.emotion_regulation",
    toTopicId: "selfreg.core",
    predicate: "part_of",
    summary: "Duygu düzenleme, self-regülasyonun duygunun zamanlaması, yoğunluğu, ifadesi ve hedefle ilişkili kullanımına odaklanan bileşenidir.",
    sourceIds: ["NIGG_2017", "COLE_ET_AL_2004", "GROSS_2015"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Duygu düzenleme self-regülasyonun tamamı veya tek biyolojik mekanizması değildir.",
  }),
  relation({
    id: "relation.emotion.strategies",
    fromTopicId: "selfreg.emotion_strategies",
    toTopicId: "selfreg.emotion_regulation",
    predicate: "part_of",
    summary: "Dikkati yönlendirme, yeniden değerlendirme, kabul ve ifade düzenleme gibi stratejiler duygu düzenleme repertuarının farklı parçalarıdır.",
    sourceIds: ["GROSS_2015", "BONANNO_BURTON_2013"],
    evidenceLevel: "moderate",
    ageScope: "adult_weighted",
    claimBoundary: "Hiçbir strateji her bağlamda evrensel olarak iyi veya kötü değildir; katalog kişisel müdahale önermez.",
  }),
  relation({
    id: "relation.emotion.measurement",
    fromTopicId: "selfreg.emotion_regulation",
    toTopicId: "selfreg.emotion_measurement",
    predicate: "measured_indirectly_by",
    summary: "Duygu düzenleme bildirim, gözlem, görev ve tekrarlı günlük yaşam ölçümleriyle farklı bileşenler üzerinden incelenir.",
    sourceIds: ["COLE_ET_AL_2004", "MAZEFSKY_ET_AL_2021", "REITSEMA_ET_AL_2022"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Tek puan düzenleyici niyet, biyolojik mekanizma, tanı veya bütün repertuar değildir.",
  }),
  relation({
    id: "relation.interoception.emotion",
    fromTopicId: "ans.interoception",
    toTopicId: "selfreg.emotion_regulation",
    predicate: "associated_with",
    summary: "İç beden sinyallerinin işlenmesi ile duygu deneyimi ve düzenleme arasında grup düzeyinde ilişkiler bildirilmiştir.",
    sourceIds: ["PINNA_EDWARDS_2020", "KHALSA_ET_AL_2018", "COLE_ET_AL_2004"],
    evidenceLevel: "moderate",
    ageScope: "adult_weighted",
    claimBoundary: "İlişkinin yönü ve kişisel mekanizması belirlenemez; DNA alanları biyolojik doğrulama değildir.",
  }),
  relation({
    id: "relation.hrv.recovery",
    fromTopicId: "ans.hrv",
    toTopicId: "selfreg.recovery_measurement",
    predicate: "measured_indirectly_by",
    summary: "HRV/RSA bazı görevlerde kardiyak otonom değişimin zaman seyrine ilişkin bilgi sağlayabilir; bütün toparlanmanın ölçümü değildir.",
    sourceIds: ["LABORDE_ET_AL_2017", "JONES_MASON_ET_AL_2018", "SACREY_ET_AL_2021"],
    evidenceLevel: "moderate",
    ageScope: "mixed",
    claimBoundary: "Tek HRV/RSA ölçümü davranışsal, hormonal veya genel self-regülasyon toparlanmasını göstermez.",
  }),
  relation({
    id: "relation.habituation.sensory",
    fromTopicId: "selfreg.habituation",
    toTopicId: "selfreg.sensory_modulation",
    predicate: "distinguished_from",
    summary: "Habituasyon yinelenen özgül uyarana öğrenmeye bağlı tepki azalmasıdır; duyusal modülasyon günlük girdiye yanıt örüntülerini daha geniş bağlamda betimler.",
    sourceIds: ["RANKIN_ET_AL_2009", "DUNN_2001"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "Kaçınma veya tepki azalması tek başına habituasyon, duyusal bozukluk ya da fizyolojik toparlanma kanıtı değildir.",
  }),
  relation({
    id: "relation.sensory.interoception",
    fromTopicId: "selfreg.sensory_modulation",
    toTopicId: "ans.interoception",
    predicate: "distinguished_from",
    summary: "Duyusal modülasyon çoğunlukla dış ve beden kaynaklı girdiye işlevsel yanıt örüntülerini; interosepsiyon iç beden sinyallerinin işlenmesini vurgular.",
    sourceIds: ["DUNN_2001", "KHALSA_ET_AL_2018"],
    evidenceLevel: "moderate",
    ageScope: "mixed",
    claimBoundary: "Kavramlar örtüşebilir fakat eşdeğer değildir; bir alandaki davranış diğerindeki kapasiteyi ölçmez.",
  }),
  relation({
    id: "relation.executive.emotion",
    fromTopicId: "selfreg.executive_functions",
    toTopicId: "selfreg.emotion_regulation",
    predicate: "associated_with",
    summary: "Yürütücü işlevler bazı duygu düzenleme stratejilerine katkı verebilir; duygu düzenleme yürütücü işlevle aynı yapı değildir.",
    sourceIds: ["DIAMOND_2013", "NIGG_2017", "COLE_ET_AL_2004"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "İlişki tek yönlü neden, tanı veya davranıştan beyin mekanizması çıkarımı değildir.",
  }),
  relation({
    id: "relation.inhibition.emotion",
    fromTopicId: "cns.inhibitory_control",
    toTopicId: "selfreg.emotion_regulation",
    predicate: "associated_with",
    summary: "Ketleyici kontrol bazı duygusal yanıtların yönetimine katkı verebilir; duygu düzenleme için tek başına yeterli değildir.",
    sourceIds: ["DIAMOND_2013", "COLE_ET_AL_2004", "NIGG_2017"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Gözlenen ketleme davranışı bütün duygu düzenleme repertuarını veya biyolojik mekanizmayı göstermez.",
  }),
  relation({
    id: "relation.arousal.emotion",
    fromTopicId: "selfreg.arousal",
    toTopicId: "selfreg.emotion_regulation",
    predicate: "conceptually_related_to",
    summary: "Fizyolojik uyarılma duygu süreçlerine eşlik edebilir; duygu düzenleme ile aynı yapı veya tek yönlü neden değildir.",
    sourceIds: ["SACREY_ET_AL_2021", "COLE_ET_AL_2004", "ASTON_JONES_COHEN_2005"],
    evidenceLevel: "moderate",
    ageScope: "mixed",
    claimBoundary: "Davranış veya duygu puanından fizyolojik uyarılma düzeyi ve kişisel mekanizma çıkarılamaz.",
  }),
  relation({
    id: "relation.hpa.stress-systems",
    fromTopicId: "selfreg.hpa_axis",
    toTopicId: "selfreg.stress_systems",
    predicate: "part_of",
    summary: "HPA ekseni çok sistemli stres yanıtı içinde incelenen nöroendokrin bileşenlerden biridir.",
    sourceIds: ["CHROUSOS_2009", "MCEWEN_2007", "GUNNAR_QUEVEDO_2007"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "HPA ekseni stres yanıtının tamamı değildir; davranış veya DNA profili hormon işlevini ölçmez.",
  }),
  relation({
    id: "relation.stress-systems.ans",
    fromTopicId: "selfreg.stress_systems",
    toTopicId: "ans.overview",
    predicate: "conceptually_related_to",
    summary: "Otonom süreçler, çok sistemli stres yanıtına katkı verebilen bileşenlerden biridir.",
    sourceIds: ["CHROUSOS_2009", "MCEWEN_2007"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Otonom yanıt bütün stres yanıtıyla eşdeğer değildir ve tek bir davranıştan belirlenemez.",
  }),
  relation({
    id: "relation.stress-systems.reactivity-recovery",
    fromTopicId: "selfreg.stress_systems",
    toTopicId: "selfreg.reactivity_recovery",
    predicate: "conceptually_related_to",
    summary: "Stres sistemleri farklı zaman ölçeklerinde reaktivite ve toparlanma örüntüleri gösterebilir.",
    sourceIds: ["CHROUSOS_2009", "GUNNAR_QUEVEDO_2007"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Davranışsal reaktivite belirli hormon veya otonom sistem tepkisini göstermez.",
  }),
  relation({
    id: "relation.toxic-stress.stress-systems",
    fromTopicId: "selfreg.toxic_stress",
    toTopicId: "selfreg.stress_systems",
    predicate: "conceptually_related_to",
    summary: "Toksik stres çerçevesi uzun süreli güçlük ve yetersiz koruyucu desteğin gelişimsel stres sistemleriyle ilişkisini ele alır.",
    sourceIds: ["SHONKOFF_ET_AL_2012", "GUNNAR_QUEVEDO_2007"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Bu çerçeve tek çocukta travma, kalıcı hasar veya stres sistemi bozukluğu tanısı değildir.",
  }),
  relation({
    id: "relation.allostatic-load.allostasis",
    fromTopicId: "ans.allostatic_load",
    toTopicId: "ans.allostasis",
    predicate: "conceptually_related_to",
    summary: "Allostatik yük, tekrarlayan veya uzun süreli uyum talepleriyle ilişkili çoklu sistem göstergelerini inceleyen allostaz temelli bir araştırma çerçevesidir.",
    sourceIds: ["MCEWEN_1998", "MCEWEN_2007", "LUCENTE_GUIDI_2023"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Allostatik yük davranıştan veya DNA puanından hesaplanan bireysel hasar skoru değildir.",
  }),
  relation({
    id: "relation.hpa.cortisol-measurement",
    fromTopicId: "selfreg.hpa_axis",
    toTopicId: "selfreg.cortisol_measurement",
    predicate: "measured_indirectly_by",
    summary: "Kortizol örneklemesi HPA ekseninin belirli zaman özelliklerini dolaylı olarak incelemek için kullanılabilir.",
    sourceIds: ["STALDER_ET_AL_2016", "CHROUSOS_2009", "GUNNAR_QUEVEDO_2007"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Tek kortizol örneği bütün HPA işlevini, travmayı veya kişisel stres kapasitesini ölçmez.",
  }),
  relation({
    id: "relation.daily-rhythm.circadian-rhythm",
    fromTopicId: "selfreg.daily_rhythm",
    toTopicId: "selfreg.circadian_rhythm",
    predicate: "distinguished_from",
    summary: "Gözlenebilir günlük uyku-etkinlik örüntüsü ile içsel sirkadiyen zamanlama ilişkili fakat ayrı düzeylerdir.",
    sourceIds: ["BORBELY_ET_AL_2016", "HASTINGS_ET_AL_2018"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Rutin veya yatış saati kişisel sirkadiyen fazı, melatonini ya da SCN işlevini doğrudan göstermez.",
  }),
  relation({
    id: "relation.sleep-regulation.circadian-rhythm",
    fromTopicId: "selfreg.sleep_regulation",
    toTopicId: "selfreg.circadian_rhythm",
    predicate: "conceptually_related_to",
    summary: "İki süreçli uyku modelinde sirkadiyen zamanlama, homeostatik uyku basıncıyla etkileşen kuramsal süreçlerden biridir.",
    sourceIds: ["BORBELY_ET_AL_2016"],
    evidenceLevel: "theoretical",
    ageScope: "mixed",
    claimBoundary: "Model süreçleri davranıştan veya DNA profilinden ölçülen kişisel biyolojik değerler değildir.",
  }),
  relation({
    id: "relation.sleep-health.daily-rhythm",
    fromTopicId: "selfreg.sleep_health",
    toTopicId: "selfreg.daily_rhythm",
    predicate: "conceptually_related_to",
    summary: "Uyku zamanlaması ve düzenliliği, günlük uyku-uyanıklık örüntüsüyle ilişkili uyku sağlığı boyutlarıdır.",
    sourceIds: ["INHULSEN_ET_AL_2022", "GALLAND_ET_AL_2012", "BORBELY_ET_AL_2016"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Günlük düzenlilik tek başına uyku sağlığını, biyolojik saati veya tanıyı belirlemez.",
  }),
  relation({
    id: "relation.sleep-health.selfreg",
    fromTopicId: "selfreg.sleep_health",
    toTopicId: "selfreg.core",
    predicate: "associated_with",
    summary: "Uyku örüntüleri ile çocukların bilişsel, duygusal ve davranışsal self-regülasyon göstergeleri arasında grup düzeyinde ilişkiler bildirilmiştir.",
    sourceIds: ["ASTILL_ET_AL_2012", "GREGORY_SADEH_2012"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "İlişki çift yönlü olabilir; uyku tek başına bireysel regülasyon örüntüsünün nedeni değildir.",
  }),
  relation({
    id: "relation.sleep-health.emotion",
    fromTopicId: "selfreg.sleep_health",
    toTopicId: "selfreg.emotion_regulation",
    predicate: "associated_with",
    summary: "Çocuklukta uyku örüntüleri ile duygusal işlev arasında grup düzeyinde ve çoğu zaman çift yönlü ilişkiler bildirilmiştir.",
    sourceIds: ["GREGORY_SADEH_2012"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Uyku gözlemi kişisel duygu düzenleme mekanizmasını, tanıyı veya tek yönlü nedeni göstermez.",
  }),
  relation({
    id: "relation.sleep-health.executive-functions",
    fromTopicId: "selfreg.sleep_health",
    toTopicId: "selfreg.executive_functions",
    predicate: "associated_with",
    summary: "Çocuklukta uyku örüntüleri ile yürütücü ve bilişsel performans arasında grup düzeyinde ilişkiler bildirilmiştir.",
    sourceIds: ["ASTILL_ET_AL_2012"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Uyku süresi veya kalitesi tek çocukta yürütücü güçlüğün nedeni, tanısı ya da prognozu değildir.",
  }),
  relation({
    id: "relation.sleep-health.attention",
    fromTopicId: "selfreg.sleep_health",
    toTopicId: "cns.attention",
    predicate: "associated_with",
    summary: "Çocuklukta uyku örüntüleri ile dikkat performansı arasında grup düzeyinde ilişkiler bildirilmiştir.",
    sourceIds: ["ASTILL_ET_AL_2012", "INHULSEN_ET_AL_2022"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Uyku ritmi veya dikkat davranışı tek çocukta neden, tanı, prognoz ya da doğrudan biyolojik mekanizma göstermez.",
  }),
  relation({
    id: "relation.executive-models.executive-functions",
    fromTopicId: "cns.executive_models",
    toTopicId: "selfreg.executive_functions",
    predicate: "conceptually_related_to",
    summary: "Birlik ve çeşitlilik modelleri yürütücü işlevlerin ortak fakat kısmen ayrışan bileşenlerini kuramsal olarak düzenler.",
    sourceIds: ["MIYAKE_ET_AL_2000", "KARR_ET_AL_2018", "DOEBEL_2020", "DIAMOND_2013"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Model faktörleri tek biyolojik mekanizma, sabit bireysel kapasite veya DNA geçerliği değildir.",
  }),
  relation({
    id: "relation.executive-development.executive-functions",
    fromTopicId: "cns.executive_development",
    toTopicId: "selfreg.executive_functions",
    predicate: "conceptually_related_to",
    summary: "Yürütücü işlev bileşenleri çocukluk boyunca farklı hızlarda ve görev taleplerine duyarlı biçimde gelişir.",
    sourceIds: ["GARON_ET_AL_2008", "HENDRY_ET_AL_2016", "DIAMOND_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Grup düzeyi gelişim örüntüsü tek çocukta olgunluk, gecikme veya prognoz vermez.",
  }),
  relation({
    id: "relation.working-memory-development.working-memory",
    fromTopicId: "cns.working_memory_development",
    toTopicId: "cns.working_memory",
    predicate: "conceptually_related_to",
    summary: "Çalışma belleğinin depolama ve kontrol taleplerindeki performans çocukluk boyunca ortalama olarak değişir.",
    sourceIds: ["COWAN_2014", "GATHERCOLE_ET_AL_2004", "BADDELEY_2000"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Yaş eğilimi tek çocukta sabit kapasite, zeka veya tanı eşiği değildir.",
  }),
  relation({
    id: "relation.working-memory.working-memory-measurement",
    fromTopicId: "cns.working_memory",
    toTopicId: "cns.working_memory_measurement",
    predicate: "measured_indirectly_by",
    summary: "Span ve güncelleme görevleri çalışma belleğinin farklı taleplerini dolaylı olarak örnekler.",
    sourceIds: ["ANDERSON_REIDY_2012", "HEDGE_ET_AL_2018", "TOPLAK_ET_AL_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Tek görev bütün çalışma belleğini, frontal-lob işlevini veya değişmez bireysel kapasiteyi ölçmez.",
  }),
  relation({
    id: "relation.attention-networks.attention",
    fromTopicId: "cns.attention_networks",
    toTopicId: "cns.attention",
    predicate: "part_of",
    summary: "Uyarılma, yöneltme ve yürütücü kontrol ağları dikkat süreçlerini analitik olarak açıklayan ilişkili modellerdir.",
    sourceIds: ["PETERSEN_POSNER_2012", "RUEDA_ET_AL_2004"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Bir görev skoru veya davranış kişisel ağ etkinliğini ya da belirli beyin bölgesi işlevini göstermez.",
  }),
  relation({
    id: "relation.sustained-attention.attention",
    fromTopicId: "cns.sustained_attention",
    toTopicId: "cns.attention",
    predicate: "part_of",
    summary: "Sürdürülen dikkat, hedefle ilgili işlemeyi zaman boyunca devam ettirmeye ilişkin dikkat süreçlerinden biridir.",
    sourceIds: ["BETTS_ET_AL_2006", "FISHER_ET_AL_2013_ATTENTION"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Tek oturum sonucu genel dikkat kapasitesi, isteksizlik, tanı veya beyin ağı ölçümü değildir.",
  }),
  relation({
    id: "relation.selective-attention.attention",
    fromTopicId: "cns.selective_attention",
    toTopicId: "cns.attention",
    predicate: "part_of",
    summary: "Seçici dikkat, hedefle ilgili bilgiyi bağlama göre önceliklendiren dikkat süreçlerinden biridir.",
    sourceIds: ["FISHER_ET_AL_2013_ATTENTION", "PETERSEN_POSNER_2012"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Dikkat dağıtıcıya yönelme tek başına seçici dikkat yetersizliği, tanı veya biyolojik neden değildir.",
  }),
  relation({
    id: "relation.attention.attention-measurement",
    fromTopicId: "cns.attention",
    toTopicId: "cns.attention_measurement",
    predicate: "measured_indirectly_by",
    summary: "Görevler, derecelendirmeler ve doğal ortam gözlemleri dikkatin farklı bileşenlerini ve bağlamlarını dolaylı olarak örnekler.",
    sourceIds: ["HEDGE_ET_AL_2018", "TOPLAK_ET_AL_2013", "FISHER_ET_AL_2013_ATTENTION"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Tek yöntem genel dikkat, beyin ağı, tanı veya değişmez kapasitenin doğrudan ölçümü değildir.",
  }),
  relation({
    id: "relation.attention-development.attention",
    fromTopicId: "cns.attention_development",
    toTopicId: "cns.attention",
    predicate: "conceptually_related_to",
    summary: "Yöneltme, seçme, sürdürme ve yürütücü dikkat çocukluk boyunca farklı hızlarda ve göreve duyarlı biçimde gelişir.",
    sourceIds: ["RUEDA_ET_AL_2004", "BETTS_ET_AL_2006", "FISHER_ET_AL_2013_ATTENTION"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Yaş grubu eğilimi tek çocukta olgunluk, gecikme, tanı veya prognoz sonucu değildir.",
  }),
  relation({
    id: "relation.attention.working-memory",
    fromTopicId: "cns.attention",
    toTopicId: "cns.working_memory",
    predicate: "associated_with",
    summary: "Dikkat ve çalışma belleği birçok görevde etkileşen fakat aynı olmayan bilişsel süreçlerdir.",
    sourceIds: ["COWAN_2014", "BADDELEY_2000", "PETERSEN_POSNER_2012"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Bir alandaki tek davranış veya puan diğer alanın değişmez kapasitesini ya da biyolojik mekanizmasını göstermez.",
  }),
  relation({
    id: "relation.attention.executive-functions",
    fromTopicId: "cns.attention",
    toTopicId: "selfreg.executive_functions",
    predicate: "associated_with",
    summary: "Hedefle ilgili dikkat kontrolü bazı yürütücü görevlerin performansına katkı verir; dikkat ile yürütücü işlevler eş anlamlı değildir.",
    sourceIds: ["PETERSEN_POSNER_2012", "DIAMOND_2013", "DOEBEL_2020"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Tek dikkat davranışı bütün yürütücü işlevleri, beyin bölgesini veya tanıyı göstermez.",
  }),
  ...V5_CASE_BOUNDARY_RELATIONS,
  ...V5_SIX_DOMAINS_RELATIONS,
  ...V5_DEVELOPMENT_RELATIONS,
  ...V5_COREGULATION_RELATIONS,
])
