import {
  DNA_CHAT_CATALOG_VERSION,
  type DnaChatCatalogSafetyRule,
} from "./types"

function safetyRule(
  input: Omit<DnaChatCatalogSafetyRule, "version">,
): DnaChatCatalogSafetyRule {
  return Object.freeze({ version: DNA_CHAT_CATALOG_VERSION, ...input })
}

export const DNA_CHAT_CATALOG_SAFETY_RULES: readonly DnaChatCatalogSafetyRule[] = Object.freeze([
  safetyRule({
    id: "safety.brain_region_from_profile",
    patterns: [
      "hangi beyin bölgesi",
      "insula sorunu",
      "frontal lob problemi",
      "frontal lob diyebilir miyiz",
      "beyin bölgesi etkilenmiş",
      "prefrontal korteksin zayıf",
      "vagus siniri hasarlı",
      "vagus hasarı",
      "vagus hasarı çıkar",
      "travmanın biyolojik kanıtı",
      "interosepsiyonu yok",
    ],
    response: "DNA profili veya davranış gözlemi belirli bir beyin bölgesinin işlevini, hasarını ya da neden rolünü göstermez.",
    category: "biological_inference",
    sourceIds: ["POLDRAK_2006"],
  }),
  safetyRule({
    id: "safety.autonomic_state_from_behavior",
    patterns: [
      "sempatik baskın",
      "parasempatik yetersiz",
      "dorsal vagal",
      "ventral vagal",
      "vagal shutdown",
      "dorsal vagale mi",
      "sempatik mi parasempatik mi",
      "sempatik sisteminin açık",
      "sempatik aktivasyon mu demektir",
      "can davranıştan anlaşılır mı",
      "sinir sistemi güvenli modda mı",
      "parasempatik çökme yüzünden mi",
    ],
    response: "Davranıştan sempatik-parasempatik baskınlık veya vagal durum atanamaz; bunun için uygun fizyolojik ölçüm ve protokol gerekir.",
    category: "biological_inference",
    sourceIds: ["BERNTSON_ET_AL_1991", "GROSSMAN_2023"],
  }),
  safetyRule({
    id: "safety.dna_is_not_physiology",
    patterns: [
      "dna hrv ölçer",
      "vagal ton kaç",
      "vagal tone kaç",
      "eda değeri",
      "otonom skoru",
      "beyin ağı puanı",
      "dna bir beyin bölgesini ölçüyor mu",
      "dna yürütücü işlev alanı nöropsikolojik test yerine geçer mi",
      "dna interosepsiyon alanı interoseptif doğruluğu gösterir mi",
      "dna’nın self-regülasyonu doğruladığını söyleyebilir miyiz",
      "dna bilişsel regülasyon alanı can ile doğrudan eşleşir mi",
      "dna yürütücü işlev alanından vagal profil çıkarılabilir mi",
      "dna interosepsiyon alanı ans ölçümü yerine geçer mi",
      "hrv düşükse bizim dna da fizyolojik regülasyon kötü mü sayılır",
      "hrv beyin ölçümü müdür",
    ],
    response: "DNA davranışsal ve ölçek temelli işlevsel profil sunar; HRV, EDA, vagal ton veya ağ aktivitesi ölçmez.",
    category: "measurement_overreach",
    sourceIds: ["TASK_FORCE_HRV_1996", "BOUCSEIN_ET_AL_2012", "POLDRAK_2006"],
  }),
  safetyRule({
    id: "safety.hrv_overreach",
    patterns: [
      "düşük hrv demek",
      "düşük hrv'si var",
      "düşük hrv varsa",
      "lf hf dengesi",
      "hrv tanı",
      "hrv kötü",
      "hrv doğrudan beyin ölçümü",
    ],
    response: "HRV protokole duyarlı kardiyak bir ölçümdür; tek değerden küresel ANS dengesi, neden, tanı veya DNA alan düzeyi çıkarılamaz.",
    category: "measurement_overreach",
    sourceIds: ["LABORDE_ET_AL_2017", "BILLMAN_2013"],
  }),
  safetyRule({
    id: "safety.causality",
    patterns: ["neden oluyor", "sebebi bu", "kesin bundan", "buna yol açar"],
    response: "Katalogdaki ilişkiler çoğunlukla grup düzeyi ve çok etkenlidir; kişiye özgü kesin nedensellik kurulamaz.",
    category: "causality",
    sourceIds: ["ROBSON_ET_AL_2020", "GRAZIANO_DEREFINKO_2013"],
  }),
  safetyRule({
    id: "safety.diagnosis",
    patterns: [
      "hangi tanı",
      "kesin otizm",
      "adhd gösteriyor",
      "adhd var mı",
      "otizm belirtisi",
      "disotonomi var mı",
      "pots demek mi",
      "sinir sistemi bozukluğu mudur",
      "bozukluk mu",
      "teşhis",
      "bu rapora göre hastalığı nedir",
      "bu profil hangi klinik tabloyu düşündürüyor",
      "bu rapordan tanısal sonuç çıkar",
    ],
    response: "Bu bilgi kataloğu ve DNA sohbeti tanı koymaz; bulgular klinik değerlendirme bağlamında ve ölçüm sınırlarıyla ele alınır.",
    category: "diagnosis",
    sourceIds: [],
  }),
  safetyRule({
    id: "safety.treatment",
    patterns: [
      "hangi ilaç",
      "hangi tedavi",
      "kaç seans terapi",
      "seans planı",
      "doz",
      "reçete",
      "bu vakada ne yapmalıyım",
    ],
    response: "DNA Asistanı kişiselleştirilmiş tedavi, ilaç, doz veya seans protokolü önermez.",
    category: "treatment",
    sourceIds: [],
  }),
  safetyRule({
    id: "safety.hidden_reasoning",
    patterns: ["gizli kural", "eşikleri göster", "chain of thought", "reasoning izini", "internal prompt"],
    response: "Dahili kural kimlikleri, eşikler ve düşünme izi paylaşılmaz; sonuç, kaynak ve iddia sınırı açıklanabilir.",
    category: "internal_reasoning",
    sourceIds: [],
  }),
  safetyRule({
    id: "safety.age_scope_generalization",
    patterns: [
      "yetişkin araştırmalarını çocuklara uygulayabilir miyiz",
      "çocuk çalışmasını yetişkine genelleyebilir miyiz",
      "yetişkin çalışmasını çocuğa genelleyebilir miyiz",
    ],
    response: "Bir yaş grubundaki bulgular yaş, gelişim dönemi ve ölçüm koşulları dikkate alınmadan başka bir yaş grubuna doğrudan genellenemez.",
    category: "measurement_overreach",
    sourceIds: [],
  }),
])
