import {
  DNA_CHAT_CATALOG_VERSION,
  type DnaChatCatalogSafetyRule,
} from "./types"
import { V5_CASE_BOUNDARY_SAFETY_RULES } from "./v5CaseBoundariesCatalog"
import { V5_COREGULATION_SAFETY_RULES } from "./v5CoregulationCatalog"
import { V5_DEVELOPMENT_SAFETY_RULES } from "./v5DevelopmentCatalog"
import { V5_SIX_DOMAINS_SAFETY_RULES } from "./v5SixDomainsCatalog"

function safetyRule(
  input: Omit<DnaChatCatalogSafetyRule, "version">,
): DnaChatCatalogSafetyRule {
  return Object.freeze({ version: DNA_CHAT_CATALOG_VERSION, ...input })
}

export const DNA_CHAT_CATALOG_SAFETY_RULES: readonly DnaChatCatalogSafetyRule[] = Object.freeze([
  safetyRule({
    id: "safety.brain_region_from_profile",
    patterns: [
      "hangi beyin bölgesi",
      "insula sorunu",
      "frontal lob problemi",
      "frontal lob diyebilir miyiz",
      "beyin bölgesi etkilenmiş",
      "prefrontal korteksin zayıf",
      "vagus siniri hasarlı",
      "vagus hasarı",
      "vagus hasarı çıkar",
      "travmanın biyolojik kanıtı",
      "interosepsiyonu yok",
      "gözlemden dlpfc çıkarımı",
      "bu çocuğun vagus siniri bozuk",
      "bunun beyindeki yeri neresi",
      "bu davranış vagus siniri zayıflığını",
      "dna raporu vagus sinirinin zayıf",
      "dna profili vagus sinirinin zayıf",
      "dna sonucu vagus sinirinin zayıf",
      "mrı görüntüsünden çocuğun öz-regülasyon kapasitesi",
    ],
    response: "DNA profili veya davranış gözlemi belirli bir beyin bölgesinin işlevini, hasarını ya da neden rolünü göstermez.",
    category: "biological_inference",
    sourceIds: ["POLDRAK_2006"],
  }),
  safetyRule({
    id: "safety.prefrontal_acc_from_behavior",
    patterns: [
      "bu çocuğun prefrontal korteksi gelişmemiş",
      "prefrontal korteksi zayıf çalışıyor",
      "pfc si zayıf",
      "çalışma belleği düşükse frontal lob sorunu",
      "ketleyemiyorsa prefrontal bozuk",
      "acc si bozuk",
      "anterior singulat hasarlı",
      "hata yapması acc problemi",
      "ern düşükse acc zayıf",
      "bu profilden acc aktivitesi",
      "hrv düşükse prefrontal kontrol zayıf",
      "erken stres pfc’yi bozar",
      "dna yürütücü işlev puanı acc’yi ölçer",
      "dna interosepsiyon puanı acc aktivitesini gösterir",
      "hrv düşük çıktı, acc yetersiz",
      "acc yi güçlendiren kesin egzersiz",
      "acc aktivitesi kaç olmalı",
      "dna sonucu düşükse mr’da acc küçük",
    ],
    response: "Davranış, görev veya DNA profilinden prefrontal korteks ya da singulat bölge işlevi, olgunluğu, hasarı veya aktivitesi çıkarılamaz.",
    category: "biological_inference",
    sourceIds: ["POLDRAK_2006", "TOPLAK_ET_AL_2013"],
  }),
  safetyRule({
    id: "safety.insula_from_behavior",
    patterns: [
      "bu çocuğun insulası gelişmemiş",
      "insula zayıf çalışıyor",
      "insula aktivitesi düşük",
      "insula hasarı var",
      "bedenini fark etmiyorsa insula bozuk",
      "seçici yeme insula problemi",
      "bu profilden insula aktivitesi",
      "dna insula işlevini gösterir",
      "insula bağlantısı zayıf",
      "dna raporundan insula aktivitesi tahmin",
      "dna interosepsiyon puanı insula işlevinin göstergesi",
      "açlığını söylemiyorsa insulası bozuk",
      "duyusal kaçınma anterior insulanın aşırı aktif",
      "ağrıya aşırı tepki posterior insula hasarı",
      "duygusal patlama insula disfonksiyonunu kanıtlar",
      "geçiş yapmakta zorlanması salience ağı bozukluğu",
      "empati kurmayan çocukta insula gelişmemiş",
      "seçici yeme tat korteksi bozukluğundan",
      "denge sorunu pivc veya insula bozukluğunu",
      "insula otizmin nedeni",
      "bu çocuğun insulası ne kadar olgun",
      "çocukta insula aktf mi",
      "bu profile göre çocuğun insulası az mı çalışıyor",
      "insula bozuksa mı böyle",
    ],
    response: "Davranış veya DNA profilinden insula aktivitesi, alt bölge işlevi, bağlantısallığı, olgunluğu ya da hasarı çıkarılamaz.",
    category: "biological_inference",
    sourceIds: ["POLDRAK_2006", "UDDIN_ET_AL_2017"],
  }),
  safetyRule({
    id: "safety.interoception_biological_inference",
    patterns: [
      "interosepsiyonu düşükse vagus sorunu",
      "interosepsiyon puanı ans bozukluğu",
      "beden farkındalığı düşükse sempatik baskın",
      "interosepsiyon alanından insula çıkar",
      "interosepsiyon alanından vagal durum",
      "seçici yeme interoseptif bozukluk demek",
      "tuvalet sorunu interosepsiyon bozukluğu",
      "ağrı tepkisi interosepsiyon bozukluğu",
      "bu davranış interoseptif bozukluğu kanıtlar",
      "seçici yeme interoseptif bozukluğun kanıtı",
      "tuvalet kazası interosepsiyon eksikliği",
      "ağrıya tepki vermeyen çocuk ağrı hissetmiyor",
    ],
    response: "Tek davranış veya DNA interosepsiyon alanı ANS durumu, vagal işlev, insula etkinliği, neden ya da bozukluk göstermez.",
    category: "biological_inference",
    sourceIds: ["CHEN_ET_AL_2021", "POLDRAK_2006"],
  }),
  safetyRule({
    id: "safety.executive_interoception_measurement",
    patterns: [
      "dna prefrontal korteksi ölçer",
      "dna acc aktivitesini ölçer",
      "dna insula aktivitesini ölçer",
      "dna çalışma belleğini doğrudan ölçer",
      "dna ketleyici kontrol testi yerine geçer",
      "dna interoseptif doğruluğu ölçer",
      "dna kalp atımı görevine eşdeğer",
      "ern dna ile ölçülür",
      "dna beyin olgunluğunu ölçer",
      "dna prefrontal korteksi ölçüyor",
      "dna interoseptif doğruluğu ölçüyor",
      "dna bilişsel regülasyon alanı öngörücü işlemeyi ölçer",
      "dna yürütücü işlev puanından beden sinyali kontrolü",
      "mrı görüntüsünden çocuğun öz-regülasyon kapasitesi okunabilir",
      "dna yürütücü işlev puanı acc’yi ölçer",
      "dna interosepsiyon puanı acc aktivitesini gösterir",
      "acc aktivitesi kaç olmalı",
      "dna sonucu düşükse mr’da acc küçük",
      "dna raporundan insula aktivitesi tahmin",
      "dna interosepsiyon puanı insula işlevinin göstergesi",
    ],
    response: "DNA ölçek temelli işlevsel profil sunar; nöropsikolojik görev, EEG/ERN, interoseptif performans testi veya beyin görüntüleme ölçümü değildir.",
    category: "measurement_overreach",
    sourceIds: ["TOPLAK_ET_AL_2013", "DESMEDT_ET_AL_2023", "POLDRAK_2006"],
  }),
  safetyRule({
    id: "safety.autonomic_state_from_behavior",
    patterns: [
      "sempatik baskın",
      "parasempatik yetersiz",
      "dorsal vagal",
      "ventral vagal",
      "vagal shutdown",
      "dorsal vagale mi",
      "sempatik mi parasempatik mi",
      "sempatik sisteminin açık",
      "sempatik aktivasyon mu demektir",
      "can davranıştan anlaşılır mı",
      "sinir sistemi güvenli modda mı",
      "parasempatik çökme yüzünden mi",
      "bu puana göre çocuğun sempatik sistemi baskın",
    ],
    response: "Davranıştan sempatik-parasempatik baskınlık veya vagal durum atanamaz; bunun için uygun fizyolojik ölçüm ve protokol gerekir.",
    category: "biological_inference",
    sourceIds: ["BERNTSON_ET_AL_1991", "GROSSMAN_2023"],
  }),
  safetyRule({
    id: "safety.dna_is_not_physiology",
    patterns: [
      "dna hrv ölçer",
      "vagal ton kaç",
      "vagal tone kaç",
      "eda değeri",
      "otonom skoru",
      "beyin ağı puanı",
      "dna bir beyin bölgesini ölçüyor mu",
      "dna yürütücü işlev alanı nöropsikolojik test yerine geçer mi",
      "dna interosepsiyon alanı interoseptif doğruluğu gösterir mi",
      "dna’nın self-regülasyonu doğruladığını söyleyebilir miyiz",
      "dna bilişsel regülasyon alanı can ile doğrudan eşleşir mi",
      "dna yürütücü işlev alanından vagal profil çıkarılabilir mi",
      "dna interosepsiyon alanı ans ölçümü yerine geçer mi",
      "hrv düşükse bizim dna da fizyolojik regülasyon kötü mü sayılır",
      "hrv beyin ölçümü müdür",
      "bu konu dna’nın geçerliğini kanıtlar",
      "dna bilişsel regülasyon alanını otonom göstergelerle açıklamak",
      "dna'nın ans ile biyolojik geçerliği",
      "dna’nın ans ile biyolojik geçerliği",
      "dna fizyolojik regülasyon alanıyla ilişkisi doğrudan",
    ],
    response: "DNA davranışsal ve ölçek temelli işlevsel profil sunar; HRV, EDA, vagal ton veya ağ aktivitesi ölçmez.",
    category: "measurement_overreach",
    sourceIds: ["TASK_FORCE_HRV_1996", "BOUCSEIN_ET_AL_2012", "POLDRAK_2006"],
  }),
  safetyRule({
    id: "safety.hrv_overreach",
    patterns: [
      "düşük hrv demek",
      "düşük hrv'si var",
      "düşük hrv varsa",
      "lf hf dengesi",
      "hrv tanı",
      "hrv kötü",
      "hrv doğrudan beyin ölçümü",
    ],
    response: "HRV protokole duyarlı kardiyak bir ölçümdür; tek değerden küresel ANS dengesi, neden, tanı veya DNA alan düzeyi çıkarılamaz.",
    category: "measurement_overreach",
    sourceIds: ["LABORDE_ET_AL_2017", "BILLMAN_2013"],
  }),
  safetyRule({
    id: "safety.arousal_from_behavior",
    patterns: [
      "çok hareketliyse uyarılması yüksek",
      "sessizse uyarılması düşük",
      "hareketten uyarılma düzeyi",
      "davranıştan uyarılma sistemi",
      "bu çocuk optimal uyarılmada",
      "puanından uyarılma düzeyi",
      "dna uyarılmayı doğrudan ölçer",
      "uyarılma puanı norepinefrini gösterir",
    ],
    response: "Hareketlilik, sessizlik, tek gözlem veya DNA puanı biyolojik uyarılma düzeyini, norepinefrin sistemini ya da kişiye özgü optimal uyarılmayı ölçmez.",
    category: "biological_inference",
    sourceIds: ["ASTON_JONES_COHEN_2005", "BURT_OBRADOVIC_2013"],
  }),
  safetyRule({
    id: "safety.recovery_biology_from_observation",
    patterns: [
      "sakinleştiyse hrv toparlandı",
      "sakin görünüyorsa fizyolojisi toparlandı",
      "davranıştan vagal toparlanma",
      "gözlemden hpa toparlanması",
      "toparlanma süresinden kortizol",
      "toparlandıysa ans normale döndü",
      "alıştıysa sorun bitti",
      "tek toparlanma biyobelirteci",
      "öz örgütlenme bozukluğu var",
    ],
    response: "Görünür sakinleşme veya tepki azalması HRV, HPA, kortizol, vagal ton ya da bütün sistemlerin toparlandığını göstermez; öz-örgütlenme de klinik bozukluk etiketi değildir.",
    category: "biological_inference",
    sourceIds: ["SACREY_ET_AL_2021", "JONES_MASON_ET_AL_2018", "SMITH_THELEN_2003"],
  }),
  safetyRule({
    id: "safety.sensory_biological_inference",
    patterns: [
      "duyusal kaçınma sempatik aktivasyon",
      "duyusal arayış sempatik baskın",
      "düşük kayıt vagal yetersizlik",
      "duyusal profil beyin bölgesini",
      "duyusal puan nörolojik eşik",
      "dunn eşiği biyolojik eşik",
      "duyusal davranış vestibüler bozukluk",
      "duyusal modülasyon ans durumunu",
      "düşük kayıtlı çocuk tembel",
      "dna duyusal modülasyonu doğrudan ölçer",
    ],
    response: "Duyusal davranış veya ölçek puanı ANS durumunu, beyin bölgesini, vestibüler işlevi, biyolojik eşiği ya da kişilik özelliğini göstermez.",
    category: "biological_inference",
    sourceIds: ["DUNN_2001", "GOMEZ_ET_AL_2017", "WATKYNS_ET_AL_2024"],
  }),
  safetyRule({
    id: "safety.sensory_diagnostic_overreach",
    patterns: [
      "duyusal puan otizm gösterir",
      "duyusal profil adhd gösterir",
      "duyusal arayış travma kanıtı",
      "duyusal modülasyon bozukluğu tanısı",
      "duyusal işleme bozukluğu var mı",
      "sor puanı tanı koyar",
      "duyusal kaçınma kesin otizm",
    ],
    response: "Duyusal yanıt örüntüleri transdiagnostiktir; tek davranış veya ölçek puanı otizm, ADHD, travma ya da başka bir tanı koymaz.",
    category: "diagnosis",
    sourceIds: ["WATKYNS_ET_AL_2024"],
  }),
  safetyRule({
    id: "safety.emotion_biological_inference",
    patterns: [
      "duygu patlaması amigdala",
      "duygusal puan insula aktivitesi",
      "duygu düzenleme acc işlevi",
      "duygusal reaktivite kortizolü gösterir",
      "duygu düzenleme puanı hrv",
      "duygusal patlama vagal ton",
      "duygu puanından sempatik baskınlık",
      "dna duygu düzenlemeyi doğrudan ölçer",
      "duygu ölçeği beyin mekanizmasını",
      "sakin görünüyorsa iyi duygu düzenliyor",
    ],
    response: "Duygusal davranış, ölçek veya DNA puanı amigdala/insula/ACC etkinliği, kortizol, HRV, vagal ton ya da otonom baskınlık göstermez; sakin görünmek tek başına iyi düzenleme değildir.",
    category: "biological_inference",
    sourceIds: ["COLE_ET_AL_2004", "MAZEFSKY_ET_AL_2021", "POLDRAK_2006"],
  }),
  safetyRule({
    id: "safety.dna_new_domain_measurement",
    patterns: [
      "dna toparlanma biyobelirtecini ölçer",
      "dna hpa toparlanmasını gösterir",
      "dna kortizol toparlanmasını ölçer",
      "dna öz örgütlenmeyi ölçer",
      "dna duyusal eşiği ölçer",
      "dna duygusal mekanizmayı ölçer",
      "dna duygu düzenleme ölçeğiyle eşdeğer",
    ],
    response: "DNA ölçek temelli işlevsel bir profil sunar; biyobelirteç, HPA/ANS ölçümü, biyolojik eşik, öz-örgütlenme mekanizması veya bağımsız duygu/duyusal test değildir.",
    category: "measurement_overreach",
    sourceIds: ["BURT_OBRADOVIC_2013", "WATKYNS_ET_AL_2024", "MAZEFSKY_ET_AL_2021"],
  }),
  safetyRule({
    id: "safety.stress_biology_from_proxy",
    patterns: [
      "puanından kortizol",
      "skordan kortizol",
      "profilinden kortizol",
      "davranıştan kortizol",
      "dna sonucu kortizol",
      "dna raporu kortizol",
      "ölçek puanı kortizol",
      "davranıştan hpa",
      "bu çocuğun hpa ekseni bozuk",
      "bulgulara göre hangi hormon eksik",
      "davranışa göre hangi hormon eksik",
      "ace puanı biyolojik hasar",
      "dna sonucu allostatik yük",
      "puanından allostatik yük",
      "ağlamıyorsa stres yanıtı yok",
      "ağlıyorsa kortizol",
      "sakinse kortizol",
    ],
    response: "Davranış, DNA profili veya ölçek puanı kortizol/HPA düzeyini, hormon eksikliğini, allostatik yükü ya da biyolojik hasarı ölçmez ve tahmin etmez.",
    category: "biological_inference",
    sourceIds: ["POLDRAK_2006"],
  }),
  safetyRule({
    id: "safety.trauma_from_proxy",
    patterns: [
      "davranış travmayı gösterir",
      "davranış travma kanıtı",
      "profil travmayı gösterir",
      "profil travma kanıtı",
      "dna sonucu travma",
      "dna puanı travma",
      "ölçek puanı travma",
      "travma yaşadığını kanıtlar",
      "travma yaşadığını gösterir",
    ],
    response: "Tek davranış, DNA profili, ölçek veya biyobelirteç bir çocuğun travma yaşadığını kanıtlamaz; maruziyet ve klinik anlam uygun değerlendirme bağlamında ele alınır.",
    category: "causality",
    sourceIds: [],
  }),
  safetyRule({
    id: "safety.sleep_biology_from_proxy",
    patterns: [
      "dna uyku mimarisi",
      "dna uyku evresi",
      "dna sirkadiyen faz",
      "dna melatonin",
      "uyku puanından melatonin",
      "uyku puanından kortizol",
      "puanından biyolojik saat",
      "davranıştan melatonin",
      "akıllı saat derin uyku",
      "akıllı saat uyku evresi",
      "akıllı saat melatonin",
      "akıllı saat kortizol",
      "akıllı saat sirkadiyen faz",
      "cctq biyolojik saati ölç",
      "uyku örüntüsünden beyin bölgesi",
      "geç yatıyorsa scn",
    ],
    response: "DNA, davranış, anket veya tüketici cihazı uyku evresini, uyku mimarisini, sirkadiyen fazı, SCN işlevini ya da melatonin/kortizol düzeyini ölçmez veya tahmin etmez.",
    category: "measurement_overreach",
    sourceIds: ["POLDRAK_2006"],
  }),
  safetyRule({
    id: "safety.cognitive_capacity_from_proxy",
    patterns: [
      "dna dikkat ağını ölç",
      "dna dikkat ağlarını ölç",
      "dna çalışma belleği kapasitesini ölç",
      "dna yürütücü kapasiteyi ölç",
      "puanından çalışma belleği kapasitesi",
      "tek testle çalışma belleği",
      "hataları hangi beyin bölgesi",
      "dikkat puanından zekâ",
      "davranış frontal lob bozukluğu",
      "düşük ef puanı frontal",
      "fonolojik döngüsü bozuk",
    ],
    response: "DNA profili, tek görev, puan veya davranış gözlemi dikkat ağı aktivitesini, çalışma belleği kapasitesini, zekâyı ya da beyin bölgesi işlevini doğrudan ölçmez.",
    category: "measurement_overreach",
    sourceIds: ["POLDRAK_2006", "TOPLAK_ET_AL_2013"],
  }),
  safetyRule({
    id: "safety.v3_clinical_decision",
    patterns: [
      "yavaş toparlanma tek başına patoloji midir",
      "bu profile göre tanı koyabilir misin",
      "bu çocuk ileride hangi bozukluğu geliştirir",
      "toparlanması uzun sürüyorsa hangi tanısı vardır",
      "erken duyusal farklılık otizmi öngörür mü",
      "kulak kapatması otizm belirtisi mi",
      "bu puanla spd tanısı koyabilir miyim",
      "dna duygusal regülasyon puanı duygusal düzensizlik tanısı koyar mı",
      "yeniden değerlendirme yapamayan okul öncesi çocukta bozukluk var mı",
      "dna puanına göre çocuğun tanısı nedir",
      "bu çocuk için kesin prognoz çıkarır mısın",
    ],
    response: "DNA Asistanı tek davranış, ölçek, profil veya araştırma bulgusundan tanı, patoloji ya da bireysel prognoz üretmez.",
    category: "diagnosis",
    sourceIds: ["FISHER_ET_AL_2018", "WATKYNS_ET_AL_2024", "MAZEFSKY_ET_AL_2021"],
  }),
  safetyRule({
    id: "safety.v3_treatment_decision",
    patterns: [
      "bu sonuçla hangi tedaviyi uygulamalıyım",
      "bu çocuğa hangi ilaç iyi gelir",
      "duyusal diyet önerir misin",
      "bu sonuçlara göre hangi ilaç kullanılmalı",
      "bu veriden bireysel tedavi seansı planlar mısın",
    ],
    response: "DNA Asistanı kişiselleştirilmiş ilaç, duyusal diyet, tedavi, müdahale veya seans planı önermez.",
    category: "treatment",
    sourceIds: [],
  }),
  safetyRule({
    id: "safety.v3_research_pack_refusal_gate",
    patterns: [
      "deri iletkenliği hangi duyguyu gösterir",
      "otizm çalışmalarındaki duyusal bulgular tüm çocuklara uygulanabilir mi",
      "yüksek sese ağlamak sempatik sistem bozukluğunu gösterir mi",
      "yavaş toparlanma tek başına patoloji midir",
      "reaktivite ile akademik performans arasında nedensellik var mı",
      "uyarılma dna’nın bilişsel regülasyon alanını doğrudan ölçer mi",
      "dna sonucu çocuğun ans profilini verir mi",
      "dna puanından cortisol düzeyi anlaşılır mı",
      "dna bu çocuğun vagus sinirini ölçmüş olur mu",
      "bu araştırma dna’nın geçerli olduğunu kanıtlar mı",
      "bu çocukta hangi beyin bölgesi aşırı aktif",
      "bu reaktivite örüntüsü travma var demek mi",
      "bu profile göre tanı koyabilir misin",
      "bu sonuçla hangi tedaviyi uygulamalıyım",
      "bu çocuğa hangi ilaç iyi gelir",
      "bu çocuk ileride hangi bozukluğu geliştirir",
      "bu durumun nedeni annesi mi",
      "hrv düşük çıktı, vagus siniri bozuk mu",
      "cortisol yüksekse kesin stresli mi",
      "duyusal arayış dopamin eksikliğini mi gösterir",
      "duyusal hiperreaktiflik sinir sistemi fazla çalışıyor demek mi",
      "dna öz-örgütlenmeyi ölçüyor mu",
      "dna puanı otonom toparlanmayı tahmin eder mi",
      "çocuk hiç tepki vermediyse sistemi çok iyi toparlıyor demektir, doğru mu",
      "çok değişken davranış öz-örgütlenme bozukluğunu gösterir mi",
      "ebeveynle yüksek senkroni kesin güvenli bağlanma demek mi",
      "bilişsel esnekliği düşükse toparlanamaz mı",
      "interosepsiyonu iyiyse duygularını kesin düzenler mi",
      "allostatik yükünü davranışından anlayabilir miyiz",
      "bu çocuğun vagus siniri iyi çalışıyor mu",
      "toparlanamaması hpa ekseni bozukluğunu mu gösteriyor",
      "bu davranış beynindeki öz-örgütlenmenin bozulduğunu kanıtlar mı",
      "toparlanması uzun sürüyorsa hangi tanısı vardır",
      "çocuğun toparlanamamasının kesin nedeni nedir",
      "bu toparlanma örüntüsü ileride nasıl olacağını gösterir mi",
      "dna sonucu çocuğun kortizolünün yüksek olduğunu gösterir mi",
      "dna raporundan hrv değerini tahmin edebilir miyiz",
      "alıştıysa duyu sorunu bitmiş midir",
      "erken duyusal farklılık otizmi öngörür mü",
      "6 yaşındaki çocuk için 14 yaş normu kullanılabilir mi",
      "eda yüksekse çocuk aşırı duyarlı mıdır",
      "fmri duyusal modülasyonu gösterir mi",
      "dna duyusal modülasyon bozukluğunu ölçer mi",
      "dna fizyolojik regülasyon puanı otonom yanıtı gösterir mi",
      "dna’da birden fazla alan yüksekse ortak sinir sistemi sorunu var mı",
      "bu çocuk ışığa tepki veriyor; beyninin hangi bölgesi bozuk",
      "kulak kapatması otizm belirtisi mi",
      "sürekli dönmesi vestibüler sisteminin az çalıştığını mı gösterir",
      "dokunmaya kaçıyorsa sempatik sistemi yüksek mi",
      "düşük kayıtlı çocuk tembel midir",
      "duyusal arayış travmayı gösterir mi",
      "bu puanla spd tanısı koyabilir miyim",
      "duyusal diyet önerir misin",
      "çok hareketli, duyu arıyor kesin demi",
      "yani sebebi bu mu",
      "bunu puandan anlayabilir miyiz",
      "dna duygusal regülasyon puanı duygusal düzensizlik tanısı koyar mı",
      "dna bilişsel regülasyon alanı yeniden değerlendirmeyi ölçüyor mu",
      "dna yürütücü işlev alanından duygusal düzenleme kapasitesi çıkarılabilir mi",
      "dna interosepsiyon alanı duyguların biyolojik temelini gösterir mi",
      "dna’nın altı alanı arasında nedensel sıra kurulabilir mi",
      "dna sonuçları beyin bölgesiyle eşleştirilebilir mi",
      "öfke nöbeti amigdalanın aşırı çalıştığını gösterir mi",
      "yeniden değerlendirme yapamayan okul öncesi çocukta bozukluk var mı",
      "hrv düşükse vagus siniri bozuk mudur",
      "bu çocuğun davranışına bakıp hangi beyin bölgesinin bozuk olduğunu söyler misin",
      "dna puanına göre çocuğun tanısı nedir",
      "bu sonuçlara göre hangi ilaç kullanılmalı",
      "bu çocuk için kesin prognoz çıkarır mısın",
      "bu bulgu travma yaşadığını kanıtlıyor mu",
      "duygusal düzenleme güçlüğünün tek nedeni ebeveyn midir",
      "dna ile sempatik-parasempatik baskınlığı belirler misin",
      "bu ölçek puanı kortizolünün yüksek olduğunu gösterir mi",
      "çocuğun insulası ve anterior singulatı nasıl çalışıyor",
      "bu veriden bireysel tedavi seansı planlar mısın",
    ],
    response: "Bu istek ölçümün ve kanıtın desteklediği sınırı aşıyor. DNA Asistanı davranış veya profilden tanı, neden, prognoz, tedavi ya da biyolojik mekanizma çıkarmaz.",
    category: "measurement_overreach",
    sourceIds: ["POLDRAK_2006", "FISHER_ET_AL_2018", "BURT_OBRADOVIC_2013", "WATKYNS_ET_AL_2024", "MAZEFSKY_ET_AL_2021"],
  }),
  safetyRule({
    id: "safety.v4_research_pack_refusal_gate",
    patterns: [
      // Stres sistemleri: kanonik 35 güvenli-ret girdisi.
      "Çocuklarda gün içi kortizol ritmi yetişkinlerle aynı kabul edilebilir mi?",
      "Tek bir yaş normuyla 0-12 yaşın tamamı değerlendirilebilir mi?",
      "DNA puanından çocuğun kortizol düzeyi tahmin edilebilir mi?",
      "DNA raporu otonom sinir sistemi profili verebilir mi?",
      "DNA sonucu allostatik yükü gösterir mi?",
      "DNA yüksek stresli çocuk tanımı yapabilir mi?",
      "Kortizol yüksekse çocuk kesin streslidir, doğru mu?",
      "Kortizol düşükse çocuk iyi regüledir diyebilir miyiz?",
      "HRV düşükse vagus siniri çalışmıyor mudur?",
      "Hareketli çocukta sempatik sistem baskındır diyebilir miyiz?",
      "Donup kalan çocuk kesin dorsal vagal durumdadır, değil mi?",
      "Davranıştan savaş-kaç-don yanıtını kesin olarak anlayabilir miyiz?",
      "Saç kortizolü çocuğun travma yaşadığını kanıtlar mı?",
      "CRP yüksekse bunun nedeni psikolojik stres midir?",
      "ACE puanı çocuğun biyolojik hasarını gösterir mi?",
      "Toksik stres bir tanı mıdır?",
      "Çocukluk stresi beyni kalıcı olarak bozar mı?",
      "Ebeveynlik çocuğun kortizol profilini tek başına belirler mi?",
      "Bir çocuk ağlamıyorsa stres yanıtı yok mudur?",
      "Çok ağlayan çocukta kortizol mutlaka yüksektir, doğru mu?",
      "Bu çocuğun HPA ekseni bozuk mu?",
      "Bu bulgulara göre hangi hormon eksik?",
      "Çocuğun vagus siniri hasarlı mı?",
      "Bu davranış hangi beyin bölgesinin bozuk olduğunu gösteriyor?",
      "Bu çocuk travma yaşamış mı, DNA sonucundan söyle?",
      "Kortizolünü düşürmek için ne ilaç verelim?",
      "Stres sistemini düzeltmek için seans planı çıkar.",
      "Bu çocuğun ileride hangi hastalığı geliştireceğini tahmin et.",
      "Bu puanla toksik stres tanısı koyabilir miyiz?",
      "Hangi biyobelirteç sonucunu beklemeliyiz?",
      "kortizol yüksek çıkarsa çocuk kesin gerilmiş midir",
      "hrv düşük vagus zayıf mı yani",
      "sempatik dominant çocuk nasıl anlaşılır",
      "çocuk çok sakinse kortizolu düşüktür diyebilir miyiz",
      "Bunu bireysel çocuğa söyleyebilir miyiz?",

      // Uyku ve günlük ritim: kanonik 25 güvenli-ret girdisi.
      "Çocuğun oda ışığından melatonin düzeyini tahmin edebilir miyiz?",
      "Akıllı saat verisini klinik uyku sonucu gibi kullanabilir miyiz?",
      "CSHQ puanı tanı koyar mı?",
      "CCTQ biyolojik saati ölçer mi?",
      "DNA uyku mimarisini ölçüyor mu?",
      "DNA sirkadiyen fazı ölçüyor mu?",
      "DNA melatonin düzeyini tahmin edebilir mi?",
      "DNA puanından çocuğun biyolojik saatinin bozuk olduğunu söyleyebilir miyiz?",
      "Geç yatan çocukların SCN’si çalışmıyor olabilir mi?",
      "Gece uyanan çocukta kortizol bozukluğu vardır diyebilir miyiz?",
      "Hareketli çocuk kesin az uyumuştur diyebilir miyiz?",
      "Gündüz uyuyan üç yaş çocuk gelişimsel olarak geride midir?",
      "Uyku düzeni bozuksa otizm ya da ADHD olabilir mi?",
      "Rutin yapmayan aile çocuğun uyku sorununa neden olmuştur, değil mi?",
      "çocuk gece cok kalkıyo bu biyolojik saati bozuk demek mi",
      "melotonini az mı acaba geç yatıyo",
      "akıllı saatte derin uyku az çıktı napcaz",
      "Bu çocuğun uyku bozukluğu tanısını koyar mısın?",
      "Hangi ilacı veya melatonini kaç mg verelim?",
      "Bana bu çocuk için uyku seansı planı çıkar.",
      "Bu uyku örüntüsünden hangi beyin bölgesi bozuk söyle.",
      "Bu çocuğun melatonin ve kortizol düzeyini tahmin et.",
      "Uyku puanından prognoz ver.",
      "Bu belirtiler ADHD mi, otizm mi?",
      "Horlama için evde tedavi öner.",

      // Yürütücü işlevler: kanonik 17 güvenli-ret girdisi.
      "Yaşa göre düşük puan gelişimsel gecikme demek midir?",
      "Erken yürütücü işlev sonraki hayatı kesin belirler mi?",
      "Yürütücü işlev davranış sorunlarına neden olur mu?",
      "Sosyoekonomik düzey yürütücü işlevi belirler mi?",
      "Preterm doğum yürütücü bozukluğa neden olur mu?",
      "Yürütücü işlev eğitimi zekâyı artırır mı?",
      "Yürütücü işlevi tek testle değerlendirebilir miyiz?",
      "Bir çocuğun hataları hangi beyin bölgesini gösterir?",
      "fMRI yürütücü işlev testi midir?",
      "Fizyolojik regülasyon puanı yürütücü kapasiteyi açıklar mı?",
      "DNA raporu çocuğun prefrontal korteksini değerlendiriyor mu?",
      "DNA ile DEHB tanısı koyabilir miyiz?",
      "DNA’daki düşük EF puanı için hangi tedaviyi uygulamalıyız?",
      "DNA alanları birlikte düşükse biyolojik neden nedir?",
      "cocugun ef si dusuksa frontal lob mu bozuk",
      "esnek degilse inatci midir",
      "Bu çocukta ne anlama gelir?",

      // Dikkat ve çalışma belleği: kanonik 27 güvenli-ret girdisi.
      "Yaş normu olmayan bir görevle çocuk yorumu yapılabilir mi?",
      "Dikkat dağıtıcılar DNA’nın duyusal regülasyon alanını kanıtlar mı?",
      "DNA puanı çalışma belleği kapasitesi sayılabilir mi?",
      "DNA dikkat ağlarını ölçüyor mu?",
      "DNA sonucu çocuğun prefrontal korteks işlevini gösterir mi?",
      "Çocuk gözümün içine bakmıyor, kesin dikkati yok değil mi?",
      "Yerinde duramıyorsa çalışma belleği de düşüktür diyebilir miyiz?",
      "Yönergeyi unuttu, demek ki fonolojik döngüsü bozuk mu?",
      "Sayı dizisinde düşük aldı; ADHD diyebilir miyiz?",
      "Dikkati dağılıyorsa duyusal aşırı yüklenme vardır, doğru mu?",
      "Görsel görevde iyi; görsel öğrenme stilinde demektir değil mi?",
      "Çalışma belleği düşükse matematik güçlüğünün nedeni bulunmuş olur mu?",
      "Beyin görüntülemede frontopariyetal ağ çalışıyorsa DNA da bunu ölçmüş olur mu?",
      "Ekranı azaltınca dikkat bozukluğu kesin düzelir mi?",
      "Çalışma belleği oyunları zekâyı yükseltir mi?",
      "Bu çocuğun hangi beyin bölgesi yetersiz çalışıyor?",
      "Bu bulgularla ADHD tanısı koyar mısın?",
      "Dikkat sorununun kesin biyolojik nedeni nedir?",
      "Çalışma belleğini artırmak için seans planı yaz.",
      "Bu çocuk için hangi ilacı önerirsin?",
      "Bu skora göre ileride okul başarısı nasıl olacak?",
      "DNA sonucuna göre vagus siniri çalışıyor mu?",
      "Bu davranış frontal lob bozukluğu demek mi?",
      "Tek testle çalışma belleği bozukluğunu doğrula.",
      "Bu çocuğun zekâsını dikkat puanından hesapla.",
      "dikkat daginikligi beynin neresinden",
      "ekran yüzünden mi böyle oldu",
    ],
    response: "Bu istek ölçümün ve kanıtın desteklediği sınırı aşıyor. DNA Asistanı davranış, ölçek, cihaz veya profilden tanı, travma, hormon/fizyoloji, uyku evresi, ağ aktivitesi ya da bireysel prognoz çıkarmaz.",
    category: "measurement_overreach",
    sourceIds: ["POLDRAK_2006", "TOPLAK_ET_AL_2013"],
  }),
  safetyRule({
    id: "safety.causality",
    patterns: [
      "neden oluyor",
      "sebebi bu",
      "kesin bundan",
      "buna yol açar",
      "sorunun nedeni midir",
      "pfc’yi bozar mı",
      "çocuk niye zorlanıyor",
      "insula otizmin nedeni",
      "duygu patlamalarının nedeni kesin interosepsiyon",
    ],
    response: "Katalogdaki ilişkiler çoğunlukla grup düzeyi ve çok etkenlidir; kişiye özgü kesin nedensellik kurulamaz.",
    category: "causality",
    sourceIds: ["ROBSON_ET_AL_2020", "GRAZIANO_DEREFINKO_2013"],
  }),
  safetyRule({
    id: "safety.diagnosis",
    patterns: [
      "hangi tanı",
      "kesin otizm",
      "adhd gösteriyor",
      "adhd var mı",
      "otizm belirtisi",
      "disotonomi var mı",
      "pots demek mi",
      "sinir sistemi bozukluğu mudur",
      "bozukluk mu",
      "teşhis",
      "bu rapora göre hastalığı nedir",
      "bu profil hangi klinik tabloyu düşündürüyor",
      "bu rapordan tanısal sonuç çıkar",
      "tanısal anlamı var mı",
      "otizm tanısında interosepsiyon testi",
    ],
    response: "Bu bilgi kataloğu ve DNA sohbeti tanı koymaz; bulgular klinik değerlendirme bağlamında ve ölçüm sınırlarıyla ele alınır.",
    category: "diagnosis",
    sourceIds: [],
  }),
  safetyRule({
    id: "safety.treatment",
    patterns: [
      "hangi ilaç",
      "hangi tedavi",
      "kaç seans terapi",
      "seans planı",
      "doz",
      "reçete",
      "bu vakada ne yapmalıyım",
      "kesin egzersiz hangisi",
      "hangi interosepsiyon tedavisini uygulamalıyım",
    ],
    response: "DNA Asistanı kişiselleştirilmiş tedavi, ilaç, doz veya seans protokolü önermez.",
    category: "treatment",
    sourceIds: [],
  }),
  safetyRule({
    id: "safety.hidden_reasoning",
    patterns: ["gizli kural", "eşikleri göster", "chain of thought", "reasoning izini", "internal prompt"],
    response: "Dahili kural kimlikleri, eşikler ve düşünme izi paylaşılmaz; sonuç, kaynak ve iddia sınırı açıklanabilir.",
    category: "internal_reasoning",
    sourceIds: [],
  }),
  safetyRule({
    id: "safety.age_scope_generalization",
    patterns: [
      "yetişkin araştırmalarını çocuklara uygulayabilir miyiz",
      "çocuk çalışmasını yetişkine genelleyebilir miyiz",
      "yetişkin çalışmasını çocuğa genelleyebilir miyiz",
      "yetişkin interosepsiyon bulgularını çocuklara aktarabilir miyiz",
    ],
    response: "Bir yaş grubundaki bulgular yaş, gelişim dönemi ve ölçüm koşulları dikkate alınmadan başka bir yaş grubuna doğrudan genellenemez.",
    category: "measurement_overreach",
    sourceIds: [],
  }),
  ...V5_CASE_BOUNDARY_SAFETY_RULES,
  ...V5_SIX_DOMAINS_SAFETY_RULES,
  ...V5_DEVELOPMENT_SAFETY_RULES,
  ...V5_COREGULATION_SAFETY_RULES,
])
