import {
  DNA_CHAT_CATALOG_VERSION,
  type DnaChatCatalogSource,
} from "./types"
import { V5_CASE_BOUNDARY_SOURCES } from "./v5CaseBoundariesCatalog"
import { V5_COREGULATION_SOURCES } from "./v5CoregulationCatalog"
import { V5_DEVELOPMENT_SOURCES } from "./v5DevelopmentCatalog"
import { V5_SIX_DOMAINS_SOURCES } from "./v5SixDomainsCatalog"

function source(
  input: Omit<DnaChatCatalogSource, "version" | "sourceVerified" | "verifiedAt">,
  verifiedAt = "2026-07-16",
): DnaChatCatalogSource {
  return Object.freeze({
    version: DNA_CHAT_CATALOG_VERSION,
    sourceVerified: true as const,
    verifiedAt,
    ...input,
  })
}

export const DNA_CHAT_CATALOG_SOURCES: readonly DnaChatCatalogSource[] = Object.freeze([
  source({
    id: "NIGG_2017",
    title: "On the relations among self-regulation, self-control, executive functioning, effortful control, cognitive control, impulsivity, risk-taking, and inhibition",
    authors: "Nigg, J. T.",
    year: 2017,
    publication: "Journal of Child Psychology and Psychiatry, 58(4), 361-383",
    publicationStatus: "published",
    studyType: "Kavramsal yıllık derleme",
    doi: "10.1111/jcpp.12675",
    pmid: "28035675",
    url: "https://doi.org/10.1111/jcpp.12675",
    evidenceDomain: "self_regulation_constructs",
    ageScope: "developmental",
    claimBoundary: "İlişkili yapıların kavramsal ayrımlarını destekler; tek bir ölçümü veya tanıyı doğrulamaz.",
  }),
  source({
    id: "INZLICHT_ET_AL_2021",
    title: "Integrating models of self-regulation",
    authors: "Inzlicht, M., Werner, K. M., Briskin, J. L., & Roberts, B. W.",
    year: 2021,
    publication: "Annual Review of Psychology, 72, 319-345",
    publicationStatus: "published",
    studyType: "Bütünleştirici anlatısal derleme",
    doi: "10.1146/annurev-psych-061020-105721",
    pmid: "33017559",
    url: "https://doi.org/10.1146/annurev-psych-061020-105721",
    evidenceDomain: "self_regulation_models",
    ageScope: "adult_weighted",
    claimBoundary: "Çoklu self-regülasyon modellerini bütünleştirir; gelişimsel tek mekanizma veya bireysel sonuç üretmez.",
  }),
  source({
    id: "ROBSON_ET_AL_2020",
    title: "Self-regulation in childhood as a predictor of future outcomes: A meta-analytic review",
    authors: "Robson, D. A., Allen, M. S., & Howard, S. J.",
    year: 2020,
    publication: "Psychological Bulletin, 146(4), 324-354",
    publicationStatus: "published",
    studyType: "Meta-analiz",
    doi: "10.1037/bul0000227",
    pmid: "31904248",
    url: "https://doi.org/10.1037/bul0000227",
    evidenceDomain: "child_self_regulation_outcomes",
    ageScope: "childhood",
    claimBoundary: "Grup düzeyi uzun dönem ilişkileri destekler; bireysel kader, kesin prognoz veya DNA geçerliği göstermez.",
    repairNote: "Self-regülasyon paketindeki K03 yalnız grup düzeyi sonuç ilişkileri için kullanıldı; DNA validasyonuna bağlanmadı.",
  }),
  source({
    id: "BLAIR_RAVER_2015",
    title: "School readiness and self-regulation: A developmental psychobiological approach",
    authors: "Blair, C., & Raver, C. C.",
    year: 2015,
    publication: "Annual Review of Psychology, 66, 711-731",
    publicationStatus: "published",
    studyType: "Gelişimsel anlatısal derleme",
    doi: "10.1146/annurev-psych-010814-015221",
    pmid: "25148852",
    url: "https://doi.org/10.1146/annurev-psych-010814-015221",
    evidenceDomain: "developmental_self_regulation",
    ageScope: "early_childhood",
    claimBoundary: "Gelişimsel ve bağlamsal çerçeveyi destekler; tek vaka için biyolojik mekanizma veya tedavi çıkarımı sağlamaz.",
    existingLiteratureId: "BLAIR_RAVER_2015",
  }),
  source({
    id: "DIAMOND_2013",
    title: "Executive functions",
    authors: "Diamond, A.",
    year: 2013,
    publication: "Annual Review of Psychology, 64, 135-168",
    publicationStatus: "published",
    studyType: "Kapsamlı anlatısal derleme",
    doi: "10.1146/annurev-psych-113011-143750",
    pmid: "23020641",
    url: "https://doi.org/10.1146/annurev-psych-113011-143750",
    evidenceDomain: "executive_functions",
    ageScope: "developmental",
    claimBoundary: "Yürütücü işlev bileşenlerini destekler; nöropsikolojik test, lokalizasyon veya tanı yerine geçmez.",
    existingLiteratureId: "DIAMOND_2013",
  }),
  source({
    id: "MONTROY_ET_AL_2016",
    title: "The development of self-regulation across early childhood",
    authors: "Montroy, J. J., Bowles, R. P., Skibbe, L. E., McClelland, M. M., & Morrison, F. J.",
    year: 2016,
    publication: "Developmental Psychology, 52(11), 1744-1762",
    publicationStatus: "published",
    studyType: "Uzunlamasına gelişimsel çalışma",
    doi: "10.1037/dev0000159",
    pmid: "27709999",
    url: "https://doi.org/10.1037/dev0000159",
    evidenceDomain: "early_self_regulation_development",
    ageScope: "early_childhood",
    claimBoundary: "Erken gelişim seyrini grup düzeyinde destekler; tek değerlendirmeden gelişimsel gidiş tahmini üretmez.",
    existingLiteratureId: "MONTROY_ET_AL_2016",
  }),
  source({
    id: "ROSANBALM_MURRAY_2017",
    title: "Co-regulation from birth through young adulthood: A practice brief",
    authors: "Rosanbalm, K. D., & Murray, D. W.",
    year: 2017,
    publication: "U.S. Department of Health and Human Services",
    publicationStatus: "practice_brief",
    studyType: "Uygulama özeti",
    doi: null,
    pmid: null,
    url: "https://fpg.unc.edu/sites/fpg.unc.edu/files/resources/reports-and-policy-briefs/Co-RegulationFromBirthThroughYoungAdulthood.pdf",
    evidenceDomain: "co_regulation_context",
    ageScope: "developmental",
    claimBoundary: "Ko-regülasyon için bağlamsal çerçeve sağlar; nedensel biyolojik model veya tedavi protokolü değildir.",
    existingLiteratureId: "ROSANBALM_MURRAY_2017",
  }),
  source({
    id: "POLDRAK_2006",
    title: "Can cognitive processes be inferred from neuroimaging data?",
    authors: "Poldrack, R. A.",
    year: 2006,
    publication: "Trends in Cognitive Sciences, 10(2), 59-63",
    publicationStatus: "published",
    studyType: "Nörogörüntüleme yöntem makalesi",
    doi: "10.1016/j.tics.2005.12.004",
    pmid: "16406760",
    url: "https://doi.org/10.1016/j.tics.2005.12.004",
    evidenceDomain: "reverse_inference_boundary",
    ageScope: "all_ages",
    claimBoundary: "Yalnız tersine çıkarım sınırını destekler; kültürel norm, eşsonluluk veya klinik lokalizasyon kanıtı değildir.",
    repairNote: "Self-regülasyon paketindeki K38 yalnız reverse-inference sınırına bağlandı.",
  }),
  source({
    id: "WEHRWEIN_ET_AL_2016",
    title: "Overview of the anatomy, physiology, and pharmacology of the autonomic nervous system",
    authors: "Wehrwein, E. A., Orer, H. S., & Barman, S. M.",
    year: 2016,
    publication: "Comprehensive Physiology, 6(3), 1239-1278",
    publicationStatus: "published",
    studyType: "Temel fizyoloji derlemesi",
    doi: "10.1002/cphy.c150037",
    pmid: "27347892",
    url: "https://doi.org/10.1002/cphy.c150037",
    evidenceDomain: "autonomic_anatomy_physiology",
    ageScope: "all_ages",
    claimBoundary: "Temel anatomi ve fizyolojiyi destekler; davranıştan otonom dal veya hastalık çıkarımı sağlamaz.",
  }),
  source({
    id: "SAPER_2002",
    title: "The central autonomic nervous system: Conscious visceral perception and autonomic pattern generation",
    authors: "Saper, C. B.",
    year: 2002,
    publication: "Annual Review of Neuroscience, 25, 433-469",
    publicationStatus: "published",
    studyType: "Nöroanatomi derlemesi",
    doi: "10.1146/annurev.neuro.25.032502.111311",
    pmid: "12052916",
    url: "https://doi.org/10.1146/annurev.neuro.25.032502.111311",
    evidenceDomain: "central_autonomic_network",
    ageScope: "mixed",
    claimBoundary: "Dağıtık merkezi otonom örgütlenmeyi destekler; bölgesel işlevden bireysel davranış çıkarımı sağlamaz.",
  }),
  source({
    id: "BERNTSON_ET_AL_1991",
    title: "Autonomic determinism: The modes of autonomic control, the doctrine of autonomic space, and the laws of autonomic constraint",
    authors: "Berntson, G. G., Cacioppo, J. T., & Quigley, K. S.",
    year: 1991,
    publication: "Psychological Review, 98(4), 459-487",
    publicationStatus: "published",
    studyType: "Kuramsal fizyoloji derlemesi",
    doi: "10.1037/0033-295X.98.4.459",
    pmid: "1660159",
    url: "https://doi.org/10.1037/0033-295X.98.4.459",
    evidenceDomain: "autonomic_space",
    ageScope: "mixed",
    claimBoundary: "Otonom dalların bağımsız ve eşzamanlı örüntülerini destekler; kişiye dal etiketi atanmasını desteklemez.",
    repairNote: "Sempatik-parasempatik paketi K03 için dergi, cilt, sayfa ve DOI düzeltildi.",
  }),
  source({
    id: "DAMPNEY_2016",
    title: "Central neural control of the cardiovascular system: Current perspectives",
    authors: "Dampney, R. A. L.",
    year: 2016,
    publication: "Advances in Physiology Education, 40(3), 283-296",
    publicationStatus: "published",
    studyType: "Anlatısal eğitim derlemesi",
    doi: "10.1152/advan.00027.2016",
    pmid: "27445275",
    url: "https://doi.org/10.1152/advan.00027.2016",
    evidenceDomain: "cardiovascular_autonomic_control",
    ageScope: "mixed",
    claimBoundary: "Kardiyovasküler merkezi kontrolü açıklar; tüm ANS veya davranışsal self-regülasyon için kapsamlı kanıt değildir.",
    repairNote: "Sempatik-parasempatik paketi K05 fabrikasyon birleşik kaydı amaçlanan eğitim derlemesiyle değiştirildi ve kanıt gücü düşürüldü.",
  }),
  source({
    id: "CRITCHLEY_HARRISON_2013",
    title: "Visceral influences on brain and behavior",
    authors: "Critchley, H. D., & Harrison, N. A.",
    year: 2013,
    publication: "Neuron, 77(4), 624-638",
    publicationStatus: "published",
    studyType: "Anlatısal nörofizyoloji derlemesi",
    doi: "10.1016/j.neuron.2013.02.008",
    pmid: "23439117",
    url: "https://doi.org/10.1016/j.neuron.2013.02.008",
    evidenceDomain: "visceral_brain_interactions",
    ageScope: "adult_weighted",
    claimBoundary: "Visseral-beyin etkileşimlerini destekler; tek davranıştan mekanizma veya bölge çıkarımı sağlamaz.",
  }),
  source({
    id: "FURNESS_2012",
    title: "The enteric nervous system and neurogastroenterology",
    authors: "Furness, J. B.",
    year: 2012,
    publication: "Nature Reviews Gastroenterology & Hepatology, 9(5), 286-294",
    publicationStatus: "published",
    studyType: "Anlatısal derleme",
    doi: "10.1038/nrgastro.2012.32",
    pmid: "22392290",
    url: "https://doi.org/10.1038/nrgastro.2012.32",
    evidenceDomain: "enteric_nervous_system",
    ageScope: "all_ages",
    claimBoundary: "Enterik sistemin yerel ve merkezi bağlantılarını açıklar; günlük belirtinin nedenini belirlemez.",
  }),
  source({
    id: "MCEWEN_1998",
    title: "Protective and damaging effects of stress mediators",
    authors: "McEwen, B. S.",
    year: 1998,
    publication: "New England Journal of Medicine, 338(3), 171-179",
    publicationStatus: "published",
    studyType: "Klasik anlatısal derleme",
    doi: "10.1056/NEJM199801153380307",
    pmid: "9428819",
    url: "https://doi.org/10.1056/NEJM199801153380307",
    evidenceDomain: "allostasis_stress",
    ageScope: "mixed",
    claimBoundary: "Allostatik yük kavramını destekler; tek davranış veya tek biyobelirteçle kişisel yük ölçümü sağlamaz.",
  }),
  source({
    id: "RAMSAY_WOODS_2014",
    title: "Clarifying the roles of homeostasis and allostasis in physiological regulation",
    authors: "Ramsay, D. S., & Woods, S. C.",
    year: 2014,
    publication: "Psychological Review, 121(2), 225-247",
    publicationStatus: "published",
    studyType: "Kuramsal derleme",
    doi: "10.1037/a0035942",
    pmid: "24730599",
    url: "https://doi.org/10.1037/a0035942",
    evidenceDomain: "homeostasis_allostasis",
    ageScope: "mixed",
    claimBoundary: "Kavramsal ayrımı destekler; klinik eşik, skor veya kişisel mekanizma sağlamaz.",
  }),
  source({
    id: "TASK_FORCE_HRV_1996",
    title: "Heart rate variability: Standards of measurement, physiological interpretation and clinical use",
    authors: "Task Force of the ESC and NASPE",
    year: 1996,
    publication: "Circulation, 93(5), 1043-1065",
    publicationStatus: "consensus",
    studyType: "Konsensüs standardı",
    doi: "10.1161/01.CIR.93.5.1043",
    pmid: "8598068",
    url: "https://doi.org/10.1161/01.CIR.93.5.1043",
    evidenceDomain: "hrv_measurement",
    ageScope: "mixed",
    claimBoundary: "HRV ölçüm ve yorum standardını destekler; DNA puanından HRV, vagal ton veya tanı çıkarımı sağlamaz.",
  }),
  source({
    id: "LABORDE_ET_AL_2017",
    title: "Heart rate variability and cardiac vagal tone in psychophysiological research",
    authors: "Laborde, S., Mosley, E., & Thayer, J. F.",
    year: 2017,
    publication: "Frontiers in Psychology, 8, 213",
    publicationStatus: "published",
    studyType: "Yöntemsel derleme ve öneriler",
    doi: "10.3389/fpsyg.2017.00213",
    pmid: "28265249",
    url: "https://doi.org/10.3389/fpsyg.2017.00213",
    evidenceDomain: "hrv_methodology",
    ageScope: "adult_weighted",
    claimBoundary: "Araştırma ölçümü ve raporlamasını destekler; klinik eşik veya bireysel sınıflama sağlamaz.",
  }),
  source({
    id: "BILLMAN_2013",
    title: "The LF/HF ratio does not accurately measure cardiac sympatho-vagal balance",
    authors: "Billman, G. E.",
    year: 2013,
    publication: "Frontiers in Physiology, 4, 26",
    publicationStatus: "published",
    studyType: "Eleştirel fizyoloji derlemesi",
    doi: "10.3389/fphys.2013.00026",
    pmid: "23431279",
    url: "https://doi.org/10.3389/fphys.2013.00026",
    evidenceDomain: "hrv_interpretation_boundary",
    ageScope: "mixed",
    claimBoundary: "LF/HF oranının küresel sempatovagal denge ölçütü olmadığını destekler; alternatif tek ANS skoru önermez.",
  }),
  source({
    id: "GRAZIANO_DEREFINKO_2013",
    title: "Cardiac vagal control and children's adaptive functioning: A meta-analysis",
    authors: "Graziano, P. A., & Derefinko, K. J.",
    year: 2013,
    publication: "Biological Psychology, 94(1), 22-37",
    publicationStatus: "published",
    studyType: "Meta-analiz",
    doi: "10.1016/j.biopsycho.2013.04.011",
    pmid: "23648264",
    url: "https://doi.org/10.1016/j.biopsycho.2013.04.011",
    evidenceDomain: "child_cardiac_vagal_adaptive_functioning",
    ageScope: "childhood",
    claimBoundary: "Grup düzeyi ilişkileri destekler; nedensellik, bireysel sınıflama veya davranıştan HRV çıkarımı sağlamaz.",
    existingLiteratureId: "GRAZIANO_DEREFINKO_2013",
    repairNote: "Sempatik-parasempatik K31 DOI .018 yerine doğrulanmış .011 ile mevcut literatür kaydına tekilleştirildi.",
  }),
  source({
    id: "BOUCSEIN_ET_AL_2012",
    title: "Publication recommendations for electrodermal measurements",
    authors: "Boucsein, W., Fowles, D. C., Grimnes, S., et al.",
    year: 2012,
    publication: "Psychophysiology, 49(8), 1017-1034",
    publicationStatus: "consensus",
    studyType: "Yöntem önerileri",
    doi: "10.1111/j.1469-8986.2012.01384.x",
    pmid: "22680988",
    url: "https://doi.org/10.1111/j.1469-8986.2012.01384.x",
    evidenceDomain: "electrodermal_activity",
    ageScope: "mixed",
    claimBoundary: "EDA kayıt ve raporlamasını destekler; sinyalden özgül duygu, tanı veya neden çıkarımı sağlamaz.",
  }),
  source({
    id: "MATHOT_2018",
    title: "Pupillometry: Psychology, physiology, and function",
    authors: "Mathot, S.",
    year: 2018,
    publication: "Journal of Cognition, 1(1), 16",
    publicationStatus: "published",
    studyType: "Yöntemsel anlatısal derleme",
    doi: "10.5334/joc.18",
    pmid: "31517190",
    url: "https://doi.org/10.5334/joc.18",
    evidenceDomain: "pupillometry",
    ageScope: "mixed",
    claimBoundary: "Pupil ölçümünün çoklu belirleyicilerini açıklar; tek beyin çekirdeği veya otonom durum çıkarımı sağlamaz.",
  }),
  source({
    id: "KHALSA_ET_AL_2018",
    title: "Interoception and mental health: A roadmap",
    authors: "Khalsa, S. S., Adolphs, R., Cameron, O. G., et al.",
    year: 2018,
    publication: "Biological Psychiatry: Cognitive Neuroscience and Neuroimaging, 3(6), 501-513",
    publicationStatus: "consensus",
    studyType: "Uzman konsensüsü ve alan yol haritası",
    doi: "10.1016/j.bpsc.2017.12.004",
    pmid: "29884281",
    url: "https://doi.org/10.1016/j.bpsc.2017.12.004",
    evidenceDomain: "interoception",
    ageScope: "adult_weighted",
    claimBoundary: "İnterosepsiyonun çok boyutlu doğasını destekler; DNA alanını veya pediatrik bireysel çıkarımı doğrulamaz.",
  }),
  source({
    id: "GARFINKEL_ET_AL_2015",
    title: "Knowing your own heart: Distinguishing interoceptive accuracy from interoceptive awareness",
    authors: "Garfinkel, S. N., Seth, A. K., Barrett, A. B., Suzuki, K., & Critchley, H. D.",
    year: 2015,
    publication: "Biological Psychology, 104, 65-74",
    publicationStatus: "published",
    studyType: "Deneysel kavramsal çalışma",
    doi: "10.1016/j.biopsycho.2014.11.004",
    pmid: "25451381",
    url: "https://doi.org/10.1016/j.biopsycho.2014.11.004",
    evidenceDomain: "interoception_dimensions",
    ageScope: "adult_weighted",
    claimBoundary: "Görev performansı, öz-bildirim ve metabiliş ayrımını destekler; çocuklara ve tüm organ sistemlerine otomatik genellenmez.",
  }),
  source({
    id: "PINNA_EDWARDS_2020",
    title: "A systematic review of associations between interoception, vagal tone, and emotional regulation",
    authors: "Pinna, T., & Edwards, D. J.",
    year: 2020,
    publication: "Frontiers in Psychology, 11, 1792",
    publicationStatus: "published",
    studyType: "Sistematik derleme",
    doi: "10.3389/fpsyg.2020.01792",
    pmid: "32849058",
    url: "https://doi.org/10.3389/fpsyg.2020.01792",
    evidenceDomain: "interoception_emotion_regulation",
    ageScope: "adult_weighted",
    claimBoundary: "İlişki adaylarını destekler; nedensellik, tanı veya kişiye özgü vagal mekanizma sağlamaz.",
    existingLiteratureId: "PINNA_EDWARDS_2020",
    repairNote: "Otonom paket S27 eksik bibliyografik kayıt tamamlandı.",
  }),
  source({
    id: "FRIEDMAN_ROBBINS_2022",
    title: "The role of prefrontal cortex in cognitive control and executive function",
    authors: "Friedman, N. P., & Robbins, T. W.",
    year: 2022,
    publication: "Neuropsychopharmacology, 47(1), 72-89",
    publicationStatus: "published",
    studyType: "Anlatısal derleme",
    doi: "10.1038/s41386-021-01132-0",
    pmid: "34408280",
    url: "https://doi.org/10.1038/s41386-021-01132-0",
    evidenceDomain: "prefrontal_executive_control",
    ageScope: "adult_weighted",
    claimBoundary: "Prefrontal katkıları dağıtık ağ çerçevesinde destekler; davranıştan bölgesel işlev bozukluğu çıkarımı sağlamaz.",
  }),
  source({
    id: "SEELEY_2019",
    title: "The salience network: A neural system for perceiving and responding to homeostatic demands",
    authors: "Seeley, W. W.",
    year: 2019,
    publication: "Journal of Neuroscience, 39(50), 9878-9882",
    publicationStatus: "published",
    studyType: "Kısa perspektif derlemesi",
    doi: "10.1523/JNEUROSCI.1138-17.2019",
    pmid: "31676604",
    url: "https://doi.org/10.1523/JNEUROSCI.1138-17.2019",
    evidenceDomain: "salience_network",
    ageScope: "adult_weighted",
    claimBoundary: "Salience ağının homeostatik taleplerdeki rolünü açıklar; ağ işlevinden bireysel belirti çıkarımı sağlamaz.",
  }),
  source({
    id: "MENON_UDDIN_2010",
    title: "Saliency, switching, attention and control: A network model of insula function",
    authors: "Menon, V., & Uddin, L. Q.",
    year: 2010,
    publication: "Brain Structure and Function, 214(5-6), 655-667",
    publicationStatus: "published",
    studyType: "Teorik ağ modeli ve derleme",
    doi: "10.1007/s00429-010-0262-0",
    pmid: "20512370",
    url: "https://doi.org/10.1007/s00429-010-0262-0",
    evidenceDomain: "insula_salience_network",
    ageScope: "adult_weighted",
    claimBoundary: "İnsulanın salience ağındaki çoklu rolünü destekler; insulayı tek bir işlev merkezi gibi göstermez.",
  }),
  source({
    id: "LAMOTTE_ET_AL_2021",
    title: "Stress and central autonomic network",
    authors: "Lamotte, G., Shouman, K., & Benarroch, E. E.",
    year: 2021,
    publication: "Autonomic Neuroscience, 235, 102870",
    publicationStatus: "published",
    studyType: "Anlatısal derleme",
    doi: "10.1016/j.autneu.2021.102870",
    pmid: "34461325",
    url: "https://doi.org/10.1016/j.autneu.2021.102870",
    evidenceDomain: "central_autonomic_network_stress",
    ageScope: "adult_weighted",
    claimBoundary: "Merkezi otonom ağın stres bağlamındaki rolünü destekler; davranıştan CAN işlevi ölçümü sağlamaz.",
  }),
  source({
    id: "FERRARO_ET_AL_2022",
    title: "The central autonomic system revisited: Convergent evidence for a regulatory role of the insular and midcingulate cortex",
    authors: "Ferraro, S., Klugah-Brown, B., Tench, C. R., et al.",
    year: 2022,
    publication: "Neuroscience & Biobehavioral Reviews, 142, 104915",
    publicationStatus: "published",
    studyType: "Nörogörüntüleme meta-analizleri sentezi",
    doi: "10.1016/j.neubiorev.2022.104915",
    pmid: "36244505",
    url: "https://doi.org/10.1016/j.neubiorev.2022.104915",
    evidenceDomain: "central_autonomic_network",
    ageScope: "adult_weighted",
    claimBoundary: "Grup düzeyi ağ katkılarını destekler; bireysel lokalizasyon veya DNA ölçümü sağlamaz.",
  }),
  source({
    id: "QUADT_ET_AL_2022",
    title: "Cognition, emotion, and the central autonomic network",
    authors: "Quadt, L., Critchley, H. D., & Garfinkel, S. N.",
    year: 2022,
    publication: "Autonomic Neuroscience, 238, 102948",
    publicationStatus: "published",
    studyType: "Anlatısal derleme",
    doi: "10.1016/j.autneu.2022.102948",
    pmid: "35149372",
    url: "https://doi.org/10.1016/j.autneu.2022.102948",
    evidenceDomain: "central_autonomic_cognition_emotion",
    ageScope: "adult_weighted",
    claimBoundary: "Biliş-duygu-otonom ilişkilerini ağ düzeyinde açıklar; tek yönlü neden veya bireysel mekanizma sağlamaz.",
  }),
  source({
    id: "GROSSMAN_2023",
    title: "Fundamental challenges and likely refutations of the five basic premises of the polyvagal theory",
    authors: "Grossman, P.",
    year: 2023,
    publication: "Biological Psychology, 180, 108589",
    publicationStatus: "published",
    studyType: "Eleştirel kuramsal derleme",
    doi: "10.1016/j.biopsycho.2023.108589",
    pmid: "37230290",
    url: "https://doi.org/10.1016/j.biopsycho.2023.108589",
    evidenceDomain: "polyvagal_critique",
    ageScope: "mixed",
    claimBoundary: "Polivagal öncüllere yönelik eleştirileri sunar; alanın tüm görüşlerini tek başına temsil etmez.",
  }),
  source({
    id: "PORGES_2021",
    title: "Polyvagal theory: A biobehavioral journey to sociality",
    authors: "Porges, S. W.",
    year: 2021,
    publication: "Comprehensive Psychoneuroendocrinology, 7, 100069",
    publicationStatus: "published",
    studyType: "Kuramsal savunucu derleme",
    doi: "10.1016/j.cpnec.2021.100069",
    pmid: "35757052",
    url: "https://doi.org/10.1016/j.cpnec.2021.100069",
    evidenceDomain: "polyvagal_theory",
    ageScope: "mixed",
    claimBoundary: "Teorinin kendi önermelerini açıklar; davranıştan vagal durum atamasını veya klinik tanıyı doğrulamaz.",
  }),
  source({
    id: "MCINTOSH_ET_AL_1999",
    title: "Sensory-modulation disruption, electrodermal responses, and functional behaviors",
    authors: "McIntosh, D. N., Miller, L. J., Shyu, V., & Hagerman, R. J.",
    year: 1999,
    publication: "Developmental Medicine & Child Neurology, 41(9), 608-615",
    publicationStatus: "published",
    studyType: "Küçük karşılaştırmalı deneysel çalışma",
    doi: "10.1111/j.1469-8749.1999.tb00664.x",
    pmid: "10503919",
    url: "https://doi.org/10.1111/j.1469-8749.1999.tb00664.x",
    evidenceDomain: "pediatric_sensory_eda",
    ageScope: "childhood",
    claimBoundary: "Seçilmiş küçük örneklemde EDA farklılıklarını bildirir; genellenebilirlik, özgüllük ve tanısal kullanım sağlamaz.",
    repairNote: "Sempatik-parasempatik K40 başlık, dergi, sayfa ve DOI doğrulandı; PubMed aynı makale için 10.1017/S0012162299001267 DOI eş adını gösterir.",
  }),
  source({
    id: "CHRISTENSEN_ET_AL_2020",
    title: "Diverse autonomic nervous system stress response patterns in childhood sensory modulation",
    authors: "Christensen, J. S., Wild, H., Kenzie, E. S., et al.",
    year: 2020,
    publication: "Frontiers in Integrative Neuroscience, 14, 6",
    publicationStatus: "published",
    studyType: "Çocukluk psikofizyoloji çalışması",
    doi: "10.3389/fnint.2020.00006",
    pmid: "32132906",
    url: "https://doi.org/10.3389/fnint.2020.00006",
    evidenceDomain: "child_sensory_autonomic_patterns",
    ageScope: "childhood",
    claimBoundary: "Heterojen grup örüntülerini destekler; otizme özgü sonuç, bireysel mekanizma veya tanı sağlamaz.",
    repairNote: "Otonom paket S25 yanlış mini-derleme kaydı yerine doğrulanmış özgün çalışma kullanıldı; otizm-spesifik iddia çıkarıldı.",
  }),
  source({
    id: "WHEDON_ET_AL_2018",
    title: "Cardiac vagal regulation in infancy predicts executive function and social competence in preschool: Indirect effects through language",
    authors: "Whedon, M., Perry, N. B., Calkins, S. D., & Bell, M. A.",
    year: 2018,
    publication: "Developmental Psychobiology, 60(5), 595-607",
    publicationStatus: "published",
    studyType: "Boylamsal çalışma",
    doi: "10.1002/dev.21636",
    pmid: "29785749",
    url: "https://doi.org/10.1002/dev.21636",
    evidenceDomain: "infant_vagal_preschool_outcomes",
    ageScope: "early_childhood",
    claimBoundary: "Boylamsal grup ilişkisini destekler; nedensellik veya bireysel prognoz sağlamaz.",
    repairNote: "Otonom paket S18 eksik DOI tamamlandı; başlık, yazarlar ve 595-607 sayfa aralığı PubMed kaydıyla düzeltildi.",
  }),
  source({
    id: "ALEN_ET_AL_2022",
    title: "The association between parenting and child autonomic nervous system activity: A systematic review and meta-analysis",
    authors: "Alen, N. V., et al.",
    year: 2022,
    publication: "Neuroscience & Biobehavioral Reviews, 139, 104734",
    publicationStatus: "published",
    studyType: "Sistematik derleme ve meta-analiz",
    doi: "10.1016/j.neubiorev.2022.104734",
    pmid: "35716874",
    url: "https://doi.org/10.1016/j.neubiorev.2022.104734",
    evidenceDomain: "parenting_child_autonomic_association",
    ageScope: "childhood",
    claimBoundary: "Ebeveynlik ve çocuk otonom etkinliği arasındaki grup ilişkilerini destekler; nedensellik veya biyolojik eş-regülasyon ölçümü değildir.",
    repairNote: "Otonom paket S21 eksik DOI tamamlandı.",
  }),
  source({
    id: "GASIOR_ET_AL_2018",
    title: "Normative values for heart rate variability parameters in school-aged children",
    authors: "Gąsior, J. S., et al.",
    year: 2018,
    publication: "Frontiers in Physiology, 9, 1495",
    publicationStatus: "published",
    studyType: "Normatif çalışma",
    doi: "10.3389/fphys.2018.01495",
    pmid: "30405445",
    url: "https://doi.org/10.3389/fphys.2018.01495",
    evidenceDomain: "child_hrv_norms",
    ageScope: "childhood",
    claimBoundary: "Belirli protokolde grup normlarını sunar; DNA puanı veya protokoller arası kişisel eşik sağlamaz.",
    repairNote: "Otonom paket S12 PMID 30337892 yerine 30405445 olarak düzeltildi.",
  }),
  source({
    id: "THAYER_LANE_2009",
    title: "Claude Bernard and the heart-brain connection: Further elaboration of a model of neurovisceral integration",
    authors: "Thayer, J. F., & Lane, R. D.",
    year: 2009,
    publication: "Neuroscience & Biobehavioral Reviews, 33(2), 81-88",
    publicationStatus: "published",
    studyType: "Kuramsal derleme",
    doi: "10.1016/j.neubiorev.2008.08.004",
    pmid: "18771686",
    url: "https://doi.org/10.1016/j.neubiorev.2008.08.004",
    evidenceDomain: "neurovisceral_integration",
    ageScope: "adult_weighted",
    claimBoundary: "Kuramsal beyin-kalp bütünleşme modelini açıklar; HRV'den bireysel beyin işlevi çıkarımı sağlamaz.",
    repairNote: "Otonom paket S09 PMID 19424767 yerine 18771686 olarak düzeltildi.",
  }),
  source({
    id: "MILLER_COHEN_2001",
    title: "An integrative theory of prefrontal cortex function",
    authors: "Miller, E. K., & Cohen, J. D.",
    year: 2001,
    publication: "Annual Review of Neuroscience, 24, 167-202",
    publicationStatus: "published",
    studyType: "Kuramsal klasik derleme",
    doi: "10.1146/annurev.neuro.24.1.167",
    pmid: "11283309",
    url: "https://doi.org/10.1146/annurev.neuro.24.1.167",
    evidenceDomain: "prefrontal_cognitive_control",
    ageScope: "adult_weighted",
    claimBoundary: "Hedefe yönelik bilişsel kontrol için bütünleştirici bir PFC modeli sunar; tek-bölge açıklaması, çocukta lokalizasyon veya bireysel mekanizma kanıtı değildir.",
  }, "2026-07-17"),
  source({
    id: "KOLK_RAKIC_2022",
    title: "Development of prefrontal cortex",
    authors: "Kolk, S. M., & Rakic, P.",
    year: 2022,
    publication: "Neuropsychopharmacology, 47(1), 41-57",
    publicationStatus: "published",
    studyType: "Gelişimsel nörobiyoloji derlemesi",
    doi: "10.1038/s41386-021-01137-9",
    pmid: "34645980",
    url: "https://doi.org/10.1038/s41386-021-01137-9",
    evidenceDomain: "prefrontal_development",
    ageScope: "developmental",
    claimBoundary: "PFC gelişimini hücresel ve ağ düzeyinde sentezler; gözlenen çocuk davranışını belirli bir olgunlaşma evresine veya bölgeye eşleştirmez.",
  }, "2026-07-17"),
  source({
    id: "FISKE_HOLMBOE_2019",
    title: "Neural substrates of early executive function development",
    authors: "Fiske, A., & Holmboe, K.",
    year: 2019,
    publication: "Developmental Review, 52, 42-62",
    publicationStatus: "published",
    studyType: "Gelişimsel anlatısal derleme",
    doi: "10.1016/j.dr.2019.100866",
    pmid: "31417205",
    url: "https://doi.org/10.1016/j.dr.2019.100866",
    evidenceDomain: "early_executive_function_development",
    ageScope: "early_childhood",
    claimBoundary: "Erken yürütücü işlev gelişiminin dağıtık sinirsel dayanaklarını özetler; davranıştan PFC etkinliği veya olgunluk düzeyi çıkarımı sağlamaz.",
  }, "2026-07-17"),
  source({
    id: "TOPLAK_ET_AL_2013",
    title: "Practitioner review: Do performance-based measures and ratings of executive function assess the same construct?",
    authors: "Toplak, M. E., West, R. F., & Stanovich, K. E.",
    year: 2013,
    publication: "Journal of Child Psychology and Psychiatry, 54(2), 131-143",
    publicationStatus: "published",
    studyType: "Yöntemsel uygulayıcı derlemesi",
    doi: "10.1111/jcpp.12001",
    pmid: "23057693",
    url: "https://doi.org/10.1111/jcpp.12001",
    evidenceDomain: "executive_function_measurement",
    ageScope: "developmental",
    claimBoundary: "Performans görevleriyle günlük yaşam derecelendirmelerinin farklı bilgi sağlayabildiğini destekler; ölçümlerden biri tek başına yürütücü işlevin tamamı değildir.",
  }, "2026-07-17"),
  source({
    id: "BUSH_ET_AL_2000",
    title: "Cognitive and emotional influences in anterior cingulate cortex",
    authors: "Bush, G., Luu, P., & Posner, M. I.",
    year: 2000,
    publication: "Trends in Cognitive Sciences, 4(6), 215-222",
    publicationStatus: "published",
    studyType: "Kurucu anlatısal derleme",
    doi: "10.1016/S1364-6613(00)01483-2",
    pmid: "10827444",
    url: "https://doi.org/10.1016/S1364-6613(00)01483-2",
    evidenceDomain: "anterior_cingulate_organization",
    ageScope: "adult_weighted",
    claimBoundary: "ACC'nin bilişsel ve duygusal katkıları için tarihsel bir çerçeve sunar; ikili altbölüm modeli güncel anatominin tamamı veya bireysel lokalizasyon aracı değildir.",
  }, "2026-07-17"),
  source({
    id: "CARTER_VAN_VEEN_2007",
    title: "Anterior cingulate cortex and conflict detection: An update of theory and data",
    authors: "Carter, C. S., & van Veen, V.",
    year: 2007,
    publication: "Cognitive, Affective, & Behavioral Neuroscience, 7(4), 367-379",
    publicationStatus: "published",
    studyType: "Kuramsal ve deneysel kanıt derlemesi",
    doi: "10.3758/CABN.7.4.367",
    pmid: "18189010",
    url: "https://doi.org/10.3758/CABN.7.4.367",
    evidenceDomain: "anterior_cingulate_performance_monitoring",
    ageScope: "adult_weighted",
    claimBoundary: "Çatışma ve performans izlemeye ilişkin modelleri sentezler; ACC işlevini tek bir hesaba indirgemez ve çocuk davranışından bölgesel sonuç çıkarmaz.",
  }, "2026-07-17"),
  source({
    id: "HEILBRONNER_HAYDEN_2016",
    title: "Dorsal anterior cingulate cortex: A bottom-up view",
    authors: "Heilbronner, S. R., & Hayden, B. Y.",
    year: 2016,
    publication: "Annual Review of Neuroscience, 39, 149-170",
    publicationStatus: "published",
    studyType: "Karşılaştırmalı anatomi ve işlev derlemesi",
    doi: "10.1146/annurev-neuro-070815-013952",
    pmid: "27090954",
    url: "https://doi.org/10.1146/annurev-neuro-070815-013952",
    evidenceDomain: "dorsal_anterior_cingulate_anatomy",
    ageScope: "mixed",
    claimBoundary: "dACC'nin bağlantıları ve çoklu işlevleri için karşılaştırmalı bir çerçeve sunar; insan çocukta tek işlev, tanı veya hasar çıkarımı sağlamaz.",
  }, "2026-07-17"),
  source({
    id: "WIERSEMA_ET_AL_2007",
    title: "Developmental changes in error monitoring: An event-related potential study",
    authors: "Wiersema, J. R., van der Meere, J. J., & Roeyers, H.",
    year: 2007,
    publication: "Neuropsychologia, 45(8), 1649-1657",
    publicationStatus: "published",
    studyType: "Kesitsel gelişimsel ERP çalışması",
    doi: "10.1016/j.neuropsychologia.2007.01.004",
    pmid: "17303199",
    url: "https://doi.org/10.1016/j.neuropsychologia.2007.01.004",
    evidenceDomain: "developmental_error_monitoring_erp",
    ageScope: "developmental",
    claimBoundary: "Hata izleme ERP bileşenlerinde yaşla ilişkili grup farklarını bildirir; ERN tek başına ACC ölçümü, klinik eşik veya bireysel gelişim göstergesi değildir.",
  }, "2026-07-17"),
  source({
    id: "UDDIN_ET_AL_2017",
    title: "Structure and function of the human insula",
    authors: "Uddin, L. Q., Nomi, J. S., Hebert-Seropian, B., Ghaziri, J., & Boucher, O.",
    year: 2017,
    publication: "Journal of Clinical Neurophysiology, 34(4), 300-306",
    publicationStatus: "published",
    studyType: "Anatomik ve işlevsel anlatısal derleme",
    doi: "10.1097/WNP.0000000000000377",
    pmid: "28644199",
    url: "https://doi.org/10.1097/WNP.0000000000000377",
    evidenceDomain: "insula_structure_function",
    ageScope: "adult_weighted",
    claimBoundary: "İnsulanın heterojen yapı, bağlantı ve işlevlerini özetler; insulayı tek merkez olarak sunmaz ve davranıştan bölgesel işlev çıkarımı sağlamaz.",
  }, "2026-07-17"),
  source({
    id: "KURTH_ET_AL_2010",
    title: "A link between the systems: Functional differentiation and integration within the human insula revealed by meta-analysis",
    authors: "Kurth, F., Zilles, K., Fox, P. T., Laird, A. R., & Eickhoff, S. B.",
    year: 2010,
    publication: "Brain Structure and Function, 214(5-6), 519-534",
    publicationStatus: "published",
    studyType: "İşlevsel nörogörüntüleme meta-analizi",
    doi: "10.1007/s00429-010-0255-z",
    pmid: "20512376",
    url: "https://doi.org/10.1007/s00429-010-0255-z",
    evidenceDomain: "insula_functional_organization",
    ageScope: "adult_weighted",
    claimBoundary: "Grup düzeyi insula işlevsel farklılaşmasını ve örtüşmesini destekler; kesin altbölge sınırı veya bireysel tersine çıkarım sağlamaz.",
  }, "2026-07-17"),
  source({
    id: "SCHULZ_2016",
    title: "Neural correlates of heart-focused interoception: A functional magnetic resonance imaging meta-analysis",
    authors: "Schulz, S. M.",
    year: 2016,
    publication: "Philosophical Transactions of the Royal Society B, 371(1708), 20160018",
    publicationStatus: "published",
    studyType: "Fonksiyonel nörogörüntüleme meta-analizi",
    doi: "10.1098/rstb.2016.0018",
    pmid: "28080975",
    url: "https://doi.org/10.1098/rstb.2016.0018",
    evidenceDomain: "cardiac_interoception_neuroimaging",
    ageScope: "adult_weighted",
    claimBoundary: "Kalp odaklı dikkat görevlerinde grup düzeyi dağıtık etkinlik örüntülerini sentezler; genel interosepsiyon, çocuk gelişimi veya bireysel insula işlevi ölçümü değildir.",
  }, "2026-07-17"),
  source({
    id: "ADDABBO_MILANI_2025",
    title: "Measuring interoception from infancy to childhood: A scoping review",
    authors: "Addabbo, M., & Milani, L.",
    year: 2025,
    publication: "Neuroscience & Biobehavioral Reviews, 173, 106161",
    publicationStatus: "published",
    studyType: "Pediatrik kapsam derlemesi",
    doi: "10.1016/j.neubiorev.2025.106161",
    pmid: "40245971",
    url: "https://doi.org/10.1016/j.neubiorev.2025.106161",
    evidenceDomain: "developmental_interoception_measurement",
    ageScope: "developmental",
    claimBoundary: "Bebeklikten çocukluğa kullanılan yöntemleri ve boşlukları haritalar; yaşa göre norm, tek altın standart veya DNA'nın biyolojik geçerliğini sağlamaz.",
  }, "2026-07-17"),
  source({
    id: "CHEN_ET_AL_2021",
    title: "The emerging science of interoception: Sensing, integrating, interpreting, and regulating signals within the self",
    authors: "Chen, W. G., Schloesser, D., Arensdorf, A. M., et al.",
    year: 2021,
    publication: "Trends in Neurosciences, 44(1), 3-16",
    publicationStatus: "published",
    studyType: "Bütünleştirici anlatısal derleme",
    doi: "10.1016/j.tins.2020.10.007",
    pmid: "33378655",
    url: "https://doi.org/10.1016/j.tins.2020.10.007",
    evidenceDomain: "interoception_processes",
    ageScope: "mixed",
    claimBoundary: "İnteroseptif sinyallerin algılanması, bütünleştirilmesi, yorumlanması ve düzenlenmesi için çok aşamalı çerçeve sunar; pediatrik eşik veya kişisel biyolojik mekanizma vermez.",
  }, "2026-07-17"),
  source({
    id: "QUIGLEY_ET_AL_2021",
    title: "Functions of interoception: From energy regulation to experience of the self",
    authors: "Quigley, K. S., Kanoski, S., Grill, W. M., Barrett, L. F., & Tsakiris, M.",
    year: 2021,
    publication: "Trends in Neurosciences, 44(1), 29-38",
    publicationStatus: "published",
    studyType: "Bütünleştirici anlatısal derleme",
    doi: "10.1016/j.tins.2020.09.008",
    pmid: "33378654",
    url: "https://doi.org/10.1016/j.tins.2020.09.008",
    evidenceDomain: "interoception_functions",
    ageScope: "mixed",
    claimBoundary: "İnterosepsiyonun enerji düzenleme ve deneyimle ilişkili çoklu işlevlerini tartışır; çocuk davranışına tek neden veya ölçüm eşdeğerliği yüklemez.",
  }, "2026-07-17"),
  source({
    id: "DESMEDT_ET_AL_2023",
    title: "The new measures of interoceptive accuracy: A systematic review and assessment",
    authors: "Desmedt, O., Luminet, O., Walentynowicz, M., & Corneille, O.",
    year: 2023,
    publication: "Neuroscience & Biobehavioral Reviews, 153, 105388",
    publicationStatus: "published",
    studyType: "Sistematik ölçüm derlemesi",
    doi: "10.1016/j.neubiorev.2023.105388",
    pmid: "37708919",
    url: "https://doi.org/10.1016/j.neubiorev.2023.105388",
    evidenceDomain: "interoceptive_accuracy_measurement",
    ageScope: "adult_weighted",
    claimBoundary: "Yeni interoseptif doğruluk ölçümlerinin güçlü ve zayıf yanlarını değerlendirir; görevler eşdeğer değildir ve sonuçlar tüm modalitelere ya da çocuklara genellenemez.",
  }, "2026-07-17"),
  source({
    id: "DONAGHY_ET_AL_2025",
    title: "Measuring cardiac interoceptive accuracy in infancy: Lessons from the adult literature",
    authors: "Donaghy, R., Lisi, M., Shinskey, J., & Murphy, J.",
    year: 2025,
    publication: "Psychophysiology, 62(3), e70041",
    publicationStatus: "published",
    studyType: "Gelişimsel yöntem derlemesi",
    doi: "10.1111/psyp.70041",
    pmid: "40066756",
    url: "https://doi.org/10.1111/psyp.70041",
    evidenceDomain: "infant_cardiac_interoception_measurement",
    ageScope: "early_childhood",
    claimBoundary: "Bebeklikte kardiyak interoseptif doğruluk ölçümünün yöntemsel güçlüklerini tanımlar; tek görevden bilinçli farkındalık, norm veya kişisel kapasite çıkarımı sağlamaz.",
  }, "2026-07-17"),
  source({
    id: "MAISTER_ET_AL_2017",
    title: "Neurobehavioral evidence of interoceptive sensitivity in early infancy",
    authors: "Maister, L., Tang, T., & Tsakiris, M.",
    year: 2017,
    publication: "eLife, 6, e25318",
    publicationStatus: "published",
    studyType: "Bebeklik deneysel çalışması",
    doi: "10.7554/eLife.25318",
    pmid: "28784203",
    url: "https://doi.org/10.7554/eLife.25318",
    evidenceDomain: "infant_interoceptive_sensitivity",
    ageScope: "early_childhood",
    claimBoundary: "Bebeklerin bedensel ritimle eşzamanlı görsel uyaranlara duyarlılığını gösterir; bilinçli farkındalık, genel interoseptif doğruluk veya bireysel gelişim ölçümü değildir.",
  }, "2026-07-17"),
  source({
    id: "ASTON_JONES_COHEN_2005",
    title: "An integrative theory of locus coeruleus-norepinephrine function: Adaptive gain and optimal performance",
    authors: "Aston-Jones, G., & Cohen, J. D.",
    year: 2005,
    publication: "Annual Review of Neuroscience, 28, 403-450",
    publicationStatus: "published",
    studyType: "Kuramsal ve bütünleştirici derleme",
    doi: "10.1146/annurev.neuro.28.061604.135709",
    pmid: "16022602",
    url: "https://doi.org/10.1146/annurev.neuro.28.061604.135709",
    evidenceDomain: "arousal_adaptive_gain",
    ageScope: "adult_weighted",
    claimBoundary: "Uyarılma ve performans için yetişkin ve hayvan ağırlıklı mekanistik çerçeve sunar; çocukta tek davranıştan nörotransmiter, beyin çekirdeği veya ideal uyarılma düzeyi çıkarımı sağlamaz.",
  }, "2026-07-17"),
  source({
    id: "BURT_OBRADOVIC_2013",
    title: "The construct of psychophysiological reactivity: Statistical and psychometric issues",
    authors: "Burt, K. B., & Obradović, J.",
    year: 2013,
    publication: "Developmental Review, 33(1), 29-57",
    publicationStatus: "published",
    studyType: "Yöntemsel derleme",
    doi: "10.1016/j.dr.2012.10.002",
    pmid: null,
    url: "https://doi.org/10.1016/j.dr.2012.10.002",
    evidenceDomain: "psychophysiological_reactivity_measurement",
    ageScope: "developmental",
    claimBoundary: "Reaktivitenin taban düzeyi, değişim büyüklüğü ve zaman bileşenlerinin ayrılmasını destekler; tek göstergeyi bütün düzenleme sistemine eşitlemez.",
  }, "2026-07-17"),
  source({
    id: "BATES_ET_AL_2022",
    title: "Early childhood stress responses to psychosocial stressors: The state of the science",
    authors: "Bates, R. A., Militello, L., Barker, E., Gonzalez Villasanti, H., & Schmeer, K.",
    year: 2022,
    publication: "Developmental Psychobiology, 64(7), e22320",
    publicationStatus: "published",
    studyType: "Kapsamlı anlatısal inceleme",
    doi: "10.1002/dev.22320",
    pmid: "36282746",
    url: "https://doi.org/10.1002/dev.22320",
    evidenceDomain: "early_childhood_stress_reactivity",
    ageScope: "early_childhood",
    claimBoundary: "Erken çocukluk stres çalışmalarındaki artmış, azalmış ve sıfır yanıt çeşitliliğini gösterir; kişisel biyolojik mekanizma veya klinik eşik sağlamaz.",
  }, "2026-07-17"),
  source({
    id: "SACREY_ET_AL_2021",
    title: "Physiological measurement of emotion from infancy to preschool: A systematic review and meta-analysis",
    authors: "Sacrey, L.-A. R., Raza, S., Armstrong, V., et al.",
    year: 2021,
    publication: "Brain and Behavior, 11(2), e01989",
    publicationStatus: "published",
    studyType: "Sistematik derleme ve meta-analiz",
    doi: "10.1002/brb3.1989",
    pmid: "33336555",
    url: "https://doi.org/10.1002/brb3.1989",
    evidenceDomain: "early_emotion_physiology_measurement",
    ageScope: "early_childhood",
    claimBoundary: "Doğumdan okul öncesine fizyolojik duygu ölçümlerindeki heterojenliği özetler; davranış ile fizyolojinin bire bir eşleştiğini göstermez.",
  }, "2026-07-17"),
  source({
    id: "SMITH_THELEN_2003",
    title: "Development as a dynamic system",
    authors: "Smith, L. B., & Thelen, E.",
    year: 2003,
    publication: "Trends in Cognitive Sciences, 7(8), 343-348",
    publicationStatus: "published",
    studyType: "Kuramsal derleme",
    doi: "10.1016/S1364-6613(03)00156-6",
    pmid: "12907229",
    url: "https://doi.org/10.1016/S1364-6613(03)00156-6",
    evidenceDomain: "developmental_dynamic_systems",
    ageScope: "developmental",
    claimBoundary: "Gelişimi çok bileşenli ve bağlama duyarlı dinamik sistem olarak çerçeveler; öz-örgütlenmeyi doğrudan ölçen klinik test veya kişisel mekanizma değildir.",
  }, "2026-07-17"),
  source({
    id: "COLE_ET_AL_2004",
    title: "Emotion regulation as a scientific construct: Methodological challenges and directions for child development research",
    authors: "Cole, P. M., Martin, S. E., & Dennis, T. A.",
    year: 2004,
    publication: "Child Development, 75(2), 317-333",
    publicationStatus: "published",
    studyType: "Kavramsal ve yöntemsel derleme",
    doi: "10.1111/j.1467-8624.2004.00673.x",
    pmid: "15056186",
    url: "https://doi.org/10.1111/j.1467-8624.2004.00673.x",
    evidenceDomain: "child_emotion_regulation_construct",
    ageScope: "childhood",
    claimBoundary: "Duygusal tepki ile düzenleyici süreçlerin kavramsal ayrımını destekler; gözlenen davranıştan niyet, mekanizma veya başarı çıkarımını çözmez.",
    existingLiteratureId: "COLE_ET_AL_2004",
  }, "2026-07-17"),
  source({
    id: "COLE_ET_AL_2020",
    title: "Development of emotion regulation dynamics across early childhood: A multiple time-scale approach",
    authors: "Cole, P. M., Lougheed, J. P., Chow, S.-M., & Ram, N.",
    year: 2020,
    publication: "Affective Science, 1(1), 28-41",
    publicationStatus: "published",
    studyType: "Boylamsal yoğun zaman serisi çalışması",
    doi: "10.1007/s42761-020-00004-y",
    pmid: "34734191",
    url: "https://doi.org/10.1007/s42761-020-00004-y",
    evidenceDomain: "early_emotion_regulation_dynamics",
    ageScope: "early_childhood",
    claimBoundary: "Erken çocuklukta duygu dinamiklerini çoklu zaman ölçeğinde inceler; laboratuvar görevi evrensel toparlanma normu veya bireysel yeterlilik testi değildir.",
  }, "2026-07-17"),
  source({
    id: "JONES_MASON_ET_AL_2018",
    title: "Autonomic nervous system functioning assessed during the Still-Face Paradigm: A meta-analysis and systematic review of methods, approach and findings",
    authors: "Jones-Mason, K., Alkon, A., Coccia, M., & Bush, N. R.",
    year: 2018,
    publication: "Developmental Review, 50, 113-139",
    publicationStatus: "published",
    studyType: "Meta-analiz ve sistematik yöntem incelemesi",
    doi: "10.1016/j.dr.2018.06.002",
    pmid: "33707809",
    url: "https://doi.org/10.1016/j.dr.2018.06.002",
    evidenceDomain: "infant_autonomic_reactivity_recovery",
    ageScope: "early_childhood",
    claimBoundary: "Bebeklerde belirli bir sosyal stres paradigmasındaki grup düzeyi otonom örüntüleri özetler; davranıştan bireysel ANS toparlanması çıkarımı sağlamaz.",
  }, "2026-07-17"),
  source({
    id: "RANKIN_ET_AL_2009",
    title: "Habituation revisited: An updated and revised description of the behavioral characteristics of habituation",
    authors: "Rankin, C. H., Abrams, T., Barry, R. J., et al.",
    year: 2009,
    publication: "Neurobiology of Learning and Memory, 92(2), 135-138",
    publicationStatus: "consensus",
    studyType: "Konsensüs niteliğinde anlatısal inceleme",
    doi: "10.1016/j.nlm.2008.09.012",
    pmid: "18854219",
    url: "https://doi.org/10.1016/j.nlm.2008.09.012",
    evidenceDomain: "habituation_characteristics",
    ageScope: "all_ages",
    claimBoundary: "Habituasyonun davranışsal özelliklerini tanımlar; çocuklara özgü norm, duyusal adaptasyon eşdeğerliği veya klinik yorum sağlamaz.",
  }, "2026-07-17"),
  source({
    id: "FISHER_ET_AL_2018",
    title: "Lack of group-to-individual generalizability is a threat to human subjects research",
    authors: "Fisher, A. J., Medaglia, J. D., & Jeronimus, B. F.",
    year: 2018,
    publication: "Proceedings of the National Academy of Sciences, 115(27), E6106-E6115",
    publicationStatus: "published",
    studyType: "Yöntemsel ve ampirik makale",
    doi: "10.1073/pnas.1711978115",
    pmid: "29915059",
    url: "https://doi.org/10.1073/pnas.1711978115",
    evidenceDomain: "group_to_individual_boundary",
    ageScope: "adult_weighted",
    claimBoundary: "Grup örüntülerinin bireye otomatik taşınamayacağını gösteren yöntem ilkesini destekler; çocuklara özgü sonuç veya alternatif kişisel tahmin sağlamaz.",
  }, "2026-07-17"),
  source({
    id: "DUNN_2001",
    title: "The sensations of everyday life: Empirical, theoretical, and pragmatic considerations",
    authors: "Dunn, W.",
    year: 2001,
    publication: "American Journal of Occupational Therapy, 55(6), 608-620",
    publicationStatus: "published",
    studyType: "Kuramsal ve ampirik anlatısal makale",
    doi: "10.5014/ajot.55.6.608",
    pmid: "12959225",
    url: "https://doi.org/10.5014/ajot.55.6.608",
    evidenceDomain: "sensory_processing_framework",
    ageScope: "mixed",
    claimBoundary: "Duyusal örüntüleri kuramsal eşik ve yanıt stratejileriyle açıklar; anket puanı biyolojik veya psikofizik eşiği doğrudan ölçmez.",
  }, "2026-07-17"),
  source({
    id: "WATKYNS_ET_AL_2024",
    title: "Sensory reactivity assessment in children: A systematic review",
    authors: "Watkyns, A. F., Cloete, L. G., & Parham, L. D.",
    year: 2024,
    publication: "Developmental Medicine & Child Neurology, 66(4), 422-439",
    publicationStatus: "published",
    studyType: "Sistematik ölçüm derlemesi",
    doi: "10.1111/dmcn.15758",
    pmid: "37771091",
    url: "https://doi.org/10.1111/dmcn.15758",
    evidenceDomain: "child_sensory_reactivity_measurement",
    ageScope: "childhood",
    claimBoundary: "Çocuklarda araç ve psikometrik kanıt heterojenliğini gösterir; tek ölçek tanı, fizyoloji veya tüm bağlamlardaki kapasiteyi belirlemez.",
  }, "2026-07-17"),
  source({
    id: "GOMEZ_ET_AL_2017",
    title: "Behavioural and autonomic regulation of response to sensory stimuli among children: A systematic review of relationship and methodology",
    authors: "Gomez, I. N. B., Lai, C. Y. Y., Morato-Espino, P. G., et al.",
    year: 2017,
    publication: "BioMed Research International, 2017, 2629310",
    publicationStatus: "published",
    studyType: "Sistematik derleme",
    doi: "10.1155/2017/2629310",
    pmid: "29333436",
    url: "https://doi.org/10.1155/2017/2629310",
    evidenceDomain: "sensory_autonomic_relationship",
    ageScope: "childhood",
    claimBoundary: "Davranışsal ve otonom duyusal yanıt çalışmalarının kesitsel ve heterojen olduğunu gösterir; duyusal davranışı belirli ANS durumuna eşitlemez.",
  }, "2026-07-17"),
  source({
    id: "GROSS_2015",
    title: "Emotion regulation: Current status and future prospects",
    authors: "Gross, J. J.",
    year: 2015,
    publication: "Psychological Inquiry, 26(1), 1-26",
    publicationStatus: "published",
    studyType: "Güçlü anlatısal derleme",
    doi: "10.1080/1047840X.2014.940781",
    pmid: null,
    url: "https://doi.org/10.1080/1047840X.2014.940781",
    evidenceDomain: "emotion_regulation_process_model",
    ageScope: "adult_weighted",
    claimBoundary: "Duygu düzenleme süreç ve stratejilerini kavramsallaştırır; yetişkin ağırlıklı çerçeve çocukta kişisel mekanizma veya en iyi strateji belirlemez.",
  }, "2026-07-17"),
  source({
    id: "BONANNO_BURTON_2013",
    title: "Regulatory flexibility: An individual differences perspective on coping and emotion regulation",
    authors: "Bonanno, G. A., & Burton, C. L.",
    year: 2013,
    publication: "Perspectives on Psychological Science, 8(6), 591-612",
    publicationStatus: "published",
    studyType: "Kuramsal derleme",
    doi: "10.1177/1745691613504116",
    pmid: "26173226",
    url: "https://doi.org/10.1177/1745691613504116",
    evidenceDomain: "regulatory_flexibility",
    ageScope: "adult_weighted",
    claimBoundary: "Strateji-bağlam uyumunu ve esnekliği vurgular; çocukluk için evrensel iyi/kötü strateji sıralaması sağlamaz.",
  }, "2026-07-17"),
  source({
    id: "MAZEFSKY_ET_AL_2021",
    title: "Evidence base update for questionnaires of emotion regulation and reactivity for children and adolescents",
    authors: "Mazefsky, C. A., Conner, C. M., Breitenfeldt, K., et al.",
    year: 2021,
    publication: "Journal of Clinical Child & Adolescent Psychology, 50(6), 683-707",
    publicationStatus: "published",
    studyType: "Sistematik kanıt güncellemesi",
    doi: "10.1080/15374416.2021.1955372",
    pmid: "34436940",
    url: "https://doi.org/10.1080/15374416.2021.1955372",
    evidenceDomain: "child_emotion_regulation_measurement",
    ageScope: "developmental",
    claimBoundary: "Çocuk ve ergen anketlerinin psikometrik kanıtını değerlendirir; ölçek puanı tanı, biyolojik mekanizma veya bütün düzenleme repertuarı değildir.",
  }, "2026-07-17"),
  source({
    id: "REITSEMA_ET_AL_2022",
    title: "Emotion dynamics in children and adolescents: A meta-analytic and descriptive review",
    authors: "Reitsema, A. M., Jeronimus, B. F., van Dijk, M., & de Jonge, P.",
    year: 2022,
    publication: "Emotion, 22(2), 374-396",
    publicationStatus: "published",
    studyType: "Meta-analitik ve betimleyici derleme",
    doi: "10.1037/emo0000970",
    pmid: "34843305",
    url: "https://doi.org/10.1037/emo0000970",
    evidenceDomain: "child_adolescent_emotion_dynamics",
    ageScope: "developmental",
    claimBoundary: "Günlük duygu yoğunluğu, değişkenliği ve ataletini grup düzeyinde özetler; kişisel neden, tanı veya tek bir normal örüntü sağlamaz.",
  }, "2026-07-17"),
  source({
    id: "CHROUSOS_2009",
    title: "Stress and disorders of the stress system",
    authors: "Chrousos, G. P.",
    year: 2009,
    publication: "Nature Reviews Endocrinology, 5(7), 374-381",
    publicationStatus: "published",
    studyType: "Güçlü anlatısal derleme",
    doi: "10.1038/nrendo.2009.106",
    pmid: "19488073",
    url: "https://doi.org/10.1038/nrendo.2009.106",
    evidenceDomain: "stress_system_overview",
    ageScope: "all_ages",
    claimBoundary: "Stres sisteminin çok bileşenli fizyolojisini açıklar; davranıştan kişisel hormon, HPA veya hastalık çıkarımı sağlamaz.",
  }, "2026-07-17"),
  source({
    id: "MCEWEN_2007",
    title: "Physiology and neurobiology of stress and adaptation: Central role of the brain",
    authors: "McEwen, B. S.",
    year: 2007,
    publication: "Physiological Reviews, 87(3), 873-904",
    publicationStatus: "published",
    studyType: "Kapsamlı mekanistik derleme",
    doi: "10.1152/physrev.00041.2006",
    pmid: "17615391",
    url: "https://doi.org/10.1152/physrev.00041.2006",
    evidenceDomain: "stress_adaptation_allostasis",
    ageScope: "mixed",
    claimBoundary: "Stres ve adaptasyon mekanizmalarını genel düzeyde açıklar; bireysel beyin işlevi, kalıcı hasar veya çocukluk normu belirlemez.",
  }, "2026-07-17"),
  source({
    id: "GUNNAR_QUEVEDO_2007",
    title: "The neurobiology of stress and development",
    authors: "Gunnar, M., & Quevedo, K.",
    year: 2007,
    publication: "Annual Review of Psychology, 58, 145-173",
    publicationStatus: "published",
    studyType: "Gelişimsel anlatısal derleme",
    doi: "10.1146/annurev.psych.58.110405.085605",
    pmid: "16903808",
    url: "https://doi.org/10.1146/annurev.psych.58.110405.085605",
    evidenceDomain: "developmental_stress_systems",
    ageScope: "developmental",
    claimBoundary: "Gelişimsel stres biyolojisini grup düzeyinde açıklar; tek çocuktaki HPA işlevi, neden veya prognoz ölçümü değildir.",
  }, "2026-07-17"),
  source({
    id: "DEJOSEPH_ET_AL_2024",
    title: "Adrenocortical and autonomic cross-system regulation in youth: A meta-analysis",
    authors: "DeJoseph, M. L., Leneman, K. B., Palmer, A. R., et al.",
    year: 2024,
    publication: "Psychoneuroendocrinology, 159, 106416",
    publicationStatus: "published",
    studyType: "Meta-analiz",
    doi: "10.1016/j.psyneuen.2023.106416",
    pmid: "39081795",
    url: "https://doi.org/10.1016/j.psyneuen.2023.106416",
    evidenceDomain: "youth_hpa_autonomic_coordination",
    ageScope: "developmental",
    claimBoundary: "Gençlerde HPA ve otonom göstergelerin grup düzeyi eşzamanlılığını özetler; bir sistemden diğerinin kişisel durumunu çıkarmaya izin vermez.",
  }, "2026-07-17"),
  source({
    id: "HOSTINAR_ET_AL_2014",
    title: "Psychobiological mechanisms underlying the social buffering of the hypothalamic-pituitary-adrenocortical axis",
    authors: "Hostinar, C. E., Sullivan, R. M., & Gunnar, M. R.",
    year: 2014,
    publication: "Psychological Bulletin, 140(1), 256-282",
    publicationStatus: "published",
    studyType: "Gelişimsel anlatısal derleme",
    doi: "10.1037/a0032671",
    pmid: "23607429",
    url: "https://doi.org/10.1037/a0032671",
    evidenceDomain: "developmental_social_buffering",
    ageScope: "developmental",
    claimBoundary: "Sosyal desteğin stres tepkileriyle grup düzeyi ilişkisini açıklar; ebeveyni tek neden yapmaz ve vaka için hormon sonucu vermez.",
  }, "2026-07-17"),
  source({
    id: "SHONKOFF_ET_AL_2012",
    title: "The lifelong effects of early childhood adversity and toxic stress",
    authors: "Shonkoff, J. P., Garner, A. S., Siegel, B. S., et al.",
    year: 2012,
    publication: "Pediatrics, 129(1), e232-e246",
    publicationStatus: "published",
    studyType: "Akademi teknik raporu",
    doi: "10.1542/peds.2011-2663",
    pmid: "22201156",
    url: "https://doi.org/10.1542/peds.2011-2663",
    evidenceDomain: "toxic_stress_public_health_framework",
    ageScope: "childhood",
    claimBoundary: "Toksik stresi halk sağlığı ve gelişim çerçevesi olarak ele alır; tek başına tanı, biyolojik test veya belirli çocukta hasar kanıtı değildir.",
  }, "2026-07-17"),
  source({
    id: "STALDER_ET_AL_2016",
    title: "Assessment of the cortisol awakening response: Expert consensus guidelines",
    authors: "Stalder, T., Kirschbaum, C., Kudielka, B. M., et al.",
    year: 2016,
    publication: "Psychoneuroendocrinology, 63, 414-432",
    publicationStatus: "consensus",
    studyType: "Uzman konsensüs kılavuzu",
    doi: "10.1016/j.psyneuen.2015.10.010",
    pmid: "26563991",
    url: "https://doi.org/10.1016/j.psyneuen.2015.10.010",
    evidenceDomain: "cortisol_awakening_measurement",
    ageScope: "mixed",
    claimBoundary: "Kortizol uyanma yanıtının örnekleme ve raporlama gerekliliklerini açıklar; davranış veya DNA puanından kortizol tahmini sağlamaz.",
  }, "2026-07-17"),
  source({
    id: "LUCENTE_GUIDI_2023",
    title: "Allostatic load in children and adolescents: A systematic review",
    authors: "Lucente, M., & Guidi, J.",
    year: 2023,
    publication: "Psychotherapy and Psychosomatics, 92(5), 295-303",
    publicationStatus: "published",
    studyType: "Sistematik derleme",
    doi: "10.1159/000533424",
    pmid: "37666236",
    url: "https://doi.org/10.1159/000533424",
    evidenceDomain: "pediatric_allostatic_load_measurement",
    ageScope: "developmental",
    claimBoundary: "Çocuk ve ergen çalışmalarındaki çoklu gösterge heterojenliğini özetler; evrensel bireysel eşik veya DNA ölçümü sağlamaz.",
  }, "2026-07-17"),
  source({
    id: "PARUTHI_ET_AL_2016",
    title: "Recommended amount of sleep for pediatric populations: A consensus statement of the American Academy of Sleep Medicine",
    authors: "Paruthi, S., Brooks, L. J., D'Ambrosio, C., et al.",
    year: 2016,
    publication: "Journal of Clinical Sleep Medicine, 12(6), 785-786",
    publicationStatus: "consensus",
    studyType: "Uzman konsensüs bildirisi",
    doi: "10.5664/jcsm.5866",
    pmid: "27250809",
    url: "https://doi.org/10.5664/jcsm.5866",
    evidenceDomain: "pediatric_sleep_duration_guidance",
    ageScope: "childhood",
    claimBoundary: "Toplum düzeyi yaş aralıkları sunar; bireysel optimum, tanı eşiği veya tedavi önerisi değildir.",
  }, "2026-07-17"),
  source({
    id: "GALLAND_ET_AL_2012",
    title: "Normal sleep patterns in infants and children: A systematic review of observational studies",
    authors: "Galland, B. C., Taylor, B. J., Elder, D. E., & Herbison, P.",
    year: 2012,
    publication: "Sleep Medicine Reviews, 16(3), 213-222",
    publicationStatus: "published",
    studyType: "Sistematik gözlemsel derleme",
    doi: "10.1016/j.smrv.2011.06.001",
    pmid: "21784676",
    url: "https://doi.org/10.1016/j.smrv.2011.06.001",
    evidenceDomain: "developmental_sleep_patterns",
    ageScope: "developmental",
    claimBoundary: "Yaşa göre grup örüntülerini özetler; tek çocuk için zorunlu süre, bozukluk veya gelişim hükmü vermez.",
  }, "2026-07-17"),
  source({
    id: "BORBELY_ET_AL_2016",
    title: "The two-process model of sleep regulation: A reappraisal",
    authors: "Borbély, A. A., Daan, S., Wirz-Justice, A., & Deboer, T.",
    year: 2016,
    publication: "Journal of Sleep Research, 25(2), 131-143",
    publicationStatus: "published",
    studyType: "Kuramsal yeniden değerlendirme",
    doi: "10.1111/jsr.12371",
    pmid: "26762182",
    url: "https://doi.org/10.1111/jsr.12371",
    evidenceDomain: "sleep_two_process_model",
    ageScope: "mixed",
    claimBoundary: "Uyku basıncı ve sirkadiyen süreçlerin kuramsal ayrımını destekler; davranıştan biyolojik süreç veya faz ölçmez.",
  }, "2026-07-17"),
  source({
    id: "HASTINGS_ET_AL_2018",
    title: "Generation of circadian rhythms in the suprachiasmatic nucleus",
    authors: "Hastings, M. H., Maywood, E. S., & Brancaccio, M.",
    year: 2018,
    publication: "Nature Reviews Neuroscience, 19(8), 453-469",
    publicationStatus: "published",
    studyType: "Mekanistik anlatısal derleme",
    doi: "10.1038/s41583-018-0026-z",
    pmid: "29934559",
    url: "https://doi.org/10.1038/s41583-018-0026-z",
    evidenceDomain: "circadian_rhythm_mechanisms",
    ageScope: "all_ages",
    claimBoundary: "Sirkadiyen ritim üretiminin genel mekanizmasını açıklar; yatış saatinden SCN işlevi veya kişisel sirkadiyen faz çıkarımı sağlamaz.",
  }, "2026-07-17"),
  source({
    id: "MELTZER_ET_AL_2012_SLEEP",
    title: "Use of actigraphy for assessment in pediatric sleep research",
    authors: "Meltzer, L. J., Montgomery-Downs, H. E., Insana, S. P., & Walsh, C. M.",
    year: 2012,
    publication: "Sleep Medicine Reviews, 16(5), 463-475",
    publicationStatus: "published",
    studyType: "Sistematik yöntem derlemesi",
    doi: "10.1016/j.smrv.2011.10.002",
    pmid: "22424706",
    url: "https://doi.org/10.1016/j.smrv.2011.10.002",
    evidenceDomain: "pediatric_sleep_actigraphy",
    ageScope: "childhood",
    claimBoundary: "Aktigrafinin hareket temelli uyku tahminini değerlendirir; uyku evresi, biyolojik saat veya tek başına tanı ölçmez.",
  }, "2026-07-17"),
  source({
    id: "ASTILL_ET_AL_2012",
    title: "Sleep, cognition, and behavioral problems in school-age children: A century of research meta-analyzed",
    authors: "Astill, R. G., Van der Heijden, K. B., Van IJzendoorn, M. H., & Van Someren, E. J. W.",
    year: 2012,
    publication: "Psychological Bulletin, 138(6), 1109-1138",
    publicationStatus: "published",
    studyType: "Meta-analiz",
    doi: "10.1037/a0028204",
    pmid: "22545685",
    url: "https://doi.org/10.1037/a0028204",
    evidenceDomain: "child_sleep_cognition_behavior",
    ageScope: "childhood",
    claimBoundary: "Uyku ile biliş ve davranış arasındaki grup ilişkilerini özetler; tek çocukta neden, tanı veya okul prognozu sağlamaz.",
  }, "2026-07-17"),
  source({
    id: "GREGORY_SADEH_2012",
    title: "Sleep, emotional and behavioral difficulties in children and adolescents",
    authors: "Gregory, A. M., & Sadeh, A.",
    year: 2012,
    publication: "Sleep Medicine Reviews, 16(2), 129-136",
    publicationStatus: "published",
    studyType: "Anlatısal derleme",
    doi: "10.1016/j.smrv.2011.03.007",
    pmid: "21676633",
    url: "https://doi.org/10.1016/j.smrv.2011.03.007",
    evidenceDomain: "child_sleep_emotion_behavior",
    ageScope: "developmental",
    claimBoundary: "Çift yönlü grup ilişkilerini açıklar; uyku örüntüsünü duygusal bozukluk, neden veya kişisel mekanizmaya eşitlemez.",
  }, "2026-07-17"),
  source({
    id: "INHULSEN_ET_AL_2022",
    title: "Measuring sleep health in primary school-aged children: A systematic review of instruments and their content validity",
    authors: "Inhulsen, M.-B. M. R., van Stralen, M. M., Terwee, C. B., et al.",
    year: 2022,
    publication: "Sleep, 45(11), zsac215",
    publicationStatus: "published",
    studyType: "Sistematik ölçüm derlemesi",
    doi: "10.1093/sleep/zsac215",
    pmid: "36087112",
    url: "https://doi.org/10.1093/sleep/zsac215",
    evidenceDomain: "child_sleep_health_measurement",
    ageScope: "childhood",
    claimBoundary: "Araçların farklı uyku boyutlarını kapsadığını gösterir; tek ölçek tanı, uyku mimarisi veya biyolojik ritim ölçümü değildir.",
  }, "2026-07-17"),
  source({
    id: "SADEH_2004",
    title: "A brief screening questionnaire for infant sleep problems: Validation and findings for an Internet sample",
    authors: "Sadeh, A.",
    year: 2004,
    publication: "Pediatrics, 113(6), e570-e577",
    publicationStatus: "published",
    studyType: "Ölçek doğrulama çalışması",
    doi: "10.1542/peds.113.6.e570",
    pmid: "15173539",
    url: "https://doi.org/10.1542/peds.113.6.e570",
    evidenceDomain: "infant_sleep_questionnaire",
    ageScope: "early_childhood",
    claimBoundary: "Bakımveren bildirimli tarama örüntülerini değerlendirir; anket puanı tanı, uyku evresi veya biyolojik mekanizma değildir.",
    repairNote: "Uyku paketindeki K41 yanlış PubMed bağlantısı 15173547 yerine DOI ile eşleşen PMID 15173539 olarak düzeltildi.",
  }, "2026-07-17"),
  source({
    id: "MIYAKE_ET_AL_2000",
    title: "The unity and diversity of executive functions and their contributions to complex frontal lobe tasks: A latent variable analysis",
    authors: "Miyake, A., Friedman, N. P., Emerson, M. J., et al.",
    year: 2000,
    publication: "Cognitive Psychology, 41(1), 49-100",
    publicationStatus: "published",
    studyType: "Latent değişken çalışması",
    doi: "10.1006/cogp.1999.0734",
    pmid: "10945922",
    url: "https://doi.org/10.1006/cogp.1999.0734",
    evidenceDomain: "executive_function_unity_diversity",
    ageScope: "adult_weighted",
    claimBoundary: "Yürütücü işlevlerin ortak ve ayrışan bileşenlerini destekler; yetişkin görev yapısı çocuk normu veya frontal-lob testi değildir.",
  }, "2026-07-17"),
  source({
    id: "KARR_ET_AL_2018",
    title: "The unity and diversity of executive functions: A systematic review and re-analysis of latent variable studies",
    authors: "Karr, J. E., Areshenkoff, C. N., Rast, P., et al.",
    year: 2018,
    publication: "Psychological Bulletin, 144(11), 1147-1185",
    publicationStatus: "published",
    studyType: "Sistematik derleme ve yeniden analiz",
    doi: "10.1037/bul0000160",
    pmid: "30080055",
    url: "https://doi.org/10.1037/bul0000160",
    evidenceDomain: "executive_function_structure",
    ageScope: "mixed",
    claimBoundary: "Yürütücü yapı modellerinin heterojenliğini gösterir; tek bir evrensel faktör yapısı veya bireysel kapasite sonucu vermez.",
  }, "2026-07-17"),
  source({
    id: "DOEBEL_2020",
    title: "Rethinking executive function and its development",
    authors: "Doebel, S.",
    year: 2020,
    publication: "Perspectives on Psychological Science, 15(4), 942-956",
    publicationStatus: "published",
    studyType: "Kuramsal anlatısal derleme",
    doi: "10.1177/1745691620904771",
    pmid: "32348707",
    url: "https://doi.org/10.1177/1745691620904771",
    evidenceDomain: "executive_function_context_development",
    ageScope: "developmental",
    claimBoundary: "Yürütücü performansın hedef, bilgi ve bağlamla ilişkisini vurgular; tek görevden sabit özellik veya biyolojik neden çıkarmaz.",
  }, "2026-07-17"),
  source({
    id: "GARON_ET_AL_2008",
    title: "Executive function in preschoolers: A review using an integrative framework",
    authors: "Garon, N., Bryson, S. E., & Smith, I. M.",
    year: 2008,
    publication: "Psychological Bulletin, 134(1), 31-60",
    publicationStatus: "published",
    studyType: "Gelişimsel bütünleştirici derleme",
    doi: "10.1037/0033-2909.134.1.31",
    pmid: "18193994",
    url: "https://doi.org/10.1037/0033-2909.134.1.31",
    evidenceDomain: "preschool_executive_function",
    ageScope: "early_childhood",
    claimBoundary: "Okul öncesi yürütücü işlev gelişimini bütünleştirir; tek davranış, görev veya yaş üzerinden tanı ve olgunluk hükmü vermez.",
    existingLiteratureId: "GARON_ET_AL_2008",
  }, "2026-07-17"),
  source({
    id: "HENDRY_ET_AL_2016",
    title: "Executive function in the first three years of life: Precursors, predictors and patterns",
    authors: "Hendry, A., Jones, E. J. H., & Charman, T.",
    year: 2016,
    publication: "Developmental Review, 42, 1-33",
    publicationStatus: "published",
    studyType: "Gelişimsel anlatısal derleme",
    doi: "10.1016/j.dr.2016.06.005",
    pmid: null,
    url: "https://doi.org/10.1016/j.dr.2016.06.005",
    evidenceDomain: "early_executive_function_development",
    ageScope: "early_childhood",
    claimBoundary: "İlk üç yıldaki öncül süreçleri özetler; bebek davranışını yetişkin tipi yürütücü işlev, tanı veya kesin prognoza eşitlemez.",
  }, "2026-07-17"),
  source({
    id: "ANDERSON_REIDY_2012",
    title: "Assessing executive function in preschoolers",
    authors: "Anderson, P. J., & Reidy, N.",
    year: 2012,
    publication: "Neuropsychology Review, 22(4), 345-360",
    publicationStatus: "published",
    studyType: "Sistematik olmayan ölçüm derlemesi",
    doi: "10.1007/s11065-012-9220-3",
    pmid: "23109046",
    url: "https://doi.org/10.1007/s11065-012-9220-3",
    evidenceDomain: "preschool_executive_measurement",
    ageScope: "early_childhood",
    claimBoundary: "Okul öncesi ölçüm zorluklarını açıklar; tek test, günlük davranış veya DNA alanı bütün yürütücü işlevleri ölçmez.",
  }, "2026-07-17"),
  source({
    id: "PETERSEN_POSNER_2012",
    title: "The attention system of the human brain: 20 years after",
    authors: "Petersen, S. E., & Posner, M. I.",
    year: 2012,
    publication: "Annual Review of Neuroscience, 35, 73-89",
    publicationStatus: "published",
    studyType: "Kavramsal nörobilim derlemesi",
    doi: "10.1146/annurev-neuro-062111-150525",
    pmid: "22524787",
    url: "https://doi.org/10.1146/annurev-neuro-062111-150525",
    evidenceDomain: "attention_network_model",
    ageScope: "adult_weighted",
    claimBoundary: "Dikkat ağları için genel model sunar; gözlenen davranıştan belirli ağın veya beyin bölgesinin kişisel işlevi çıkarılamaz.",
  }, "2026-07-17"),
  source({
    id: "RUEDA_ET_AL_2004",
    title: "Development of attentional networks in childhood",
    authors: "Rueda, M. R., Fan, J., McCandliss, B. D., et al.",
    year: 2004,
    publication: "Neuropsychologia, 42(8), 1029-1040",
    publicationStatus: "published",
    studyType: "Kesitsel gelişimsel görev çalışması",
    doi: "10.1016/j.neuropsychologia.2003.12.012",
    pmid: "15093142",
    url: "https://doi.org/10.1016/j.neuropsychologia.2003.12.012",
    evidenceDomain: "child_attention_network_development",
    ageScope: "childhood",
    claimBoundary: "Çocuklarda görev tabanlı grup farklarını gösterir; ağ skoru bireysel beyin işlevi, tanı veya değişmez kapasite değildir.",
  }, "2026-07-17"),
  source({
    id: "FISHER_ET_AL_2013_ATTENTION",
    title: "Assessing selective sustained attention in 3- to 5-year-old children: Evidence from a new paradigm",
    authors: "Fisher, A. V., Thiessen, E. D., Godwin, K. E., et al.",
    year: 2013,
    publication: "Journal of Experimental Child Psychology, 114(2), 275-294",
    publicationStatus: "published",
    studyType: "Gelişimsel görev çalışması",
    doi: "10.1016/j.jecp.2012.07.006",
    pmid: "23022318",
    url: "https://doi.org/10.1016/j.jecp.2012.07.006",
    evidenceDomain: "preschool_selective_sustained_attention",
    ageScope: "early_childhood",
    claimBoundary: "Belirli bir okul öncesi paradigmasındaki performansı inceler; tek görev genel dikkat, tanı veya biyolojik ağ ölçümü değildir.",
  }, "2026-07-17"),
  source({
    id: "BETTS_ET_AL_2006",
    title: "The development of sustained attention in children: The effect of age and task load",
    authors: "Betts, J., McKay, J., Maruff, P., & Anderson, V.",
    year: 2006,
    publication: "Child Neuropsychology, 12(3), 205-221",
    publicationStatus: "published",
    studyType: "Kesitsel gelişimsel çalışma",
    doi: "10.1080/09297040500488522",
    pmid: "16837396",
    url: "https://doi.org/10.1080/09297040500488522",
    evidenceDomain: "sustained_attention_development",
    ageScope: "childhood",
    claimBoundary: "Yaş ve görev yüküyle grup düzeyi performans değişimini gösterir; tek oturum değişmez dikkat kapasitesi veya tanı değildir.",
  }, "2026-07-17"),
  source({
    id: "COWAN_2014",
    title: "Working memory underpins cognitive development, learning, and education",
    authors: "Cowan, N.",
    year: 2014,
    publication: "Educational Psychology Review, 26, 197-223",
    publicationStatus: "published",
    studyType: "Kavramsal anlatısal derleme",
    doi: "10.1007/s10648-013-9246-y",
    pmid: "25346585",
    url: "https://doi.org/10.1007/s10648-013-9246-y",
    evidenceDomain: "working_memory_development_learning",
    ageScope: "developmental",
    claimBoundary: "Çalışma belleğinin gelişim ve öğrenmeyle grup düzeyi ilişkisini açıklar; tek puandan zeka, başarı veya neden çıkarmaz.",
  }, "2026-07-17"),
  source({
    id: "BADDELEY_2000",
    title: "The episodic buffer: A new component of working memory?",
    authors: "Baddeley, A.",
    year: 2000,
    publication: "Trends in Cognitive Sciences, 4(11), 417-423",
    publicationStatus: "published",
    studyType: "Kuramsal anlatısal makale",
    doi: "10.1016/S1364-6613(00)01538-2",
    pmid: "11058819",
    url: "https://doi.org/10.1016/S1364-6613(00)01538-2",
    evidenceDomain: "working_memory_model",
    ageScope: "mixed",
    claimBoundary: "Çalışma belleğinin kuramsal bileşenlerinden birini açıklar; model tek görev sonucu, beyin bölgesi veya klinik sınıf değildir.",
  }, "2026-07-17"),
  source({
    id: "GATHERCOLE_ET_AL_2004",
    title: "The structure of working memory from 4 to 15 years of age",
    authors: "Gathercole, S. E., Pickering, S. J., Ambridge, B., & Wearing, H.",
    year: 2004,
    publication: "Developmental Psychology, 40(2), 177-190",
    publicationStatus: "published",
    studyType: "Gelişimsel yapısal çalışma",
    doi: "10.1037/0012-1649.40.2.177",
    pmid: "14979759",
    url: "https://doi.org/10.1037/0012-1649.40.2.177",
    evidenceDomain: "working_memory_development_structure",
    ageScope: "developmental",
    claimBoundary: "4-15 yaş grubunda yapısal örüntüleri destekler; grup modeli tek çocuk için kapasite, tanı veya gelişim eşiği değildir.",
  }, "2026-07-17"),
  source({
    id: "HEDGE_ET_AL_2018",
    title: "The reliability paradox: Why robust cognitive tasks do not produce reliable individual differences",
    authors: "Hedge, C., Powell, G., & Sumner, P.",
    year: 2018,
    publication: "Behavior Research Methods, 50(3), 1166-1186",
    publicationStatus: "published",
    studyType: "Yöntemsel ampirik çalışma",
    doi: "10.3758/s13428-017-0935-1",
    pmid: "28726177",
    url: "https://doi.org/10.3758/s13428-017-0935-1",
    evidenceDomain: "cognitive_task_reliability_boundary",
    ageScope: "adult_weighted",
    claimBoundary: "Grup etkisi güçlü görevlerin bireysel fark güvenirliğinin sınırlı olabileceğini gösterir; çocuk normu veya alternatif tanı aracı değildir.",
  }, "2026-07-17"),
  ...V5_CASE_BOUNDARY_SOURCES,
  ...V5_SIX_DOMAINS_SOURCES,
  ...V5_DEVELOPMENT_SOURCES,
  ...V5_COREGULATION_SOURCES,
])

export const DNA_CHAT_CATALOG_SOURCE_BY_ID = new Map(
  DNA_CHAT_CATALOG_SOURCES.map((entry) => [entry.id, entry]),
)
