import {
  DNA_CHAT_CATALOG_VERSION,
  type DnaChatCatalogSource,
} from "./types"

function source(
  input: Omit<DnaChatCatalogSource, "version" | "sourceVerified" | "verifiedAt">,
): DnaChatCatalogSource {
  return Object.freeze({
    version: DNA_CHAT_CATALOG_VERSION,
    sourceVerified: true as const,
    verifiedAt: "2026-07-16",
    ...input,
  })
}

export const DNA_CHAT_CATALOG_SOURCES: readonly DnaChatCatalogSource[] = Object.freeze([
  source({
    id: "NIGG_2017",
    title: "On the relations among self-regulation, self-control, executive functioning, effortful control, cognitive control, impulsivity, risk-taking, and inhibition",
    authors: "Nigg, J. T.",
    year: 2017,
    publication: "Journal of Child Psychology and Psychiatry, 58(4), 361-383",
    publicationStatus: "published",
    studyType: "Kavramsal yıllık derleme",
    doi: "10.1111/jcpp.12675",
    pmid: "28035675",
    url: "https://doi.org/10.1111/jcpp.12675",
    evidenceDomain: "self_regulation_constructs",
    ageScope: "developmental",
    claimBoundary: "İlişkili yapıların kavramsal ayrımlarını destekler; tek bir ölçümü veya tanıyı doğrulamaz.",
  }),
  source({
    id: "INZLICHT_ET_AL_2021",
    title: "Integrating models of self-regulation",
    authors: "Inzlicht, M., Werner, K. M., Briskin, J. L., & Roberts, B. W.",
    year: 2021,
    publication: "Annual Review of Psychology, 72, 319-345",
    publicationStatus: "published",
    studyType: "Bütünleştirici anlatısal derleme",
    doi: "10.1146/annurev-psych-061020-105721",
    pmid: "33017559",
    url: "https://doi.org/10.1146/annurev-psych-061020-105721",
    evidenceDomain: "self_regulation_models",
    ageScope: "adult_weighted",
    claimBoundary: "Çoklu self-regülasyon modellerini bütünleştirir; gelişimsel tek mekanizma veya bireysel sonuç üretmez.",
  }),
  source({
    id: "ROBSON_ET_AL_2020",
    title: "Self-regulation in childhood as a predictor of future outcomes: A meta-analytic review",
    authors: "Robson, D. A., Allen, M. S., & Howard, S. J.",
    year: 2020,
    publication: "Psychological Bulletin, 146(4), 324-354",
    publicationStatus: "published",
    studyType: "Meta-analiz",
    doi: "10.1037/bul0000227",
    pmid: "31904248",
    url: "https://doi.org/10.1037/bul0000227",
    evidenceDomain: "child_self_regulation_outcomes",
    ageScope: "childhood",
    claimBoundary: "Grup düzeyi uzun dönem ilişkileri destekler; bireysel kader, kesin prognoz veya DNA geçerliği göstermez.",
    repairNote: "Self-regülasyon paketindeki K03 yalnız grup düzeyi sonuç ilişkileri için kullanıldı; DNA validasyonuna bağlanmadı.",
  }),
  source({
    id: "BLAIR_RAVER_2015",
    title: "School readiness and self-regulation: A developmental psychobiological approach",
    authors: "Blair, C., & Raver, C. C.",
    year: 2015,
    publication: "Annual Review of Psychology, 66, 711-731",
    publicationStatus: "published",
    studyType: "Gelişimsel anlatısal derleme",
    doi: "10.1146/annurev-psych-010814-015221",
    pmid: "25148852",
    url: "https://doi.org/10.1146/annurev-psych-010814-015221",
    evidenceDomain: "developmental_self_regulation",
    ageScope: "early_childhood",
    claimBoundary: "Gelişimsel ve bağlamsal çerçeveyi destekler; tek vaka için biyolojik mekanizma veya tedavi çıkarımı sağlamaz.",
    existingLiteratureId: "BLAIR_RAVER_2015",
  }),
  source({
    id: "DIAMOND_2013",
    title: "Executive functions",
    authors: "Diamond, A.",
    year: 2013,
    publication: "Annual Review of Psychology, 64, 135-168",
    publicationStatus: "published",
    studyType: "Kapsamlı anlatısal derleme",
    doi: "10.1146/annurev-psych-113011-143750",
    pmid: "23020641",
    url: "https://doi.org/10.1146/annurev-psych-113011-143750",
    evidenceDomain: "executive_functions",
    ageScope: "developmental",
    claimBoundary: "Yürütücü işlev bileşenlerini destekler; nöropsikolojik test, lokalizasyon veya tanı yerine geçmez.",
    existingLiteratureId: "DIAMOND_2013",
  }),
  source({
    id: "MONTROY_ET_AL_2016",
    title: "The development of self-regulation across early childhood",
    authors: "Montroy, J. J., Bowles, R. P., Skibbe, L. E., McClelland, M. M., & Morrison, F. J.",
    year: 2016,
    publication: "Developmental Psychology, 52(11), 1744-1762",
    publicationStatus: "published",
    studyType: "Uzunlamasına gelişimsel çalışma",
    doi: "10.1037/dev0000159",
    pmid: "27709999",
    url: "https://doi.org/10.1037/dev0000159",
    evidenceDomain: "early_self_regulation_development",
    ageScope: "early_childhood",
    claimBoundary: "Erken gelişim seyrini grup düzeyinde destekler; tek değerlendirmeden gelişimsel gidiş tahmini üretmez.",
    existingLiteratureId: "MONTROY_ET_AL_2016",
  }),
  source({
    id: "ROSANBALM_MURRAY_2017",
    title: "Co-regulation from birth through young adulthood: A practice brief",
    authors: "Rosanbalm, K. D., & Murray, D. W.",
    year: 2017,
    publication: "U.S. Department of Health and Human Services",
    publicationStatus: "practice_brief",
    studyType: "Uygulama özeti",
    doi: null,
    pmid: null,
    url: "https://fpg.unc.edu/sites/fpg.unc.edu/files/resources/reports-and-policy-briefs/Co-RegulationFromBirthThroughYoungAdulthood.pdf",
    evidenceDomain: "co_regulation_context",
    ageScope: "developmental",
    claimBoundary: "Ko-regülasyon için bağlamsal çerçeve sağlar; nedensel biyolojik model veya tedavi protokolü değildir.",
    existingLiteratureId: "ROSANBALM_MURRAY_2017",
  }),
  source({
    id: "POLDRAK_2006",
    title: "Can cognitive processes be inferred from neuroimaging data?",
    authors: "Poldrack, R. A.",
    year: 2006,
    publication: "Trends in Cognitive Sciences, 10(2), 59-63",
    publicationStatus: "published",
    studyType: "Nörogörüntüleme yöntem makalesi",
    doi: "10.1016/j.tics.2005.12.004",
    pmid: "16406760",
    url: "https://doi.org/10.1016/j.tics.2005.12.004",
    evidenceDomain: "reverse_inference_boundary",
    ageScope: "all_ages",
    claimBoundary: "Yalnız tersine çıkarım sınırını destekler; kültürel norm, eşsonluluk veya klinik lokalizasyon kanıtı değildir.",
    repairNote: "Self-regülasyon paketindeki K38 yalnız reverse-inference sınırına bağlandı.",
  }),
  source({
    id: "WEHRWEIN_ET_AL_2016",
    title: "Overview of the anatomy, physiology, and pharmacology of the autonomic nervous system",
    authors: "Wehrwein, E. A., Orer, H. S., & Barman, S. M.",
    year: 2016,
    publication: "Comprehensive Physiology, 6(3), 1239-1278",
    publicationStatus: "published",
    studyType: "Temel fizyoloji derlemesi",
    doi: "10.1002/cphy.c150037",
    pmid: "27347892",
    url: "https://doi.org/10.1002/cphy.c150037",
    evidenceDomain: "autonomic_anatomy_physiology",
    ageScope: "all_ages",
    claimBoundary: "Temel anatomi ve fizyolojiyi destekler; davranıştan otonom dal veya hastalık çıkarımı sağlamaz.",
  }),
  source({
    id: "SAPER_2002",
    title: "The central autonomic nervous system: Conscious visceral perception and autonomic pattern generation",
    authors: "Saper, C. B.",
    year: 2002,
    publication: "Annual Review of Neuroscience, 25, 433-469",
    publicationStatus: "published",
    studyType: "Nöroanatomi derlemesi",
    doi: "10.1146/annurev.neuro.25.032502.111311",
    pmid: "12052916",
    url: "https://doi.org/10.1146/annurev.neuro.25.032502.111311",
    evidenceDomain: "central_autonomic_network",
    ageScope: "mixed",
    claimBoundary: "Dağıtık merkezi otonom örgütlenmeyi destekler; bölgesel işlevden bireysel davranış çıkarımı sağlamaz.",
  }),
  source({
    id: "BERNTSON_ET_AL_1991",
    title: "Autonomic determinism: The modes of autonomic control, the doctrine of autonomic space, and the laws of autonomic constraint",
    authors: "Berntson, G. G., Cacioppo, J. T., & Quigley, K. S.",
    year: 1991,
    publication: "Psychological Review, 98(4), 459-487",
    publicationStatus: "published",
    studyType: "Kuramsal fizyoloji derlemesi",
    doi: "10.1037/0033-295X.98.4.459",
    pmid: "1660159",
    url: "https://doi.org/10.1037/0033-295X.98.4.459",
    evidenceDomain: "autonomic_space",
    ageScope: "mixed",
    claimBoundary: "Otonom dalların bağımsız ve eşzamanlı örüntülerini destekler; kişiye dal etiketi atanmasını desteklemez.",
    repairNote: "Sempatik-parasempatik paketi K03 için dergi, cilt, sayfa ve DOI düzeltildi.",
  }),
  source({
    id: "DAMPNEY_2016",
    title: "Central neural control of the cardiovascular system: Current perspectives",
    authors: "Dampney, R. A. L.",
    year: 2016,
    publication: "Advances in Physiology Education, 40(3), 283-296",
    publicationStatus: "published",
    studyType: "Anlatısal eğitim derlemesi",
    doi: "10.1152/advan.00027.2016",
    pmid: "27445275",
    url: "https://doi.org/10.1152/advan.00027.2016",
    evidenceDomain: "cardiovascular_autonomic_control",
    ageScope: "mixed",
    claimBoundary: "Kardiyovasküler merkezi kontrolü açıklar; tüm ANS veya davranışsal self-regülasyon için kapsamlı kanıt değildir.",
    repairNote: "Sempatik-parasempatik paketi K05 fabrikasyon birleşik kaydı amaçlanan eğitim derlemesiyle değiştirildi ve kanıt gücü düşürüldü.",
  }),
  source({
    id: "CRITCHLEY_HARRISON_2013",
    title: "Visceral influences on brain and behavior",
    authors: "Critchley, H. D., & Harrison, N. A.",
    year: 2013,
    publication: "Neuron, 77(4), 624-638",
    publicationStatus: "published",
    studyType: "Anlatısal nörofizyoloji derlemesi",
    doi: "10.1016/j.neuron.2013.02.008",
    pmid: "23439117",
    url: "https://doi.org/10.1016/j.neuron.2013.02.008",
    evidenceDomain: "visceral_brain_interactions",
    ageScope: "adult_weighted",
    claimBoundary: "Visseral-beyin etkileşimlerini destekler; tek davranıştan mekanizma veya bölge çıkarımı sağlamaz.",
  }),
  source({
    id: "FURNESS_2012",
    title: "The enteric nervous system and neurogastroenterology",
    authors: "Furness, J. B.",
    year: 2012,
    publication: "Nature Reviews Gastroenterology & Hepatology, 9(5), 286-294",
    publicationStatus: "published",
    studyType: "Anlatısal derleme",
    doi: "10.1038/nrgastro.2012.32",
    pmid: "22392290",
    url: "https://doi.org/10.1038/nrgastro.2012.32",
    evidenceDomain: "enteric_nervous_system",
    ageScope: "all_ages",
    claimBoundary: "Enterik sistemin yerel ve merkezi bağlantılarını açıklar; günlük belirtinin nedenini belirlemez.",
  }),
  source({
    id: "MCEWEN_1998",
    title: "Protective and damaging effects of stress mediators",
    authors: "McEwen, B. S.",
    year: 1998,
    publication: "New England Journal of Medicine, 338(3), 171-179",
    publicationStatus: "published",
    studyType: "Klasik anlatısal derleme",
    doi: "10.1056/NEJM199801153380307",
    pmid: "9428819",
    url: "https://doi.org/10.1056/NEJM199801153380307",
    evidenceDomain: "allostasis_stress",
    ageScope: "mixed",
    claimBoundary: "Allostatik yük kavramını destekler; tek davranış veya tek biyobelirteçle kişisel yük ölçümü sağlamaz.",
  }),
  source({
    id: "RAMSAY_WOODS_2014",
    title: "Clarifying the roles of homeostasis and allostasis in physiological regulation",
    authors: "Ramsay, D. S., & Woods, S. C.",
    year: 2014,
    publication: "Psychological Review, 121(2), 225-247",
    publicationStatus: "published",
    studyType: "Kuramsal derleme",
    doi: "10.1037/a0035942",
    pmid: "24730599",
    url: "https://doi.org/10.1037/a0035942",
    evidenceDomain: "homeostasis_allostasis",
    ageScope: "mixed",
    claimBoundary: "Kavramsal ayrımı destekler; klinik eşik, skor veya kişisel mekanizma sağlamaz.",
  }),
  source({
    id: "TASK_FORCE_HRV_1996",
    title: "Heart rate variability: Standards of measurement, physiological interpretation and clinical use",
    authors: "Task Force of the ESC and NASPE",
    year: 1996,
    publication: "Circulation, 93(5), 1043-1065",
    publicationStatus: "consensus",
    studyType: "Konsensüs standardı",
    doi: "10.1161/01.CIR.93.5.1043",
    pmid: "8598068",
    url: "https://doi.org/10.1161/01.CIR.93.5.1043",
    evidenceDomain: "hrv_measurement",
    ageScope: "mixed",
    claimBoundary: "HRV ölçüm ve yorum standardını destekler; DNA puanından HRV, vagal ton veya tanı çıkarımı sağlamaz.",
  }),
  source({
    id: "LABORDE_ET_AL_2017",
    title: "Heart rate variability and cardiac vagal tone in psychophysiological research",
    authors: "Laborde, S., Mosley, E., & Thayer, J. F.",
    year: 2017,
    publication: "Frontiers in Psychology, 8, 213",
    publicationStatus: "published",
    studyType: "Yöntemsel derleme ve öneriler",
    doi: "10.3389/fpsyg.2017.00213",
    pmid: "28265249",
    url: "https://doi.org/10.3389/fpsyg.2017.00213",
    evidenceDomain: "hrv_methodology",
    ageScope: "adult_weighted",
    claimBoundary: "Araştırma ölçümü ve raporlamasını destekler; klinik eşik veya bireysel sınıflama sağlamaz.",
  }),
  source({
    id: "BILLMAN_2013",
    title: "The LF/HF ratio does not accurately measure cardiac sympatho-vagal balance",
    authors: "Billman, G. E.",
    year: 2013,
    publication: "Frontiers in Physiology, 4, 26",
    publicationStatus: "published",
    studyType: "Eleştirel fizyoloji derlemesi",
    doi: "10.3389/fphys.2013.00026",
    pmid: "23431279",
    url: "https://doi.org/10.3389/fphys.2013.00026",
    evidenceDomain: "hrv_interpretation_boundary",
    ageScope: "mixed",
    claimBoundary: "LF/HF oranının küresel sempatovagal denge ölçütü olmadığını destekler; alternatif tek ANS skoru önermez.",
  }),
  source({
    id: "GRAZIANO_DEREFINKO_2013",
    title: "Cardiac vagal control and children's adaptive functioning: A meta-analysis",
    authors: "Graziano, P. A., & Derefinko, K. J.",
    year: 2013,
    publication: "Biological Psychology, 94(1), 22-37",
    publicationStatus: "published",
    studyType: "Meta-analiz",
    doi: "10.1016/j.biopsycho.2013.04.011",
    pmid: "23648264",
    url: "https://doi.org/10.1016/j.biopsycho.2013.04.011",
    evidenceDomain: "child_cardiac_vagal_adaptive_functioning",
    ageScope: "childhood",
    claimBoundary: "Grup düzeyi ilişkileri destekler; nedensellik, bireysel sınıflama veya davranıştan HRV çıkarımı sağlamaz.",
    existingLiteratureId: "GRAZIANO_DEREFINKO_2013",
    repairNote: "Sempatik-parasempatik K31 DOI .018 yerine doğrulanmış .011 ile mevcut literatür kaydına tekilleştirildi.",
  }),
  source({
    id: "BOUCSEIN_ET_AL_2012",
    title: "Publication recommendations for electrodermal measurements",
    authors: "Boucsein, W., Fowles, D. C., Grimnes, S., et al.",
    year: 2012,
    publication: "Psychophysiology, 49(8), 1017-1034",
    publicationStatus: "consensus",
    studyType: "Yöntem önerileri",
    doi: "10.1111/j.1469-8986.2012.01384.x",
    pmid: "22680988",
    url: "https://doi.org/10.1111/j.1469-8986.2012.01384.x",
    evidenceDomain: "electrodermal_activity",
    ageScope: "mixed",
    claimBoundary: "EDA kayıt ve raporlamasını destekler; sinyalden özgül duygu, tanı veya neden çıkarımı sağlamaz.",
  }),
  source({
    id: "MATHOT_2018",
    title: "Pupillometry: Psychology, physiology, and function",
    authors: "Mathot, S.",
    year: 2018,
    publication: "Journal of Cognition, 1(1), 16",
    publicationStatus: "published",
    studyType: "Yöntemsel anlatısal derleme",
    doi: "10.5334/joc.18",
    pmid: "31517190",
    url: "https://doi.org/10.5334/joc.18",
    evidenceDomain: "pupillometry",
    ageScope: "mixed",
    claimBoundary: "Pupil ölçümünün çoklu belirleyicilerini açıklar; tek beyin çekirdeği veya otonom durum çıkarımı sağlamaz.",
  }),
  source({
    id: "KHALSA_ET_AL_2018",
    title: "Interoception and mental health: A roadmap",
    authors: "Khalsa, S. S., Adolphs, R., Cameron, O. G., et al.",
    year: 2018,
    publication: "Biological Psychiatry: Cognitive Neuroscience and Neuroimaging, 3(6), 501-513",
    publicationStatus: "consensus",
    studyType: "Uzman konsensüsü ve alan yol haritası",
    doi: "10.1016/j.bpsc.2017.12.004",
    pmid: "29884281",
    url: "https://doi.org/10.1016/j.bpsc.2017.12.004",
    evidenceDomain: "interoception",
    ageScope: "adult_weighted",
    claimBoundary: "İnterosepsiyonun çok boyutlu doğasını destekler; DNA alanını veya pediatrik bireysel çıkarımı doğrulamaz.",
  }),
  source({
    id: "GARFINKEL_ET_AL_2015",
    title: "Knowing your own heart: Distinguishing interoceptive accuracy from interoceptive awareness",
    authors: "Garfinkel, S. N., Seth, A. K., Barrett, A. B., Suzuki, K., & Critchley, H. D.",
    year: 2015,
    publication: "Biological Psychology, 104, 65-74",
    publicationStatus: "published",
    studyType: "Deneysel kavramsal çalışma",
    doi: "10.1016/j.biopsycho.2014.11.004",
    pmid: "25451381",
    url: "https://doi.org/10.1016/j.biopsycho.2014.11.004",
    evidenceDomain: "interoception_dimensions",
    ageScope: "adult_weighted",
    claimBoundary: "Görev performansı, öz-bildirim ve metabiliş ayrımını destekler; çocuklara ve tüm organ sistemlerine otomatik genellenmez.",
  }),
  source({
    id: "PINNA_EDWARDS_2020",
    title: "A systematic review of associations between interoception, vagal tone, and emotional regulation",
    authors: "Pinna, T., & Edwards, D. J.",
    year: 2020,
    publication: "Frontiers in Psychology, 11, 1792",
    publicationStatus: "published",
    studyType: "Sistematik derleme",
    doi: "10.3389/fpsyg.2020.01792",
    pmid: "32849058",
    url: "https://doi.org/10.3389/fpsyg.2020.01792",
    evidenceDomain: "interoception_emotion_regulation",
    ageScope: "adult_weighted",
    claimBoundary: "İlişki adaylarını destekler; nedensellik, tanı veya kişiye özgü vagal mekanizma sağlamaz.",
    existingLiteratureId: "PINNA_EDWARDS_2020",
    repairNote: "Otonom paket S27 eksik bibliyografik kayıt tamamlandı.",
  }),
  source({
    id: "FRIEDMAN_ROBBINS_2022",
    title: "The role of prefrontal cortex in cognitive control and executive function",
    authors: "Friedman, N. P., & Robbins, T. W.",
    year: 2022,
    publication: "Neuropsychopharmacology, 47(1), 72-89",
    publicationStatus: "published",
    studyType: "Anlatısal derleme",
    doi: "10.1038/s41386-021-01132-0",
    pmid: "34408280",
    url: "https://doi.org/10.1038/s41386-021-01132-0",
    evidenceDomain: "prefrontal_executive_control",
    ageScope: "adult_weighted",
    claimBoundary: "Prefrontal katkıları dağıtık ağ çerçevesinde destekler; davranıştan bölgesel işlev bozukluğu çıkarımı sağlamaz.",
  }),
  source({
    id: "SEELEY_2019",
    title: "The salience network: A neural system for perceiving and responding to homeostatic demands",
    authors: "Seeley, W. W.",
    year: 2019,
    publication: "Journal of Neuroscience, 39(50), 9878-9882",
    publicationStatus: "published",
    studyType: "Kısa perspektif derlemesi",
    doi: "10.1523/JNEUROSCI.1138-17.2019",
    pmid: "31676604",
    url: "https://doi.org/10.1523/JNEUROSCI.1138-17.2019",
    evidenceDomain: "salience_network",
    ageScope: "adult_weighted",
    claimBoundary: "Salience ağının homeostatik taleplerdeki rolünü açıklar; ağ işlevinden bireysel belirti çıkarımı sağlamaz.",
  }),
  source({
    id: "MENON_UDDIN_2010",
    title: "Saliency, switching, attention and control: A network model of insula function",
    authors: "Menon, V., & Uddin, L. Q.",
    year: 2010,
    publication: "Brain Structure and Function, 214(5-6), 655-667",
    publicationStatus: "published",
    studyType: "Teorik ağ modeli ve derleme",
    doi: "10.1007/s00429-010-0262-0",
    pmid: "20512370",
    url: "https://doi.org/10.1007/s00429-010-0262-0",
    evidenceDomain: "insula_salience_network",
    ageScope: "adult_weighted",
    claimBoundary: "İnsulanın salience ağındaki çoklu rolünü destekler; insulayı tek bir işlev merkezi gibi göstermez.",
  }),
  source({
    id: "LAMOTTE_ET_AL_2021",
    title: "Stress and central autonomic network",
    authors: "Lamotte, G., Shouman, K., & Benarroch, E. E.",
    year: 2021,
    publication: "Autonomic Neuroscience, 235, 102870",
    publicationStatus: "published",
    studyType: "Anlatısal derleme",
    doi: "10.1016/j.autneu.2021.102870",
    pmid: "34461325",
    url: "https://doi.org/10.1016/j.autneu.2021.102870",
    evidenceDomain: "central_autonomic_network_stress",
    ageScope: "adult_weighted",
    claimBoundary: "Merkezi otonom ağın stres bağlamındaki rolünü destekler; davranıştan CAN işlevi ölçümü sağlamaz.",
  }),
  source({
    id: "FERRARO_ET_AL_2022",
    title: "The central autonomic system revisited: Convergent evidence for a regulatory role of the insular and midcingulate cortex",
    authors: "Ferraro, S., Klugah-Brown, B., Tench, C. R., et al.",
    year: 2022,
    publication: "Neuroscience & Biobehavioral Reviews, 142, 104915",
    publicationStatus: "published",
    studyType: "Nörogörüntüleme meta-analizleri sentezi",
    doi: "10.1016/j.neubiorev.2022.104915",
    pmid: "36244505",
    url: "https://doi.org/10.1016/j.neubiorev.2022.104915",
    evidenceDomain: "central_autonomic_network",
    ageScope: "adult_weighted",
    claimBoundary: "Grup düzeyi ağ katkılarını destekler; bireysel lokalizasyon veya DNA ölçümü sağlamaz.",
  }),
  source({
    id: "QUADT_ET_AL_2022",
    title: "Cognition, emotion, and the central autonomic network",
    authors: "Quadt, L., Critchley, H. D., & Garfinkel, S. N.",
    year: 2022,
    publication: "Autonomic Neuroscience, 238, 102948",
    publicationStatus: "published",
    studyType: "Anlatısal derleme",
    doi: "10.1016/j.autneu.2022.102948",
    pmid: "35149372",
    url: "https://doi.org/10.1016/j.autneu.2022.102948",
    evidenceDomain: "central_autonomic_cognition_emotion",
    ageScope: "adult_weighted",
    claimBoundary: "Biliş-duygu-otonom ilişkilerini ağ düzeyinde açıklar; tek yönlü neden veya bireysel mekanizma sağlamaz.",
  }),
  source({
    id: "GROSSMAN_2023",
    title: "Fundamental challenges and likely refutations of the five basic premises of the polyvagal theory",
    authors: "Grossman, P.",
    year: 2023,
    publication: "Biological Psychology, 180, 108589",
    publicationStatus: "published",
    studyType: "Eleştirel kuramsal derleme",
    doi: "10.1016/j.biopsycho.2023.108589",
    pmid: "37230290",
    url: "https://doi.org/10.1016/j.biopsycho.2023.108589",
    evidenceDomain: "polyvagal_critique",
    ageScope: "mixed",
    claimBoundary: "Polivagal öncüllere yönelik eleştirileri sunar; alanın tüm görüşlerini tek başına temsil etmez.",
  }),
  source({
    id: "PORGES_2021",
    title: "Polyvagal theory: A biobehavioral journey to sociality",
    authors: "Porges, S. W.",
    year: 2021,
    publication: "Comprehensive Psychoneuroendocrinology, 7, 100069",
    publicationStatus: "published",
    studyType: "Kuramsal savunucu derleme",
    doi: "10.1016/j.cpnec.2021.100069",
    pmid: "35757052",
    url: "https://doi.org/10.1016/j.cpnec.2021.100069",
    evidenceDomain: "polyvagal_theory",
    ageScope: "mixed",
    claimBoundary: "Teorinin kendi önermelerini açıklar; davranıştan vagal durum atamasını veya klinik tanıyı doğrulamaz.",
  }),
  source({
    id: "MCINTOSH_ET_AL_1999",
    title: "Sensory-modulation disruption, electrodermal responses, and functional behaviors",
    authors: "McIntosh, D. N., Miller, L. J., Shyu, V., & Hagerman, R. J.",
    year: 1999,
    publication: "Developmental Medicine & Child Neurology, 41(9), 608-615",
    publicationStatus: "published",
    studyType: "Küçük karşılaştırmalı deneysel çalışma",
    doi: "10.1111/j.1469-8749.1999.tb00664.x",
    pmid: "10503919",
    url: "https://doi.org/10.1111/j.1469-8749.1999.tb00664.x",
    evidenceDomain: "pediatric_sensory_eda",
    ageScope: "childhood",
    claimBoundary: "Seçilmiş küçük örneklemde EDA farklılıklarını bildirir; genellenebilirlik, özgüllük ve tanısal kullanım sağlamaz.",
    repairNote: "Sempatik-parasempatik K40 başlık, dergi, sayfa ve DOI doğrulandı; PubMed aynı makale için 10.1017/S0012162299001267 DOI eş adını gösterir.",
  }),
  source({
    id: "CHRISTENSEN_ET_AL_2020",
    title: "Diverse autonomic nervous system stress response patterns in childhood sensory modulation",
    authors: "Christensen, J. S., Wild, H., Kenzie, E. S., et al.",
    year: 2020,
    publication: "Frontiers in Integrative Neuroscience, 14, 6",
    publicationStatus: "published",
    studyType: "Çocukluk psikofizyoloji çalışması",
    doi: "10.3389/fnint.2020.00006",
    pmid: "32132906",
    url: "https://doi.org/10.3389/fnint.2020.00006",
    evidenceDomain: "child_sensory_autonomic_patterns",
    ageScope: "childhood",
    claimBoundary: "Heterojen grup örüntülerini destekler; otizme özgü sonuç, bireysel mekanizma veya tanı sağlamaz.",
    repairNote: "Otonom paket S25 yanlış mini-derleme kaydı yerine doğrulanmış özgün çalışma kullanıldı; otizm-spesifik iddia çıkarıldı.",
  }),
  source({
    id: "WHEDON_ET_AL_2018",
    title: "Cardiac vagal regulation in infancy predicts executive function and social competence in preschool",
    authors: "Whedon, M., Perry, N. B., Calkins, S. D., & Bell, M. A.",
    year: 2018,
    publication: "Developmental Psychobiology, 60(5), 547-560",
    publicationStatus: "published",
    studyType: "Boylamsal çalışma",
    doi: "10.1002/dev.21636",
    pmid: "29785749",
    url: "https://doi.org/10.1002/dev.21636",
    evidenceDomain: "infant_vagal_preschool_outcomes",
    ageScope: "early_childhood",
    claimBoundary: "Boylamsal grup ilişkisini destekler; nedensellik veya bireysel prognoz sağlamaz.",
    repairNote: "Otonom paket S18 eksik DOI tamamlandı.",
  }),
  source({
    id: "ALEN_ET_AL_2022",
    title: "The association between parenting and child autonomic nervous system activity: A systematic review and meta-analysis",
    authors: "Alen, N. V., et al.",
    year: 2022,
    publication: "Neuroscience & Biobehavioral Reviews, 139, 104734",
    publicationStatus: "published",
    studyType: "Sistematik derleme ve meta-analiz",
    doi: "10.1016/j.neubiorev.2022.104734",
    pmid: "35716874",
    url: "https://doi.org/10.1016/j.neubiorev.2022.104734",
    evidenceDomain: "parenting_child_autonomic_association",
    ageScope: "childhood",
    claimBoundary: "Ebeveynlik ve çocuk otonom etkinliği arasındaki grup ilişkilerini destekler; nedensellik veya biyolojik eş-regülasyon ölçümü değildir.",
    repairNote: "Otonom paket S21 eksik DOI tamamlandı.",
  }),
  source({
    id: "GASIOR_ET_AL_2018",
    title: "Normative values for heart rate variability parameters in school-aged children",
    authors: "Gąsior, J. S., et al.",
    year: 2018,
    publication: "Frontiers in Physiology, 9, 1495",
    publicationStatus: "published",
    studyType: "Normatif çalışma",
    doi: "10.3389/fphys.2018.01495",
    pmid: "30405445",
    url: "https://doi.org/10.3389/fphys.2018.01495",
    evidenceDomain: "child_hrv_norms",
    ageScope: "childhood",
    claimBoundary: "Belirli protokolde grup normlarını sunar; DNA puanı veya protokoller arası kişisel eşik sağlamaz.",
    repairNote: "Otonom paket S12 PMID 30337892 yerine 30405445 olarak düzeltildi.",
  }),
  source({
    id: "THAYER_LANE_2009",
    title: "Claude Bernard and the heart-brain connection: Further elaboration of a model of neurovisceral integration",
    authors: "Thayer, J. F., & Lane, R. D.",
    year: 2009,
    publication: "Neuroscience & Biobehavioral Reviews, 33(2), 81-88",
    publicationStatus: "published",
    studyType: "Kuramsal derleme",
    doi: "10.1016/j.neubiorev.2008.08.004",
    pmid: "18771686",
    url: "https://doi.org/10.1016/j.neubiorev.2008.08.004",
    evidenceDomain: "neurovisceral_integration",
    ageScope: "adult_weighted",
    claimBoundary: "Kuramsal beyin-kalp bütünleşme modelini açıklar; HRV'den bireysel beyin işlevi çıkarımı sağlamaz.",
    repairNote: "Otonom paket S09 PMID 19424767 yerine 18771686 olarak düzeltildi.",
  }),
])

export const DNA_CHAT_CATALOG_SOURCE_BY_ID = new Map(
  DNA_CHAT_CATALOG_SOURCES.map((entry) => [entry.id, entry]),
)
