import {
  DNA_CHAT_CATALOG_VERSION,
  type DnaChatCatalogTopic,
} from "./types"

function topic(
  input: Omit<DnaChatCatalogTopic, "version" | "reviewStatus">,
): DnaChatCatalogTopic {
  return Object.freeze({
    version: DNA_CHAT_CATALOG_VERSION,
    reviewStatus: "source_verified_expert_pending" as const,
    ...input,
  })
}

export const DNA_CHAT_CATALOG_TOPICS: readonly DnaChatCatalogTopic[] = Object.freeze([
  topic({
    id: "selfreg.core",
    category: "self_regulation",
    title: "Self-regülasyon",
    aliases: ["öz düzenleme", "öz-düzenleme", "self regulation", "self regulasyon"],
    summary: "Self-regülasyon; dikkat, duygu, davranış, bilişsel kontrol ve bedensel uyarılma süreçlerini bağlam içinde düzenleyen çok bileşenli bir süreç ailesidir.",
    details: [
      "Tek bir beceriye, beyin bölgesine veya puana indirgenemez.",
      "Performans talep, çevresel yapı, yorgunluk, motivasyon ve sosyal destekle değişebilir.",
    ],
    keywords: ["dikkat", "duygu", "davranış", "bağlam", "hedef", "regülasyon"],
    claimIds: ["claim.selfreg.multicomponent", "claim.selfreg.contextual"],
    sourceIds: ["NIGG_2017", "INZLICHT_ET_AL_2021", "BLAIR_RAVER_2015"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Self-regülasyon profili tanı, sabit kişilik özelliği veya tek biyolojik mekanizma değildir.",
  }),
  topic({
    id: "selfreg.self_control",
    category: "self_regulation",
    title: "Self-kontrol",
    aliases: ["öz kontrol", "öz-kontrol", "self control", "dürtü kontrolü"],
    summary: "Self-kontrol, kısa vadeli tepki veya dürtüyü daha uzun vadeli amaç doğrultusunda yönetmeye odaklanan, self-regülasyondan daha dar bir kavramdır.",
    details: ["Terimler literatürde kısmen örtüşebilir.", "Katalog self-regülasyonu üst şemsiye olarak kullanır."],
    keywords: ["dürtü", "hedef", "gecikmiş ödül", "kontrol"],
    claimIds: ["claim.selfcontrol.distinction"],
    sourceIds: ["NIGG_2017", "INZLICHT_ET_AL_2021"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Self-kontrol gözlemi tanı veya geleceğe ilişkin kesin tahmin sağlamaz.",
  }),
  topic({
    id: "selfreg.executive_functions",
    category: "self_regulation",
    title: "Yürütücü işlevler",
    aliases: [
      "executive functions",
      "ef",
      "yürütücü işlev",
      "yürütücü kontrol",
      "bilişsel kontrol",
      "bilişsel reg",
      "bilişsel regülasyon",
      "ketleyici kontrol",
      "inhibitör kontrol",
      "çalışma belleği",
      "bilişsel esneklik",
    ],
    summary: "Yürütücü işlevler ketleyici kontrol, çalışma belleği ve bilişsel esneklik gibi hedefe yönelik kontrol süreçlerini kapsar.",
    details: ["Bileşenler ilişkili fakat özdeş değildir.", "Self-regülasyonun tamamıyla eş anlamlı değildir."],
    keywords: ["ketleme", "çalışma belleği", "bilişsel esneklik", "planlama"],
    claimIds: ["claim.ef.components"],
    sourceIds: ["DIAMOND_2013", "NIGG_2017"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Sohbet yanıtı nöropsikolojik değerlendirme veya yürütücü işlev tanısı değildir.",
  }),
  topic({
    id: "selfreg.coregulation",
    category: "self_regulation",
    title: "Ko-regülasyon",
    aliases: ["eş-regülasyon", "eş düzenleme", "co-regulation", "coregulation"],
    summary: "Ko-regülasyon, düzenlemenin başka bir kişi ve çevresel yapı tarafından karşılıklı biçimde desteklenmesidir.",
    details: ["Erken çocuklukta bakımveren desteği özellikle görünürdür.", "Yaşam boyunca ilişki ve çevre düzenleyici bağlam sağlayabilir."],
    keywords: ["bakımveren", "ebeveyn", "sosyal destek", "ilişki", "çevresel yapı"],
    claimIds: ["claim.coregulation.support"],
    sourceIds: ["ROSANBALM_MURRAY_2017", "BLAIR_RAVER_2015"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Ko-regülasyon biyolojik senkroni ölçümü, tek yönlü neden veya tedavi protokolü değildir.",
  }),
  topic({
    id: "selfreg.reactivity_recovery",
    category: "self_regulation",
    title: "Reaktivite ve toparlanma",
    aliases: [
      "reaktivite",
      "duygusal reaktivite",
      "duygusal tepkisellik",
      "toparlanma",
      "recovery",
      "arousal recovery",
      "tepki yoğunluğu",
    ],
    summary: "Reaktivite ilk tepkinin hız ve yoğunluğunu, toparlanma ise zorlanma sonrasında daha dengeli işleyişe dönüşü betimler.",
    details: ["İki boyut ayrı değerlendirilir.", "Bağlam, süre, yoğunluk ve gereken dış destek önemlidir."],
    keywords: ["uyarılma", "tepki", "sakinleşme", "stres", "dengeye dönüş"],
    claimIds: ["claim.reactivity.recovery"],
    sourceIds: ["BLAIR_RAVER_2015"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Davranışsal reaktivite otonom dal etkinliği veya sabit mizaç ölçümü değildir.",
  }),
  topic({
    id: "selfreg.development",
    category: "self_regulation",
    title: "Self-regülasyonun gelişimi",
    aliases: [
      "öz düzenleme gelişimi",
      "self-regülasyon gelişimi",
      "self-regülasyon çocuklukta nasıl gelişir",
      "erken self-regülasyon geleceği",
      "çocuklarda regülasyon",
      "regülasyon kaç yaşında",
    ],
    summary: "Self-regülasyon gelişim boyunca değişir; erken çocuklukta dış destek ve görev yapısı özellikle önemlidir.",
    details: ["Grup düzeyi gelişim eğrileri bireysel prognoz değildir.", "Sonuç ilişkileri olasılıksal ve bağlama duyarlıdır."],
    keywords: ["erken çocukluk", "gelişim", "yaş", "olgunlaşma", "prognoz"],
    claimIds: ["claim.selfreg.development", "claim.selfreg.outcomes"],
    sourceIds: ["MONTROY_ET_AL_2016", "BLAIR_RAVER_2015", "ROBSON_ET_AL_2020"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Tek değerlendirmeden gelişim hızı, gelecek sonuç veya değişmez kapasite tahmini yapılamaz.",
  }),
  topic({
    id: "cns.overview",
    category: "central_nervous_system",
    title: "Merkezi sinir sistemi",
    aliases: ["mss", "cns", "central nervous system", "beyin ve omurilik"],
    summary: "Merkezi sinir sistemi beyin ve omurilikten oluşan, duyusal, motor, bilişsel ve düzenleyici süreçlerin geniş anatomik zeminidir.",
    details: ["Self-regülasyon için tek bir merkez yoktur.", "Merkezi ve periferik sistemler sürekli bilgi alışverişindedir."],
    keywords: ["beyin", "omurilik", "sinir sistemi", "merkezi"],
    claimIds: ["claim.cns.overview"],
    sourceIds: ["FRIEDMAN_ROBBINS_2022", "SAPER_2002"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "DNA merkezi sinir sistemi yapısını, hasarını veya bölgesel işlevini ölçmez.",
  }),
  topic({
    id: "cns.distributed_networks",
    category: "central_nervous_system",
    title: "Dağıtık beyin ağları",
    aliases: [
      "beyin ağları",
      "dağıtık ağ",
      "dağıtık beyin ağı",
      "network neuroscience",
      "tek merkez",
      "tek bir öz-düzenleme merkezi",
      "ağ düzeyi açıklama",
      "dağıtık açıklama",
    ],
    summary: "Düzenleme süreçleri tek bir bölgeden değil, dağıtık ve etkileşen beyin ağlarının katkısından doğar.",
    details: ["Aynı bölge birden fazla sürece katılabilir.", "Aynı süreç farklı ağların işbirliğini gerektirebilir."],
    keywords: ["ağ", "dağıtık", "bağlantı", "düğüm", "bölge"],
    claimIds: ["claim.cns.distributed"],
    sourceIds: ["FRIEDMAN_ROBBINS_2022", "QUADT_ET_AL_2022", "FERRARO_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "Grup nörobilimi bulguları bireysel beyin haritası veya lokalizasyon sağlamaz.",
  }),
  topic({
    id: "cns.insula",
    category: "central_nervous_system",
    title: "İnsular korteks",
    aliases: ["insula", "insluar korteks", "insular cortex", "insular korteks", "insular bölge"],
    summary: "İnsular korteks iç beden sinyalleri, duygulanım, önem belirleme ve ağlar arası geçişle ilişkili çok işlevli bir kortikal bölgedir.",
    details: ["Tek bir interosepsiyon merkezi değildir.", "Ön ve arka alt bölgeler ile bağlantılar farklı süreçlere katkı verir."],
    keywords: ["interosepsiyon", "salience", "beden sinyali", "duygu", "korteks"],
    claimIds: ["claim.insula.multifunction", "claim.insula.boundary"],
    sourceIds: ["MENON_UDDIN_2010", "FERRARO_ET_AL_2022", "CRITCHLEY_HARRISON_2013", "POLDRAK_2006"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "Davranış veya DNA profilinden insula işlevi, hasarı ya da zayıflığı çıkarılamaz.",
  }),
  topic({
    id: "cns.salience_network",
    category: "central_nervous_system",
    title: "Salience ağı",
    aliases: ["önem ağı", "salience network", "belirginlik ağı", "sn"],
    summary: "Salience ağı, iç ve dış olayların davranışsal önemini ağırlıklandırma ve diğer ağlar arasındaki geçişe katkı sağlar.",
    details: ["Ön insula ve singulat bölgeler önemli düğümlerdir.", "Ağ sabit bir alarm düğmesi değildir."],
    keywords: ["önem", "dikkat", "insula", "singulat", "ağ geçişi"],
    claimIds: ["claim.salience.network"],
    sourceIds: ["SEELEY_2019", "MENON_UDDIN_2010"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "DNA salience ağı aktivitesini veya 'beyin alarmı' durumunu ölçmez.",
  }),
  topic({
    id: "cns.central_autonomic_network",
    category: "central_nervous_system",
    title: "Merkezi otonom ağ",
    aliases: ["central autonomic network", "can", "merkezi otonom sistem", "otonom beyin ağı"],
    summary: "Merkezi otonom ağ, visseral bilgiyi bütünleştiren ve otonom çıktının bağlama göre düzenlenmesine katkı veren dağıtık merkezi devreleri anlatır.",
    details: ["İnsula, singulat, hipotalamus, amigdala ve beyin sapı düğümleri farklı tanımlarda yer alabilir.", "Ağ kavramı doğrudan klinik ölçüm değildir."],
    keywords: ["visseral", "otonom", "insula", "singulat", "hipotalamus", "beyin sapı"],
    claimIds: ["claim.can.network", "claim.can.boundary"],
    sourceIds: ["SAPER_2002", "LAMOTTE_ET_AL_2021", "FERRARO_ET_AL_2022", "POLDRAK_2006"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "DNA veya davranış gözlemi CAN etkinliğini, hasarını veya kapasitesini ölçmez.",
  }),
  topic({
    id: "cns.prefrontal_control",
    category: "central_nervous_system",
    title: "Prefrontal kontrol",
    aliases: ["prefrontal korteks", "pfc", "frontal lob", "prefrontal cortex"],
    summary: "Prefrontal bölgeler yürütücü kontrol ve hedefe yönelik davranışta önemli, fakat tek başına yeterli olmayan katkılar sağlar.",
    details: ["Kontrol dağıtık ağlara dayanır.", "Günlük davranış doğrudan frontal işlev ölçümü değildir."],
    keywords: ["yürütücü işlev", "kontrol", "planlama", "ketleme", "frontal"],
    claimIds: ["claim.pfc.control"],
    sourceIds: ["FRIEDMAN_ROBBINS_2022", "DIAMOND_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "DNA profilinden frontal lob problemi veya prefrontal disfonksiyon çıkarılamaz.",
  }),
  topic({
    id: "cns.reverse_inference",
    category: "central_nervous_system",
    title: "Tersine çıkarım",
    aliases: ["reverse inference", "bölgeden davranış çıkarma", "davranıştan beyin bölgesi", "lokalizasyon hatası"],
    summary: "Tersine çıkarım, davranış veya grup düzeyi beyin bulgusundan tek ve özgül bir bilişsel süreç ya da patoloji sonucu üretme hatasıdır.",
    details: ["Aynı bölge farklı işlevlere katılabilir.", "Aynı davranış farklı yollarla ortaya çıkabilir."],
    keywords: ["nörogörüntüleme", "çıkarım", "bölge", "patoloji", "lokalizasyon"],
    claimIds: ["claim.reverse_inference"],
    sourceIds: ["POLDRAK_2006"],
    evidenceLevel: "boundary",
    ageScope: "all_ages",
    claimBoundary: "Bu yöntem sınırı kültürel norm, eşsonluluk veya klinik tanı için doğrudan kanıt değildir.",
  }),
  topic({
    id: "ans.overview",
    category: "autonomic_nervous_system",
    title: "Otonom sinir sistemi",
    aliases: ["oss", "ans", "autonomic nervous system", "otonom sistem"],
    summary: "Otonom sinir sistemi, iç organ işlevlerinin koşullara göre ayarlanmasına katılan merkezi ve periferik düzenleme ağıdır.",
    details: ["Kalp, damar, terleme, pupil, sindirim ve başka süreçlere katılır.", "Örüntüler organ ve bağlama özgüdür."],
    keywords: ["kalp", "damar", "terleme", "pupil", "sindirim", "visseral"],
    claimIds: ["claim.ans.overview", "claim.ans.not_personality"],
    sourceIds: ["WEHRWEIN_ET_AL_2016", "SAPER_2002", "BERNTSON_ET_AL_1991"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "DNA otonom hastalık, dal baskınlığı veya kişisel biyolojik mekanizma ölçmez.",
  }),
  topic({
    id: "ans.homeostasis",
    category: "autonomic_nervous_system",
    title: "Homeostaz",
    aliases: ["homeostasis", "iç denge", "bedensel denge", "dengeyi koruma"],
    summary: "Homeostaz, iç değişkenlerin geri bildirim süreçleriyle işlevsel aralıklarda tutulmasını anlatan dinamik düzenlemedir.",
    details: ["Hareketsiz veya tek bir ideal nokta değildir.", "Sürekli düzeltici ayarlamalar içerebilir."],
    keywords: ["geri bildirim", "denge", "iç ortam", "fizyoloji"],
    claimIds: ["claim.homeostasis.definition"],
    sourceIds: ["RAMSAY_WOODS_2014"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "Homeostaz DNA tarafından doğrudan ölçülen bir skor veya klinik eşik değildir.",
  }),
  topic({
    id: "ans.allostasis",
    category: "autonomic_nervous_system",
    title: "Allostaz",
    aliases: [
      "allostasis",
      "allostatik düzenleme",
      "öngörücü düzenleme",
      "allostatik yük",
      "homeostaz ile allostaz",
      "homeostaz ve allostaz",
    ],
    summary: "Allostaz, fizyolojik düzenlemenin değişen ve beklenen taleplere göre ayarlanmasını vurgulayan kuramsal çerçevedir.",
    details: ["Homeostazla rakip değil, farklı vurgu taşıyan bir açıklamadır.", "Allostatik yük tek davranıştan çıkarılamaz."],
    keywords: ["stres", "öngörü", "uyum", "fizyolojik maliyet", "yük"],
    claimIds: ["claim.allostasis.definition"],
    sourceIds: ["RAMSAY_WOODS_2014", "MCEWEN_1998"],
    evidenceLevel: "theoretical",
    ageScope: "mixed",
    claimBoundary: "Allostaz ve allostatik yük DNA puanı, tanı veya kişisel mekanizma değildir.",
  }),
  topic({
    id: "ans.hrv",
    category: "autonomic_nervous_system",
    title: "Kalp hızı değişkenliği",
    aliases: [
      "hrv",
      "heart rate variability",
      "kalp atım değişkenliği",
      "rsa",
      "rmssd",
      "hf-hrv",
      "lf-hrv",
      "lf hf",
    ],
    summary: "HRV, ardışık kalp atımları arasındaki zaman aralıklarının değişkenliğidir; kardiyak zaman serisinden hesaplanır.",
    details: ["Bazı ölçütler kardiyak vagal modülasyonla ilişkilidir.", "ANS'nin tamamı, beyin veya self-regülasyon için özgül ve doğrudan ölçüm değildir."],
    keywords: ["kalp", "vagal", "rmssd", "hf", "lf", "atım aralığı"],
    claimIds: [
      "claim.hrv.definition",
      "claim.hrv.measurement_boundary",
      "claim.hrv.association",
      "claim.hrv.lfhf",
    ],
    sourceIds: ["TASK_FORCE_HRV_1996", "LABORDE_ET_AL_2017", "BILLMAN_2013", "GRAZIANO_DEREFINKO_2013"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "DNA skorundan HRV, vagal ton, LF/HF dengesi veya otonom bozukluk çıkarılamaz.",
  }),
  topic({
    id: "ans.eda",
    category: "autonomic_nervous_system",
    title: "Elektrodermal aktivite",
    aliases: ["eda", "electrodermal activity", "deri iletkenliği", "galvanik deri yanıtı", "scr", "scl"],
    summary: "EDA, ter bezlerinin sempatik sinirsel kontrolüyle ilişkili deri iletkenliği değişimlerinin ölçümüdür.",
    details: ["Uyarılma, dikkat, sıcaklık ve hareketten etkilenebilir.", "Belirli bir duygu veya tanıya özgül değildir."],
    keywords: ["terleme", "deri", "iletkenlik", "sempatik", "uyarılma"],
    claimIds: ["claim.eda.definition", "claim.eda.sensory"],
    sourceIds: ["BOUCSEIN_ET_AL_2012", "CHRISTENSEN_ET_AL_2020", "MCINTOSH_ET_AL_1999"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "DNA duyusal veya fizyolojik alan puanı EDA ölçümü değildir.",
  }),
  topic({
    id: "ans.interoception",
    category: "autonomic_nervous_system",
    title: "İnterosepsiyon",
    aliases: [
      "interoception",
      "beden sinyallerini fark etme",
      "iç beden algısı",
      "interoseptif doğruluk",
      "interoseptif duyarlılık",
      "interoseptif farkındalık",
    ],
    summary: "İnterosepsiyon, iç beden sinyallerinin algılanması, bütünleştirilmesi, yorumlanması ve düzenleyici kullanımını kapsayan çok boyutlu süreçlerdir.",
    details: ["Görev performansı, öz-bildirim ve metabiliş ayrılmalıdır.", "Çocukluk ölçümleri ve yetişkin bulguları otomatik eşitlenmez."],
    keywords: ["beden sinyali", "farkındalık", "doğruluk", "duyarlılık", "duygu"],
    claimIds: ["claim.interoception.multidimensional", "claim.interoception.emotion"],
    sourceIds: ["KHALSA_ET_AL_2018", "GARFINKEL_ET_AL_2015", "PINNA_EDWARDS_2020"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "DNA interosepsiyon alanı doğrudan ANS bozukluğu, insula işlevi veya tıbbi durum göstermez.",
  }),
  topic({
    id: "ans.development",
    category: "autonomic_nervous_system",
    title: "Otonom gelişim ve yaş",
    aliases: [
      "çocuklarda otonom sinir sistemi",
      "ans gelişimi",
      "hrv normları",
      "yaşa göre hrv",
      "çocuklarda hrv yaşa göre değişir",
      "otonom gelişim",
      "otonom olgunlaşma",
      "puberte",
      "yaş ilerledikçe",
      "yetişkin bulgularını çocuklara",
      "yetişkin hrv",
      "çocuklara aktar",
    ],
    summary: "Otonom göstergeler çocukluk boyunca yaş, büyüme, solunum, aktivite ve ölçüm protokolüyle değişebilir.",
    details: ["Pediatrik normlar protokole duyarlıdır.", "Grup değerleri bireysel klinik eşik değildir."],
    keywords: ["çocuk", "gelişim", "yaş", "norm", "pediatrik", "protokol"],
    claimIds: ["claim.ans.development"],
    sourceIds: ["GASIOR_ET_AL_2018", "WHEDON_ET_AL_2018"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Yaş normu DNA puanına çevrilemez ve bireysel prognoz sağlamaz.",
  }),
  topic({
    id: "ans.sympathetic_parasympathetic",
    category: "sympathetic_parasympathetic",
    title: "Sempatik ve parasempatik süreçler",
    aliases: [
      "sempatik parasempatik",
      "sempatik ve parasempatik sistem",
      "sempatik sistem",
      "sempatik sinir sistemi",
      "sempatik aktivite",
      "sempatik reaktivite",
      "sempatik baskın",
      "sempatik",
      "parasempatik sistem",
      "parasempatik sinir sistemi",
      "parasempatik",
      "sympathetic parasympathetic",
      "savaş kaç",
      "dinlen sindir",
      "otonom dallar",
    ],
    summary: "Sempatik ve parasempatik süreçler günlük uyum için birlikte çalışan, organ ve bağlama göre farklılaşan otonom bileşenlerdir.",
    details: ["Biri evrensel olarak kötü, diğeri iyi değildir.", "Klasik sloganlar fizyolojinin yalnız kaba bir özetidir."],
    keywords: ["sempatik", "parasempatik", "enerji", "toparlanma", "organ"],
    claimIds: ["claim.sympathetic.parasympathetic"],
    sourceIds: ["WEHRWEIN_ET_AL_2016", "BERNTSON_ET_AL_1991"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "Davranıştan sempatik baskınlık, parasempatik yetersizlik veya kişisel dal durumu çıkarılamaz.",
  }),
  topic({
    id: "ans.autonomic_space",
    category: "sympathetic_parasympathetic",
    title: "Otonom uzam",
    aliases: [
      "autonomic space",
      "otonom tahterevalli",
      "eşzamanlı aktivasyon",
      "aynı anda etkinleşme",
      "aynı anda etkinleşebilir",
      "eşzamanlı etkinleşme",
      "sempatovagal denge",
      "sempatik ve parasempatik aynı anda etkin",
    ],
    summary: "Otonom uzam, sempatik ve parasempatik süreçlerin yalnız karşıt değil; eşzamanlı veya bağımsız örüntüler de gösterebildiğini anlatır.",
    details: ["Örüntü organa ve göreve göre değişir.", "Tek küresel denge skoru fizyolojiyi yeterince temsil etmez."],
    keywords: ["bağımsızlık", "eşzamanlı", "karşılıklı", "denge", "otonom dallar"],
    claimIds: ["claim.autonomic.space"],
    sourceIds: ["BERNTSON_ET_AL_1991", "DAMPNEY_2016"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Çerçeve kişiye özgü organ örüntüsünü davranıştan belirlemez.",
  }),
  topic({
    id: "ans.measurement_limits",
    category: "sympathetic_parasympathetic",
    title: "Otonom ölçüm sınırları",
    aliases: [
      "otonom test",
      "ans ölçümü",
      "ans hangi yöntemlerle ölçülür",
      "tek bir giyilebilir sensör bütün ans",
      "vagus ölçümü",
      "otonom biyobelirteç",
      "wearable",
      "akıllı saat sinir sistemi",
      "pep",
      "ecg",
      "ppg",
      "pupillometri",
      "barorefleks",
    ],
    summary: "HRV, EDA, pupil ve diğer ölçümler otonom işlevin farklı parçalarına ilişkin bilgi verir; hiçbiri tek başına bütün ANS'yi ölçmez.",
    details: ["Her sinyal farklı fizyolojik belirleyicilere sahiptir.", "Kayıt protokolü ve artefakt kontrolü zorunludur."],
    keywords: ["hrv", "eda", "pupil", "ölçüm", "sensör", "protokol"],
    claimIds: ["claim.ans.measurement"],
    sourceIds: ["TASK_FORCE_HRV_1996", "BOUCSEIN_ET_AL_2012", "MATHOT_2018"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Davranış, öz-bildirim veya DNA skoru fizyolojik otonom test yerine geçmez.",
  }),
  topic({
    id: "ans.polyvagal",
    category: "sympathetic_parasympathetic",
    title: "Polivagal teori",
    aliases: ["polyvagal", "polivagal", "dorsal vagal", "ventral vagal", "vagal shutdown"],
    summary: "Polivagal teori etkili bir kuramsal çerçevedir; bazı anatomik ve fizyolojik öncülleri bilimsel tartışma konusudur.",
    details: ["Savunucu ve eleştirel kaynaklarla birlikte sunulmalıdır.", "Yerleşik ve tartışmasız fizyoloji gibi anlatılmamalıdır."],
    keywords: ["vagus", "dorsal", "ventral", "güvenlik", "sosyal bağlılık"],
    claimIds: ["claim.polyvagal.status", "claim.polyvagal.boundary"],
    sourceIds: ["PORGES_2021", "GROSSMAN_2023", "LABORDE_ET_AL_2017"],
    evidenceLevel: "theoretical",
    ageScope: "mixed",
    claimBoundary: "Davranıştan dorsal/ventral vagal durum veya kişisel vagal ton atanamaz.",
  }),
])

export const DNA_CHAT_CATALOG_TOPIC_BY_ID = new Map(
  DNA_CHAT_CATALOG_TOPICS.map((entry) => [entry.id, entry]),
)
