import {
  DNA_CHAT_CATALOG_VERSION,
  type DnaChatCatalogTopic,
} from "./types"
import { V5_CASE_BOUNDARY_TOPICS } from "./v5CaseBoundariesCatalog"
import { V5_COREGULATION_TOPICS } from "./v5CoregulationCatalog"
import { V5_DEVELOPMENT_TOPICS } from "./v5DevelopmentCatalog"
import { V5_SIX_DOMAINS_TOPICS } from "./v5SixDomainsCatalog"

function topic(
  input: Omit<DnaChatCatalogTopic, "version" | "reviewStatus">,
): DnaChatCatalogTopic {
  return Object.freeze({
    version: DNA_CHAT_CATALOG_VERSION,
    reviewStatus: "source_verified_expert_pending" as const,
    ...input,
  })
}

export const DNA_CHAT_CATALOG_TOPICS: readonly DnaChatCatalogTopic[] = Object.freeze([
  topic({
    id: "selfreg.core",
    category: "self_regulation",
    title: "Self-regülasyon",
    aliases: ["öz düzenleme", "öz-düzenleme", "self regulation", "self regulasyon"],
    summary: "Self-regülasyon; dikkat, duygu, davranış, bilişsel kontrol ve bedensel uyarılma süreçlerini bağlam içinde düzenleyen çok bileşenli bir süreç ailesidir.",
    details: [
      "Tek bir beceriye, beyin bölgesine veya puana indirgenemez.",
      "Performans talep, çevresel yapı, yorgunluk, motivasyon ve sosyal destekle değişebilir.",
    ],
    keywords: ["dikkat", "duygu", "davranış", "bağlam", "hedef", "regülasyon"],
    claimIds: [
      "claim.selfreg.multicomponent",
      "claim.selfreg.contextual",
      "claim.selfreg.not_fixed_trait",
    ],
    sourceIds: ["NIGG_2017", "INZLICHT_ET_AL_2021", "BLAIR_RAVER_2015"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Self-regülasyon profili tanı, sabit kişilik özelliği veya tek biyolojik mekanizma değildir.",
  }),
  topic({
    id: "selfreg.self_control",
    category: "self_regulation",
    title: "Self-kontrol",
    aliases: ["öz kontrol", "öz-kontrol", "self control", "dürtü kontrolü"],
    summary: "Self-kontrol, kısa vadeli tepki veya dürtüyü daha uzun vadeli amaç doğrultusunda yönetmeye odaklanan, self-regülasyondan daha dar bir kavramdır.",
    details: ["Terimler literatürde kısmen örtüşebilir.", "Katalog self-regülasyonu üst şemsiye olarak kullanır."],
    keywords: ["dürtü", "hedef", "gecikmiş ödül", "kontrol"],
    claimIds: ["claim.selfcontrol.distinction"],
    sourceIds: ["NIGG_2017", "INZLICHT_ET_AL_2021"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Self-kontrol gözlemi tanı veya geleceğe ilişkin kesin tahmin sağlamaz.",
  }),
  topic({
    id: "selfreg.executive_functions",
    category: "self_regulation",
    title: "Yürütücü işlevler",
    aliases: [
      "executive functions",
      "ef",
      "yürütücü işlev",
      "yürütücü kontrol",
      "bilişsel kontrol",
      "bilişsel reg",
      "bilişsel regülasyon",
    ],
    summary: "Yürütücü işlevler ketleyici kontrol, çalışma belleği ve bilişsel esneklik gibi hedefe yönelik kontrol süreçlerini kapsar.",
    details: ["Bileşenler ilişkili fakat özdeş değildir.", "Self-regülasyonun tamamıyla eş anlamlı değildir."],
    keywords: ["ketleme", "çalışma belleği", "bilişsel esneklik", "planlama"],
    claimIds: ["claim.ef.components", "claim.ef.development"],
    sourceIds: ["DIAMOND_2013", "NIGG_2017"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Sohbet yanıtı nöropsikolojik değerlendirme veya yürütücü işlev tanısı değildir.",
  }),
  topic({
    id: "selfreg.coregulation",
    category: "self_regulation",
    title: "Ko-regülasyon",
    aliases: ["eş-regülasyon", "eş düzenleme", "co-regulation", "coregulation"],
    summary: "Ko-regülasyon, düzenlemenin başka bir kişi ve çevresel yapı tarafından karşılıklı biçimde desteklenmesidir.",
    details: ["Erken çocuklukta bakımveren desteği özellikle görünürdür.", "Yaşam boyunca ilişki ve çevre düzenleyici bağlam sağlayabilir."],
    keywords: ["bakımveren", "ebeveyn", "sosyal destek", "ilişki", "çevresel yapı"],
    claimIds: ["claim.coregulation.support"],
    sourceIds: ["ROSANBALM_MURRAY_2017", "BLAIR_RAVER_2015"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Ko-regülasyon biyolojik senkroni ölçümü, tek yönlü neden veya tedavi protokolü değildir.",
  }),
  topic({
    id: "selfreg.reactivity_recovery",
    category: "self_regulation",
    title: "Reaktivite ve toparlanma",
    aliases: [
      "reaktivite",
      "duygusal reaktivite",
      "duygusal tepkisellik",
      "toparlanma",
      "recovery",
      "arousal recovery",
      "tepki yoğunluğu",
      "tepki gecikmesi",
      "toparlanma süresi",
      "duygusal tepkisellik ile düzenleme farkı",
    ],
    summary: "Reaktivite bir olayla ortaya çıkan değişimi; toparlanma ise değişimin zaman içindeki dönüş örüntüsünü betimler. Taban düzeyi, büyüklük, gecikme ve süre ayrı bileşenlerdir.",
    details: [
      "Reaktivite ile düzenleme aynı yapı değildir; güçlü ilk tepki tek başına düzenleme güçlüğü göstermez.",
      "Davranış, öz-bildirim ve fizyolojik göstergeler farklı ölçüm katmanlarıdır ve aynı yönde değişmeyebilir.",
      "Toparlanma bağlama, başlangıç düzeyine, talebin sürmesine ve sağlanan desteğe göre değişebilir.",
    ],
    keywords: ["uyarılma", "tepki", "taban düzeyi", "gecikme", "süre", "stres", "dengeye dönüş"],
    claimIds: [
      "claim.reactivity.components",
      "claim.reactivity.measurement_layers",
      "claim.reactivity.recovery_distinction",
      "claim.recovery.trajectory",
    ],
    sourceIds: ["BURT_OBRADOVIC_2013", "BATES_ET_AL_2022", "SACREY_ET_AL_2021", "COLE_ET_AL_2004"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Davranışsal reaktivite veya görünür sakinleşme otonom dal, HPA ekseni, vagal ton, beyin bölgesi ya da sabit mizaç ölçümü değildir.",
  }),
  topic({
    id: "selfreg.arousal",
    category: "self_regulation",
    title: "Uyarılma",
    aliases: [
      "uyarılma",
      "uyarılmışlık",
      "arousal",
      "fizyolojik uyarılma",
      "tonik uyarılma",
      "fazik uyarılma",
      "optimal uyarılma",
      "uyanıklık düzeyi",
    ],
    summary: "Uyarılma; uyanıklık, dikkat hazırlığı, motor etkinlik ve fizyolojik değişimler gibi birden çok bileşeni olan, zamana ve bağlama göre değişen bir durum ailesidir.",
    details: [
      "Tek bir düşük-yüksek ekseni bütün uyarılma bileşenlerini temsil etmez.",
      "Göreve uygun uyarılma düzeyi kişi, görev ve çevresel talebe göre değişir; evrensel bir ideal düzey yoktur.",
      "Hareketlilik, sessizlik veya tek bir gözlem biyolojik uyarılmayı doğrudan ölçmez.",
    ],
    keywords: ["uyanıklık", "hazırlık", "aktivasyon", "tonik", "fazik", "performans", "bağlam"],
    claimIds: ["claim.arousal.multicomponent", "claim.arousal.contextual"],
    sourceIds: ["ASTON_JONES_COHEN_2005", "BATES_ET_AL_2022", "BURT_OBRADOVIC_2013"],
    evidenceLevel: "moderate",
    ageScope: "mixed",
    claimBoundary: "Davranıştan uyarılma sistemi, norepinefrin, ANS dalı veya kişiye özgü optimal düzey çıkarılamaz.",
  }),
  topic({
    id: "selfreg.recovery_measurement",
    category: "self_regulation",
    title: "Toparlanmanın değerlendirilmesi",
    aliases: [
      "toparlanma nasıl ölçülür",
      "toparlanma süresi",
      "normal toparlanma süresi",
      "toparlanma biyobelirteci",
      "recovery measurement",
      "baseline dönüş",
      "bazale dönüş",
    ],
    summary: "Toparlanma başlangıç düzeyi, tepkinin zirvesi, dönüş eğimi, süre ve yeni denge noktası gibi zaman bileşenleriyle; seçilen davranışsal veya fizyolojik göstergeye özgü değerlendirilir.",
    details: [
      "Her durum ve yaş için geçerli tek bir normal toparlanma süresi yoktur.",
      "HRV, kalp hızı, EDA, kortizol, gözlem ve öz-bildirim aynı sistemi veya aynı zaman ölçeğini ölçmez.",
    ],
    keywords: ["süre", "eğim", "bazal", "zaman serisi", "biyobelirteç", "çoklu yöntem"],
    claimIds: ["claim.recovery.no_universal_duration", "claim.recovery.no_single_biomarker", "claim.recovery.system_divergence"],
    sourceIds: ["BURT_OBRADOVIC_2013", "JONES_MASON_ET_AL_2018", "SACREY_ET_AL_2021", "FISHER_ET_AL_2018"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Gözlenen sakinleşme fizyolojik toparlanma kanıtı değildir; tek ölçüm DNA alanı, klinik eşik veya kişisel mekanizma sağlamaz.",
  }),
  topic({
    id: "selfreg.self_organization",
    category: "self_regulation",
    title: "Öz-örgütlenme",
    aliases: [
      "öz örgütlenme",
      "öz-örgütlenme",
      "self organization",
      "dinamik sistem",
      "dynamic systems",
      "çekici durum",
      "attractor state",
    ],
    summary: "Öz-örgütlenme, davranış veya gelişim örüntülerinin tek bir merkezi yönetici olmadan çok sayıda bileşenin zaman içindeki etkileşiminden ortaya çıkmasını anlatan dinamik sistem kavramıdır.",
    details: [
      "Bu bir klinik tanı, kişilik özelliği veya doğrudan ölçülen tek beyin süreci değildir.",
      "Toparlanma belirli bir değişimden sonraki zaman seyridir; öz-örgütlenme ise örüntünün çok bileşenli ortaya çıkışını açıklayan daha geniş kuramsal çerçevedir.",
    ],
    keywords: ["dinamik sistem", "ortaya çıkış", "çok bileşenli", "bağlam", "zaman ölçeği", "çekici"],
    claimIds: ["claim.selforganization.definition", "claim.selforganization.boundary"],
    sourceIds: ["SMITH_THELEN_2003", "COLE_ET_AL_2020"],
    evidenceLevel: "theoretical",
    ageScope: "developmental",
    claimBoundary: "Öz-örgütlenme etiketi tek vakada mekanizma, bozukluk, beyin durumu veya tedavi hedefi belirlemez.",
  }),
  topic({
    id: "selfreg.habituation",
    category: "self_regulation",
    title: "Habituasyon",
    aliases: [
      "habituasyon",
      "uyarana alışma",
      "habituation",
      "duyusal adaptasyon",
    ],
    summary: "Habituasyon, yinelenen bir uyarana verilen davranışsal tepkinin belirli ölçütlerle azalmasını anlatan temel bir öğrenme biçimidir.",
    details: [
      "Yorgunluk, reseptör düzeyindeki duyusal adaptasyon veya motor yetersizlikle aynı değildir.",
      "Bir tepkinin azalması sorunun bittiğini, bütün sistemlerin toparlandığını veya çocuğun her bağlamda alıştığını göstermez.",
    ],
    keywords: ["alışma", "tekrar", "tepki azalması", "öğrenme", "duyusal adaptasyon"],
    claimIds: ["claim.habituation.definition", "claim.habituation.distinction"],
    sourceIds: ["RANKIN_ET_AL_2009"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "Habituasyon gözlemi tanı, genel duyusal kapasite veya fizyolojik toparlanma ölçümü değildir.",
  }),
  topic({
    id: "selfreg.sensory_modulation",
    category: "self_regulation",
    title: "Duyusal modülasyon",
    aliases: [
      "duyusal modülasyon",
      "sensory modulation",
      "duyusal reaktivite",
      "duyusal yanıtlılık",
      "duyusal aşırı yanıtlılık",
      "duyusal düşük yanıtlılık",
      "düşük yanıtlılık",
      "duyusal arayış",
      "sor sur sensory seeking",
      "düşük kayıt",
      "duyusal eşik",
      "duyusal hassasiyet",
      "duyusal kaçınma",
      "dunn modeli",
    ],
    summary: "Duyusal modülasyon, duyusal girdiye verilen davranışsal yanıtın yoğunluk, süre ve bağlam açısından günlük işleve uyarlanmasını betimleyen işlevsel bir şemsiye kavramdır.",
    details: [
      "Aşırı yanıtlılık, düşük yanıtlılık ve arayış betimleyici örüntülerdir; tek başına tanı değildir.",
      "Dunn çerçevesindeki düşük kayıt, arayış, hassasiyet ve kaçınma kadranları kuramsal eşik ve yanıt stratejisini birleştirir.",
      "Anketten çıkan 'eşik' biyolojik veya psikofizik eşiğin doğrudan ölçümü değildir.",
    ],
    keywords: ["aşırı yanıt", "düşük yanıt", "arayış", "hassasiyet", "kaçınma", "dunn", "eşik"],
    claimIds: ["claim.sensory.definition", "claim.sensory.patterns", "claim.sensory.dunn_boundary"],
    sourceIds: ["DUNN_2001", "WATKYNS_ET_AL_2024"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Duyusal davranış tanı, ANS durumu, beyin bölgesi, vestibüler işlev veya gerçek nörolojik eşik göstermez.",
  }),
  topic({
    id: "selfreg.sensory_measurement",
    category: "self_regulation",
    title: "Duyusal modülasyonun değerlendirilmesi",
    aliases: [
      "duyusal modülasyon nasıl ölçülür",
      "duyusal reaktivite ölçümü",
      "duyusal reaktivite araçları",
      "sensory profile",
      "duyusal profil",
      "bakımveren anketi",
      "duyusal performans testi",
      "duyusal gözlem",
      "duyusal ölçüm",
      "duyusal eşik",
      "duyusal eşik ölçümü",
    ],
    summary: "Duyusal yanıt örüntüleri bakımveren veya öz-bildirim, yapılandırılmış gözlem ve performans temelli yöntemlerle farklı katmanlarda değerlendirilebilir.",
    details: [
      "Araçlar aynı yapıyı aynı biçimde ölçmez ve psikometrik destekleri yaş ile örnekleme göre değişir.",
      "Çok yöntemli değerlendirme kaynaklar arasındaki uyumu ve farkı görünür kılar; daha fazla test otomatik olarak daha doğru sonuç değildir.",
      "Davranışsal ve otonom ölçümler arasındaki çocukluk kanıtı heterojen ve sonuçsuzdur.",
    ],
    keywords: ["anket", "gözlem", "performans", "psikometri", "çoklu yöntem", "bağlam"],
    claimIds: ["claim.sensory.multimethod", "claim.sensory.physiology_boundary"],
    sourceIds: ["WATKYNS_ET_AL_2024", "GOMEZ_ET_AL_2017"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Tek puan veya gözlem tanı, fizyolojik mekanizma, biyolojik eşik ya da tüm ortamlardaki kapasiteyi belirlemez.",
  }),
  topic({
    id: "selfreg.emotion_regulation",
    category: "self_regulation",
    title: "Duygu düzenleme",
    aliases: [
      "duygu düzenleme",
      "duygusal düzenleme",
      "duygusal regülasyon",
      "emotion regulation",
      "duygu regülasyonu",
      "duygusal reaktivite ile düzenleme",
      "duygusal tepki",
      "duygusal tepki örüntüsü",
    ],
    summary: "Duygu düzenleme, duygunun ortaya çıkışı, yoğunluğu, süresi, ifadesi veya hedefle ilişkili kullanımını bağlama göre etkileyen çok aşamalı süreçlerdir.",
    details: [
      "Amaç her zaman duyguyu azaltmak veya sakin görünmek değildir; işlevsel yanıt hedef ve bağlama bağlıdır.",
      "Duygusal reaktivite ilk tepkinin özelliklerini, düzenleme ise tepkinin zaman içinde ve hedef doğrultusunda nasıl değiştirildiğini anlatır.",
      "Duygu düzenleme tek bir beyin merkezi, ANS durumu veya sabit kişilik özelliği değildir.",
    ],
    keywords: ["duygu", "reaktivite", "yoğunluk", "süre", "ifade", "hedef", "bağlam"],
    claimIds: ["claim.emotion.definition", "claim.emotion.reactivity_distinction", "claim.emotion.not_calmness"],
    sourceIds: ["COLE_ET_AL_2004", "GROSS_2015", "REITSEMA_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Gözlenen duygu veya DNA puanı düzenleyici niyet, tanı, kişisel mekanizma ya da belirli beyin/otonom durumu göstermez.",
  }),
  topic({
    id: "selfreg.emotion_strategies",
    category: "self_regulation",
    title: "Duygu düzenleme stratejileri ve esneklik",
    aliases: [
      "duygu düzenleme stratejileri",
      "yeniden değerlendirme",
      "bastırma",
      "kabul",
      "dikkat dağıtma",
      "regulatory flexibility",
      "düzenleme esnekliği",
      "en iyi duygu düzenleme stratejisi",
    ],
    summary: "Duygu düzenleme stratejisinin işlevi hedefe, gelişim düzeyine, zamanlamaya ve bağlama göre değişir; evrensel olarak her durumda iyi veya kötü tek strateji yoktur.",
    details: [
      "Esneklik, bağlamı fark etme, uygun repertuardan seçim yapma ve işe yaramadığında yanıtı güncelleyebilme kapasitesini vurgular.",
      "Yetişkin ağırlıklı strateji bulguları çocuklara doğrudan reçete gibi aktarılamaz.",
    ],
    keywords: ["strateji", "esneklik", "yeniden değerlendirme", "bastırma", "kabul", "bağlam"],
    claimIds: ["claim.emotion.strategy_context", "claim.emotion.flexibility_boundary"],
    sourceIds: ["GROSS_2015", "BONANNO_BURTON_2013"],
    evidenceLevel: "moderate",
    ageScope: "adult_weighted",
    claimBoundary: "Katalog kişiye özel strateji, müdahale, seans veya tedavi önerisi üretmez.",
  }),
  topic({
    id: "selfreg.emotion_measurement",
    category: "self_regulation",
    title: "Duygu düzenlemenin değerlendirilmesi",
    aliases: [
      "duygu düzenleme nasıl ölçülür",
      "duygusal reaktivite ölçeği",
      "duygu düzenleme anketi",
      "duygusal düzenleme ölçekleri",
      "duygu düzenleme ölçekleri",
      "emotion regulation measurement",
      "duygu günlüğü",
      "duygu dinamik",
      "ekolojik anlık değerlendirme",
      "ema",
    ],
    summary: "Duygu düzenleme anket, gözlem, deneysel görev ve günlük yaşamda tekrarlı ölçüm gibi yöntemlerle farklı bileşenler üzerinden incelenir; evrensel tek bir altın standart yoktur.",
    details: [
      "Ölçek puanları bildirilen davranış örüntülerini özetler; düzenleyici niyet veya biyolojik mekanizmayı doğrudan ölçmez.",
      "Yoğunluk, değişkenlik ve atalet gibi duygu dinamiği ölçütleri aynı değildir ve örnekleme planına duyarlıdır.",
    ],
    keywords: ["ölçek", "anket", "gözlem", "görev", "ema", "duygu dinamik", "yoğunluk", "değişkenlik", "atalet"],
    claimIds: ["claim.emotion.multimethod", "claim.emotion.measurement_boundary"],
    sourceIds: ["MAZEFSKY_ET_AL_2021", "REITSEMA_ET_AL_2022", "COLE_ET_AL_2004"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Tek puan tanı, beyin bölgesi, HRV, kortizol, vagal ton veya bütün düzenleme repertuarı değildir.",
  }),
  topic({
    id: "selfreg.development",
    category: "self_regulation",
    title: "Self-regülasyonun gelişimi",
    aliases: [
      "öz düzenleme gelişimi",
      "self-regülasyon gelişimi",
      "self-regülasyon çocuklukta nasıl gelişir",
      "self-regülasyon erken çocuklukta nasıl gelişir",
      "erken self-regülasyon geleceği",
      "çocuklarda regülasyon",
      "regülasyon kaç yaşında",
    ],
    summary: "Self-regülasyon gelişim boyunca değişir; erken çocuklukta dış destek ve görev yapısı özellikle önemlidir.",
    details: ["Grup düzeyi gelişim eğrileri bireysel prognoz değildir.", "Sonuç ilişkileri olasılıksal ve bağlama duyarlıdır."],
    keywords: ["erken çocukluk", "gelişim", "yaş", "olgunlaşma", "prognoz"],
    claimIds: ["claim.selfreg.development", "claim.selfreg.outcomes"],
    sourceIds: ["MONTROY_ET_AL_2016", "BLAIR_RAVER_2015", "ROBSON_ET_AL_2020"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Tek değerlendirmeden gelişim hızı, gelecek sonuç veya değişmez kapasite tahmini yapılamaz.",
  }),
  topic({
    id: "cns.overview",
    category: "central_nervous_system",
    title: "Merkezi sinir sistemi",
    aliases: ["mss", "cns", "central nervous system", "beyin ve omurilik"],
    summary: "Merkezi sinir sistemi beyin ve omurilikten oluşan, duyusal, motor, bilişsel ve düzenleyici süreçlerin geniş anatomik zeminidir.",
    details: ["Self-regülasyon için tek bir merkez yoktur.", "Merkezi ve periferik sistemler sürekli bilgi alışverişindedir."],
    keywords: ["beyin", "omurilik", "sinir sistemi", "merkezi"],
    claimIds: ["claim.cns.overview"],
    sourceIds: ["FRIEDMAN_ROBBINS_2022", "SAPER_2002"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "DNA merkezi sinir sistemi yapısını, hasarını veya bölgesel işlevini ölçmez.",
  }),
  topic({
    id: "cns.distributed_networks",
    category: "central_nervous_system",
    title: "Dağıtık beyin ağları",
    aliases: [
      "beyin ağları",
      "dağıtık ağ",
      "dağıtık beyin ağı",
      "network neuroscience",
      "tek merkez",
      "tek bir öz-düzenleme merkezi",
      "ağ düzeyi açıklama",
      "dağıtık açıklama",
    ],
    summary: "Düzenleme süreçleri tek bir bölgeden değil, dağıtık ve etkileşen beyin ağlarının katkısından doğar.",
    details: ["Aynı bölge birden fazla sürece katılabilir.", "Aynı süreç farklı ağların işbirliğini gerektirebilir."],
    keywords: ["ağ", "dağıtık", "bağlantı", "düğüm", "bölge"],
    claimIds: ["claim.cns.distributed", "claim.cns.not_single_center"],
    sourceIds: ["FRIEDMAN_ROBBINS_2022", "QUADT_ET_AL_2022", "FERRARO_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "Grup nörobilimi bulguları bireysel beyin haritası veya lokalizasyon sağlamaz.",
  }),
  topic({
    id: "cns.insula",
    category: "central_nervous_system",
    title: "İnsular korteks",
    aliases: [
      "insula",
      "insluar korteks",
      "insular cortex",
      "insular korteks",
      "insular bölge",
      "insula nedir",
    ],
    summary: "İnsular korteks iç beden sinyalleri, duygulanım, önem belirleme, duyusal bütünleştirme ve ağlar arası geçişle ilişkili çok işlevli bir kortikal bölgedir.",
    details: [
      "Tek bir interosepsiyon, duygu, tat veya ağrı merkezi değildir.",
      "Ön ve arka alt bölgeler arasında işlevsel eğilimler vardır; sınırlar keskin ve görevden bağımsız bölmeler değildir.",
      "İnsulaya ilişkin kanıtın büyük bölümü yetişkin nörogörüntüleme ve klinik yöntemlere dayanır.",
    ],
    keywords: ["interosepsiyon", "salience", "beden sinyali", "duygu", "korteks", "ön insula", "arka insula"],
    claimIds: [
      "claim.insula.multifunction",
      "claim.insula.anatomical_gradients",
      "claim.insula.boundary",
    ],
    sourceIds: [
      "UDDIN_ET_AL_2017",
      "KURTH_ET_AL_2010",
      "MENON_UDDIN_2010",
      "FERRARO_ET_AL_2022",
      "CRITCHLEY_HARRISON_2013",
      "POLDRAK_2006",
    ],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "Davranış veya DNA profilinden insula işlevi, hasarı ya da zayıflığı çıkarılamaz.",
  }),
  topic({
    id: "cns.insula_subregions",
    category: "central_nervous_system",
    title: "İnsula alt bölgeleri",
    aliases: [
      "insula alt bölgeleri",
      "insula altbolgeleri",
      "insulanın alt bölgelere ayrılması",
      "ön ve arka insula",
      "anterior posterior insula",
      "anterior insula",
      "posterior insula",
      "insular lateralizasyon",
      "insula lateralizasyonu",
      "granüler ve agranüler insula",
      "op2 pivc",
    ],
    summary: "İnsulada ön-arka, dorsal-ventral ve bağlantısallığa dayalı alt bölge eğilimleri tanımlanır; bunlar kesin ve tek işlevli bölmeler değildir.",
    details: [
      "Arka insula daha çok somatoduyusal ve visseral temsil süreçleriyle, ön insula ise bütünleştirme ve önem işleme ağlarıyla ilişkilendirilir.",
      "Alt bölge sınırları atlas, yöntem ve göreve göre değişebilir.",
    ],
    keywords: ["anterior", "posterior", "ön insula", "arka insula", "alt bölge", "bağlantısallık"],
    claimIds: ["claim.insula.subregions", "claim.insula.subregion_boundary"],
    sourceIds: ["UDDIN_ET_AL_2017", "KURTH_ET_AL_2010"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "Alt bölge bilgisi bireysel duygu, interoseptif kapasite veya davranışın beyindeki yerini göstermez.",
  }),
  topic({
    id: "cns.insula_measurement",
    category: "central_nervous_system",
    title: "İnsula nasıl incelenir?",
    aliases: [
      "insula ölçümü",
      "insula nasıl ölçülür",
      "insula aktivitesi nasıl ölçülür",
      "insula fMRI",
      "insula nörogörüntüleme",
      "insula işlevini ölçmek",
      "bold sinyali",
      "işlevsel bağlantısallık",
    ],
    summary: "İnsulanın yapısal ve işlevsel özellikleri MRI, görev tabanlı fMRI ve nörogörüntüleme meta-analizleriyle araştırılır; yöntemler aynı şeyi ölçmez.",
    details: [
      "BOLD etkinliği doğrudan nöral çıktı, duygu veya interoseptif doğruluk değildir.",
      "Kalp odaklı bir görevdeki insula etkinliği insulanın bütün işlevlerini temsil etmez.",
    ],
    keywords: ["fMRI", "MRI", "BOLD", "ölçüm", "görüntüleme", "aktivasyon"],
    claimIds: ["claim.insula.measurement_methods", "claim.insula.measurement_boundary"],
    sourceIds: ["UDDIN_ET_AL_2017", "SCHULZ_2016", "POLDRAK_2006", "KURTH_ET_AL_2010"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "DNA, davranış gözlemi veya öz-bildirim insula aktivitesi, hacmi ya da bağlantısallığı ölçmez.",
  }),
  topic({
    id: "cns.insula_development",
    category: "central_nervous_system",
    title: "İnsulanın gelişimi",
    aliases: [
      "insula gelişimi",
      "insular korteks gelişimi",
      "çocuklarda insula",
      "bebeklerde insula",
      "insula olgunlaşması",
      "yetişkin insula çalışmalarını çocuklara",
      "yetişkin insula bulgularını çocuklara",
      "yetişkin insula çocuklara aktarım",
    ],
    summary: "Bu katalogdaki pediatrik interosepsiyon ve yetişkin-ağırlıklı insula kaynakları, 0–12 yaş için insulaya özgü normatif bir gelişim çizgisi kurmaz.",
    details: [
      "Pediatrik interosepsiyon ölçümleri sınırlı, yaşa ve yönteme duyarlıdır; bunlar doğrudan insula gelişim ölçümü değildir.",
      "Yetişkin insula bulguları çocuklarda bireysel açıklama veya norm olarak kullanılamaz.",
    ],
    keywords: ["çocuk", "bebek", "gelişim", "olgunlaşma", "pediatrik", "yaş"],
    claimIds: ["claim.insula.development_boundary"],
    sourceIds: ["ADDABBO_MILANI_2025", "UDDIN_ET_AL_2017", "POLDRAK_2006"],
    evidenceLevel: "limited",
    ageScope: "childhood",
    claimBoundary: "Bir çocuğun davranışından insula olgunluğu, bağlantısı veya gelişimsel gecikmesi çıkarılamaz.",
  }),
  topic({
    id: "cns.salience_network",
    category: "central_nervous_system",
    title: "Salience ağı",
    aliases: ["önem ağı", "salience network", "belirginlik ağı", "sn"],
    summary: "Salience ağı, iç ve dış olayların davranışsal önemini ağırlıklandırma ve diğer ağlar arasındaki geçişe katkı sağlar.",
    details: ["Ön insula ve singulat bölgeler önemli düğümlerdir.", "Ağ sabit bir alarm düğmesi değildir."],
    keywords: ["önem", "dikkat", "insula", "singulat", "ağ geçişi"],
    claimIds: ["claim.salience.network"],
    sourceIds: ["SEELEY_2019", "MENON_UDDIN_2010"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "DNA salience ağı aktivitesini veya 'beyin alarmı' durumunu ölçmez.",
  }),
  topic({
    id: "cns.central_autonomic_network",
    category: "central_nervous_system",
    title: "Merkezi otonom ağ",
    aliases: ["central autonomic network", "can", "merkezi otonom sistem", "otonom beyin ağı"],
    summary: "Merkezi otonom ağ, visseral bilgiyi bütünleştiren ve otonom çıktının bağlama göre düzenlenmesine katkı veren dağıtık merkezi devreleri anlatır.",
    details: ["İnsula, singulat, hipotalamus, amigdala ve beyin sapı düğümleri farklı tanımlarda yer alabilir.", "Ağ kavramı doğrudan klinik ölçüm değildir."],
    keywords: ["visseral", "otonom", "insula", "singulat", "hipotalamus", "beyin sapı"],
    claimIds: ["claim.can.network", "claim.can.boundary"],
    sourceIds: ["SAPER_2002", "LAMOTTE_ET_AL_2021", "FERRARO_ET_AL_2022", "POLDRAK_2006"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "DNA veya davranış gözlemi CAN etkinliğini, hasarını veya kapasitesini ölçmez.",
  }),
  topic({
    id: "cns.prefrontal_control",
    category: "central_nervous_system",
    title: "Prefrontal kontrol",
    aliases: [
      "prefrontal korteks",
      "pfc",
      "frontal lob",
      "prefrontal cortex",
      "prefrontal süreçler",
      "prefrontal işlevler",
      "prefrontal süreç",
      "prefrontal bir süreç",
      "dorsolateral prefrontal korteks",
      "ventrolateral prefrontal korteks",
      "ventromedial prefrontal korteks",
      "orbitofrontal korteks",
      "medial prefrontal korteks",
      "multiple-demand ağ",
      "multiple demand ağ",
      "frontoparietal kontrol ağı",
      "bilişsel kontrol",
      "prefontal",
    ],
    summary: "Prefrontal bölgeler hedeflerin sürdürülmesi, çalışma belleği, ketleyici kontrol ve esnek davranışa dağıtık ağlar içinde katkı verir.",
    details: [
      "Prefrontal korteks tek bir yürütücü merkez veya davranış freni değildir.",
      "Alt bölgeler ve bağlantılar farklı görevlerde farklı ağırlıklarla devreye girer.",
      "Günlük davranış doğrudan frontal işlev ölçümü değildir.",
    ],
    keywords: ["yürütücü işlev", "kontrol", "planlama", "ketleme", "frontal", "hedef sürdürme"],
    claimIds: ["claim.pfc.control", "claim.pfc.heterogeneity", "claim.pfc.boundary"],
    sourceIds: [
      "MILLER_COHEN_2001",
      "KOLK_RAKIC_2022",
      "FRIEDMAN_ROBBINS_2022",
      "DIAMOND_2013",
      "POLDRAK_2006",
    ],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "DNA profilinden frontal lob problemi veya prefrontal disfonksiyon çıkarılamaz.",
  }),
  topic({
    id: "cns.prefrontal_development",
    category: "central_nervous_system",
    title: "Prefrontal gelişim",
    aliases: [
      "prefrontal korteks gelişimi",
      "pfc gelişimi",
      "frontal olgunlaşma",
      "prefrontal olgunlaşma",
      "çocuklarda prefrontal korteks",
      "prefrontal süreçler okul çağı",
      "çocuklarda prefrontal süreçler yetişkinlerle",
    ],
    summary: "Prefrontal korteksin yapısal ve işlevsel örgütlenmesi çocukluk ve ergenlik boyunca değişir; gelişim tekdüze veya tek yaşta tamamlanan bir süreç değildir.",
    details: [
      "Alt bölgeler, bağlantılar ve görev performansı aynı hızda gelişmez.",
      "Grup düzeyi gelişim bulguları bir çocuğun olgunluk düzeyi veya geleceği için bireysel ölçüm değildir.",
    ],
    keywords: ["gelişim", "olgunlaşma", "çocukluk", "ergenlik", "plastisite", "prefrontal"],
    claimIds: ["claim.pfc.development", "claim.pfc.development_boundary"],
    sourceIds: ["KOLK_RAKIC_2022", "FISKE_HOLMBOE_2019"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Davranıştan prefrontal olgunluk yaşı, gecikme, hasar veya bireysel gelişim hızı çıkarılamaz.",
  }),
  topic({
    id: "cns.working_memory",
    category: "central_nervous_system",
    title: "Çalışma belleği",
    aliases: [
      "working memory",
      "işleyen bellek",
      "bilgiyi akılda tutma",
      "akılda tutup işleme",
      "çalışma belleği kapasitesi",
    ],
    summary: "Çalışma belleği, amaçla ilgili bilgiyi kısa süre etkin tutma ve gerektiğinde onun üzerinde işlem yapma süreçlerini kapsar.",
    details: [
      "Tek bir depodan çok, dikkat ve kontrol ağlarıyla birlikte çalışan süreçler bütünüdür.",
      "Görev performansı talimat, dikkat, dil, motivasyon ve yorgunluktan etkilenebilir.",
    ],
    keywords: ["bilgiyi sürdürme", "güncelleme", "akılda tutma", "hedef", "bellek"],
    claimIds: ["claim.working_memory.definition", "claim.working_memory.boundary"],
    sourceIds: ["MILLER_COHEN_2001", "DIAMOND_2013", "FRIEDMAN_ROBBINS_2022"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Tek görev veya günlük unutkanlık prefrontal hasar, tanı ya da sabit çalışma belleği kapasitesi göstermez.",
  }),
  topic({
    id: "cns.inhibitory_control",
    category: "central_nervous_system",
    title: "Ketleyici kontrol",
    aliases: [
      "inhibitory control",
      "inhibitör kontrol",
      "inhibisyon",
      "tepki ketleme",
      "dürtüyü durdurma",
      "davranışsal ketleme",
    ],
    summary: "Ketleyici kontrol, baskın veya otomatik bir tepkiyi bağlamdaki hedef doğrultusunda durdurma, erteleme ya da değiştirme süreçlerini kapsar.",
    details: [
      "Tepki ketleme ile dikkat dağıtıcıyı bastırma ilişkili fakat özdeş değildir.",
      "Performans yaş, görev zorluğu, motivasyon ve çevresel destekle değişebilir.",
    ],
    keywords: ["ketleme", "inhibisyon", "dürtü", "stop signal", "go no go", "tepki kontrolü"],
    claimIds: ["claim.inhibitory_control.definition", "claim.inhibitory_control.development"],
    sourceIds: ["DIAMOND_2013", "FISKE_HOLMBOE_2019"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Bir davranış veya tek ketleme görevi prefrontal işlevi, tanıyı ya da değişmez bir kapasiteyi göstermez.",
  }),
  topic({
    id: "cns.cognitive_flexibility",
    category: "central_nervous_system",
    title: "Bilişsel esneklik",
    aliases: [
      "cognitive flexibility",
      "zihinsel esneklik",
      "kural değiştirme",
      "set shifting",
      "görev değiştirme",
      "bakış açısı değiştirme",
    ],
    summary: "Bilişsel esneklik, kural, strateji, dikkat odağı veya bakış açısını değişen talebe göre güncelleyebilme süreçlerini kapsar.",
    details: [
      "Çalışma belleği ve ketleyici kontrolle ilişkilidir fakat onlarla aynı süreç değildir.",
      "Bir bağlamdaki katılık bütün bağlamlara genellenemez.",
    ],
    keywords: ["esneklik", "kural", "geçiş", "strateji", "güncelleme", "set shifting"],
    claimIds: ["claim.cognitive_flexibility.definition", "claim.cognitive_flexibility.context"],
    sourceIds: ["DIAMOND_2013", "FRIEDMAN_ROBBINS_2022"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Günlük katılık tek başına prefrontal bozukluk, tanı veya sabit bilişsel esneklik puanı değildir.",
  }),
  topic({
    id: "cns.executive_measurement",
    category: "central_nervous_system",
    title: "Yürütücü işlevlerin ölçümü",
    aliases: [
      "yürütücü işlev ölçümü",
      "executive function measurement",
      "yürütücü işlev testi",
      "performans görevi ve derecelendirme",
      "görev ve ölçek farkı",
      "yürütücü işlev ölçeği",
      "test puanı ile günlük gözlem",
      "derecelendirme ölçeği ile performans testi",
      "ekolojik geçerlilik",
    ],
    summary: "Yürütücü işlev performans görevleri ile günlük davranış derecelendirmeleri ilişkili fakat aynı olmayan bilgi düzeyleri sağlar.",
    details: [
      "Laboratuvar görevi belirli koşuldaki performansı, derecelendirme ise çoklu günlük bağlamlardaki gözlemi örnekler.",
      "Tek bir test veya ölçek yürütücü işlevlerin tamamını ölçmez.",
    ],
    keywords: ["test", "ölçek", "derecelendirme", "performans görevi", "ekolojik geçerlik", "ölçüm"],
    claimIds: ["claim.ef.measurement_distinction", "claim.ef.measurement_boundary"],
    sourceIds: ["TOPLAK_ET_AL_2013", "DIAMOND_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "DNA nöropsikolojik test bataryasının veya doğrudan beyin ölçümünün yerine geçmez.",
  }),
  topic({
    id: "cns.anterior_cingulate",
    category: "central_nervous_system",
    title: "Anterior singulat korteks",
    aliases: [
      "anterior cingulate cortex",
      "anterior singulat",
      "ön singulat korteks",
      "acc",
      "dacc",
      "dorsal acc",
      "ventral acc",
    ],
    summary: "Anterior singulat korteks, medial frontal-singulat bölgede yer alan; performans izleme, önem değerlendirme, duygulanım ve bedensel ayarlamalarla ilişkili heterojen bir bölge ailesidir.",
    details: [
      "ACC tek bir hata, duygu veya kontrol merkezi değildir.",
      "Dorsal ACC etiketi bazı anatomik çerçevelerde anterior midcingulate ile örtüşebilir.",
      "İşlevsel yorum alt bölge, görev ve ağ bağlamına bağlıdır.",
    ],
    keywords: ["singulat", "hata", "çatışma", "performans izleme", "duygu", "aMCC"],
    claimIds: [
      "claim.acc.heterogeneity",
      "claim.acc.naming_boundary",
      "claim.acc.not_single_center",
      "claim.acc.profile_boundary",
    ],
    sourceIds: ["BUSH_ET_AL_2000", "HEILBRONNER_HAYDEN_2016", "POLDRAK_2006"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "DNA veya davranıştan ACC etkinliği, yapısı, hasarı ya da kişiye özgü mekanizma çıkarılamaz.",
  }),
  topic({
    id: "cns.midcingulate",
    category: "central_nervous_system",
    title: "Orta singulat korteks",
    aliases: [
      "midcingulate cortex",
      "midcingulate",
      "mcc",
      "anterior midcingulate",
      "amcc",
      "orta singulat",
    ],
    summary: "Orta singulat korteks, singulatın bazı modern anatomik sınıflamalarında ACC'den ayrılan ve eylem, performans izleme, ağrı ve duygulanım süreçleriyle ilişkilendirilen bölgedir.",
    details: [
      "Anterior ve posterior midcingulate alt bölümleri tanımlanabilir.",
      "dACC ile aMCC terimleri literatürde her zaman aynı anatomik sınırla kullanılmaz.",
    ],
    keywords: ["mcc", "aMCC", "dacc", "singulat anatomi", "eylem", "performans"],
    claimIds: ["claim.midcingulate.anatomy", "claim.midcingulate.naming"],
    sourceIds: ["HEILBRONNER_HAYDEN_2016", "BUSH_ET_AL_2000"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "Anatomik etiketler davranıştan bölgesel işlev veya patoloji çıkarmaya izin vermez.",
  }),
  topic({
    id: "cns.performance_monitoring",
    category: "central_nervous_system",
    title: "Performans izleme",
    aliases: [
      "performance monitoring",
      "hata izleme",
      "çatışma izleme",
      "sonuç izleme",
      "performansı izleme",
      "hata fark etme",
    ],
    summary: "Performans izleme, devam eden davranışta hata, çatışma ve sonuç sinyallerini değerlendirip sonraki kontrolü ayarlamaya katkı veren süreçler bütünüdür.",
    details: [
      "Tek bir beyin bölgesi veya tek ERP bileşeniyle eş anlamlı değildir.",
      "Görev talebi, geri bildirim, motivasyon ve gelişim dönemi yanıtı değiştirebilir.",
    ],
    keywords: ["hata", "çatışma", "geri bildirim", "kontrol ayarlama", "izleme", "performans"],
    claimIds: ["claim.performance_monitoring.process", "claim.performance_monitoring.distributed"],
    sourceIds: ["CARTER_VAN_VEEN_2007", "HEILBRONNER_HAYDEN_2016"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Hata davranışı tek başına ACC işlevi, tanı veya sabit izleme kapasitesi ölçmez.",
  }),
  topic({
    id: "cns.error_related_negativity",
    category: "central_nervous_system",
    title: "Hata ilişkili negatiflik",
    aliases: [
      "error related negativity",
      "error-related negativity",
      "ern",
      "hata sonrası negatiflik",
      "hata erp bileşeni",
    ],
    summary: "Hata ilişkili negatiflik (ERN/Ne), hata yanıtının hemen ardından kafa derisi EEG'sinde gözlenen yanıt-kilitli bir ERP bileşenidir.",
    details: [
      "ERN performans izlemenin yalnız bir göstergesidir; ACC'nin doğrudan ölçümü değildir.",
      "Genlik yaş, görev, hata sayısı, referanslama ve analiz seçimine duyarlıdır.",
    ],
    keywords: ["EEG", "ERP", "hata", "negatiflik", "genlik", "yanıt kilitli"],
    claimIds: ["claim.ern.definition", "claim.ern.development_measurement"],
    sourceIds: ["WIERSEMA_ET_AL_2007", "CARTER_VAN_VEEN_2007"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "ERN tek başına tanı, kaygı düzeyi, ACC aktivitesi veya bireysel gelecek sonucu göstermez.",
  }),
  topic({
    id: "cns.cingulo_opercular_network",
    category: "central_nervous_system",
    title: "Singulo-operküler ağ",
    aliases: [
      "cingulo-opercular network",
      "cingulo opercular network",
      "singulo operküler ağ",
      "singulo operkular ağ",
      "cingulo-opercular ağ",
      "co network",
    ],
    summary: "Singulo-operküler ağ, bazı parselasyonlarda anterior insula/frontal operkulum ile dorsal singulat veya midcingulate düğümlerini birlikte adlandıran kontrol ve önem işleme ağıdır.",
    details: [
      "Ağ adları ve sınırları atlas ile yönteme göre değişebilir.",
      "Salience ağıyla önemli düğüm örtüşmesi vardır; iki etiket her çalışmada tam eş anlamlı değildir.",
    ],
    keywords: ["cingulo", "operküler", "frontal operkulum", "anterior insula", "singulat", "kontrol ağı"],
    claimIds: ["claim.cingulo_opercular.definition", "claim.cingulo_opercular.naming_boundary"],
    sourceIds: ["MENON_UDDIN_2010", "UDDIN_ET_AL_2017", "SEELEY_2019"],
    evidenceLevel: "moderate",
    ageScope: "adult_weighted",
    claimBoundary: "Ağ etiketi DNA puanı, bireysel bağlantısallık ölçümü veya davranışın tek mekanizması değildir.",
  }),
  topic({
    id: "cns.reverse_inference",
    category: "central_nervous_system",
    title: "Tersine çıkarım",
    aliases: ["reverse inference", "bölgeden davranış çıkarma", "davranıştan beyin bölgesi", "lokalizasyon hatası"],
    summary: "Tersine çıkarım, davranış veya grup düzeyi beyin bulgusundan tek ve özgül bir bilişsel süreç ya da patoloji sonucu üretme hatasıdır.",
    details: ["Aynı bölge farklı işlevlere katılabilir.", "Aynı davranış farklı yollarla ortaya çıkabilir."],
    keywords: ["nörogörüntüleme", "çıkarım", "bölge", "patoloji", "lokalizasyon"],
    claimIds: ["claim.reverse_inference"],
    sourceIds: ["POLDRAK_2006"],
    evidenceLevel: "boundary",
    ageScope: "all_ages",
    claimBoundary: "Bu yöntem sınırı kültürel norm, eşsonluluk veya klinik tanı için doğrudan kanıt değildir.",
  }),
  topic({
    id: "ans.overview",
    category: "autonomic_nervous_system",
    title: "Otonom sinir sistemi",
    aliases: ["oss", "ans", "autonomic nervous system", "otonom sistem"],
    summary: "Otonom sinir sistemi, iç organ işlevlerinin koşullara göre ayarlanmasına katılan merkezi ve periferik düzenleme ağıdır.",
    details: ["Kalp, damar, terleme, pupil, sindirim ve başka süreçlere katılır.", "Örüntüler organ ve bağlama özgüdür."],
    keywords: ["kalp", "damar", "terleme", "pupil", "sindirim", "visseral"],
    claimIds: ["claim.ans.overview", "claim.ans.not_personality", "claim.ans.behavior_not_disorder"],
    sourceIds: ["WEHRWEIN_ET_AL_2016", "SAPER_2002", "BERNTSON_ET_AL_1991"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "DNA otonom hastalık, dal baskınlığı veya kişisel biyolojik mekanizma ölçmez.",
  }),
  topic({
    id: "ans.homeostasis",
    category: "autonomic_nervous_system",
    title: "Homeostaz",
    aliases: ["homeostasis", "iç denge", "bedensel denge", "dengeyi koruma"],
    summary: "Homeostaz, iç değişkenlerin geri bildirim süreçleriyle işlevsel aralıklarda tutulmasını anlatan dinamik düzenlemedir.",
    details: ["Hareketsiz veya tek bir ideal nokta değildir.", "Sürekli düzeltici ayarlamalar içerebilir."],
    keywords: ["geri bildirim", "denge", "iç ortam", "fizyoloji"],
    claimIds: ["claim.homeostasis.definition"],
    sourceIds: ["RAMSAY_WOODS_2014"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "Homeostaz DNA tarafından doğrudan ölçülen bir skor veya klinik eşik değildir.",
  }),
  topic({
    id: "ans.allostasis",
    category: "autonomic_nervous_system",
    title: "Allostaz",
    aliases: [
      "allostasis",
      "allostatik düzenleme",
      "öngörücü düzenleme",
      "allostatik yük",
      "homeostaz ile allostaz",
      "homeostaz ve allostaz",
    ],
    summary: "Allostaz, fizyolojik düzenlemenin değişen ve beklenen taleplere göre ayarlanmasını vurgulayan kuramsal çerçevedir.",
    details: ["Homeostazla rakip değil, farklı vurgu taşıyan bir açıklamadır.", "Allostatik yük tek davranıştan çıkarılamaz."],
    keywords: ["stres", "öngörü", "uyum", "fizyolojik maliyet", "yük"],
    claimIds: ["claim.allostasis.definition"],
    sourceIds: ["RAMSAY_WOODS_2014", "MCEWEN_1998"],
    evidenceLevel: "theoretical",
    ageScope: "mixed",
    claimBoundary: "Allostaz ve allostatik yük DNA puanı, tanı veya kişisel mekanizma değildir.",
  }),
  topic({
    id: "ans.hrv",
    category: "autonomic_nervous_system",
    title: "Kalp hızı değişkenliği",
    aliases: [
      "hrv",
      "heart rate variability",
      "kalp atım değişkenliği",
      "rsa",
      "rmssd",
      "hf-hrv",
      "lf-hrv",
      "lf hf",
    ],
    summary: "HRV, ardışık kalp atımları arasındaki zaman aralıklarının değişkenliğidir; kardiyak zaman serisinden hesaplanır.",
    details: ["Bazı ölçütler kardiyak vagal modülasyonla ilişkilidir.", "ANS'nin tamamı, beyin veya self-regülasyon için özgül ve doğrudan ölçüm değildir."],
    keywords: ["kalp", "vagal", "rmssd", "hf", "lf", "atım aralığı"],
    claimIds: [
      "claim.hrv.definition",
      "claim.hrv.measurement_boundary",
      "claim.hrv.development_boundary",
      "claim.hrv.association",
      "claim.hrv.lfhf",
    ],
    sourceIds: ["TASK_FORCE_HRV_1996", "LABORDE_ET_AL_2017", "BILLMAN_2013", "GRAZIANO_DEREFINKO_2013", "GASIOR_ET_AL_2018"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "DNA skorundan HRV, vagal ton, LF/HF dengesi veya otonom bozukluk çıkarılamaz.",
  }),
  topic({
    id: "ans.eda",
    category: "autonomic_nervous_system",
    title: "Elektrodermal aktivite",
    aliases: ["eda", "electrodermal activity", "deri iletkenliği", "galvanik deri yanıtı", "scr", "scl"],
    summary: "EDA, ter bezlerinin sempatik sinirsel kontrolüyle ilişkili deri iletkenliği değişimlerinin ölçümüdür.",
    details: ["Uyarılma, dikkat, sıcaklık ve hareketten etkilenebilir.", "Belirli bir duygu veya tanıya özgül değildir."],
    keywords: ["terleme", "deri", "iletkenlik", "sempatik", "uyarılma"],
    claimIds: ["claim.eda.definition", "claim.eda.sensory"],
    sourceIds: ["BOUCSEIN_ET_AL_2012", "CHRISTENSEN_ET_AL_2020", "MCINTOSH_ET_AL_1999"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "DNA duyusal veya fizyolojik alan puanı EDA ölçümü değildir.",
  }),
  topic({
    id: "ans.interoception",
    category: "autonomic_nervous_system",
    title: "İnterosepsiyon",
    aliases: [
      "interoception",
      "interasepsiyon",
      "beden sinyallerini fark etme",
      "beden sinyalleri",
      "beden sinyali",
      "beden sinyalini fark etmek",
      "iç beden algısı",
      "interoseptif sinyal",
      "interoseptif dikkat",
      "interoseptif performans",
      "interoseptif süreç",
      "bedenin içinden gelen sinyaller",
    ],
    summary: "İnterosepsiyon, organizmanın iç beden sinyallerini algılama, bütünleştirme, yorumlama ve düzenleyici biçimde kullanma süreçlerinin geniş şemsiyesidir.",
    details: [
      "İşlemenin önemli bir bölümü bilinçli farkındalık dışında gerçekleşebilir.",
      "Görev performansı, öz-bildirim eğilimi ve metabilişsel farkındalık ayrılmalıdır.",
      "Kalp, solunum, gastrointestinal, termal ve başka beden kanalları birbirinin yerine geçmez.",
      "Çocukluk ölçümleri ve yetişkin bulguları otomatik eşitlenmez.",
    ],
    keywords: ["beden sinyali", "farkındalık", "doğruluk", "duyarlılık", "duygu", "içsel sinyal", "visseral"],
    claimIds: [
      "claim.interoception.multidimensional",
      "claim.interoception.consciousness_boundary",
      "claim.interoception.emotion",
    ],
    sourceIds: [
      "CHEN_ET_AL_2021",
      "QUIGLEY_ET_AL_2021",
      "KHALSA_ET_AL_2018",
      "GARFINKEL_ET_AL_2015",
      "PINNA_EDWARDS_2020",
    ],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "DNA interosepsiyon alanı doğrudan ANS bozukluğu, insula işlevi veya tıbbi durum göstermez.",
  }),
  topic({
    id: "ans.interoception_dimensions",
    category: "autonomic_nervous_system",
    title: "İnterosepsiyonun boyutları",
    aliases: [
      "interoseptif doğruluk farkındalık farkı",
      "interoseptif doğruluk ve farkındalık",
      "interoseptif eğilim",
      "interoceptive accuracy",
      "interoceptive sensibility",
      "interoceptive awareness",
      "interoseptif metabiliş",
      "interoseptif doğruluk",
      "interoseptif duyarlılık",
      "interoseptif farkındalık",
      "metabilişsel interoseptif farkındalık",
      "öz bildirimli beden farkındalığı",
      "maia-y",
    ],
    summary: "İnteroseptif görev performansı, kişinin kendi deneyimini bildirme eğilimi ve performansına ilişkin metabilişsel isabet aynı boyut değildir.",
    details: [
      "Bir kişi beden sinyallerine çok dikkat ettiğini bildirebilir fakat belirli bir görevde yüksek doğruluk göstermeyebilir; tersi de mümkündür.",
      "Terimler literatürde zaman içinde değiştiği için ölçümün operasyonel tanımı açıkça belirtilmelidir.",
    ],
    keywords: ["accuracy", "sensibility", "awareness", "öz bildirim", "metabiliş", "güven", "doğruluk"],
    claimIds: ["claim.interoception.dimensions_distinct", "claim.interoception.terminology_boundary"],
    sourceIds: ["GARFINKEL_ET_AL_2015", "DESMEDT_ET_AL_2023", "KHALSA_ET_AL_2018"],
    evidenceLevel: "strong",
    ageScope: "adult_weighted",
    claimBoundary: "Bir boyuttaki sonuç diğer boyutların veya genel interoseptif kapasitenin doğrudan ölçümü değildir.",
  }),
  topic({
    id: "ans.interoception_measurement",
    category: "autonomic_nervous_system",
    title: "İnterosepsiyonun ölçümü",
    aliases: [
      "interosepsiyon nasıl ölçülür",
      "interosepsiyon",
      "interoseptif ölçüm",
      "interoception measurement",
      "kalp atımı sayma görevi",
      "kalp atışı sayma görevi",
      "heartbeat counting task",
      "kalp atımı ayırt etme",
      "interosepsiyon testi",
      "hep",
      "maia-y ile fizyolojik görev",
      "interoseptif görevler",
      "çocuk ve ebeveyn raporları",
      "kalbini sayamıyorsa",
    ],
    summary: "İnterosepsiyon performans görevleri, öz-bildirimler, güven değerlendirmeleri ve bazı nörofizyolojik yöntemlerle farklı düzeylerde incelenir; evrensel tek bir altın standart yoktur.",
    details: [
      "Kalp atımı sayma, ayırt etme ve sinyal tespit görevleri aynı beceriyi aynı biçimde ölçmez.",
      "Kalp bilgisi, zaman tahmini, dikkat, talimat ve fizyolojik sinyal gücü sonucu etkileyebilir.",
      "Çocuklarda görev uygunluğu, yaş ve anlama düzeyi ayrıca değerlendirilmelidir.",
    ],
    keywords: ["ölçüm", "görev", "kalp atımı", "öz bildirim", "geçerlik", "altın standart", "test"],
    claimIds: ["claim.interoception.no_gold_standard", "claim.interoception.tasks_not_equivalent"],
    sourceIds: ["DESMEDT_ET_AL_2023", "DONAGHY_ET_AL_2025", "ADDABBO_MILANI_2025"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Tek görev veya DNA alanı genel interoseptif doğruluk, ANS durumu ya da beyin bölgesi işlevi göstermez.",
  }),
  topic({
    id: "ans.interoception_development",
    category: "autonomic_nervous_system",
    title: "İnterosepsiyonun gelişimi",
    aliases: [
      "interosepsiyon gelişimi",
      "çocuklarda interosepsiyon",
      "bebeklerde interosepsiyon",
      "interoseptif gelişim",
      "pediatrik interosepsiyon",
      "yaşa göre interosepsiyon",
      "çocuk öz bildirimi",
    ],
    summary: "İç beden sinyallerine duyarlılık yaşamın erken dönemlerinde incelenebilir; ancak 0–12 yaş için tek, normatif ve tüm modalitelere uyan bir gelişim eğrisi yoktur.",
    details: [
      "Bebeklerde bedenle eşzamanlı uyaranlara farklı yanıt verilmesi bilinçli farkındalık kanıtı değildir.",
      "Çocukluk çalışmaları az sayıda, görev ve yaş aralıkları açısından heterojendir.",
      "Yetişkin görev sonuçları çocuk normu olarak kullanılamaz.",
    ],
    keywords: ["bebek", "çocuk", "gelişim", "yaş", "norm", "erken çocukluk", "pediatrik"],
    claimIds: ["claim.interoception.infant_sensitivity", "claim.interoception.development_gap"],
    sourceIds: ["MAISTER_ET_AL_2017", "ADDABBO_MILANI_2025"],
    evidenceLevel: "limited",
    ageScope: "childhood",
    claimBoundary: "Davranıştan çocuğun genel interoseptif olgunluğu, gecikmesi, tanısı veya geleceği çıkarılamaz.",
  }),
  topic({
    id: "ans.interoception_modalities",
    category: "autonomic_nervous_system",
    title: "İnteroseptif modaliteler",
    aliases: [
      "interosepsiyon türleri",
      "interoceptive modalities",
      "interoseptif kanallar",
      "kardiyak interosepsiyon",
      "solunumsal interosepsiyon",
      "gastrointestinal interosepsiyon",
      "açlık tokluk sinyalleri",
      "açlık ve tokluk",
      "tuvalet rutinleri",
      "yorgunluk hissi",
      "nosisepsiyon ve ağrı",
      "nosisepsiyon ile ağrı",
      "ağrı ve nosisepsiyon",
      "ağrı ile nosisepsiyon",
      "acıktığını anlamıyor",
      "acıktığını anlamıyo",
    ],
    summary: "İnterosepsiyon kardiyak, solunumsal, gastrointestinal, mesane-bağırsak, termal, ağrı ve efor gibi birden çok beden sinyali alanını kapsar.",
    details: [
      "Modaliteler farklı reseptörler, yollar, görevler ve bağlamsal etkiler içerir.",
      "Bir modalitedeki yüksek veya düşük performans diğer modalitelere otomatik genellenemez.",
    ],
    keywords: ["kardiyak", "solunum", "gastrointestinal", "açlık", "tokluk", "mesane", "termal", "ağrı"],
    claimIds: ["claim.interoception.multimodal", "claim.interoception.modality_specificity"],
    sourceIds: ["CHEN_ET_AL_2021", "QUIGLEY_ET_AL_2021"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Tek bir günlük davranış veya beden kanalı genel interosepsiyon, neden ya da tanı göstermez.",
  }),
  topic({
    id: "ans.development",
    category: "autonomic_nervous_system",
    title: "Otonom gelişim ve yaş",
    aliases: [
      "çocuklarda otonom sinir sistemi",
      "çocuklarda ans hangi yaşlarda",
      "yenidoğanda ans olgunlaşması",
      "ans gelişimi",
      "hrv normları",
      "yaşa göre hrv",
      "çocuklarda hrv yaşa göre değişir",
      "otonom gelişim",
      "otonom olgunlaşma",
      "puberte",
      "yaş ilerledikçe",
      "yetişkin bulgularını çocuklara",
      "yetişkin hrv",
      "çocuklara aktar",
    ],
    summary: "Otonom göstergeler çocukluk boyunca yaş, büyüme, solunum, aktivite ve ölçüm protokolüyle değişebilir.",
    details: ["Pediatrik normlar protokole duyarlıdır.", "Grup değerleri bireysel klinik eşik değildir."],
    keywords: ["çocuk", "gelişim", "yaş", "norm", "pediatrik", "protokol"],
    claimIds: ["claim.ans.development"],
    sourceIds: ["GASIOR_ET_AL_2018", "WHEDON_ET_AL_2018"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Yaş normu DNA puanına çevrilemez ve bireysel prognoz sağlamaz.",
  }),
  topic({
    id: "ans.sympathetic_parasympathetic",
    category: "sympathetic_parasympathetic",
    title: "Sempatik ve parasempatik süreçler",
    aliases: [
      "sempatik parasempatik",
      "sempatik ve parasempatik sistem",
      "sempatik sistem",
      "sempatik sinir sistemi",
      "sempatik aktivite",
      "sempatik reaktivite",
      "sempatik baskın",
      "sempatik",
      "parasempatik sistem",
      "parasempatik sinir sistemi",
      "parasempatik",
      "sympathetic parasympathetic",
      "savaş kaç",
      "dinlen sindir",
      "otonom dallar",
    ],
    summary: "Sempatik ve parasempatik süreçler günlük uyum için birlikte çalışan, organ ve bağlama göre farklılaşan otonom bileşenlerdir.",
    details: ["Biri evrensel olarak kötü, diğeri iyi değildir.", "Klasik sloganlar fizyolojinin yalnız kaba bir özetidir."],
    keywords: ["sempatik", "parasempatik", "enerji", "toparlanma", "organ"],
    claimIds: ["claim.sympathetic.parasympathetic", "claim.sympathetic.measurement_boundary"],
    sourceIds: [
      "WEHRWEIN_ET_AL_2016",
      "BERNTSON_ET_AL_1991",
      "BOUCSEIN_ET_AL_2012",
      "TASK_FORCE_HRV_1996",
      "MATHOT_2018",
    ],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "Davranıştan sempatik baskınlık, parasempatik yetersizlik veya kişisel dal durumu çıkarılamaz.",
  }),
  topic({
    id: "ans.autonomic_space",
    category: "sympathetic_parasympathetic",
    title: "Otonom uzam",
    aliases: [
      "autonomic space",
      "otonom tahterevalli",
      "eşzamanlı aktivasyon",
      "aynı anda etkinleşme",
      "aynı anda etkinleşebilir",
      "eşzamanlı etkinleşme",
      "sempatovagal denge",
      "sempatik ve parasempatik aynı anda etkin",
      "sempatik ve parasempatik sistemler aynı anda etkinleşebilir mi",
    ],
    summary: "Otonom uzam, sempatik ve parasempatik süreçlerin yalnız karşıt değil; eşzamanlı veya bağımsız örüntüler de gösterebildiğini anlatır.",
    details: ["Örüntü organa ve göreve göre değişir.", "Tek küresel denge skoru fizyolojiyi yeterince temsil etmez."],
    keywords: ["bağımsızlık", "eşzamanlı", "karşılıklı", "denge", "otonom dallar"],
    claimIds: ["claim.autonomic.space"],
    sourceIds: ["BERNTSON_ET_AL_1991", "DAMPNEY_2016"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Çerçeve kişiye özgü organ örüntüsünü davranıştan belirlemez.",
  }),
  topic({
    id: "ans.measurement_limits",
    category: "sympathetic_parasympathetic",
    title: "Otonom ölçüm sınırları",
    aliases: [
      "otonom test",
      "ans ölçümü",
      "ans hangi yöntemlerle ölçülür",
      "tek bir giyilebilir sensör bütün ans",
      "vagus ölçümü",
      "otonom biyobelirteç",
      "wearable",
      "akıllı saat sinir sistemi",
      "pep",
      "ecg",
      "ppg",
      "pupillometri",
      "barorefleks",
    ],
    summary: "HRV, EDA, pupil ve diğer ölçümler otonom işlevin farklı parçalarına ilişkin bilgi verir; hiçbiri tek başına bütün ANS'yi ölçmez.",
    details: ["Her sinyal farklı fizyolojik belirleyicilere sahiptir.", "Kayıt protokolü ve artefakt kontrolü zorunludur."],
    keywords: ["hrv", "eda", "pupil", "ölçüm", "sensör", "protokol"],
    claimIds: ["claim.ans.measurement"],
    sourceIds: ["TASK_FORCE_HRV_1996", "BOUCSEIN_ET_AL_2012", "MATHOT_2018"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Davranış, öz-bildirim veya DNA skoru fizyolojik otonom test yerine geçmez.",
  }),
  topic({
    id: "ans.polyvagal",
    category: "sympathetic_parasympathetic",
    title: "Polivagal teori",
    aliases: ["polyvagal", "polivagal", "dorsal vagal", "ventral vagal", "vagal shutdown"],
    summary: "Polivagal teori etkili bir kuramsal çerçevedir; bazı anatomik ve fizyolojik öncülleri bilimsel tartışma konusudur.",
    details: ["Savunucu ve eleştirel kaynaklarla birlikte sunulmalıdır.", "Yerleşik ve tartışmasız fizyoloji gibi anlatılmamalıdır."],
    keywords: ["vagus", "dorsal", "ventral", "güvenlik", "sosyal bağlılık"],
    claimIds: ["claim.polyvagal.status", "claim.polyvagal.boundary"],
    sourceIds: ["PORGES_2021", "GROSSMAN_2023", "LABORDE_ET_AL_2017"],
    evidenceLevel: "theoretical",
    ageScope: "mixed",
    claimBoundary: "Davranıştan dorsal/ventral vagal durum veya kişisel vagal ton atanamaz.",
  }),
  topic({
    id: "selfreg.stress_systems",
    category: "self_regulation",
    title: "Stres sistemleri",
    aliases: [
      "stres sistemi",
      "stres yanıt sistemi",
      "stress systems",
      "stres fizyolojisi",
      "stres yanıtı",
      "stresör",
    ],
    summary: "Stres yanıtı; sinir sistemi, HPA ekseni, otonom, bağışıklık ve metabolik süreçlerin bağlama göre koordine olabildiği çok sistemli bir süreçtir.",
    details: [
      "Stresör, öznel deneyim, davranışsal yanıt ve fizyolojik göstergeler aynı şey değildir.",
      "Farklı sistemler aynı anda ve aynı yönde değişmek zorunda değildir.",
    ],
    keywords: ["stres", "stresör", "hpa", "otonom", "kortizol", "uyum", "çok sistemli"],
    claimIds: ["claim.stress.multisystem", "claim.stress.systems_not_interchangeable"],
    sourceIds: ["CHROUSOS_2009", "MCEWEN_2007", "GUNNAR_QUEVEDO_2007", "DEJOSEPH_ET_AL_2024"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Davranış, DNA profili veya tek biyobelirteç bir çocuğun bütün stres sistemini, travma geçmişini ya da hastalığını göstermez.",
  }),
  topic({
    id: "selfreg.hpa_axis",
    category: "self_regulation",
    title: "HPA ekseni",
    aliases: [
      "hipotalamus hipofiz adrenal ekseni",
      "hipotalamik hipofizer adrenal eksen",
      "hypothalamic pituitary adrenal axis",
      "hpa axis",
      "crh acth kortizol",
      "adrenal stres sistemi",
    ],
    summary: "HPA ekseni, hipotalamus, hipofiz ve adrenal korteks arasındaki hormon sinyalleri ile geri bildirim döngülerini içeren nöroendokrin bir stres sistemidir.",
    details: [
      "CRH ve ilişkili hipotalamik sinyaller ACTH salımını, ACTH ise adrenal kortizol üretimini etkiler.",
      "Bazal ritim, reaktivite ve toparlanma aynı ölçüm değildir ve gelişim ile örnekleme koşullarına duyarlıdır.",
    ],
    keywords: ["hpa", "hipotalamus", "hipofiz", "adrenal", "crh", "acth", "kortizol", "geri bildirim"],
    claimIds: ["claim.hpa.axis_definition", "claim.hpa.behavior_boundary"],
    sourceIds: ["CHROUSOS_2009", "MCEWEN_2007", "GUNNAR_QUEVEDO_2007"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Davranıştan, gözlemden veya DNA puanından HPA ekseni işlevi, hormon düzeyi ya da bozukluk çıkarılamaz.",
  }),
  topic({
    id: "selfreg.cortisol_measurement",
    category: "self_regulation",
    title: "Kortizol ve ölçüm sınırları",
    aliases: [
      "kortizol ölçümü",
      "cortisol measurement",
      "tükürük kortizolü",
      "saç kortizolü",
      "kortizol uyanma yanıtı",
      "cortisol awakening response",
      "car",
    ],
    summary: "Kortizol kan, tükürük, idrar veya saç gibi örneklerle farklı zaman ölçeklerinde incelenebilir; bu ölçümler birbirinin yerine geçmez.",
    details: [
      "Günün saati, uyanma zamanı, örnekleme aralığı, hastalık, ilaç ve protokol sonuçları etkileyebilir.",
      "Tek kortizol değeri bütün stres yanıtını veya yaşanmış travmayı göstermez.",
    ],
    keywords: ["kortizol", "tükürük", "saç", "uyanma yanıtı", "örnekleme", "hormon", "ölçüm"],
    claimIds: ["claim.cortisol.time_scales", "claim.cortisol.measurement_boundary"],
    sourceIds: ["STALDER_ET_AL_2016", "CHROUSOS_2009", "GUNNAR_QUEVEDO_2007"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Kortizol DNA veya davranıştan tahmin edilemez; tek değer tanı, neden, travma kanıtı veya kişisel regülasyon puanı değildir.",
  }),
  topic({
    id: "selfreg.toxic_stress",
    category: "self_regulation",
    title: "Toksik stres kavramı",
    aliases: ["toxic stress", "toksik stres", "çocukluk toksik stresi", "erken yaşam stresi"],
    summary: "Toksik stres, güçlü veya uzun süreli güçlüklerin yeterli koruyucu ilişkisel destek olmadan gelişim sistemlerini zorlayabilmesini anlatan bir halk sağlığı çerçevesidir.",
    details: [
      "Kavram tek bir hormon değeri, davranış veya ACE puanıyla doğrulanmaz.",
      "Klinik tanı adı ya da belirli çocukta kalıcı biyolojik hasar sonucu değildir.",
    ],
    keywords: ["toksik stres", "erken güçlük", "adversite", "koruyucu ilişki", "halk sağlığı"],
    claimIds: ["claim.toxic_stress.framework"],
    sourceIds: ["SHONKOFF_ET_AL_2012", "GUNNAR_QUEVEDO_2007"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "DNA profili, ACE puanı, kortizol veya davranış bir çocuğun toksik stres yaşadığını, travmasını ya da biyolojik hasarını kanıtlamaz.",
  }),
  topic({
    id: "ans.allostatic_load",
    category: "autonomic_nervous_system",
    title: "Allostatik yük",
    aliases: ["allostatic load", "allostatik yük", "fizyolojik yük", "kümülatif biyolojik yük"],
    summary: "Allostatik yük, uzun süreli uyum talepleriyle ilişkili çoklu fizyolojik sistem göstergelerini bir arada incelemeye çalışan araştırma çerçevesidir.",
    details: [
      "Kullanılan biyobelirteçler, puanlama ve eşikler çalışmalar arasında değişir.",
      "Çocuklar için evrensel tek bir klinik eşik bulunmaz.",
    ],
    keywords: ["allostatik", "yük", "biyobelirteç", "çoklu sistem", "eşik", "kümülatif"],
    claimIds: ["claim.allostatic_load.multisystem", "claim.allostatic_load.no_universal_threshold"],
    sourceIds: ["LUCENTE_GUIDI_2023", "MCEWEN_1998", "MCEWEN_2007"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Allostatik yük davranıştan veya DNA puanından hesaplanamaz ve bireysel tanı ya da hasar skoru değildir.",
  }),
  topic({
    id: "selfreg.sleep_health",
    category: "self_regulation",
    title: "Uyku sağlığı",
    aliases: ["sleep health", "uyku", "çocuk uykusu", "uyku kalitesi", "sağlıklı uyku"],
    summary: "Çocuk uykusu süre, zamanlama, düzenlilik, süreklilik, gündüz uyanıklığı ve uykuya ilişkin davranışlar gibi birden çok boyutla ele alınır.",
    details: [
      "Uyku süresi tek başına bütün uyku sağlığını temsil etmez.",
      "Uyku ile bilişsel, duygusal ve davranışsal işlev arasındaki ilişkiler grup düzeyinde ve çoğu zaman çift yönlüdür.",
    ],
    keywords: ["uyku", "süre", "zamanlama", "düzenlilik", "süreklilik", "gündüz", "sağlık"],
    claimIds: ["claim.sleep.multidimensional", "claim.sleep.function_association"],
    sourceIds: ["INHULSEN_ET_AL_2022", "ASTILL_ET_AL_2012", "GREGORY_SADEH_2012"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "Tek gözlem, anket veya DNA alanı uyku bozukluğu, biyolojik saat, uyku evresi ya da bireysel neden göstermez.",
  }),
  topic({
    id: "selfreg.daily_rhythm",
    category: "self_regulation",
    title: "Günlük ritim",
    aliases: ["daily rhythm", "günlük ritim", "24 saatlik örüntü", "dinlenme etkinlik ritmi", "uyku uyanıklık ritmi"],
    summary: "Günlük ritim, uyku, uyanıklık, etkinlik, dinlenme ve rutinlerin gün içindeki gözlenebilir zaman örüntüsünü anlatır.",
    details: [
      "Günlük düzenlilik davranışsal bir örüntüdür; sirkadiyen fazın doğrudan ölçümü değildir.",
      "Hareketsizlik uykuya, yatış saati biyolojik saate otomatik olarak eşitlenemez.",
    ],
    keywords: ["günlük", "ritim", "uyku uyanıklık", "etkinlik", "rutin", "24 saat"],
    claimIds: ["claim.daily_circadian.distinction"],
    sourceIds: ["BORBELY_ET_AL_2016", "HASTINGS_ET_AL_2018"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Günlük davranış örüntüsünden melatonin, kortizol, SCN işlevi veya kişisel sirkadiyen faz çıkarılamaz.",
  }),
  topic({
    id: "selfreg.circadian_rhythm",
    category: "self_regulation",
    title: "Sirkadiyen ritim",
    aliases: ["circadian rhythm", "sirkadiyen ritim", "biyolojik saat", "sirkadiyen faz", "scn", "suprakiazmatik çekirdek"],
    summary: "Sirkadiyen ritimler, yaklaşık 24 saatlik biyolojik zamanlama süreçleridir ve ışık gibi zamanlayıcılarla çevreye ayarlanır.",
    details: [
      "Uyku zamanlaması sirkadiyen sistemle etkileşir, ancak uyku ve sirkadiyen ritim aynı şey değildir.",
      "Davranışsal yatış saati kişisel melatonin başlangıcı veya SCN işlevini doğrudan ölçmez.",
    ],
    keywords: ["sirkadiyen", "biyolojik saat", "ışık", "faz", "melatonin", "scn", "24 saat"],
    claimIds: ["claim.circadian.definition", "claim.circadian.behavior_boundary"],
    sourceIds: ["HASTINGS_ET_AL_2018", "BORBELY_ET_AL_2016"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "DNA, akıllı saat veya rutin gözlemi sirkadiyen fazı, melatonin düzeyini ya da SCN işlevini ölçmez.",
  }),
  topic({
    id: "selfreg.sleep_regulation",
    category: "self_regulation",
    title: "Uykunun iki süreçli düzenlenmesi",
    aliases: ["two process model", "iki süreç modeli", "uyku basıncı", "homeostatik uyku süreci", "process s", "process c"],
    summary: "İki süreçli model, uyku zamanlamasını biriken homeostatik uyku basıncı ile sirkadiyen zamanlama süreçlerinin etkileşimi üzerinden açıklar.",
    details: [
      "Modeldeki süreçler kuramsal yapılardır ve günlük davranıştan doğrudan ölçülmez.",
      "Model tek bir çocuğun uyku bozukluğunu veya kişisel müdahalesini belirlemez.",
    ],
    keywords: ["uyku basıncı", "homeostatik", "sirkadiyen", "iki süreç", "process s", "process c"],
    claimIds: ["claim.sleep.two_process"],
    sourceIds: ["BORBELY_ET_AL_2016"],
    evidenceLevel: "theoretical",
    ageScope: "mixed",
    claimBoundary: "İki süreçli model davranıştan biyolojik süreç değeri, tanı veya kişiselleştirilmiş tedavi üretmez.",
  }),
  topic({
    id: "selfreg.sleep_measurement",
    category: "self_regulation",
    title: "Çocuk uykusunun ölçümü",
    aliases: [
      "sleep measurement",
      "uyku ölçümü",
      "aktigrafi",
      "actigraphy",
      "uyku günlüğü",
      "uyku anketi",
      "cshq",
      "bisq",
      "polisomnografi",
      "psg",
    ],
    summary: "Uyku günlüğü, bakımveren anketi, aktigrafi ve polisomnografi farklı veri düzeyleri sağlar; hiçbiri her soruyu tek başına yanıtlamaz.",
    details: [
      "Aktigrafi hareketten uyku-uyanıklık tahmini yapar ve uyku evresini doğrudan ölçmez.",
      "Anket puanları bildirilen örüntüleri tarar; tanı veya biyolojik saat testi değildir.",
    ],
    keywords: ["ölçüm", "aktigrafi", "anket", "günlük", "polisomnografi", "akıllı saat", "uyku evresi"],
    claimIds: ["claim.sleep.measurement_multimethod", "claim.sleep.device_boundary"],
    sourceIds: ["MELTZER_ET_AL_2012_SLEEP", "INHULSEN_ET_AL_2022", "SADEH_2004"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "Akıllı saat, aktigrafi, anket veya DNA tek başına uyku evresi, tanı, sirkadiyen faz veya hormon düzeyi göstermez.",
  }),
  topic({
    id: "selfreg.sleep_development",
    category: "self_regulation",
    title: "Çocuklukta uyku gelişimi",
    aliases: ["sleep development", "uyku gelişimi", "çocuklarda uyku süresi", "bebek uykusu", "gündüz uykusu", "yaşa göre uyku"],
    summary: "Uyku süresi, dağılımı, gündüz uykuları ve zamanlama çocukluk boyunca ortalama olarak değişir; bireysel farklılık geniştir.",
    details: [
      "Yaş grubu için önerilen süre aralıkları toplum düzeyi rehberidir ve tanı eşiği değildir.",
      "Aynı yaştaki çocuklarda ölçüm yöntemi, kültür, rutin ve bireysel gereksinimler farklı olabilir.",
    ],
    keywords: ["bebek", "çocuk", "gelişim", "yaş", "gündüz uykusu", "uyku süresi", "öneri"],
    claimIds: ["claim.sleep.development", "claim.sleep.guidance_boundary"],
    sourceIds: ["GALLAND_ET_AL_2012", "PARUTHI_ET_AL_2016"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Yaş ortalaması veya rehber aralığı tek çocukta bozukluk, gelişimsel gecikme ya da zorunlu uyku miktarı belirlemez.",
  }),
  topic({
    id: "cns.executive_models",
    category: "central_nervous_system",
    title: "Yürütücü işlev modelleri",
    aliases: ["executive function models", "birlik ve çeşitlilik", "unity and diversity", "yürütücü bileşenler", "ef modeli"],
    summary: "Yürütücü işlevler ortak bir kontrol yönü taşıyan fakat çalışma belleği, ketleyici kontrol ve bilişsel esneklik gibi kısmen ayrışan süreçler ailesidir.",
    details: [
      "Bileşenlerin ayrışma derecesi yaşa, görevlere ve istatistiksel modele göre değişebilir.",
      "Tek faktörlü model tek biyolojik mekanizma veya tek bir yetenek anlamına gelmez.",
    ],
    keywords: ["yürütücü", "birlik", "çeşitlilik", "faktör", "bileşen", "model"],
    claimIds: ["claim.ef.unity_diversity", "claim.ef.contextual_performance"],
    sourceIds: ["MIYAKE_ET_AL_2000", "KARR_ET_AL_2018", "DOEBEL_2020", "DIAMOND_2013"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Model yapısı tek çocuk için sabit kapasite, frontal-lob işlevi, tanı veya DNA geçerliği belirlemez.",
  }),
  topic({
    id: "cns.executive_development",
    category: "central_nervous_system",
    title: "Yürütücü işlevlerin gelişimi",
    aliases: ["executive function development", "yürütücü işlev gelişimi", "okul öncesi yürütücü işlev", "çocuklarda ef", "erken yürütücü işlev"],
    summary: "Yürütücü işlevler erken çocukluktan itibaren gelişir; bileşenler aynı hızda, doğrusal biçimde veya tek bir yaşta tamamlanmaz.",
    details: [
      "Erken görevler dikkat, dil, motor yanıt, bellek ve motivasyon taleplerini birlikte içerir.",
      "Grup eğilimleri bireysel olgunluk, gecikme veya yaşam boyu prognoz değildir.",
    ],
    keywords: ["gelişim", "erken çocukluk", "okul öncesi", "yaş", "olgunlaşma", "görev"],
    claimIds: ["claim.ef.development_not_uniform", "claim.ef.task_impurity"],
    sourceIds: ["GARON_ET_AL_2008", "HENDRY_ET_AL_2016", "DIAMOND_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Tek davranış veya puan gelişimsel gecikme, prefrontal olgunluk yaşı ya da kesin gelecek sonucu göstermez.",
  }),
  topic({
    id: "cns.working_memory_development",
    category: "central_nervous_system",
    title: "Çalışma belleğinin gelişimi",
    aliases: ["working memory development", "çalışma belleği gelişimi", "çocuklarda çalışma belleği", "erken çalışma belleği", "yaşa göre çalışma belleği"],
    summary: "Çalışma belleğiyle ilişkili depolama, güncelleme ve kontrol performansı çocukluk boyunca ortalama olarak değişir; görev ve alanlara göre farklılaşır.",
    details: [
      "Sözel ve görsel-uzamsal görevler aynı talepleri taşımaz.",
      "Yaşa göre grup modelleri bireysel kapasite eşiği veya zeka ölçümü değildir.",
    ],
    keywords: ["çalışma belleği", "gelişim", "sözel", "görsel uzamsal", "yaş", "kapasite"],
    claimIds: ["claim.working_memory.development", "claim.working_memory.short_term_distinction"],
    sourceIds: ["COWAN_2014", "GATHERCOLE_ET_AL_2004", "BADDELEY_2000"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Tek span puanı yaşa göre sabit kapasite, zeka, tanı veya gelecekteki okul başarısı değildir.",
  }),
  topic({
    id: "cns.working_memory_measurement",
    category: "central_nervous_system",
    title: "Çalışma belleğinin ölçümü",
    aliases: ["working memory measurement", "çalışma belleği ölçümü", "span görevi", "sayı dizisi", "basit span", "karmaşık span", "çalışma belleği testi"],
    summary: "Basit span, karmaşık span, güncelleme ve sözel ya da görsel-uzamsal görevler çalışma belleğinin farklı taleplerini örnekler.",
    details: [
      "Tek görev hedef süreç dışında dikkat, dil, hız, strateji ve motivasyon da gerektirir.",
      "Görev etkisinin güçlü olması bireysel fark ölçümünün otomatik olarak güvenilir olduğu anlamına gelmez.",
    ],
    keywords: ["ölçüm", "span", "sayı dizisi", "güncelleme", "görev saflığı", "güvenirlik"],
    claimIds: ["claim.working_memory.multimethod", "claim.ef.task_impurity"],
    sourceIds: ["ANDERSON_REIDY_2012", "HEDGE_ET_AL_2018", "TOPLAK_ET_AL_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Tek görev veya DNA puanı çalışma belleğinin tamamını, frontal-lob işlevini, tanıyı ya da zekayı ölçmez.",
  }),
  topic({
    id: "cns.attention",
    category: "central_nervous_system",
    title: "Dikkat",
    aliases: ["attention", "dikkat süreçleri", "dikkatini verme", "odaklanma", "dikkat kapasitesi"],
    summary: "Dikkat; uyarılma, yöneltme, seçme, sürdürme ve hedefle ilgili kontrol gibi kısmen ayrışan süreçler ailesidir.",
    details: [
      "Dikkat tek bir enerji, sabit özellik veya tek beyin bölgesi değildir.",
      "Göz teması, oturma süresi veya tek görev genel dikkatin doğrudan ölçümü değildir.",
    ],
    keywords: ["dikkat", "odak", "yöneltme", "seçme", "sürdürme", "kontrol"],
    claimIds: ["claim.attention.multicomponent", "claim.attention.no_behavior_proxy"],
    sourceIds: ["PETERSEN_POSNER_2012", "RUEDA_ET_AL_2004"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Davranış veya DNA puanı dikkat ağı, beyin bölgesi, tanı, zeka ya da değişmez dikkat kapasitesi göstermez.",
  }),
  topic({
    id: "cns.attention_networks",
    category: "central_nervous_system",
    title: "Dikkat ağları",
    aliases: ["attention networks", "dikkat ağı", "uyarılma ağı", "yöneltme ağı", "yürütücü dikkat ağı", "attention network test", "ant"],
    summary: "Dikkat ağı modelleri uyarılma, yöneltme ve yürütücü kontrol gibi işlevleri analitik olarak ayırır; gerçek görevlerde bu süreçler etkileşebilir.",
    details: [
      "Model yetişkin nörobilimi ağırlıklıdır; çocuk görevleri yaş ve güvenirlik açısından ayrıca değerlendirilir.",
      "Görev skoru belirli ağın ya da beyin bölgesinin bireysel işlevini doğrudan ölçmez.",
    ],
    keywords: ["dikkat ağı", "uyarılma ağı", "yöneltme", "yürütücü dikkat", "ant", "ağ"],
    claimIds: ["claim.attention.networks_interact", "claim.attention.networks_boundary"],
    sourceIds: ["PETERSEN_POSNER_2012", "RUEDA_ET_AL_2004"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Davranıştan, ANT skorundan veya DNA profilinden kişisel dikkat ağı ya da beyin bölgesi etkinliği çıkarılamaz.",
  }),
  topic({
    id: "cns.sustained_attention",
    category: "central_nervous_system",
    title: "Sürdürülen dikkat",
    aliases: ["sustained attention", "sürdürülmüş dikkat", "dikkati sürdürme", "uzun süre dikkat", "vigilance", "uyanıklık görevi"],
    summary: "Sürdürülen dikkat, hedefle ilgili işlemeyi zaman boyunca devam ettirme ve performans değişimini izleme taleplerini kapsar.",
    details: [
      "Performans çocukluk boyunca ortalama olarak değişir ve görev süresi ile yüküne duyarlıdır.",
      "Kaçırma, yanlış alarm, tepki süresi ve değişkenlik aynı ölçüm değildir.",
    ],
    keywords: ["sürdürme", "vigilance", "görev süresi", "kaçırma", "yanlış alarm", "değişkenlik"],
    claimIds: ["claim.sustained_attention.development", "claim.sustained_attention.task_load"],
    sourceIds: ["BETTS_ET_AL_2006", "FISHER_ET_AL_2013_ATTENTION"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Tek oturumdaki performans değişmez dikkat kapasitesi, isteksizlik, ADHD veya beyin ağı sonucu değildir.",
  }),
  topic({
    id: "cns.selective_attention",
    category: "central_nervous_system",
    title: "Seçici dikkat",
    aliases: ["selective attention", "seçici odaklanma", "dikkat dağıtıcıyı eleme", "ilgili bilgiyi seçme"],
    summary: "Seçici dikkat, hedefle ilgili bilgiyi önceliklendirirken ilgisiz girdinin etkisini bağlama göre yönetme süreçlerini kapsar.",
    details: [
      "Dikkat dağıtıcıya yönelmek her durumda seçici dikkat yetersizliği değildir.",
      "Uyaranın çekiciliği, yönerge, motivasyon ve görev yapısı sonucu etkileyebilir.",
    ],
    keywords: ["seçici", "dikkat dağıtıcı", "hedef", "uyaran", "öncelik", "filtreleme"],
    claimIds: ["claim.selective_attention.definition", "claim.selective_attention.context"],
    sourceIds: ["FISHER_ET_AL_2013_ATTENTION", "PETERSEN_POSNER_2012"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Tek davranış veya görev sonucu duyusal aşırı yüklenme, dikkat bozukluğu, biyolojik neden ya da tanı göstermez.",
  }),
  topic({
    id: "cns.attention_measurement",
    category: "central_nervous_system",
    title: "Dikkatin ölçümü",
    aliases: ["attention measurement", "dikkat ölçümü", "dikkat testi", "sürekli performans testi", "cpt", "tepki süresi değişkenliği", "ebeveyn dikkat ölçeği"],
    summary: "Dikkat görevleri, davranış derecelendirmeleri ve doğal ortam gözlemleri farklı bilgi düzeyleri sağlar; tek bir altın standart yoktur.",
    details: [
      "Laboratuvar görevi belirli koşuldaki performansı, dereceleme ise günlük bağlamlardaki gözlemi örnekler.",
      "Görev sonucu dikkat dışında hız, dil, motor yanıt, motivasyon ve stratejiden etkilenebilir.",
    ],
    keywords: ["ölçüm", "test", "cpt", "tepki süresi", "ölçek", "gözlem", "güvenirlik"],
    claimIds: ["claim.attention.measurement_multimethod", "claim.attention.no_behavior_proxy"],
    sourceIds: ["HEDGE_ET_AL_2018", "TOPLAK_ET_AL_2013", "FISHER_ET_AL_2013_ATTENTION"],
    evidenceLevel: "strong",
    ageScope: "mixed",
    claimBoundary: "Tek görev, anket, gözlem veya DNA alanı dikkat ağını, tanıyı, zekayı ya da kişisel biyolojik nedeni ölçmez.",
  }),
  topic({
    id: "cns.attention_development",
    category: "central_nervous_system",
    title: "Dikkatin gelişimi",
    aliases: ["attention development", "dikkat gelişimi", "çocuklarda dikkat", "bebeklerde dikkat", "yaşa göre dikkat", "erken dikkat"],
    summary: "Yöneltme, sürdürme, seçme ve yürütücü dikkat performansı çocukluk boyunca farklı hızlarda ve göreve duyarlı biçimde değişir.",
    details: [
      "Bebeklikte bakış süresi yetişkin tipi dikkat kapasitesi değildir.",
      "Yaş grubu eğilimleri tek çocuk için olgunluk, gecikme veya prognoz sonucu vermez.",
    ],
    keywords: ["gelişim", "bebek", "çocuk", "yaş", "bakış", "yöneltme", "yürütücü dikkat"],
    claimIds: ["claim.attention.development"],
    sourceIds: ["RUEDA_ET_AL_2004", "BETTS_ET_AL_2006", "FISHER_ET_AL_2013_ATTENTION"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Erken dikkat davranışı bireysel ADHD, beyin ağı, gelecekteki kapasite veya kesin gelişimsel sonuç değildir.",
  }),
  ...V5_CASE_BOUNDARY_TOPICS,
  ...V5_SIX_DOMAINS_TOPICS,
  ...V5_DEVELOPMENT_TOPICS,
  ...V5_COREGULATION_TOPICS,
])

export const DNA_CHAT_CATALOG_TOPIC_BY_ID = new Map(
  DNA_CHAT_CATALOG_TOPICS.map((entry) => [entry.id, entry]),
)
