import {
  DNA_CHAT_CATALOG_VERSION,
  type DnaChatCatalogClaim,
  type DnaChatCatalogRelation,
  type DnaChatCatalogSafetyRule,
  type DnaChatCatalogSource,
  type DnaChatCatalogTopic,
} from "./types"

function source(
  input: Omit<DnaChatCatalogSource, "version" | "sourceVerified" | "verifiedAt">,
): DnaChatCatalogSource {
  return Object.freeze({
    version: DNA_CHAT_CATALOG_VERSION,
    sourceVerified: true as const,
    verifiedAt: "2026-07-17",
    ...input,
  })
}

function topic(
  input: Omit<DnaChatCatalogTopic, "version" | "reviewStatus">,
): DnaChatCatalogTopic {
  return Object.freeze({
    version: DNA_CHAT_CATALOG_VERSION,
    reviewStatus: "source_verified_expert_pending" as const,
    ...input,
  })
}

function claim(
  input: Omit<DnaChatCatalogClaim, "version" | "safetyStatus" | "sourceVerified">,
): DnaChatCatalogClaim {
  return Object.freeze({
    version: DNA_CHAT_CATALOG_VERSION,
    safetyStatus: "safe" as const,
    sourceVerified: true as const,
    ...input,
  })
}

function relation(
  input: Omit<DnaChatCatalogRelation, "version" | "maxHops">,
): DnaChatCatalogRelation {
  return Object.freeze({
    version: DNA_CHAT_CATALOG_VERSION,
    maxHops: 1 as const,
    ...input,
  })
}

function safetyRule(
  input: Omit<DnaChatCatalogSafetyRule, "version">,
): DnaChatCatalogSafetyRule {
  return Object.freeze({ version: DNA_CHAT_CATALOG_VERSION, ...input })
}

/**
 * Source-verified subset of the V5 case/report-boundary pack. Source IDs are
 * derived only from evidence_map.refs; broad source_catalog.claims ranges are
 * intentionally not used as evidence mappings.
 */
export const V5_CASE_BOUNDARY_SOURCES: readonly DnaChatCatalogSource[] = Object.freeze([
  source({
    id: "AERA_APA_NCME_2014",
    title: "Standards for Educational and Psychological Testing",
    authors: "American Educational Research Association, American Psychological Association, & National Council on Measurement in Education",
    year: 2014,
    publication: "American Educational Research Association",
    publicationStatus: "consensus",
    studyType: "Konsensüs standardı",
    doi: null,
    pmid: null,
    url: "https://www.testingstandards.net/open-access-files.html",
    evidenceDomain: "assessment_validity_and_score_interpretation",
    ageScope: "all_ages",
    claimBoundary: "Genel test standardıdır; DNA'nın psikometrik geçerliğini veya belirli bir bireysel yorumu doğrulamaz.",
  }),
  source({
    id: "APA_ASSESSMENT_GUIDELINES_2020",
    title: "APA Guidelines for Psychological Assessment and Evaluation",
    authors: "American Psychological Association, APA Task Force on Psychological Assessment and Evaluation Guidelines",
    year: 2020,
    publication: "American Psychological Association",
    publicationStatus: "consensus",
    studyType: "Mesleki değerlendirme kılavuzu",
    doi: null,
    pmid: null,
    url: "https://www.apa.org/about/policy/guidelines-psychological-assessment-evaluation.pdf",
    evidenceDomain: "assessment_use_and_reporting",
    ageScope: "all_ages",
    claimBoundary: "Mesleki değerlendirme ilkeleri sunar; DNA için tanı, tedavi veya araç geçerliği kanıtı değildir.",
  }),
  source({
    id: "MOKKINK_ET_AL_2010_COSMIN",
    title: "The COSMIN study reached international consensus on taxonomy, terminology, and definitions of measurement properties for health-related patient-reported outcomes",
    authors: "Mokkink, L. B., Terwee, C. B., Patrick, D. L., et al.",
    year: 2010,
    publication: "Journal of Clinical Epidemiology, 63(7), 737-745",
    publicationStatus: "published",
    studyType: "Delphi ve konsensüs çalışması",
    doi: "10.1016/j.jclinepi.2010.02.006",
    pmid: null,
    url: "https://doi.org/10.1016/j.jclinepi.2010.02.006",
    evidenceDomain: "measurement_properties",
    ageScope: "all_ages",
    claimBoundary: "PROM terminolojisine odaklanır; DNA veya gözlemsel profil için doğrudan geçerlik sağlamaz.",
  }),
  source({
    id: "SHELDRICK_ET_AL_2020",
    title: "Comparative Accuracy of Developmental Screening Questionnaires",
    authors: "Sheldrick, R. C., Marakovitz, S., Garfinkel, D., Carter, A. S., & Perrin, E. C.",
    year: 2020,
    publication: "JAMA Pediatrics, 174(4), 366-374",
    publicationStatus: "published",
    studyType: "Tanısal doğruluk çalışması",
    doi: "10.1001/jamapediatrics.2019.6000",
    pmid: "32065615",
    url: "https://pubmed.ncbi.nlm.nih.gov/32065615/",
    evidenceDomain: "developmental_screening_accuracy",
    ageScope: "early_childhood",
    claimBoundary: "Gelişimsel tarama araçlarını karşılaştırır; pozitif sonucu tanıya veya DNA puanına dönüştürmez.",
    repairNote: "Kaynak paketteki yanlış PMID 32065601 yerine DOI ile eşleşen PMID 32065615 kullanıldı.",
  }),
  source({
    id: "LEEFLANG_ET_AL_2013",
    title: "Variation of a test's sensitivity and specificity with disease prevalence",
    authors: "Leeflang, M. M. G., Rutjes, A. W. S., Reitsma, J. B., Hooft, L., & Bossuyt, P. M. M.",
    year: 2013,
    publication: "CMAJ, 185(11), E537-E544",
    publicationStatus: "published",
    studyType: "Meta-epidemiyolojik yöntem çalışması",
    doi: "10.1503/cmaj.121286",
    pmid: "23798453",
    url: "https://pubmed.ncbi.nlm.nih.gov/23798453/",
    evidenceDomain: "diagnostic_accuracy_and_prevalence",
    ageScope: "all_ages",
    claimBoundary: "Tıbbi tanısal testlere dayanır; DNA için tanısal doğruluk, prevalans veya bireysel olasılık üretmez.",
  }),
  source({
    id: "DE_LOS_REYES_KAZDIN_2005",
    title: "Informant discrepancies in the assessment of childhood psychopathology: A critical review, theoretical framework, and recommendations for further study",
    authors: "De Los Reyes, A., & Kazdin, A. E.",
    year: 2005,
    publication: "Psychological Bulletin, 131(4), 483-509",
    publicationStatus: "published",
    studyType: "Eleştirel derleme",
    doi: "10.1037/0033-2909.131.4.483",
    pmid: "16060799",
    url: "https://pubmed.ncbi.nlm.nih.gov/16060799/",
    evidenceDomain: "multi_informant_discrepancy",
    ageScope: "childhood",
    claimBoundary: "Bilgi veren uyuşmazlığını bağlamsal olarak açıklar; tek bir kaynağın doğru olduğunu veya tanıyı göstermez.",
    repairNote: "Kaynak paketteki yanlış PMID 16060800 yerine DOI ile eşleşen PMID 16060799 kullanıldı.",
  }),
  source({
    id: "DE_LOS_REYES_ET_AL_2013",
    title: "Principles underlying the use of multiple informants' reports",
    authors: "De Los Reyes, A., Thomas, S. A., Goodman, K. L., & Kundey, S. M. A.",
    year: 2013,
    publication: "Annual Review of Clinical Psychology, 9, 123-149",
    publicationStatus: "published",
    studyType: "Anlatısal yöntem derlemesi",
    doi: "10.1146/annurev-clinpsy-050212-185617",
    pmid: "23140332",
    url: "https://pubmed.ncbi.nlm.nih.gov/23140332/",
    evidenceDomain: "multi_informant_assessment",
    ageScope: "childhood",
    claimBoundary: "Çoklu bilgi veren ilkelerini destekler; evrensel bir otomatik birleştirme algoritması vermez.",
    repairNote: "Kaynak paketteki yanlış PMID 23297733 yerine DOI ile eşleşen PMID 23140332 kullanıldı.",
  }),
  source({
    id: "KOTTNER_ET_AL_2011",
    title: "Guidelines for Reporting Reliability and Agreement Studies (GRRAS) were proposed",
    authors: "Kottner, J., Audigé, L., Brorson, S., et al.",
    year: 2011,
    publication: "Journal of Clinical Epidemiology, 64(1), 96-106",
    publicationStatus: "published",
    studyType: "Raporlama kılavuzu",
    doi: "10.1016/j.jclinepi.2010.03.002",
    pmid: "21130355",
    url: "https://pubmed.ncbi.nlm.nih.gov/21130355/",
    evidenceDomain: "reliability_and_agreement",
    ageScope: "all_ages",
    claimBoundary: "Güvenirlik ve uyumun raporlanmasını ayırır; belirli DNA puanlarının güvenirliğini göstermez.",
  }),
  source({
    id: "DE_VET_ET_AL_2006",
    title: "Minimal changes in health status questionnaires: Distinction between minimally detectable change and minimally important change",
    authors: "de Vet, H. C. W., Terwee, C. B., Ostelo, R. W., Beckerman, H., Knol, D. L., & Bouter, L. M.",
    year: 2006,
    publication: "Health and Quality of Life Outcomes, 4, 54",
    publicationStatus: "published",
    studyType: "Yöntemsel makale",
    doi: "10.1186/1477-7525-4-54",
    pmid: "16925807",
    url: "https://pubmed.ncbi.nlm.nih.gov/16925807/",
    evidenceDomain: "measurement_change",
    ageScope: "all_ages",
    claimBoundary: "Değişim kavramlarını ayırır; DNA için araç-özel eşik veya terapi etkisi sağlamaz.",
  }),
  source({
    id: "JACOBSON_TRUAX_1991",
    title: "Clinical significance: A statistical approach to defining meaningful change in psychotherapy research",
    authors: "Jacobson, N. S., & Truax, P.",
    year: 1991,
    publication: "Journal of Consulting and Clinical Psychology, 59(1), 12-19",
    publicationStatus: "published",
    studyType: "Klasik yöntem makalesi",
    doi: "10.1037/0022-006X.59.1.12",
    pmid: null,
    url: "https://doi.org/10.1037/0022-006X.59.1.12",
    evidenceDomain: "reliable_and_clinically_significant_change",
    ageScope: "adult_weighted",
    claimBoundary: "Tarihsel değişim yöntemidir; çocuk DNA puanlarına araç-özel norm, hata ve geçerlik kanıtı olmadan uygulanamaz.",
  }),
  source({
    id: "SPEER_1992",
    title: "Clinically significant change: Jacobson and Truax (1991) revisited",
    authors: "Speer, D. C.",
    year: 1992,
    publication: "Journal of Consulting and Clinical Psychology, 60(3), 402-408",
    publicationStatus: "published",
    studyType: "Yöntemsel eleştiri",
    doi: "10.1037/0022-006X.60.3.402",
    pmid: null,
    url: "https://doi.org/10.1037/0022-006X.60.3.402",
    evidenceDomain: "reliable_change_methodology",
    ageScope: "adult_weighted",
    claimBoundary: "Tarihsel yöntem tartışmasıdır; güncel DNA aracında güvenilir veya anlamlı değişimi doğrulamaz.",
  }),
  source({
    id: "PUTNICK_BORNSTEIN_2016",
    title: "Measurement Invariance Conventions and Reporting: The State of the Art and Future Directions for Psychological Research",
    authors: "Putnick, D. L., & Bornstein, M. H.",
    year: 2016,
    publication: "Developmental Review, 41, 71-90",
    publicationStatus: "published",
    studyType: "Yöntem derlemesi",
    doi: "10.1016/j.dr.2016.06.004",
    pmid: "27942093",
    url: "https://pubmed.ncbi.nlm.nih.gov/27942093/",
    evidenceDomain: "measurement_invariance",
    ageScope: "developmental",
    claimBoundary: "Gruplar arası ölçüm eşdeğerliği ilkelerini destekler; belirli kültürel farkı veya bireysel sonucu açıklamaz.",
  }),
  source({
    id: "ROHRER_2018",
    title: "Thinking Clearly About Correlations and Causation: Graphical Causal Models for Observational Data",
    authors: "Rohrer, J. M.",
    year: 2018,
    publication: "Advances in Methods and Practices in Psychological Science, 1(1), 27-42",
    publicationStatus: "published",
    studyType: "Yöntemsel öğretici makale",
    doi: "10.1177/2515245917745629",
    pmid: null,
    url: "https://doi.org/10.1177/2515245917745629",
    evidenceDomain: "causal_inference",
    ageScope: "all_ages",
    claimBoundary: "Nedensel varsayımları açıklar; gözlemsel vaka verisinden kesin neden üretmez.",
  }),
  source({
    id: "DOMBROWSKI_ET_AL_2022",
    title: "Beyond the rhetoric of evidence-based assessment: A framework for critical thinking in clinical practice",
    authors: "Dombrowski, S. C., McGill, R. J., Farmer, R. L., Kranzler, J. H., & Canivez, G. L.",
    year: 2022,
    publication: "School Psychology Review, 51(6), 771-784",
    publicationStatus: "published",
    studyType: "Eleştirel anlatısal inceleme",
    doi: "10.1080/2372966X.2021.1960126",
    pmid: null,
    url: "https://doi.org/10.1080/2372966X.2021.1960126",
    evidenceDomain: "evidence_based_assessment",
    ageScope: "childhood",
    claimBoundary: "Eleştirel değerlendirme çerçevesidir; tek profil farkını sendrom, neden veya biyolojik mekanizma yapmaz.",
  }),
  source({
    id: "BAUM_ET_AL_2018",
    title: "Communication is key: The utility of a revised neuropsychological report format",
    authors: "Baum, K. T., von Thomsen, C., Elam, M., et al.",
    year: 2018,
    publication: "The Clinical Neuropsychologist, 32(3), 345-367",
    publicationStatus: "published",
    studyType: "Kalite geliştirme çalışması",
    doi: "10.1080/13854046.2017.1413208",
    pmid: "29243544",
    url: "https://pubmed.ncbi.nlm.nih.gov/29243544/",
    evidenceDomain: "report_communication",
    ageScope: "mixed",
    claimBoundary: "Rapor biçiminin kullanılabilirliğini destekler; sade dil klinik doğruluk veya uzun dönem çocuk sonucu garantisi değildir.",
  }),
  source({
    id: "WHO_ICF_2001",
    title: "International Classification of Functioning, Disability and Health",
    authors: "World Health Organization",
    year: 2001,
    publication: "World Health Organization",
    publicationStatus: "consensus",
    studyType: "Uluslararası sınıflandırma ve kavramsal çerçeve",
    doi: null,
    pmid: null,
    url: "https://www.who.int/standards/classifications/international-classification-of-functioning-disability-and-health",
    evidenceDomain: "function_activity_participation",
    ageScope: "all_ages",
    claimBoundary: "İşlev, aktivite, katılım ve bağlamı ayırır; DNA alanlarını veya biyolojik mekanizmayı doğrulamaz.",
  }),
  source({
    id: "NIST_AI_RMF_2023",
    title: "Artificial Intelligence Risk Management Framework (AI RMF 1.0)",
    authors: "National Institute of Standards and Technology",
    year: 2023,
    publication: "NIST AI 100-1, U.S. Department of Commerce",
    publicationStatus: "consensus",
    studyType: "Yapay zekâ risk yönetimi çerçevesi",
    doi: "10.6028/NIST.AI.100-1",
    pmid: null,
    url: "https://doi.org/10.6028/NIST.AI.100-1",
    evidenceDomain: "ai_risk_governance",
    ageScope: "all_ages",
    claimBoundary: "Genel AI yönetişim çerçevesidir; DNA Asistanı'nın klinik performansını veya doğruluk oranını göstermez.",
  }),
  source({
    id: "VASEY_ET_AL_2022",
    title: "Reporting guideline for the early-stage clinical evaluation of decision support systems driven by artificial intelligence: DECIDE-AI",
    authors: "Vasey, B., Nagendran, M., Campbell, B., et al.",
    year: 2022,
    publication: "Nature Medicine, 28, 924-933",
    publicationStatus: "consensus",
    studyType: "Konsensüs ve raporlama kılavuzu",
    doi: "10.1038/s41591-022-01772-9",
    pmid: "35585198",
    url: "https://pubmed.ncbi.nlm.nih.gov/35585198/",
    evidenceDomain: "clinical_ai_evaluation",
    ageScope: "all_ages",
    claimBoundary: "Klinik AI değerlendirmesinin raporlanmasını destekler; üretken metni otomatik olarak geçerli veya güvenli yapmaz.",
    repairNote: "Kaynak paketteki yanlış PMID 35508717 yerine DOI ile eşleşen PMID 35585198 kullanıldı.",
  }),
])

export const V5_CASE_BOUNDARY_TOPICS: readonly DnaChatCatalogTopic[] = Object.freeze([
  topic({
    id: "case.interpretation_boundaries",
    category: "self_regulation",
    title: "Vaka ve rapor yorum sınırları",
    aliases: ["vaka yorum sınırı", "rapor yorum sınırı", "güvenli rapor yorumu", "veri yorum karar zinciri"],
    summary: "Vaka ve rapor yorum sınırları, verinin hangi amaç ve koşullarda hangi anlamı taşıyabileceğini ve hangi çıkarımların desteklenmediğini belirleyen yatay bir güvenlik katmanıdır.",
    details: [
      "Bu konu özel bir vaka veya tanı alanı değil, bütün DNA alanlarına uygulanan genel teori ve ürün sınırıdır.",
      "Veri, puan, yorum, hipotez ve karar aynı düzey değildir.",
    ],
    keywords: ["vaka", "rapor", "yorum", "sınır", "amaç", "belirsizlik"],
    claimIds: ["claim.case.interpretation.intended_use"],
    sourceIds: ["AERA_APA_NCME_2014", "APA_ASSESSMENT_GUIDELINES_2020"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Genel yorum ilkeleri seçili raporda olmayan klinik bilgiyi, tanıyı veya mekanizmayı üretmez.",
  }),
  topic({
    id: "case.validity_reliability",
    category: "self_regulation",
    title: "Geçerlik, güvenirlik ve uyum",
    aliases: ["geçerlik", "güvenirlik", "güvenilirlik", "uyum", "cronbach alfa", "iç tutarlılık"],
    summary: "Geçerlik belirli yorum ve kullanımın kanıtını; güvenirlik puan tutarlılığını; uyum ise puanların yakınlığını ele alır.",
    details: ["Bu üç kavram birbirinin yerine geçmez.", "Yüksek iç tutarlılık tek başına yapı geçerliği veya klinik yarar değildir."],
    keywords: ["validity", "reliability", "agreement", "alfa", "ölçüm özelliği"],
    claimIds: [
      "claim.case.validity.use_specific",
      "claim.case.reliability.agreement_distinction",
      "claim.case.validity.alpha_limit",
    ],
    sourceIds: ["AERA_APA_NCME_2014", "MOKKINK_ET_AL_2010_COSMIN", "KOTTNER_ET_AL_2011"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "Genel ölçüm ilkeleri DNA'nın geçerli, tanısal veya biyolojik ölçüm olduğunu kanıtlamaz.",
  }),
  topic({
    id: "case.measurement_uncertainty",
    category: "self_regulation",
    title: "Ölçüm belirsizliği",
    aliases: ["ölçüm hatası", "standart ölçüm hatası", "güven aralığı", "puan belirsizliği"],
    summary: "Gözlenen her puan ölçüm ve örnekleme belirsizliği içerir; nokta puan kesin gerçek değer gibi sunulamaz.",
    details: ["Araç-özel hata verisi yoksa yapay güven aralığı üretilemez.", "Güven aralığı tanı olasılığı değildir."],
    keywords: ["hata", "belirsizlik", "sem", "güven aralığı", "nokta puan"],
    claimIds: ["claim.case.uncertainty.score", "claim.case.uncertainty.no_fabricated_interval"],
    sourceIds: ["AERA_APA_NCME_2014", "MOKKINK_ET_AL_2010_COSMIN"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "Araç-özel parametre olmadan bireysel sayısal belirsizlik veya olasılık hesaplanmaz.",
  }),
  topic({
    id: "case.score_interpretation",
    category: "self_regulation",
    title: "Puan, norm ve kesme yorumu",
    aliases: [
      "standart puan",
      "ham puan",
      "yüzdelik",
      "persentil",
      "norm grubu",
      "kesme puanı",
      "norm referanslı yorum",
      "ölçüt referanslı yorum",
    ],
    summary: "Puanlar yalnız tanımlı araç, norm, yaş ve kullanım amacı içinde göreli bilgi sağlar.",
    details: ["Yüzdelik becerinin yüzde miktarı değildir.", "Kesme puanı doğal biyolojik sınır veya tanı değildir."],
    keywords: ["puan", "norm", "yüzdelik", "persentil", "eşik", "cut-off"],
    claimIds: [
      "claim.case.score.percentile",
      "claim.case.score.cut_boundary",
      "claim.case.score.norm_criterion_distinction",
    ],
    sourceIds: ["AERA_APA_NCME_2014"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Normatif konum neden, bozukluk, mekanizma veya bütünsel kapasite değildir.",
  }),
  topic({
    id: "case.screening_diagnosis",
    category: "self_regulation",
    title: "Tarama ve tanısal değerlendirme",
    aliases: ["tarama", "screening", "tanısal değerlendirme", "tanı dışlama", "pozitif tarama"],
    summary: "Tarama olası gereksinimi belirleyip ileri değerlendirmeyi yönlendirir; tanı koyma veya dışlamanın eş anlamlısı değildir.",
    details: ["Pozitif veya negatif sonuç kesin klinik durum değildir.", "Tek ölçek sonucu tanısal sürecin yerine geçmez."],
    keywords: ["tarama", "tanı", "duyarlılık", "özgüllük", "ileri değerlendirme"],
    claimIds: [
      "claim.case.screening.not_diagnosis",
      "claim.case.screening.single_score",
      "claim.case.screening.assessment_distinction",
      "claim.case.screening.ppv_prevalence",
    ],
    sourceIds: ["AERA_APA_NCME_2014", "APA_ASSESSMENT_GUIDELINES_2020", "SHELDRICK_ET_AL_2020"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "DNA tanısal araç, tarama doğruluk testi veya tanı olasılığı üreticisi değildir.",
  }),
  topic({
    id: "case.multi_informant",
    category: "self_regulation",
    title: "Çoklu bilgi veren değerlendirmesi",
    aliases: ["çoklu bilgi veren", "ebeveyn öğretmen farkı", "bilgi veren uyuşmazlığı", "informant discrepancy", "proxy bildirim"],
    summary: "Ebeveyn, öğretmen, çocuk ve terapist farklı bağlamlara ve gözlem fırsatlarına erişir; bildirimleri özdeş veri değildir.",
    details: ["Uyuşmazlık hata, bağlamsal özgüllük veya her ikisini yansıtabilir.", "Kaynaklar mekanik olarak ortalanmamalıdır."],
    keywords: ["ebeveyn", "öğretmen", "çocuk bildirimi", "uyuşmazlık", "perspektif"],
    claimIds: ["claim.case.informants.perspectives", "claim.case.informants.no_mechanical_average"],
    sourceIds: ["DE_LOS_REYES_KAZDIN_2005", "DE_LOS_REYES_ET_AL_2013", "TOPLAK_ET_AL_2013"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "Tek bir bilgi veren otomatik olarak doğru ilan edilmez; uyuşmazlık tanı veya neden değildir.",
  }),
  topic({
    id: "case.contextual_variability",
    category: "self_regulation",
    title: "Bağlamsal değişkenlik",
    aliases: ["bağlamsal değişkenlik", "ortama göre değişim", "ev okul farkı", "ekolojik bağlam"],
    summary: "Davranış ve performans ortam, talep, destek, zamanlama ve gözlem koşullarıyla değişebilir.",
    details: ["Bağlam farkı rol yapma veya tutarsızlık kanıtı değildir.", "Aynı davranış birden fazla açıklamayla uyumlu olabilir."],
    keywords: ["bağlam", "ortam", "ev", "okul", "talep", "destek"],
    claimIds: ["claim.case.context.variability"],
    sourceIds: ["DE_LOS_REYES_KAZDIN_2005", "DE_LOS_REYES_ET_AL_2013"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "Bağlamsal örüntü tek neden, sabit kapasite veya biyolojik durum değildir.",
  }),
  topic({
    id: "case.capacity_performance",
    category: "self_regulation",
    title: "Kapasite, performans ve katılım",
    aliases: ["kapasite performans farkı", "günlük yaşam karşılığı", "aktivite ve katılım", "işlevsel karşılık"],
    summary: "Kapasite yapılandırılmış koşulda yapılabileni, performans günlük bağlamda yapılanı; aktivite ve katılım ise yaşam görevlerine dahil olmayı betimler.",
    details: ["Tek oturum bütün günlük işlevi temsil etmez.", "İşlevsel betimleme biyolojik mekanizma göstermez."],
    keywords: ["kapasite", "performans", "aktivite", "katılım", "günlük yaşam"],
    claimIds: ["claim.case.capacity.performance"],
    sourceIds: ["WHO_ICF_2001", "TOPLAK_ET_AL_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Görev veya ölçek sonucu bütün ortamlardaki sabit kapasiteye genellenemez.",
  }),
  topic({
    id: "case.change_interpretation",
    category: "self_regulation",
    title: "Tekrarlı ölçüm ve değişim yorumu",
    aliases: ["puan değişimi", "ilerleme gerileme", "minimal saptanabilir değişim", "mdc", "terapi etkisi"],
    summary: "İki zaman noktası arasındaki fark, ölçüm hatası ve koşul değişkenleri incelenmeden gerçek değişim sayılamaz.",
    details: ["Saptanabilir değişim ile kişi açısından önemli değişim farklıdır.", "Puan farkı tek başına müdahale etkisini kanıtlamaz."],
    keywords: ["değişim", "tekrar ölçüm", "mdc", "mic", "uygulama etkisi", "regresyon"],
    claimIds: [
      "claim.case.change.error",
      "claim.case.change.not_treatment_effect",
      "claim.case.change.regression_to_mean",
    ],
    sourceIds: ["MOKKINK_ET_AL_2010_COSMIN", "KOTTNER_ET_AL_2011", "DE_VET_ET_AL_2006", "FISHER_ET_AL_2018"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Araç-özel hata ve duyarlılık kanıtı olmadan ilerleme, gerileme veya tedavi etkisi ilan edilmez.",
  }),
  topic({
    id: "case.development_culture",
    category: "self_regulation",
    title: "Gelişimsel, kültürel ve dilsel uygunluk",
    aliases: [
      "gelişimsel uygunluk",
      "yaş eşdeğeri",
      "ölçüm değişmezliği",
      "kültürel adalet",
      "kültürel uyarlama",
      "çeviri geçerliği",
    ],
    summary: "Yaş, dil, kültür, norm ve erişilebilirlik yorumun hangi gruba ve kullanıma taşınabileceğini sınırlar.",
    details: ["Yaş eşdeğeri bütünsel gelişim yaşı değildir.", "Çeviri, kavramsal eşdeğerlik veya ölçüm değişmezliğini tek başına sağlamaz."],
    keywords: ["yaş", "gelişim", "kültür", "dil", "uyarlama", "değişmezlik"],
    claimIds: [
      "claim.case.development.age_equivalent",
      "claim.case.culture.translation",
      "claim.case.culture.invariance",
    ],
    sourceIds: ["AERA_APA_NCME_2014", "PUTNICK_BORNSTEIN_2016", "WHO_ICF_2001"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Yaş veya grup bilgisi tek başına bireysel gelişim düzeyi, bozukluk veya neden değildir.",
  }),
  topic({
    id: "case.causal_biological_boundary",
    category: "self_regulation",
    title: "Nedensellik ve biyolojik çıkarım sınırı",
    aliases: ["nedensellik", "biyolojik mekanizma çıkarımı", "beyin bölgesi çıkarımı", "vagus çıkarımı", "travma çıkarımı"],
    summary: "Korelasyon, puan veya gözlem tek başına neden, yön, travma öyküsü, beyin bölgesi ya da biyolojik mekanizma göstermez.",
    details: ["Alternatif açıklamalar görünür tutulmalıdır.", "Grup araştırması bireysel deterministik sonuç üretmez."],
    keywords: ["neden", "korelasyon", "beyin", "vagus", "hormon", "travma", "mekanizma"],
    claimIds: ["claim.case.causality.correlation", "claim.case.biological.no_inference"],
    sourceIds: ["AERA_APA_NCME_2014", "APA_ASSESSMENT_GUIDELINES_2020", "FISHER_ET_AL_2018", "ROHRER_2018", "DOMBROWSKI_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Genel kuramsal yakınlık bireysel biyolojik veya travmatik mekanizma ölçümü değildir.",
  }),
  topic({
    id: "case.report_communication",
    category: "self_regulation",
    title: "Güvenli rapor iletişimi",
    aliases: [
      "rapor dili",
      "veri yorum hipotez",
      "veri",
      "yorum",
      "hipotez",
      "anlaşılır rapor",
      "güçlü yön raporu",
      "damgalamayan dil",
    ],
    summary: "Rapor dili veri, yorum, hipotez, sınırlılık ve öneriyi ayırmalı; kesinlik düzeyi kanıtla orantılı olmalıdır.",
    details: ["Düz dil ve güçlü yönler anlaşılabilirliği destekleyebilir.", "Kısalık kritik belirsizlikleri veya eksik veriyi silmemelidir."],
    keywords: ["rapor", "iletişim", "düz dil", "hipotez", "sınırlılık", "güçlü yön"],
    claimIds: ["claim.case.report.layers", "claim.case.report.accessible"],
    sourceIds: ["AERA_APA_NCME_2014", "APA_ASSESSMENT_GUIDELINES_2020", "BAUM_ET_AL_2018", "WHO_ICF_2001"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Anlaşılır biçim klinik geçerlik, doğruluk veya tedavi önerisi sağlamaz.",
  }),
  topic({
    id: "case.ai_oversight",
    category: "self_regulation",
    title: "AI destekli raporlamada insan denetimi",
    aliases: [
      "ai raporu",
      "ai destekli özet",
      "uzman raporu",
      "yapay zeka raporu",
      "insan denetimi",
      "kaynak izlenebilirliği",
      "otomasyon yanlılığı",
    ],
    summary: "AI destekli metin, kaynak ve veri doğru görünse bile otomatik olarak klinik olarak geçerli değildir; insan denetimi ve kaynak izlenebilirliği gerekir.",
    details: [
      "İnsan denetimi veri yeterliğini, iddia-kaynak uyumunu ve sınır ihlalini kapsar.",
      "Kullanıcı yanıtı dahili reasoning izi, kural kimliği, audit içeriği veya gizli eşik açığa çıkarmaz.",
    ],
    keywords: ["ai", "yapay zeka", "denetim", "kaynak", "izlenebilirlik", "güven"],
    claimIds: [
      "claim.case.ai.not_clinically_valid",
      "claim.case.ai.human_oversight",
      "claim.case.ai.confidence_boundary",
    ],
    sourceIds: ["NIST_AI_RMF_2023", "VASEY_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "Yönetişim ilkeleri DNA Asistanı'nın doğruluk oranı, klinik geçerliği veya bireysel karar yetkisi değildir.",
  }),
])

export const V5_CASE_BOUNDARY_CLAIMS: readonly DnaChatCatalogClaim[] = Object.freeze([
  claim({
    id: "claim.case.interpretation.intended_use",
    topicId: "case.interpretation_boundaries",
    text: "Vaka verisinin anlamı, değerlendirme amacı ve kullanım sınırı belirtilmeden güvenli biçimde yorumlanamaz.",
    detail: "Aynı veri tarama, betimleme, izlem veya araştırma gibi farklı amaçlarda farklı kanıt gerektirir; amaç aracın sağlayamadığı tanı ya da mekanizma çıkarımını meşrulaştırmaz.",
    sourceIds: ["AERA_APA_NCME_2014", "APA_ASSESSMENT_GUIDELINES_2020"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "product_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.validity.use_specific",
    topicId: "case.validity_reliability",
    text: "Geçerlik, aracın değişmez etiketi değil; belirli amaç için yapılan puan yorumunu ve kullanımını destekleyen kanıt bütünüdür.",
    detail: "Bir kullanım için yeterli kanıt başka yaş, dil, bağlam veya karar amacı için otomatik olarak yeterli değildir.",
    sourceIds: ["AERA_APA_NCME_2014", "APA_ASSESSMENT_GUIDELINES_2020", "MOKKINK_ET_AL_2010_COSMIN"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "definition",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.reliability.agreement_distinction",
    topicId: "case.validity_reliability",
    text: "Güvenirlik bireyleri ayırma tutarlılığıyla, uyum ise puanların ne kadar yakın olduğuyla ilgilidir; aynı kavram değildir.",
    detail: "Yüksek korelasyon mutlak uyumu garanti etmez ve kullanılan istatistik yorum sınırını değiştirir.",
    sourceIds: ["MOKKINK_ET_AL_2010_COSMIN", "KOTTNER_ET_AL_2011"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "definition",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.validity.alpha_limit",
    topicId: "case.validity_reliability",
    text: "Yüksek iç tutarlılık tek başına tek boyutluluk, yapı geçerliği veya klinik yarar göstermez.",
    detail: "Bir alfa katsayısı tanısal doğruluğu, biyolojik bütünlüğü veya belirli bir yorumun geçerliğini kanıtlamaz.",
    sourceIds: ["AERA_APA_NCME_2014", "MOKKINK_ET_AL_2010_COSMIN", "KOTTNER_ET_AL_2011"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "misconception_correction",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.uncertainty.score",
    topicId: "case.measurement_uncertainty",
    text: "Her gözlenen puan ölçüm ve örnekleme belirsizliği içerir; tek puan kesin gerçek değer gibi sunulmamalıdır.",
    detail: "Belirsizlik, puanın bağlam ve diğer veri kaynaklarıyla birlikte yorumlanmasını gerektirir.",
    sourceIds: ["AERA_APA_NCME_2014", "MOKKINK_ET_AL_2010_COSMIN"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "measurement_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.uncertainty.no_fabricated_interval",
    topicId: "case.measurement_uncertainty",
    text: "Araç-özel standart hata verisi yoksa yapay bir güven aralığı veya bireysel doğruluk olasılığı üretilmemelidir.",
    detail: "Genel yöntem bilgisi, DNA için sayısal hata parametresi yerine kullanılamaz.",
    sourceIds: ["AERA_APA_NCME_2014", "MOKKINK_ET_AL_2010_COSMIN"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "product_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.score.percentile",
    topicId: "case.score_interpretation",
    text: "Yüzdelik sıra uygun norm grubundaki göreli konumu gösterir; becerinin yüzde miktarı değildir.",
    detail: "Yüzdelikler eşit aralıklı değildir ve normun güncelliği ile temsiliyeti yorumu sınırlar.",
    sourceIds: ["AERA_APA_NCME_2014"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "misconception_correction",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.score.cut_boundary",
    topicId: "case.score_interpretation",
    text: "Kesme puanı sürekli dağılım üzerindeki karar kuralıdır; doğal biyolojik sınır veya tanı değildir.",
    detail: "Eşiğin iki yanındaki yakın puanlar kökten farklı çocuk grupları gibi sunulmamalıdır.",
    sourceIds: ["AERA_APA_NCME_2014"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "misconception_correction",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.score.norm_criterion_distinction",
    topicId: "case.score_interpretation",
    text: "Norm referanslı yorum kişiyi tanımlı norm grubundaki göreli konumuna göre; ölçüt referanslı yorum ise önceden tanımlanmış görev veya beceri ölçütüne göre açıklar.",
    detail: "İki yorum türü aynı değildir; kullanılan norm, ölçüt, yaş ve kullanım amacı açıkça belirtilmelidir.",
    sourceIds: ["AERA_APA_NCME_2014"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "definition",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.screening.not_diagnosis",
    topicId: "case.screening_diagnosis",
    text: "Tarama olası gereksinimi belirleyip ileri değerlendirmeyi yönlendirir; pozitif sonuç tanı değildir.",
    detail: "Yanlış pozitif ve yanlış negatif sonuçlar olabilir; doğruluk araç, eşik, örneklem ve referans standarda bağlıdır.",
    sourceIds: ["SHELDRICK_ET_AL_2020", "AERA_APA_NCME_2014"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "misconception_correction",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.screening.assessment_distinction",
    topicId: "case.screening_diagnosis",
    text: "Tarama ile tanısal değerlendirme aynı süreç değildir: tarama ileri inceleme gereksinimini sınıflar, tanısal değerlendirme ise çok kaynaklı ve yetkili klinik inceleme gerektirir.",
    detail: "Pozitif tarama sonucu tanı değildir; negatif sonuç da kapsamlı tanısal sürecin yerine geçmez.",
    sourceIds: ["AERA_APA_NCME_2014", "APA_ASSESSMENT_GUIDELINES_2020", "SHELDRICK_ET_AL_2020"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "definition",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.screening.ppv_prevalence",
    topicId: "case.screening_diagnosis",
    text: "Pozitif yordayıcı değer, duyarlılık ve özgüllüğün yanında değerlendirilen durumun taban oranına yani prevalansına bağlıdır.",
    detail: "Prevalans değiştiğinde pozitif sonuçlar içindeki gerçek ve yanlış pozitiflerin oranı değişebilir; bir araştırmadaki değer başka popülasyona aynen taşınamaz.",
    sourceIds: ["LEEFLANG_ET_AL_2013", "SHELDRICK_ET_AL_2020"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "association",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.screening.single_score",
    topicId: "case.screening_diagnosis",
    text: "Tek bir ölçek veya DNA sonucu gelişimsel ya da psikiyatrik tanı koymak veya dışlamak için yeterli değildir.",
    detail: "Tanısal süreç mesleki yetki, başvuru sorusu ve çok bileşenli değerlendirme gerektirir.",
    sourceIds: ["AERA_APA_NCME_2014", "APA_ASSESSMENT_GUIDELINES_2020", "SHELDRICK_ET_AL_2020"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "product_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.case.informants.perspectives",
    topicId: "case.multi_informant",
    text: "Ebeveyn, öğretmen, çocuk ve terapist verileri aynı olguyu aynı perspektiften ölçmez.",
    detail: "Bilgi veren uyuşmazlığı bağlam, gözlem fırsatı, yöntem farkı, yanlılık veya bunların birleşimini yansıtabilir.",
    sourceIds: ["DE_LOS_REYES_KAZDIN_2005", "DE_LOS_REYES_ET_AL_2013", "TOPLAK_ET_AL_2013"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "association",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.case.informants.no_mechanical_average",
    topicId: "case.multi_informant",
    text: "Çoklu bilgi veren verileri mekanik olarak ortalanmamalı; her kaynağın sorusu, bağlamı ve gözlem erişimi açıklanmalıdır.",
    detail: "Hangi kaynağın daha uygun olduğu kullanım amacına göre değişebilir; tek evrensel ağırlıklandırma algoritması yoktur.",
    sourceIds: ["DE_LOS_REYES_KAZDIN_2005", "DE_LOS_REYES_ET_AL_2013", "TOPLAK_ET_AL_2013"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "measurement_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.context.variability",
    topicId: "case.contextual_variability",
    text: "Farklı ortamlarda farklı davranış görülmesi tek başına hata veya rol yapma değil, bağlamsal özgüllük de olabilir.",
    detail: "Ortam talebi, destek, zamanlama ve gözlem fırsatı ayrı ayrı görünür kılınmalıdır.",
    sourceIds: ["DE_LOS_REYES_KAZDIN_2005", "DE_LOS_REYES_ET_AL_2013"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "association",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.case.capacity.performance",
    topicId: "case.capacity_performance",
    text: "Yapılandırılmış koşuldaki kapasite ile günlük bağlamdaki performans ve katılım aynı veri düzeyi değildir.",
    detail: "Performans görevi ile günlük yaşam derecelendirmesinin ayrışması beklenebilir; tek oturum bütün günlük işlevi temsil etmez.",
    sourceIds: ["WHO_ICF_2001", "TOPLAK_ET_AL_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.case.change.error",
    topicId: "case.change_interpretation",
    text: "İki zaman noktası arasındaki ham puan farkı, ölçüm hatası ve doğal değişkenlik dikkate alınmadan gerçek değişim sayılmaz.",
    detail: "Saptanabilir değişim ile çocuk veya aile açısından önemli değişim ayrı kavramlardır.",
    sourceIds: ["MOKKINK_ET_AL_2010_COSMIN", "KOTTNER_ET_AL_2011", "DE_VET_ET_AL_2006"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "measurement_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.change.not_treatment_effect",
    topicId: "case.change_interpretation",
    text: "DNA puanındaki değişim tek başına ilerleme, gerileme veya terapi etkisi kanıtlamaz.",
    detail: "Ölçüm hatası, uygulama etkisi, gelişim, yorgunluk, bilgi kaynağı ve bağlam değişikliği alternatif açıklamalardır.",
    sourceIds: ["AERA_APA_NCME_2014", "KOTTNER_ET_AL_2011", "FISHER_ET_AL_2018"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "product_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.case.change.regression_to_mean",
    topicId: "case.change_interpretation",
    text: "Uç bir ilk puanı izleyen ölçüm, gerçek değişim olmasa da ortalamaya yaklaşabilir; bu ortalamaya regresyon özellikle uç puanla seçilen vakalarda iyileşme izlenimi yaratabilir.",
    detail: "İkinci puanın daha ortalama görünmesi tek başına gelişim, gerileme veya müdahale etkisi değildir; ölçüm hatası ve karşılaştırılabilir koşullar birlikte incelenmelidir.",
    sourceIds: ["JACOBSON_TRUAX_1991", "SPEER_1992", "AERA_APA_NCME_2014"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "association",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.development.age_equivalent",
    topicId: "case.development_culture",
    text: "Yaş eşdeğeri çocuğun bütün gelişiminin o yaşta olduğunu göstermez.",
    detail: "Varsa yalnız ilgili test ve alt alanla sınırlı bir dönüşümdür; genel gelişim yaşı veya neden değildir.",
    sourceIds: ["AERA_APA_NCME_2014"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "misconception_correction",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.culture.translation",
    topicId: "case.development_culture",
    text: "Bir formun çevrilmesi kavramsal eşdeğerlik, norm uygunluğu veya kültürel geçerliği otomatik olarak sağlamaz.",
    detail: "Hedef dil ve grupta içerik, yanıt süreçleri ve psikometrik özellikler ayrıca incelenmelidir.",
    sourceIds: ["PUTNICK_BORNSTEIN_2016", "AERA_APA_NCME_2014"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "misconception_correction",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.culture.invariance",
    topicId: "case.development_culture",
    text: "Ölçüm değişmezliği ile kültürel adalet aynı kavram değildir; değişmezlik karşılaştırılabilir ölçümü sınarken kültürel adalet erişim, temsil ve kullanım sonuçlarını da kapsar.",
    detail: "Ölçüm değişmezliği gösterilmeden gruplar arası puan farkı gerçek fark gibi yorumlanamaz; gösterilmesi de bütün kültürel adalet sorunlarını tek başına çözmez.",
    sourceIds: ["AERA_APA_NCME_2014", "PUTNICK_BORNSTEIN_2016"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "measurement_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.causality.correlation",
    topicId: "case.causal_biological_boundary",
    text: "Korelasyon birlikte değişimi gösterebilir; tek başına neden, yön veya mekanizma kanıtlamaz.",
    detail: "Grup bulgusu bireysel çocuk için deterministik neden veya kesin öngörü üretmez.",
    sourceIds: ["ROHRER_2018", "FISHER_ET_AL_2018"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "misconception_correction",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.biological.no_inference",
    topicId: "case.causal_biological_boundary",
    text: "Bir DNA puanı veya davranış gözleminden beyin bölgesi, vagal durum, hormon düzeyi, travma öyküsü ya da tek biyolojik mekanizma çıkarılamaz.",
    detail: "Bu tür bilgiler doğrudan ölçülmemiştir; kuramsal yakınlık bireysel biyolojik bulgu değildir.",
    sourceIds: ["AERA_APA_NCME_2014", "APA_ASSESSMENT_GUIDELINES_2020", "FISHER_ET_AL_2018", "ROHRER_2018", "DOMBROWSKI_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "product_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.case.report.layers",
    topicId: "case.report_communication",
    text: "Rapor dili veri, yorum, hipotez, sınırlılık ve öneriyi birbirinden ayırmalıdır.",
    detail: "İddianın kesinlik düzeyi kanıtla orantılı olmalı; eksik veri ve alternatif açıklamalar görünür tutulmalıdır.",
    sourceIds: ["AERA_APA_NCME_2014", "APA_ASSESSMENT_GUIDELINES_2020", "DOMBROWSKI_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "product_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.report.accessible",
    topicId: "case.report_communication",
    text: "Düz dil, yapılandırılmış özet ve korunmuş kapasitelerin görünür kılınması raporun anlaşılabilirliğini destekleyebilir.",
    detail: "Sadelik kritik sınırlılıkları silmemeli ve güçlü yön dili puanları olduğundan olumlu göstermemelidir.",
    sourceIds: ["BAUM_ET_AL_2018", "WHO_ICF_2001"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "association",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.ai.not_clinically_valid",
    topicId: "case.ai_oversight",
    text: "AI tarafından oluşturulan rapor metni, kullanılan veri ve kaynak doğru olsa bile otomatik olarak klinik olarak geçerli değildir.",
    detail: "Gerçek ürün performansı kullanım amacı, kullanıcı grubu ve güvenlik davranışlarıyla ayrıca doğrulanmalıdır.",
    sourceIds: ["NIST_AI_RMF_2023", "VASEY_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "product_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.ai.human_oversight",
    topicId: "case.ai_oversight",
    text: "AI destekli özet ile uzman raporunun sorumluluğu aynı değildir; klinik sorumluluk ve son değerlendirme yetkili uzmanda kalır.",
    detail: "İnsan denetimi veri yeterliğini, iddia-kaynak uyumunu ve kapsam sınırını incelemelidir; kaynak ve sürüm izlenebilirliği bu denetimi destekler.",
    sourceIds: ["NIST_AI_RMF_2023", "VASEY_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "product_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.case.ai.confidence_boundary",
    topicId: "case.ai_oversight",
    text: "AI çıktısının dilsel güveni doğruluk olasılığı değildir; eksik veri varsa sistem yorum üretmek yerine eksikliği belirtmelidir.",
    detail: "Kalibrasyon gösterilmeden olasılık verilemez ve eksik vaka içeriği serbest klinik metinle tamamlanamaz.",
    sourceIds: ["NIST_AI_RMF_2023", "VASEY_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimType: "product_boundary",
    dnaRelation: "none",
  }),
])

export const V5_CASE_BOUNDARY_RELATIONS: readonly DnaChatCatalogRelation[] = Object.freeze([
  relation({
    id: "relation.case.validity.boundaries",
    fromTopicId: "case.validity_reliability",
    toTopicId: "case.interpretation_boundaries",
    predicate: "part_of",
    summary: "Geçerlik, güvenirlik ve uyum ayrımları güvenli vaka yorumunun ölçüm temelini oluşturur.",
    sourceIds: ["AERA_APA_NCME_2014", "MOKKINK_ET_AL_2010_COSMIN", "KOTTNER_ET_AL_2011"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "Genel ölçüm ilkeleri bireysel DNA sonucunu doğrulamaz.",
  }),
  relation({
    id: "relation.case.uncertainty.boundaries",
    fromTopicId: "case.measurement_uncertainty",
    toTopicId: "case.interpretation_boundaries",
    predicate: "part_of",
    summary: "Ölçüm belirsizliği nokta puanın hangi kesinlikle yorumlanabileceğini sınırlar.",
    sourceIds: ["AERA_APA_NCME_2014", "MOKKINK_ET_AL_2010_COSMIN"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "Araç-özel hata verisi olmadan sayısal aralık üretilmez.",
  }),
  relation({
    id: "relation.case.score.boundaries",
    fromTopicId: "case.score_interpretation",
    toTopicId: "case.interpretation_boundaries",
    predicate: "part_of",
    summary: "Norm, yüzdelik ve kesme puanı anlamları rapor yorum sınırının bir parçasıdır.",
    sourceIds: ["AERA_APA_NCME_2014"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Puan nedeni, tanıyı veya biyolojik mekanizmayı göstermez.",
  }),
  relation({
    id: "relation.case.screening.boundaries",
    fromTopicId: "case.screening_diagnosis",
    toTopicId: "case.interpretation_boundaries",
    predicate: "part_of",
    summary: "Tarama ile tanısal değerlendirme ayrımı kullanım amacının temel sınırlarından biridir.",
    sourceIds: ["AERA_APA_NCME_2014", "APA_ASSESSMENT_GUIDELINES_2020", "SHELDRICK_ET_AL_2020"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "DNA tanı koymaz veya dışlamaz.",
  }),
  relation({
    id: "relation.case.screening.score",
    fromTopicId: "case.screening_diagnosis",
    toTopicId: "case.score_interpretation",
    predicate: "distinguished_from",
    summary: "Bir puanın normatif yorumu, tarama sonucu veya tanısal karar ile aynı değildir.",
    sourceIds: ["AERA_APA_NCME_2014", "SHELDRICK_ET_AL_2020"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "Puan tek başına klinik durum olasılığı üretmez.",
  }),
  relation({
    id: "relation.case.informants.boundaries",
    fromTopicId: "case.multi_informant",
    toTopicId: "case.interpretation_boundaries",
    predicate: "part_of",
    summary: "Bilgi verenlerin gözlem erişimi ve perspektifi güvenli vaka yorumunda ayrı tutulur.",
    sourceIds: ["DE_LOS_REYES_KAZDIN_2005", "DE_LOS_REYES_ET_AL_2013"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "Uyuşmazlık tek kaynağın yanlış olduğunu göstermez.",
  }),
  relation({
    id: "relation.case.context.informants",
    fromTopicId: "case.contextual_variability",
    toTopicId: "case.multi_informant",
    predicate: "associated_with",
    summary: "Farklı bilgi verenler farklı ortamlardaki bağlamsal değişkenliği görünür kılabilir.",
    sourceIds: ["DE_LOS_REYES_KAZDIN_2005", "DE_LOS_REYES_ET_AL_2013"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "Her uyuşmazlık anlamlı bağlamsal örüntü değildir.",
  }),
  relation({
    id: "relation.case.capacity.context",
    fromTopicId: "case.capacity_performance",
    toTopicId: "case.contextual_variability",
    predicate: "conceptually_related_to",
    summary: "Kapasite ve günlük performans ayrımı, çevresel talep ve desteğin işlev üzerindeki rolünü görünür kılar.",
    sourceIds: ["WHO_ICF_2001", "TOPLAK_ET_AL_2013"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Bağlam farkı sabit kapasite veya biyolojik neden değildir.",
  }),
  relation({
    id: "relation.case.change.uncertainty",
    fromTopicId: "case.change_interpretation",
    toTopicId: "case.measurement_uncertainty",
    predicate: "associated_with",
    summary: "Tekrarlı puan değişiminin yorumu ölçüm hatası ve değişime duyarlılıkla birlikte yapılır.",
    sourceIds: ["MOKKINK_ET_AL_2010_COSMIN", "KOTTNER_ET_AL_2011", "DE_VET_ET_AL_2006"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Puan farkı terapi etkisini göstermez.",
  }),
  relation({
    id: "relation.case.development-culture.boundaries",
    fromTopicId: "case.development_culture",
    toTopicId: "case.interpretation_boundaries",
    predicate: "part_of",
    summary: "Yaş, dil, kültür ve norm uygunluğu yorumun hangi gruba taşınabileceğini sınırlar.",
    sourceIds: ["AERA_APA_NCME_2014", "PUTNICK_BORNSTEIN_2016"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Grup uygunluğu bireysel gelişim yaşı veya neden üretmez.",
  }),
  relation({
    id: "relation.case.causal-boundary.interpretation",
    fromTopicId: "case.causal_biological_boundary",
    toTopicId: "case.interpretation_boundaries",
    predicate: "supports",
    summary: "Nedensellik ve biyolojik çıkarım sınırı, gözlem ile açıklanmayan mekanizmayı birbirinden ayırır.",
    sourceIds: ["FISHER_ET_AL_2018", "ROHRER_2018", "DOMBROWSKI_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "Kuramsal açıklama bireysel mekanizma ölçümü değildir.",
  }),
  relation({
    id: "relation.case.communication.interpretation",
    fromTopicId: "case.report_communication",
    toTopicId: "case.interpretation_boundaries",
    predicate: "supports",
    summary: "Veri, yorum, hipotez ve sınırlılıkların ayrılması yorum sınırını okuyucuya taşır.",
    sourceIds: ["AERA_APA_NCME_2014", "APA_ASSESSMENT_GUIDELINES_2020", "BAUM_ET_AL_2018"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Açık rapor dili klinik geçerliği garanti etmez.",
  }),
  relation({
    id: "relation.case.ai.communication",
    fromTopicId: "case.ai_oversight",
    toTopicId: "case.report_communication",
    predicate: "supports",
    summary: "İnsan denetimi ve kaynak izlenebilirliği AI destekli rapor iletişiminin güvenlik katmanıdır.",
    sourceIds: ["NIST_AI_RMF_2023", "VASEY_ET_AL_2022"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "Denetim kaydı kullanıcıya dahili reasoning, audit içeriği veya gizli kural açmaz.",
  }),
  relation({
    id: "relation.case.ai.validity",
    fromTopicId: "case.ai_oversight",
    toTopicId: "case.validity_reliability",
    predicate: "conceptually_related_to",
    summary: "AI destekli raporun klinik geçerliği, kullanılan kaynakların doğruluğundan ayrı olarak amaç, kullanıcı, veri ve gerçek ürün performansı üzerinde sınanmalıdır.",
    sourceIds: ["NIST_AI_RMF_2023", "VASEY_ET_AL_2022", "AERA_APA_NCME_2014"],
    evidenceLevel: "strong",
    ageScope: "all_ages",
    claimBoundary: "Genel yönetişim ilkeleri DNA Asistanı'nın klinik geçerli veya hatasız olduğunu kanıtlamaz.",
  }),
  relation({
    id: "relation.case.interpretation.dna-six-domains",
    fromTopicId: "case.interpretation_boundaries",
    toTopicId: "dna.six_domains",
    predicate: "supports",
    summary: "Vaka yorum sınırları altı alanın yalnız işlevsel başlıklar olarak kullanılmasını, veri-yorum ayrımını ve eksik ölçümün açıkça belirtilmesini sağlar.",
    sourceIds: ["AERA_APA_NCME_2014", "APA_ASSESSMENT_GUIDELINES_2020", "NIGG_2017"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Bu ilişki altı alanın psikometrik faktör, tanı sınıfı veya biyolojik taksonomi olduğunu doğrulamaz.",
  }),
])

export const V5_CASE_BOUNDARY_SAFETY_RULES: readonly DnaChatCatalogSafetyRule[] = Object.freeze([
  safetyRule({
    id: "safety.v5.case-diagnosis",
    patterns: [
      "Bu rapora göre çocuğun tanısı nedir?",
      "Bu puanla otizm veya DEHB dışlanabilir mi?",
    ],
    response: "DNA raporu tanı koyamaz veya tanıyı dışlayamaz. Tanısal değerlendirme yetkin sağlık profesyonelinin kapsamlı değerlendirmesini gerektirir.",
    category: "diagnosis",
    sourceIds: ["AERA_APA_NCME_2014", "APA_ASSESSMENT_GUIDELINES_2020", "SHELDRICK_ET_AL_2020"],
  }),
  safetyRule({
    id: "safety.v5.case-biological-inference",
    patterns: [
      "Hangi beyin bölgesi bozuk çalışıyor?",
      "Vagus sinirinde sorun var mı?",
      "DNA sonucundan hormon veya kortizol düzeyi anlaşılır mı?",
      "Bu profilin kesin biyolojik nedeni nedir?",
      "bu kesin beyinle alakalı demi",
    ],
    response: "DNA raporu beyin bölgesi, vagal durum, hormon düzeyi veya başka bir biyolojik mekanizmayı doğrudan ölçmez; bu çıkarım yapılamaz.",
    category: "biological_inference",
    sourceIds: ["AERA_APA_NCME_2014", "APA_ASSESSMENT_GUIDELINES_2020", "FISHER_ET_AL_2018", "ROHRER_2018", "DOMBROWSKI_ET_AL_2022"],
  }),
  safetyRule({
    id: "safety.v5.case-trauma-causality",
    patterns: ["Bu çocuk travma yaşamış mı?"],
    response: "DNA raporu travma öyküsünü veya davranışın kesin nedenini göstermez; bu çıkarım yapılamaz.",
    category: "causality",
    sourceIds: ["AERA_APA_NCME_2014", "APA_ASSESSMENT_GUIDELINES_2020", "FISHER_ET_AL_2018", "ROHRER_2018"],
  }),
  safetyRule({
    id: "safety.v5.case-treatment",
    patterns: ["Hangi ilaç verilmelidir?", "Kaç seans terapi gerekir?"],
    response: "DNA Asistanı ilaç, tedavi veya bireysel seans planı üretmez; bu karar uygun yetkinlikteki sağlık profesyonelinin kapsamlı değerlendirmesini gerektirir.",
    category: "treatment",
    sourceIds: ["APA_ASSESSMENT_GUIDELINES_2020", "NIST_AI_RMF_2023", "VASEY_ET_AL_2022"],
  }),
  safetyRule({
    id: "safety.v5.case-prognosis",
    patterns: ["Bu çocuk ileride nasıl olacak?"],
    response: "Tek değerlendirme veya DNA puanı bireysel prognoz vermez; geleceğe ilişkin kesin sonuç üretilemez.",
    category: "causality",
    sourceIds: ["AERA_APA_NCME_2014", "APA_ASSESSMENT_GUIDELINES_2020", "FISHER_ET_AL_2018"],
  }),
])
