import {
  DNA_CHAT_CATALOG_VERSION,
  type DnaChatCatalogClaim,
  type DnaChatCatalogRelation,
  type DnaChatCatalogSafetyRule,
  type DnaChatCatalogSource,
  type DnaChatCatalogTopic,
} from "./types"

const VERIFIED_AT = "2026-07-17"

export const V5_COREGULATION_SOURCES = Object.freeze([
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "VERHAGEN_ET_AL_2024_COREG",
    title: "Coregulation between parents and elementary school-aged children in response to challenge and in association with child outcomes: A systematic review",
    authors: "Verhagen, C., Boekhorst, M. G. B. M., Kupper, N., van Bakel, H., & Duijndam, S.",
    year: 2024,
    publication: "Developmental Psychology, advance online publication",
    publicationStatus: "published",
    studyType: "Sistematik derleme",
    doi: "10.1037/dev0001864",
    pmid: null,
    url: "https://doi.org/10.1037/dev0001864",
    evidenceDomain: "parent_child_coregulation",
    ageScope: "childhood",
    claimBoundary: "Davranışsal, duygusal ve fizyolojik eş-regülasyon çalışmalarını grup düzeyinde özetler; tek gözlemden ilişki kalitesi, neden veya prognoz çıkarmaz.",
    existingLiteratureId: "VERHAGEN_ET_AL_2024",
    verifiedAt: VERIFIED_AT,
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "BIRK_ET_AL_2022_COREG",
    title: "Parent-child synchrony after early childhood: A systematic review",
    authors: "Birk, S. L., Stewart, L., & Olino, T. M.",
    year: 2022,
    publication: "Clinical Child and Family Psychology Review, 25(3), 529-551",
    publicationStatus: "published",
    studyType: "Sistematik derleme",
    doi: "10.1007/s10567-022-00383-7",
    pmid: null,
    url: "https://doi.org/10.1007/s10567-022-00383-7",
    evidenceDomain: "parent_child_synchrony_development",
    ageScope: "developmental",
    claimBoundary: "Senkroninin gelişimsel ve bağlamsal çeşitliliğini özetler; senkroniyi eş-regülasyon, bağlanma ya da iyi sonuçla eşitlemez.",
    verifiedAt: VERIFIED_AT,
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "DEPASQUALE_2020_COREG",
    title: "A systematic review of caregiver-child physiological synchrony across systems: Associations with behavior and child functioning",
    authors: "DePasquale, C. E.",
    year: 2020,
    publication: "Development and Psychopathology, 32(5), 1754-1777",
    publicationStatus: "published",
    studyType: "Sistematik derleme",
    doi: "10.1017/S0954579420001236",
    pmid: null,
    url: "https://doi.org/10.1017/S0954579420001236",
    evidenceDomain: "caregiver_child_physiological_synchrony",
    ageScope: "developmental",
    claimBoundary: "Fizyolojik sistemler, zaman ölçekleri ve analizler heterojendir; eşzamanlılık valans, yön veya vagal durum göstermez.",
    verifiedAt: VERIFIED_AT,
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "FELDMAN_2007_SYNCHRONY",
    title: "Parent-infant synchrony and the construction of shared timing: Physiological precursors, developmental outcomes, and risk conditions",
    authors: "Feldman, R.",
    year: 2007,
    publication: "Journal of Child Psychology and Psychiatry, 48(3-4), 329-354",
    publicationStatus: "published",
    studyType: "Gelişimsel anlatısal derleme",
    doi: "10.1111/j.1469-7610.2006.01701.x",
    pmid: null,
    url: "https://doi.org/10.1111/j.1469-7610.2006.01701.x",
    evidenceDomain: "parent_infant_synchrony",
    ageScope: "early_childhood",
    claimBoundary: "Paylaşılan zamanlama için kuramsal çerçeve sunar; tek etkileşimden kalıcı ilişki özelliği veya biyolojik mekanizma çıkarmaz.",
    verifiedAt: VERIFIED_AT,
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "LUNKENHEIMER_ET_AL_2017_COREG",
    title: "Assessing biobehavioural self-regulation and coregulation in early childhood: The Parent-Child Challenge Task",
    authors: "Lunkenheimer, E., Kemp, C. J., Lucas-Thompson, R. G., Cole, P. M., & Albrecht, E. C.",
    year: 2017,
    publication: "Infant and Child Development, 26(1), e1965",
    publicationStatus: "published",
    studyType: "Yöntem ve görev çalışması",
    doi: "10.1002/icd.1965",
    pmid: null,
    url: "https://doi.org/10.1002/icd.1965",
    evidenceDomain: "coregulation_observation_method",
    ageScope: "early_childhood",
    claimBoundary: "Belirli bir zorluk görevinin gözlemsel kodlarını açıklar; tek görev gündelik eş-regülasyonun tamamı veya tanı aracı değildir.",
    verifiedAt: VERIFIED_AT,
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "MESMAN_ET_AL_2009_STILL_FACE",
    title: "The many faces of the Still-Face Paradigm: A review and meta-analysis",
    authors: "Mesman, J., van IJzendoorn, M. H., & Bakermans-Kranenburg, M. J.",
    year: 2009,
    publication: "Developmental Review, 29(2), 120-162",
    publicationStatus: "published",
    studyType: "Derleme ve meta-analiz",
    doi: "10.1016/j.dr.2009.02.001",
    pmid: null,
    url: "https://doi.org/10.1016/j.dr.2009.02.001",
    evidenceDomain: "still_face_interaction_repair",
    ageScope: "early_childhood",
    claimBoundary: "Grup düzeyi still-face etkilerini özetler; tek bebeğin tepkisi ilişki bozukluğu, travma veya bakımveren niteliği göstermez.",
    verifiedAt: VERIFIED_AT,
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "MADIGAN_ET_AL_2024_SENSITIVITY",
    title: "Maternal and paternal sensitivity: Key determinants of child attachment security examined through meta-analysis",
    authors: "Madigan, S., Deneault, A.-A., Duschinsky, R., et al.",
    year: 2024,
    publication: "Psychological Bulletin, 150(7), 839-872",
    publicationStatus: "published",
    studyType: "Meta-analiz",
    doi: "10.1037/bul0000433",
    pmid: null,
    url: "https://doi.org/10.1037/bul0000433",
    evidenceDomain: "caregiver_sensitivity_attachment",
    ageScope: "developmental",
    claimBoundary: "Duyarlılık ve bağlanma güvenliği arasındaki grup ilişkisini özetler; tek gözlemden bağlanma sınıfı ya da ebeveyn kusuru çıkarmaz.",
    verifiedAt: VERIFIED_AT,
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "COOKE_ET_AL_2022_SENSITIVITY",
    title: "Parental sensitivity and child behavioral problems: A meta-analytic review",
    authors: "Cooke, J. E., Deneault, A.-A., Devereux, C., Eirich, R., Fearon, R. M. P., & Madigan, S.",
    year: 2022,
    publication: "Child Development, 93(5), 1231-1248",
    publicationStatus: "published",
    studyType: "Meta-analiz",
    doi: "10.1111/cdev.13764",
    pmid: null,
    url: "https://doi.org/10.1111/cdev.13764",
    evidenceDomain: "caregiver_sensitivity_child_behavior",
    ageScope: "developmental",
    claimBoundary: "Küçük grup ilişkilerini özetler; duyarlılığı çocuk davranışının tek nedeni veya bireysel açıklaması yapmaz.",
    verifiedAt: VERIFIED_AT,
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "ENGLAND_MASON_ET_AL_2023",
    title: "Emotion socialization parenting interventions targeting emotional competence in young children: A systematic review and meta-analysis of randomized controlled trials",
    authors: "England-Mason, G., Andrews, K., Atkinson, L., & Gonzalez, A.",
    year: 2023,
    publication: "Clinical Psychology Review, 100, 102252",
    publicationStatus: "published",
    studyType: "Sistematik derleme ve meta-analiz",
    doi: "10.1016/j.cpr.2023.102252",
    pmid: null,
    url: "https://doi.org/10.1016/j.cpr.2023.102252",
    evidenceDomain: "emotion_socialization_parenting",
    ageScope: "early_childhood",
    claimBoundary: "Grup düzeyi müdahale etkilerini özetler; DNA Asistanı için kişiselleştirilmiş tedavi veya seans protokolü sağlamaz.",
    verifiedAt: VERIFIED_AT,
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "SANKALAITE_ET_AL_2021",
    title: "Strengthening executive function and self-regulation through teacher-student interaction in preschool and primary school children: A systematic review",
    authors: "Sankalaite, S., Huizinga, M., Dewandeleer, J., et al.",
    year: 2021,
    publication: "Frontiers in Psychology, 12, 718262",
    publicationStatus: "published",
    studyType: "Sistematik derleme",
    doi: "10.3389/fpsyg.2021.718262",
    pmid: null,
    url: "https://doi.org/10.3389/fpsyg.2021.718262",
    evidenceDomain: "teacher_student_self_regulation",
    ageScope: "childhood",
    claimBoundary: "Öğretmen-öğrenci etkileşimleriyle grup düzeyi ilişkileri özetler; öğretmen ilişkisini eş-regülasyonun doğrudan ölçümü saymaz.",
    existingLiteratureId: "SANKALAITE_ET_AL_2021",
    verifiedAt: VERIFIED_AT,
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "VANDENBROUCKE_ET_AL_2018",
    title: "The classroom as a developmental context for cognitive development: A meta-analysis on the importance of teacher-student interactions for children's executive functions",
    authors: "Vandenbroucke, L., Spilt, J., Verschueren, K., Piccinin, C., & Baeyens, D.",
    year: 2018,
    publication: "Review of Educational Research, 88(1), 125-164",
    publicationStatus: "published",
    studyType: "Meta-analiz",
    doi: "10.3102/0034654317743200",
    pmid: null,
    url: "https://doi.org/10.3102/0034654317743200",
    evidenceDomain: "teacher_interaction_executive_function",
    ageScope: "childhood",
    claimBoundary: "Sınıf etkileşimleriyle yürütücü işlev arasındaki grup ilişkilerini özetler; tek çocuk için neden veya kapasite tahmini değildir.",
    verifiedAt: VERIFIED_AT,
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "NIELSEN_ET_AL_2017",
    title: "The persistent sampling bias in developmental psychology: A call to action",
    authors: "Nielsen, M., Haun, D., Kärtner, J., & Legare, C. H.",
    year: 2017,
    publication: "Journal of Experimental Child Psychology, 162, 31-38",
    publicationStatus: "published",
    studyType: "Yöntemsel ve kavramsal makale",
    doi: "10.1016/j.jecp.2017.04.017",
    pmid: null,
    url: "https://doi.org/10.1016/j.jecp.2017.04.017",
    evidenceDomain: "developmental_sampling_bias",
    ageScope: "developmental",
    claimBoundary: "Gelişim araştırmalarındaki örnekleme yanlılığını açıklar; kültür adına bireysel davranışa kalıp yargı atamaz.",
    verifiedAt: VERIFIED_AT,
    sourceVerified: true,
  },
] satisfies readonly DnaChatCatalogSource[])

export const V5_COREGULATION_TOPICS = Object.freeze([
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "selfreg.codyregulation",
    category: "self_regulation",
    title: "Eş-düzensizlik",
    aliases: ["eş-düzensizlik", "ortak düzensizlik", "co-dysregulation", "karşılıklı tırmanma"],
    summary: "Eş-düzensizlik, iki tarafın tepkilerinin sıkıntıyı veya katılığı karşılıklı artırdığı zaman sınırlı bir etkileşim örüntüsüdür.",
    details: ["Klinik tanı değildir.", "Tek olay kalıcı ilişki özelliği veya ebeveyn kusuru göstermez."],
    keywords: ["tırmanma", "ortak sıkıntı", "katılık", "onarım"],
    claimIds: ["claim.coreg.codyregulation.definition"],
    sourceIds: ["VERHAGEN_ET_AL_2024_COREG", "DEPASQUALE_2020_COREG"],
    evidenceLevel: "limited",
    ageScope: "developmental",
    claimBoundary: "Yüksek eşzamanlılık veya yoğun duygu tek başına eş-düzensizlik kanıtı değildir.",
    reviewStatus: "source_verified_expert_pending",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "selfreg.dyadic_synchrony",
    category: "self_regulation",
    title: "Dyadik eşzamanlılık",
    aliases: ["dyadik eşzamanlılık", "ebeveyn çocuk senkronisi", "fizyolojik eşzamanlılık", "davranışsal eşzamanlılık"],
    summary: "Dyadik eşzamanlılık, iki kişinin davranışsal veya fizyolojik sinyalleri arasındaki zaman ilişkisini betimler.",
    details: ["Davranışsal ve fizyolojik eşzamanlılık aynı ölçüm değildir.", "Daha yüksek eşleşme her bağlamda daha iyi değildir."],
    keywords: ["senkroni", "zamanlama", "fizyolojik sinyal", "davranışsal uyum"],
    claimIds: ["claim.coreg.synchrony.definition", "claim.coreg.synchrony.valence_boundary"],
    sourceIds: ["BIRK_ET_AL_2022_COREG", "DEPASQUALE_2020_COREG", "FELDMAN_2007_SYNCHRONY"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Eşzamanlılık etkili eş-regülasyonun, bağlanmanın veya biyolojik güvenliğin doğrudan ölçümü değildir.",
    reviewStatus: "source_verified_expert_pending",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "selfreg.interaction_repair",
    category: "self_regulation",
    title: "Etkileşim onarımı",
    aliases: ["etkileşim onarımı", "uyumsuzluk onarımı", "rupture and repair", "mismatch repair"],
    summary: "Etkileşim onarımı, kısa süreli uyumsuzluktan sonra ortak katılımın yeniden kurulmasını anlatır.",
    details: ["Etkileşimde küçük aksaklıklar gelişimsel olarak olağandır.", "Onarımın niteliği, aksaklığın hiç olmamasından daha bilgi verici olabilir."],
    keywords: ["aksaklık", "yeniden katılım", "uyum", "zamanlama"],
    claimIds: ["claim.coreg.repair.normal_mismatch"],
    sourceIds: ["MESMAN_ET_AL_2009_STILL_FACE"],
    evidenceLevel: "moderate",
    ageScope: "early_childhood",
    claimBoundary: "Tek gecikmiş onarım ilişki bozukluğu, ihmal veya travma göstermez.",
    reviewStatus: "source_verified_expert_pending",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "selfreg.caregiver_sensitivity",
    category: "self_regulation",
    title: "Bakımveren duyarlılığı",
    aliases: ["bakımveren duyarlılığı", "ebeveyn duyarlılığı", "caregiver sensitivity", "parental sensitivity"],
    summary: "Bakımveren duyarlılığı çocuğun sinyalini fark etme, yorumlama ve uygun zamanda yanıt verme boyutlarını kapsar.",
    details: ["Eş-regülasyon için destekleyici bir koşuldur.", "Eş-regülasyonun veya bağlanmanın kendisi değildir."],
    keywords: ["sinyal", "yanıtlayıcılık", "zamanlama", "bakımveren"],
    claimIds: ["claim.coreg.sensitivity.definition", "claim.coreg.sensitivity.small_group_association"],
    sourceIds: ["MADIGAN_ET_AL_2024_SENSITIVITY", "COOKE_ET_AL_2022_SENSITIVITY"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimBoundary: "Tek gözlemden bakımveren niteliği, bağlanma sınıfı veya çocuk davranışının nedeni çıkarılamaz.",
    reviewStatus: "source_verified_expert_pending",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "selfreg.social_buffering",
    category: "self_regulation",
    title: "Sosyal tamponlama",
    aliases: ["sosyal tamponlama", "social buffering", "stres tamponlama", "sosyal destekle stres azalması"],
    summary: "Sosyal tamponlama, başka bir kişinin varlığı veya desteğiyle stres tepkisinin grup düzeyinde azalabilmesini anlatır.",
    details: ["Eş-regülasyonun olası bir sonucu veya alt süreci olabilir.", "Her kişi ve bağlamda aynı yönde ortaya çıkmaz."],
    keywords: ["sosyal destek", "stres", "bakımveren", "bağlam"],
    claimIds: ["claim.coreg.social_buffering.definition"],
    sourceIds: ["HOSTINAR_ET_AL_2014"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Sosyal tamponlama eş-regülasyonun tamamı değildir ve vaka için kortizol sonucu vermez.",
    reviewStatus: "source_verified_expert_pending",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "selfreg.coregulation_scaffolding",
    category: "self_regulation",
    title: "Eş-regülasyon desteği ve iskeleleme",
    aliases: [
      "eş-regülasyon desteği",
      "iskeleleme",
      "scaffolding",
      "öngörülebilir yapı",
      "beceri koçluğu",
      "duygu koçluğu",
    ],
    summary: "Eş-regülasyon desteği sıcak ilişki, öngörülebilir yapı ve gelişime uygun beceri koçluğunun birlikte kullanılmasını kapsayabilir.",
    details: ["Yapı katı kontrol değildir.", "Destek çocuğun etkin katılımını ve giderek artan özerkliğini korumalıdır."],
    keywords: ["sıcaklık", "rutin", "özerklik", "koçluk", "çevresel yapı"],
    claimIds: ["claim.coreg.scaffolding.complementary_support"],
    sourceIds: ["ROSANBALM_MURRAY_2017", "SANKALAITE_ET_AL_2021"],
    evidenceLevel: "theoretical",
    ageScope: "developmental",
    claimBoundary: "Bu çerçeve tek ve doğrulanmış biyolojik model ya da kişiselleştirilmiş müdahale protokolü değildir.",
    reviewStatus: "source_verified_expert_pending",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "selfreg.coregulation_development",
    category: "self_regulation",
    title: "Eş-regülasyonun gelişimi",
    aliases: ["eş-regülasyon gelişimi", "ko-regülasyon yaşla", "coregulation development", "çocuklukta eş-regülasyon"],
    summary: "Eş-regülasyon çocukluk boyunca sürer; destek biçimi yaş, görev ve çocuğun mevcut kapasitesine göre değişebilir.",
    details: ["Bebeklikte bedensel ve anlık destek daha görünürdür.", "Okul çağında sözel hazırlık, ortak problem çözme ve özerklik desteği artabilir."],
    keywords: ["bebeklik", "okul çağı", "özerklik", "gelişim"],
    claimIds: ["claim.coreg.development.form_changes"],
    sourceIds: ["VERHAGEN_ET_AL_2024_COREG", "BIRK_ET_AL_2022_COREG", "ROSANBALM_MURRAY_2017"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Bu bir gelişimsel eğilimdir; katı yaş basamağı veya bireysel olgunluk ölçüsü değildir.",
    reviewStatus: "source_verified_expert_pending",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "selfreg.coregulation_measurement",
    category: "self_regulation",
    title: "Eş-regülasyonun değerlendirilmesi",
    aliases: ["eş-regülasyon ölçümü", "ko-regülasyon değerlendirmesi", "coregulation assessment", "dyadik gözlem"],
    summary: "Eş-regülasyon araştırmaları gözlem, zaman serisi, bildirim ve fizyolojik kayıt gibi farklı veri katmanları kullanır.",
    details: ["Katmanlar birbirinin yerine geçmez.", "Görev ve kodlama sistemi yalnız belirli bir bağlamı örnekler."],
    keywords: ["gözlem", "zaman serisi", "çoklu yöntem", "fizyoloji", "görev"],
    claimIds: ["claim.coreg.measurement.multimethod", "claim.coreg.measurement.biological_boundary"],
    sourceIds: ["VERHAGEN_ET_AL_2024_COREG", "DEPASQUALE_2020_COREG", "LUNKENHEIMER_ET_AL_2017_COREG"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Davranış gözlemi vagal durum, kortizol, beyin eşzamanlılığı, bağlanma sınıfı veya tanı ölçümü değildir.",
    reviewStatus: "source_verified_expert_pending",
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "selfreg.coregulation_culture",
    category: "self_regulation",
    title: "Eş-regülasyon ve kültürel bağlam",
    aliases: ["eş-regülasyon kültür", "kültürel eş-regülasyon", "coregulation culture", "bakım kültürü"],
    summary: "Yakınlık, göz teması, dokunma, özerklik ve yetişkin-çocuk rol beklentileri kültürel bağlama göre farklı anlamlar taşıyabilir.",
    details: ["Tek bir etkileşim biçimi evrensel başarı ölçütü değildir.", "Kültür bireysel davranış için basmakalıp açıklama olarak kullanılmamalıdır."],
    keywords: ["kültür", "göz teması", "dokunma", "özerklik", "örnekleme"],
    claimIds: ["claim.coreg.culture.context"],
    sourceIds: ["HENRICH_ET_AL_2010", "NIELSEN_ET_AL_2017"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Kültürel grup bilgisi tek çocuk için niyet, yeterlilik veya klinik anlam belirlemez.",
    reviewStatus: "source_verified_expert_pending",
  },
] satisfies readonly DnaChatCatalogTopic[])

export const V5_COREGULATION_CLAIMS = Object.freeze([
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "claim.coreg.process.reciprocal",
    topicId: "selfreg.coregulation",
    text: "Eş-regülasyon, iki kişinin durumlarını zaman içinde karşılıklı uyarladığı ilişkisel bir süreçtir; yalnız yetişkinin çocuğu sakinleştirmesi değildir.",
    detail: "Yetişkin daha fazla sorumluluk taşıyabilir, ancak çocuk da ipuçları ve tepkileriyle süreci şekillendirir.",
    sourceIds: ["VERHAGEN_ET_AL_2024_COREG", "FELDMAN_2007_SYNCHRONY"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
    safetyStatus: "safe",
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "claim.coreg.process.function",
    topicId: "selfreg.coregulation",
    text: "Eş-regülasyon duyguyu her zaman söndürmek yerine günlük işlevi, düzenlenebilir katılımı, göreve dönüşü ve onarımı destekleyebilir.",
    detail: "Yorgunluk, açlık ve duyusal yük düzenleme yükünü ve destek ihtiyacını bağlamsal olarak değiştirebilir; negatif duygu tek başına başarısızlık değildir.",
    sourceIds: ["MESMAN_ET_AL_2009_STILL_FACE", "BLAIR_RAVER_2015"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "association",
    dnaRelation: "conceptual_proximity",
    safetyStatus: "safe",
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "claim.coreg.negative_emotion_dependency_boundary",
    topicId: "selfreg.coregulation",
    text: "Çocuğun ağlaması veya desteğe ihtiyaç duyması eş-regülasyonun başarısız olduğunu ya da çocuğu bağımlı yaptığını göstermez.",
    detail: "Uygun destek çocuğun aktif katkısı, beceri kullanımı ve kademeli özerkliğiyle birlikte ele alınır; sürekli aşırı kontrol farklı bir olgudur.",
    sourceIds: ["VERHAGEN_ET_AL_2024_COREG", "ROSANBALM_MURRAY_2017", "MESMAN_ET_AL_2009_STILL_FACE"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "misconception_correction",
    dnaRelation: "conceptual_proximity",
    safetyStatus: "safe",
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "claim.coreg.dna_measurement_boundary",
    topicId: "selfreg.coregulation",
    text: "DNA eş-regülasyonu doğrudan ölçen veya doğrulanmış ayrı bir alan olarak sınıflayan bir araç değildir.",
    detail: "Rapor yalnız desteğe yanıt ve bağlamsal işlev gibi dolaylı gözlemleri ayırabilir; bunlar dyadik süreç, senkroni veya ilişki kalitesi ölçümü değildir.",
    sourceIds: ["VERHAGEN_ET_AL_2024_COREG", "LUNKENHEIMER_ET_AL_2017_COREG", "DEPASQUALE_2020_COREG"],
    evidenceLevel: "boundary",
    ageScope: "developmental",
    claimType: "product_boundary",
    dnaRelation: "not_established",
    safetyStatus: "safe",
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "claim.coreg.codyregulation.definition",
    topicId: "selfreg.codyregulation",
    text: "Eş-düzensizlik, dyadın tepkilerinin sıkıntıyı veya katılığı karşılıklı artırdığı bağlama ve zamana bağlı örüntüdür.",
    detail: "Klinik tanı değildir; yüksek duygu veya senkroni tek başına bu örüntüyü kanıtlamaz.",
    sourceIds: ["VERHAGEN_ET_AL_2024_COREG", "DEPASQUALE_2020_COREG"],
    evidenceLevel: "limited",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "theory_only",
    safetyStatus: "safe",
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "claim.coreg.synchrony.definition",
    topicId: "selfreg.dyadic_synchrony",
    text: "Dyadik eşzamanlılık, iki kişinin sinyalleri arasındaki zamansal bağlantıyı betimler; etkili eş-regülasyonun doğrudan ölçümü değildir.",
    detail: "Davranış, kalp hızı, RSA, EDA ve nöral kayıtlar farklı veri katmanlarıdır ve aynı anlama gelmez.",
    sourceIds: ["BIRK_ET_AL_2022_COREG", "DEPASQUALE_2020_COREG"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
    safetyStatus: "safe",
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "claim.coreg.synchrony.valence_boundary",
    topicId: "selfreg.dyadic_synchrony",
    text: "Daha yüksek eşzamanlılık her zaman daha iyi değildir; bazı bağlamlarda ortak sıkıntıyı da yansıtabilir.",
    detail: "Yorum için yön, süre, bağlam, risk ve sonuç birlikte değerlendirilmelidir.",
    sourceIds: ["VERHAGEN_ET_AL_2024_COREG", "DEPASQUALE_2020_COREG"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "misconception_correction",
    dnaRelation: "none",
    safetyStatus: "safe",
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "claim.coreg.repair.normal_mismatch",
    topicId: "selfreg.interaction_repair",
    text: "Etkileşimde kısa süreli uyumsuzluklar olağandır; yeniden katılımın kurulması onarım olarak ele alınır.",
    detail: "Tek bir aksaklık veya gecikme ilişki bozukluğu ya da travma kanıtı değildir.",
    sourceIds: ["MESMAN_ET_AL_2009_STILL_FACE"],
    evidenceLevel: "moderate",
    ageScope: "early_childhood",
    claimType: "development",
    dnaRelation: "conceptual_proximity",
    safetyStatus: "safe",
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "claim.coreg.sensitivity.definition",
    topicId: "selfreg.caregiver_sensitivity",
    text: "Bakımveren duyarlılığı sinyali fark etme, yorumlama ve uygun-zamanlı yanıt verme boyutlarını içerir.",
    detail: "Eş-regülasyon için destekleyici koşuldur; eş-regülasyon veya bağlanma güvenliğiyle özdeş değildir.",
    sourceIds: ["MADIGAN_ET_AL_2024_SENSITIVITY"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
    safetyStatus: "safe",
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "claim.coreg.sensitivity.small_group_association",
    topicId: "selfreg.caregiver_sensitivity",
    text: "Bakımveren duyarlılığı ile çocuk davranış sorunları arasındaki ortalama ilişkiler küçüktür.",
    detail: "Küçük grup ilişkisi tek çocuk için neden, ebeveyn kusuru veya prognoz değildir.",
    sourceIds: ["COOKE_ET_AL_2022_SENSITIVITY"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "association",
    dnaRelation: "none",
    safetyStatus: "safe",
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "claim.coreg.social_buffering.definition",
    topicId: "selfreg.social_buffering",
    text: "Sosyal tamponlama, sosyal destekle stres tepkisinin azalabilmesini anlatır ve eş-regülasyonun tamamı değildir.",
    detail: "Etki yaşa ve bağlama göre değişebilir; tek vaka için HPA, kortizol veya otonom sonuç üretmez.",
    sourceIds: ["HOSTINAR_ET_AL_2014"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
    safetyStatus: "safe",
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "claim.coreg.scaffolding.complementary_support",
    topicId: "selfreg.coregulation_scaffolding",
    text: "Sıcak ilişki, öngörülebilir yapı ve beceri koçluğu eş-regülasyon desteğinin tamamlayıcı boyutları olarak kullanılabilir.",
    detail: "Bu üçlü kurumlar arası tek standart değildir ve kişiselleştirilmiş müdahale reçetesi sağlamaz.",
    sourceIds: ["ROSANBALM_MURRAY_2017", "SANKALAITE_ET_AL_2021"],
    evidenceLevel: "theoretical",
    ageScope: "developmental",
    claimType: "definition",
    dnaRelation: "theory_only",
    safetyStatus: "safe",
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "claim.coreg.development.form_changes",
    topicId: "selfreg.coregulation_development",
    text: "Eş-regülasyon desteğinin biçimi çocukluk boyunca daha bedensel ve anlık destekten daha sözel, öngörücü ve işbirlikçi desteğe doğru değişebilir.",
    detail: "Bu katı basamak değildir; çocuk, görev, ilişki ve bağlam gelişimsel yaştan bağımsız katkı sunar.",
    sourceIds: ["VERHAGEN_ET_AL_2024_COREG", "BIRK_ET_AL_2022_COREG", "ROSANBALM_MURRAY_2017"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "development",
    dnaRelation: "conceptual_proximity",
    safetyStatus: "safe",
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "claim.coreg.measurement.multimethod",
    topicId: "selfreg.coregulation_measurement",
    text: "Eş-regülasyon değerlendirmesi gözlem, zaman serisi, bildirim ve fizyolojik kayıt gibi farklı yöntemlerin neyi örneklediğini ayrı tutmalıdır.",
    detail: "Yöntemler farklı zaman ölçeği ve bağlamları temsil eder; tek görev veya tek bilgi kaynağı bütün süreci ölçmez.",
    sourceIds: ["VERHAGEN_ET_AL_2024_COREG", "DEPASQUALE_2020_COREG", "LUNKENHEIMER_ET_AL_2017_COREG"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
    safetyStatus: "safe",
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "claim.coreg.measurement.biological_boundary",
    topicId: "selfreg.coregulation_measurement",
    text: "Eş-regülasyon gözlemi belirli beyin bölgesi, vagus işlevi, HPA bozukluğu, kortizol düzeyi veya travma öyküsünü göstermez.",
    detail: "Biyolojik çıkarım için doğrudan, uygun ve doğrulanmış ölçüm gerekir; DNA davranış profili bu ölçümlerin yerine geçmez.",
    sourceIds: ["DEPASQUALE_2020_COREG", "ALEN_ET_AL_2022", "HOSTINAR_ET_AL_2014", "GROSSMAN_2023"],
    evidenceLevel: "strong",
    ageScope: "developmental",
    claimType: "product_boundary",
    dnaRelation: "not_established",
    safetyStatus: "safe",
    sourceVerified: true,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "claim.coreg.culture.context",
    topicId: "selfreg.coregulation_culture",
    text: "Göz teması, dokunma, yakınlık ve özerklik beklentilerinin anlamı kültürel ve ilişkisel bağlama göre değişebilir.",
    detail: "Tek bir biçim evrensel başarı ölçütü değildir; kültür bireysel davranışı basmakalıp biçimde açıklamaz.",
    sourceIds: ["HENRICH_ET_AL_2010", "NIELSEN_ET_AL_2017"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimType: "misconception_correction",
    dnaRelation: "none",
    safetyStatus: "safe",
    sourceVerified: true,
  },
] satisfies readonly DnaChatCatalogClaim[])

export const V5_COREGULATION_RELATIONS = Object.freeze([
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "relation.coreg.synchrony.coregulation",
    fromTopicId: "selfreg.dyadic_synchrony",
    toTopicId: "selfreg.coregulation",
    predicate: "distinguished_from",
    summary: "Eşzamanlılık bir zaman ilişkisi ölçümüdür; eş-regülasyon ise bağlam ve işlev içeren daha geniş ilişkisel süreçtir.",
    sourceIds: ["VERHAGEN_ET_AL_2024_COREG", "DEPASQUALE_2020_COREG"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "İki kavram ilişkili olabilir, fakat biri diğerinin doğrulanmış ölçümü değildir.",
    maxHops: 1,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "relation.coreg.codyregulation.coregulation",
    fromTopicId: "selfreg.codyregulation",
    toTopicId: "selfreg.coregulation",
    predicate: "distinguished_from",
    summary: "Eş-düzensizlik sıkıntının karşılıklı tırmandığı örüntüyü; eş-regülasyon düzenlenebilir katılımı destekleyen süreci anlatır.",
    sourceIds: ["VERHAGEN_ET_AL_2024_COREG", "DEPASQUALE_2020_COREG"],
    evidenceLevel: "limited",
    ageScope: "developmental",
    claimBoundary: "Tek olaydan kalıcı dyad sınıflaması yapılmaz.",
    maxHops: 1,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "relation.coreg.repair.coregulation",
    fromTopicId: "selfreg.interaction_repair",
    toTopicId: "selfreg.coregulation",
    predicate: "supports",
    summary: "Aksaklık sonrasında ortak katılımın yeniden kurulması eş-regülasyon sürecinin gözlenebilir bir yönüdür.",
    sourceIds: ["MESMAN_ET_AL_2009_STILL_FACE"],
    evidenceLevel: "moderate",
    ageScope: "early_childhood",
    claimBoundary: "Onarım tek başına ilişki kalitesi, bağlanma veya klinik durum ölçümü değildir.",
    maxHops: 1,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "relation.coreg.sensitivity.coregulation",
    fromTopicId: "selfreg.caregiver_sensitivity",
    toTopicId: "selfreg.coregulation",
    predicate: "supports",
    summary: "Bakımveren duyarlılığı eş-regülasyon için destekleyici bir ilişkisel koşul sağlayabilir.",
    sourceIds: ["MADIGAN_ET_AL_2024_SENSITIVITY", "VERHAGEN_ET_AL_2024_COREG"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Duyarlılık eş-regülasyonla özdeş değildir ve tek neden değildir.",
    maxHops: 1,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "relation.coreg.social-buffering.coregulation",
    fromTopicId: "selfreg.social_buffering",
    toTopicId: "selfreg.coregulation",
    predicate: "conceptually_related_to",
    summary: "Sosyal tamponlama eş-regülasyonun olası bir sonucu veya alt sürecidir; iki kavram eş anlamlı değildir.",
    sourceIds: ["HOSTINAR_ET_AL_2014"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Sosyal destekten tek vaka için hormon veya otonom sonuç çıkarılmaz.",
    maxHops: 1,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "relation.coreg.scaffolding.coregulation",
    fromTopicId: "selfreg.coregulation_scaffolding",
    toTopicId: "selfreg.coregulation",
    predicate: "supports",
    summary: "Sıcak ilişki, yapı ve koçluk eş-regülasyon için çevresel destek sağlayabilir.",
    sourceIds: ["ROSANBALM_MURRAY_2017", "SANKALAITE_ET_AL_2021"],
    evidenceLevel: "theoretical",
    ageScope: "developmental",
    claimBoundary: "Çerçeve tedavi reçetesi veya tek biyolojik mekanizma değildir.",
    maxHops: 1,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "relation.coreg.development.coregulation",
    fromTopicId: "selfreg.coregulation_development",
    toTopicId: "selfreg.coregulation",
    predicate: "part_of",
    summary: "Eş-regülasyonun görünür biçimi gelişimsel dönem ve bağlamla birlikte değişir.",
    sourceIds: ["VERHAGEN_ET_AL_2024_COREG", "BIRK_ET_AL_2022_COREG", "ROSANBALM_MURRAY_2017"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Gelişimsel eğilim katı basamak veya tek çocuk için norm değildir.",
    maxHops: 1,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "relation.coreg.measurement.coregulation",
    fromTopicId: "selfreg.coregulation",
    toTopicId: "selfreg.coregulation_measurement",
    predicate: "measured_indirectly_by",
    summary: "Eş-regülasyon farklı yöntemlerle yalnız belirli davranışsal veya fizyolojik örüntüler üzerinden dolaylı olarak örneklenir.",
    sourceIds: ["VERHAGEN_ET_AL_2024_COREG", "DEPASQUALE_2020_COREG", "LUNKENHEIMER_ET_AL_2017_COREG"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Tek yöntem bütün süreci, tanıyı veya biyolojik mekanizmayı ölçmez.",
    maxHops: 1,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "relation.coreg.culture.coregulation",
    fromTopicId: "selfreg.coregulation_culture",
    toTopicId: "selfreg.coregulation",
    predicate: "associated_with",
    summary: "Eş-regülasyonun kabul edilen görünümü ve anlamı kültürel bakım beklentileriyle birlikte değişebilir.",
    sourceIds: ["HENRICH_ET_AL_2010", "NIELSEN_ET_AL_2017"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Kültürel örüntü bireysel niyeti veya yeterliliği belirlemez.",
    maxHops: 1,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "relation.coreg.emotion-regulation",
    fromTopicId: "selfreg.coregulation",
    toTopicId: "selfreg.emotion_regulation",
    predicate: "supports",
    summary: "Eş-regülasyon duygusal deneyimin düzenlenebilir düzeyde tutulması ve yeniden katılım için sosyal bağlam sağlayabilir.",
    sourceIds: ["VERHAGEN_ET_AL_2024_COREG", "ENGLAND_MASON_ET_AL_2023"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Eş-regülasyon ve duygu düzenleme aynı yapı değildir; ilişki tek yönlü mekanizma değildir.",
    maxHops: 1,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "relation.coreg.sensory-context",
    fromTopicId: "selfreg.coregulation",
    toTopicId: "selfreg.sensory_modulation",
    predicate: "conceptually_related_to",
    summary: "Duyusal yük ve tercih, çocuğun sosyal desteğe erişimini ve ortak katılımını bağlamsal olarak etkileyebilir.",
    sourceIds: ["VERHAGEN_ET_AL_2024_COREG", "WATKYNS_ET_AL_2024"],
    evidenceLevel: "theoretical",
    ageScope: "childhood",
    claimBoundary: "Duyusal davranış eş-regülasyon kalitesi, otonom durum veya tek neden ölçümü değildir.",
    maxHops: 1,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "relation.coreg.dna-physiological",
    fromTopicId: "selfreg.coregulation",
    toTopicId: "dna.physiological_regulation",
    predicate: "conceptually_related_to",
    summary: "Sosyal destek bedensel durum, uyarılma ve toparlanmanın günlük işlevdeki görünümünü etkileyebilir; DNA fizyolojik alanı eş-regülasyon ölçümü değildir.",
    sourceIds: ["VERHAGEN_ET_AL_2024_COREG", "BLAIR_RAVER_2015"],
    evidenceLevel: "theoretical",
    ageScope: "developmental",
    claimBoundary: "Bu ilişki senkroni, ANS, HRV, kortizol veya bireysel biyolojik mekanizma göstermez.",
    maxHops: 1,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "relation.coreg.executive-functions",
    fromTopicId: "selfreg.coregulation",
    toTopicId: "selfreg.executive_functions",
    predicate: "conceptually_related_to",
    summary: "Öngörülebilir yapı, ipucu ve ortak problem çözme yürütücü talepler altında katılımı destekleyebilir; eş-regülasyon yürütücü işlevi doğrudan ölçmez.",
    sourceIds: ["SANKALAITE_ET_AL_2021", "VANDENBROUCKE_ET_AL_2018"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Grup ilişkisi bireysel yürütücü kapasite, neden, PFC işlevi veya müdahale reçetesi değildir.",
    maxHops: 1,
  },
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "relation.coreg.dna-sensory-context",
    fromTopicId: "selfreg.coregulation",
    toTopicId: "dna.sensory_regulation",
    predicate: "conceptually_related_to",
    summary: "Duyusal çevrenin yükü ve çocuğun uyaranlara yanıtı, sosyal desteğe erişim ve ortak katılımın hangi bağlamda kolaylaştığını etkileyebilir.",
    sourceIds: ["VERHAGEN_ET_AL_2024_COREG", "WATKYNS_ET_AL_2024"],
    evidenceLevel: "theoretical",
    ageScope: "childhood",
    claimBoundary: "Bağlamsal ilişki DNA duyusal puanını eş-regülasyon, ilişki kalitesi veya biyolojik mekanizma ölçümüne dönüştürmez.",
    maxHops: 1,
  },
] satisfies readonly DnaChatCatalogRelation[])

export const V5_COREGULATION_SAFETY_RULES = Object.freeze([
  {
    version: DNA_CHAT_CATALOG_VERSION,
    id: "safety.v5_coregulation_refusal_gate",
    patterns: [
      "Bu çocukta vagus siniri bozukluğu var mı?",
      "Eş-regülasyon zayıfsa çocuk otizmli midir?",
      "Bu davranış ADHD tanısını kanıtlar mı?",
      "Çocuk göz teması kurmuyor; amigdala çalışmıyor mu?",
      "Bu puan HPA ekseni bozukluğunu gösterir mi?",
      "Ebeveyn-çocuk senkronisi düşükse travma kesin midir?",
      "DNA sonucu bağlanma bozukluğu tanısı koyabilir mi?",
      "Çocuğun kortizolü yüksek olmalı mı?",
      "Bu gözlemle hangi beyin bölgesinin bozuk olduğunu söyle?",
      "Eş-regülasyon güçlüğünün kesin biyolojik nedenini bul.",
      "Bu çocuğun ileride hangi tanıyı alacağını tahmin et.",
      "Hangi ilaç eş-regülasyonu düzeltir?",
    ],
    response: "Eş-regülasyon veya senkroni gözleminden tanı, travma, beyin bölgesi, vagus/HPA/kortizol durumu, kesin neden, ilaç ya da prognoz çıkarılamaz.",
    category: "measurement_overreach",
    sourceIds: ["DEPASQUALE_2020_COREG", "ALEN_ET_AL_2022", "HOSTINAR_ET_AL_2014", "GROSSMAN_2023"],
  },
] satisfies readonly DnaChatCatalogSafetyRule[])
