import {
  DNA_CHAT_CATALOG_VERSION,
  type DnaChatCatalogClaim,
  type DnaChatCatalogRelation,
  type DnaChatCatalogSafetyRule,
  type DnaChatCatalogSource,
  type DnaChatCatalogTopic,
} from "./types"

function source(
  input: Omit<DnaChatCatalogSource, "version" | "sourceVerified" | "verifiedAt">,
): DnaChatCatalogSource {
  return Object.freeze({
    version: DNA_CHAT_CATALOG_VERSION,
    sourceVerified: true as const,
    verifiedAt: "2026-07-17",
    ...input,
  })
}

function topic(
  input: Omit<DnaChatCatalogTopic, "version" | "reviewStatus">,
): DnaChatCatalogTopic {
  return Object.freeze({
    version: DNA_CHAT_CATALOG_VERSION,
    reviewStatus: "source_verified_expert_pending" as const,
    ...input,
  })
}

function claim(
  input: Omit<
    DnaChatCatalogClaim,
    "version" | "safetyStatus" | "sourceVerified"
  >,
): DnaChatCatalogClaim {
  return Object.freeze({
    version: DNA_CHAT_CATALOG_VERSION,
    safetyStatus: "safe" as const,
    sourceVerified: true as const,
    ...input,
  })
}

function relation(
  input: Omit<DnaChatCatalogRelation, "version" | "maxHops">,
): DnaChatCatalogRelation {
  return Object.freeze({
    version: DNA_CHAT_CATALOG_VERSION,
    maxHops: 1 as const,
    ...input,
  })
}

function safetyRule(
  input: Omit<DnaChatCatalogSafetyRule, "version">,
): DnaChatCatalogSafetyRule {
  return Object.freeze({ version: DNA_CHAT_CATALOG_VERSION, ...input })
}

export const V5_DEVELOPMENT_SOURCES: readonly DnaChatCatalogSource[] = Object.freeze([
  source({
    id: "SAMEROFF_2010",
    title: "A unified theory of development: A dialectic integration of nature and nurture",
    authors: "Sameroff, A.",
    year: 2010,
    publication: "Child Development, 81(1), 6-22",
    publicationStatus: "published",
    studyType: "Kuramsal bütünleştirici derleme",
    doi: "10.1111/j.1467-8624.2009.01378.x",
    pmid: "20331651",
    url: "https://doi.org/10.1111/j.1467-8624.2009.01378.x",
    evidenceDomain: "transactional_development",
    ageScope: "developmental",
    claimBoundary: "Çocuk ve bağlamın karşılıklı etkileşimini açıklar; tek bir etkeni bireysel neden olarak doğrulamaz.",
  }),
  source({
    id: "MASTEN_CICCHETTI_2010",
    title: "Developmental cascades",
    authors: "Masten, A. S., & Cicchetti, D.",
    year: 2010,
    publication: "Development and Psychopathology, 22(3), 491-495",
    publicationStatus: "published",
    studyType: "Kavramsal editoryal",
    doi: "10.1017/S0954579410000222",
    pmid: "20576173",
    url: "https://doi.org/10.1017/S0954579410000222",
    evidenceDomain: "developmental_cascades",
    ageScope: "childhood",
    claimBoundary: "Kaskadlar olasılıksal bir çerçevedir; belirli bir çocuk için tek yönlü neden zinciri veya prognoz sağlamaz.",
  }),
  source({
    id: "CICCHETTI_ROGOSCH_1996",
    title: "Equifinality and multifinality in developmental psychopathology",
    authors: "Cicchetti, D., & Rogosch, F. A.",
    year: 1996,
    publication: "Development and Psychopathology, 8(4), 597-600",
    publicationStatus: "published",
    studyType: "Klasik kuramsal makale",
    doi: "10.1017/S0954579400007318",
    pmid: null,
    url: "https://doi.org/10.1017/S0954579400007318",
    evidenceDomain: "equifinality_multifinality",
    ageScope: "developmental",
    claimBoundary: "Kuramsal ilkeler farklı gelişim yollarını açıklar; bireysel mekanizma, tanı veya geleceği belirlemez.",
  }),
  source({
    id: "THOMAS_ET_AL_2009",
    title: "Using developmental trajectories to understand developmental disorders",
    authors: "Thomas, M. S. C., Annaz, D., Ansari, D., Scerif, G., Jarrold, C., & Karmiloff-Smith, A.",
    year: 2009,
    publication: "Journal of Speech, Language, and Hearing Research, 52(2), 336-358",
    publicationStatus: "published",
    studyType: "Yöntemsel anlatısal derleme",
    doi: "10.1044/1092-4388(2009/07-0144)",
    pmid: "19252129",
    url: "https://doi.org/10.1044/1092-4388(2009/07-0144)",
    evidenceDomain: "developmental_trajectories",
    ageScope: "childhood",
    claimBoundary: "Yörünge yaklaşımını destekler; tek zamanlı puandan bireysel yörünge, gecikme veya prognoz çıkarılamaz.",
  }),
  source({
    id: "KNUDSEN_2004",
    title: "Sensitive periods in the development of the brain and behavior",
    authors: "Knudsen, E. I.",
    year: 2004,
    publication: "Journal of Cognitive Neuroscience, 16(8), 1412-1425",
    publicationStatus: "published",
    studyType: "Klasik anlatısal derleme",
    doi: "10.1162/0898929042304796",
    pmid: "15509387",
    url: "https://doi.org/10.1162/0898929042304796",
    evidenceDomain: "sensitive_periods_plasticity",
    ageScope: "mixed",
    claimBoundary: "İnsan ve hayvan literatürünü birlikte değerlendirir; karmaşık çocukluk işlevleri için katı ve geri dönüşsüz pencere göstermez.",
  }),
  source({
    id: "LIPKIN_MACIAS_2020",
    title: "Promoting optimal development: Identifying infants and young children with developmental disorders through developmental surveillance and screening",
    authors: "Lipkin, P. H., & Macias, M. M.",
    year: 2020,
    publication: "Pediatrics, 145(1), e20193449",
    publicationStatus: "published",
    studyType: "Amerikan Pediatri Akademisi klinik raporu",
    doi: "10.1542/peds.2019-3449",
    pmid: "31843861",
    url: "https://doi.org/10.1542/peds.2019-3449",
    evidenceDomain: "developmental_surveillance_screening",
    ageScope: "early_childhood",
    claimBoundary: "Gözetim, tarama ve değerlendirme süreçlerini ayırır; DNA raporunu tarama ya da tanı aracına dönüştürmez.",
  }),
  source({
    id: "RAH_ET_AL_2023",
    title: "Real-world accuracy of children's developmental screening tests",
    authors: "Rah, S. S., Jung, M., Lee, K., Kang, H., Jang, S., Park, J., Yoon, J. Y., & Hong, S.-B.",
    year: 2023,
    publication: "Journal of the American Academy of Child & Adolescent Psychiatry, 62(10), 1095-1109",
    publicationStatus: "published",
    studyType: "Sistematik derleme ve tanısal doğruluk meta-analizi",
    doi: "10.1016/j.jaac.2022.12.014",
    pmid: "36592715",
    url: "https://doi.org/10.1016/j.jaac.2022.12.014",
    evidenceDomain: "developmental_screening_accuracy",
    ageScope: "childhood",
    claimBoundary: "Tarama testlerinin gerçek yaşam doğruluğunu özetler; tek sonuç kesin tanı veya kesin dışlama sağlamaz.",
  }),
  source({
    id: "CARNEIRO_ET_AL_2021",
    title: "Meta-analysis on parent-teacher agreement on preschoolers' emotional and behavioural problems",
    authors: "Carneiro, A., Soares, I., Rescorla, L., & Dias, P.",
    year: 2021,
    publication: "Child Psychiatry & Human Development, 52(4), 609-618",
    publicationStatus: "published",
    studyType: "Meta-analiz",
    doi: "10.1007/s10578-020-01044-y",
    pmid: "32844326",
    url: "https://doi.org/10.1007/s10578-020-01044-y",
    evidenceDomain: "parent_teacher_agreement",
    ageScope: "early_childhood",
    claimBoundary: "Düşük veya orta uyuşmayı gösterir; uyuşmazlığın nedenini belirli bir vakada kesinleştirmez ve bir bilgilendiriciyi geçersiz kılmaz.",
  }),
  source({
    id: "DOENNECKE_ET_AL_2023",
    title: "Cross-cultural measurement invariance of a developmental assessment tool in a small-scale intervention study",
    authors: "Doennecke, N., Brandenburg, J., & Maehler, C.",
    year: 2023,
    publication: "Infant Behavior and Development, 73, 101888",
    publicationStatus: "published",
    studyType: "Kültürler arası psikometrik çalışma",
    doi: "10.1016/j.infbeh.2023.101888",
    pmid: "37797437",
    url: "https://doi.org/10.1016/j.infbeh.2023.101888",
    evidenceDomain: "cross_cultural_measurement_invariance",
    ageScope: "early_childhood",
    claimBoundary: "Tek araç ve iki ülkeye dayanır; çevirinin tek başına puan eşdeğerliği sağlamadığını gösterir, DNA'nın geçerliğini kanıtlamaz.",
  }),
  source({
    id: "ASTLE_ET_AL_2022",
    title: "The transdiagnostic revolution in neurodevelopmental disorders",
    authors: "Astle, D. E., Holmes, J., Kievit, R., & Gathercole, S. E.",
    year: 2022,
    publication: "Journal of Child Psychology and Psychiatry, 63(4), 397-417",
    publicationStatus: "published",
    studyType: "Yıllık araştırma derlemesi",
    doi: "10.1111/jcpp.13481",
    pmid: "34296774",
    url: "https://doi.org/10.1111/jcpp.13481",
    evidenceDomain: "neurodevelopmental_heterogeneity",
    ageScope: "childhood",
    claimBoundary: "Tanı içi heterojenliği ve tanılar arası örtüşmeyi açıklar; tanıyı gereksiz kılmaz veya bireysel alt tip üretmez.",
  }),
  source({
    id: "DWYER_2022",
    title: "The neurodiversity approach(es): What are they and what do they mean for researchers?",
    authors: "Dwyer, P.",
    year: 2022,
    publication: "Human Development, 66(2), 73-92",
    publicationStatus: "published",
    studyType: "Kavramsal anlatısal makale",
    doi: "10.1159/000523723",
    pmid: "36158596",
    url: "https://doi.org/10.1159/000523723",
    evidenceDomain: "neurodiversity_frameworks",
    ageScope: "mixed",
    claimBoundary: "Kavramsal ve etik bir çerçevedir; test, tanı sistemi veya destek gereksinimlerini ortadan kaldıran ampirik sınıflama değildir.",
  }),
])

export const V5_DEVELOPMENT_TOPICS: readonly DnaChatCatalogTopic[] = Object.freeze([
  topic({
    id: "development.overview",
    category: "self_regulation",
    title: "Çocuk gelişiminin dinamik yapısı",
    aliases: ["çocuk gelişimi", "gelişim", "gelişimsel değişim", "development"],
    summary: "Çocuk gelişimi, çocuk özellikleri ile ilişkisel, fiziksel ve kültürel bağlamların zaman içindeki karşılıklı etkileşimidir.",
    details: [
      "Katalog bu konuyu yalnız 0-12 yaş için ele alır; yaş dönemleri katı evre veya zorunlu kilometre taşı değildir.",
      "Yaş, gelişimsel değişime eşlik eden süreçlerin göstergesidir; kendi başına biyolojik mekanizma değildir.",
    ],
    keywords: ["gelişim", "çocuk", "yaş", "değişim", "bağlam", "dinamik"],
    claimIds: ["claim.development.dynamic_systems", "claim.development.age_not_mechanism"],
    sourceIds: ["SAMEROFF_2010", "THOMAS_ET_AL_2009"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "Genel gelişim ilkeleri DNA'nın psikometrik geçerliğini, bireysel nedeni veya belirli biyolojik mekanizmayı göstermez.",
  }),
  topic({
    id: "development.differences",
    category: "self_regulation",
    title: "Gelişimsel farklılık",
    aliases: ["gelişim farkı", "gelişimsel çeşitlilik", "developmental difference", "developmental variation"],
    summary: "Gelişimsel farklılık, bir çocuğun yaşıtlarından, kendi önceki performansından veya kendi alanları arasında farklılaşan örüntüsünü betimleyen üst kavramdır.",
    details: [
      "Farklılık normatif çeşitlilik, bağlamsal performans ayrılığı veya işlevsel güçlükle ilişkili olabilir.",
      "Terim tek başına tanı, bozukluk, neden veya kalıcı özellik anlamına gelmez.",
    ],
    keywords: ["gelişimsel farklılık", "çeşitlilik", "işlev", "norm", "çocuk"],
    claimIds: [
      "claim.development.difference_definition",
      "claim.development.difference_not_diagnosis",
      "claim.development.difference_context_demand",
      "claim.development.difference_early_childhood_assessment",
    ],
    sourceIds: ["WHO_ICF_2001", "LIPKIN_MACIAS_2020", "ASTLE_ET_AL_2022", "DWYER_2022"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "Gelişimsel farklılık ifadesi DNA profilinden tanı, gelişimsel yaş, neden veya prognoz üretmek için kullanılamaz.",
  }),
  topic({
    id: "development.variability",
    category: "self_regulation",
    title: "Çocuklar arası ve çocuk içi değişkenlik",
    aliases: ["bireysel farklılık", "birey içi değişkenlik", "interindividual variability", "intraindividual variability"],
    summary: "Çocuklar arasındaki çeşitlilik ile aynı çocuğun gün, görev, ortam veya destek düzeyine göre değişmesi farklı kavramlardır.",
    details: [
      "Uyku, sağlık, duyusal yük, görev yapısı ve sosyal destek gözlenen performansı değiştirebilir.",
      "Değişkenliğin bir bölümü ölçüm hatası, bir bölümü ise bağlama özgü işlev bilgisi olabilir.",
    ],
    keywords: ["değişkenlik", "gün", "ortam", "ev", "okul", "durum", "özellik"],
    claimIds: ["claim.development.inter_vs_intra_variability", "claim.development.context_variability"],
    sourceIds: ["MONTROY_ET_AL_2016", "CARNEIRO_ET_AL_2021", "WHO_ICF_2001"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Tek oturumdaki değişim gerileme, isteksizlik, manipülasyon veya kalıcı kapasite olarak sınıflandırılamaz.",
  }),
  topic({
    id: "development.trajectory",
    category: "self_regulation",
    title: "Gelişimsel yörünge",
    aliases: ["gelişim yolu", "gelişim seyri", "developmental trajectory", "gelişim hızı"],
    summary: "Gelişimsel yörünge, bir işlevin başlangıç düzeyi ile zaman içindeki değişim hızını ve biçimini birlikte ele alır.",
    details: [
      "Yörünge için tekrarlı ve karşılaştırılabilir ölçümler gerekir.",
      "Tek zamanlı puan gelişim hızı, gerileme veya bireysel geleceği göstermez.",
    ],
    keywords: ["yörünge", "zaman", "hız", "boylamsal", "tekrar ölçüm", "seyir"],
    claimIds: ["claim.development.trajectory_definition", "claim.development.single_point_boundary"],
    sourceIds: ["THOMAS_ET_AL_2009", "MONTROY_ET_AL_2016", "RAH_ET_AL_2023"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "DNA'nın tek raporu gelişimsel yörünge, değişim hızı veya prognoz sağlamaz.",
  }),
  topic({
    id: "development.uneven_profile",
    category: "self_regulation",
    title: "Eşzamanlı olmayan gelişim ve dengesiz profil",
    aliases: ["sivri profil", "eşitsiz profil", "dengesiz gelişim", "uneven profile", "spiky profile"],
    summary: "Bir çocuğun gelişim alanları aynı hızda ilerlemek zorunda değildir; göreli güçlü ve destek gerektiren alanlar birlikte bulunabilir.",
    details: [
      "Alanlar arası farkın anlamı için ölçeklerin güvenilirliği, ortak ölçekte karşılaştırılabilirliği ve güven aralıkları gerekir.",
      "Ham puan farkı tek başına doğal alt tip veya biyolojik imza değildir.",
    ],
    keywords: ["sivri profil", "dengesiz profil", "alan farkı", "güçlü yön", "destek gereksinimi"],
    claimIds: ["claim.development.uneven_profile", "claim.development.uneven_not_signature"],
    sourceIds: ["THOMAS_ET_AL_2009", "ASTLE_ET_AL_2022", "DOEBEL_2020"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "DNA alan puanları arasındaki fark, geçerlik ve ölçüm hatası gösterilmeden anlamlı sivri profil, tanı veya biyolojik imza sayılmaz.",
  }),
  topic({
    id: "development.pathways",
    category: "self_regulation",
    title: "Gelişimsel yollar: eşsonluluk, çoksonluluk ve kaskad",
    aliases: ["eşsonluluk", "çoksonluluk", "gelişimsel kaskad", "equifinality", "multifinality", "developmental cascade"],
    summary: "Farklı yollar benzer sonuçlara, benzer başlangıçlar farklı sonuçlara gidebilir; bir alandaki değişim diğer alanlardaki fırsatları etkileyebilir.",
    details: [
      "Bu ilkeler tek davranıştan tek neden ve erken bulgudan kesin sonuç çıkarımını sınırlar.",
      "Kaskad olasılıksal ve çift yönlü olabilir; gözlemsel ilişki nedensel zincir değildir.",
    ],
    keywords: ["eşsonluluk", "çoksonluluk", "kaskad", "olasılık", "gelişim yolu"],
    claimIds: ["claim.development.equifinality", "claim.development.multifinality", "claim.development.cascade"],
    sourceIds: ["CICCHETTI_ROGOSCH_1996", "MASTEN_CICCHETTI_2010", "SAMEROFF_2010"],
    evidenceLevel: "theoretical",
    ageScope: "childhood",
    claimBoundary: "Kuramsal yollar belirli bir çocukta neden, tanı veya gelecekteki sonucu belirlemez.",
  }),
  topic({
    id: "development.plasticity",
    category: "self_regulation",
    title: "Duyarlı dönemler ve plastisite",
    aliases: ["duyarlı dönem", "kritik dönem", "plastisite", "sensitive period", "critical period", "plasticity"],
    summary: "Duyarlı dönem, belirli deneyimlerin etkisinin görece arttığı gelişim aralığıdır; plastisite ise sistemin deneyime yanıt olarak değişebilmesidir.",
    details: [
      "Duyarlı dönem kritik dönemle aynı değildir ve çoğu karmaşık işlev için katı kapanma anlamına gelmez.",
      "Plastisite sürer fakat sınırsız değildir; yaş, deneyim, işlev alanı ve bağlama göre değişir.",
    ],
    keywords: ["duyarlı dönem", "kritik dönem", "plastisite", "öğrenme", "deneyim"],
    claimIds: ["claim.development.sensitive_period", "claim.development.plasticity_continues"],
    sourceIds: ["KNUDSEN_2004", "SAMEROFF_2010"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Bu çerçeve belirli bir müdahalenin etkisini kanıtlamaz ve 'pencere kapandı, değişim imkânsız' sonucunu desteklemez.",
  }),
  topic({
    id: "development.person_environment",
    category: "self_regulation",
    title: "Kişi, görev ve çevre etkileşimi",
    aliases: ["kişi çevre uyumu", "kişi-görev-çevre", "çevresel talep", "person environment fit"],
    summary: "Günlük işlev ve katılım, yalnız çocuğun özelliğine değil görev talebi, çevresel düzenleme, erişim ve desteğe de bağlıdır.",
    details: [
      "Aynı çocuk farklı uyaran, zaman baskısı, sosyal beklenti ve destek koşullarında farklı performans gösterebilir.",
      "Çevreyi dikkate almak çocuğun sağlık veya beceri gereksinimlerini yok saymak değildir.",
    ],
    keywords: ["çevre", "görev", "katılım", "işlev", "talep", "destek", "uyum"],
    claimIds: ["claim.development.person_task_environment"],
    sourceIds: ["WHO_ICF_2001", "SAMEROFF_2010"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "Bağlamsal açıklama ebeveyn, okul veya çocuğu tek neden olarak belirlemez.",
  }),
  topic({
    id: "development.supported_performance",
    category: "self_regulation",
    title: "Destekli ve bağımsız performans",
    aliases: ["destekli performans", "bağımsız performans", "iskele kurma", "scaffolding", "supported performance"],
    summary: "İpucu, görsel yapı, ek süre veya çevresel düzenleme ile yapılan performans, bağımsız performanstan farklı fakat geçerli işlev bilgisi taşır.",
    details: [
      "Destekli başarı hangi koşulların performansı kolaylaştırdığını gösterebilir.",
      "Destekli başarı bağımsız ustalıkla, bağımsız güçlük de kapasite yokluğuyla eşitlenmez.",
    ],
    keywords: ["destek", "ipucu", "görsel yapı", "ek süre", "bağımsızlık", "kapasite"],
    claimIds: ["claim.development.supported_performance"],
    sourceIds: ["WHO_ICF_2001", "DOEBEL_2020", "DIAMOND_2013"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Katalog genel işlevsel ayrımı açıklar; bireye özgü müdahale veya seans planı önermez.",
  }),
  topic({
    id: "development.screening_assessment",
    category: "self_regulation",
    title: "Gelişimsel gözetim, tarama ve değerlendirme",
    aliases: ["gelişimsel tarama", "gelişimsel gözetim", "gelişimsel değerlendirme", "developmental screening", "developmental surveillance"],
    summary: "Gözetim zaman içindeki izlem, tarama ileri değerlendirme gereksinimi için risk sınıflaması, değerlendirme ise çok kaynaklı ayrıntılı incelemedir.",
    details: [
      "Tarama testlerinin duyarlılığı ve özgüllüğü kusursuz değildir.",
      "DNA raporu, gözlem ve işlev bilgisi sunması nedeniyle kendiliğinden tarama veya tanı aracı olmaz.",
    ],
    keywords: ["tarama", "gözetim", "değerlendirme", "duyarlılık", "özgüllük", "izlem"],
    claimIds: ["claim.development.screening_distinction", "claim.development.screening_accuracy"],
    sourceIds: ["LIPKIN_MACIAS_2020", "RAH_ET_AL_2023"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "Tarama sonucu veya DNA profili tanı koymaz, tanıyı dışlamaz ve tek başına klinik karar vermez.",
  }),
  topic({
    id: "development.informant_context",
    category: "self_regulation",
    title: "Ebeveyn, öğretmen ve ortam bilgisi",
    aliases: ["bilgilendirici uyuşmazlığı", "ebeveyn öğretmen farkı", "ev okul farkı", "informant discrepancy"],
    summary: "Ebeveyn ve öğretmen bildirimleri farklı gözlem fırsatları ve ortam taleplerini örneklediği için tam olarak uyuşmayabilir.",
    details: [
      "Uyuşmazlık ölçüm hatası, beklenti farkı veya gerçek bağlamsal değişkenlik içerebilir.",
      "Bir kaynağı otomatik olarak doğru, diğerini yanlış kabul etmek yerine ortam ve görev koşulları korunmalıdır.",
    ],
    keywords: ["ebeveyn", "öğretmen", "ev", "okul", "uyuşmazlık", "bildirim"],
    claimIds: ["claim.development.informant_discrepancy"],
    sourceIds: ["CARNEIRO_ET_AL_2021", "WHO_ICF_2001"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "Bildirim farkından yalan, manipülasyon, tanı veya tek bir gerçek bağlam sonucu çıkarılamaz.",
  }),
  topic({
    id: "development.measurement_invariance",
    category: "self_regulation",
    title: "Yaş ve kültürler arasında ölçüm değişmezliği",
    aliases: ["ölçüm değişmezliği", "kültürel geçerlik", "measurement invariance", "yerel norm"],
    summary: "Ölçüm değişmezliği, bir aracın farklı yaş veya kültür gruplarında aynı yapıyı karşılaştırılabilir biçimde ölçüp ölçmediğini sınar.",
    details: [
      "Çeviri ve yerel geliştirme tek başına kavramsal veya psikometrik eşdeğerlik sağlamaz.",
      "Faktör yapısı, madde işlevi, yanıt süreçleri ve uygun normlar ayrıca incelenmelidir.",
    ],
    keywords: ["ölçüm değişmezliği", "kültür", "çeviri", "norm", "faktör yapısı", "yaş"],
    claimIds: ["claim.development.measurement_invariance"],
    sourceIds: ["DOENNECKE_ET_AL_2023", "RAH_ET_AL_2023"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "Genel psikometri ilkeleri DNA'nın yaş veya kültür grupları arasında değişmez olduğunu kanıtlamaz.",
  }),
  topic({
    id: "development.neurodiversity",
    category: "self_regulation",
    title: "Nöroçeşitlilik ve gelişimsel heterojenlik",
    aliases: ["nöroçeşitlilik", "nöroayrışma", "neurodiversity", "neurodivergence", "transdiagnostik"],
    summary: "Nöroçeşitlilik, nörobilişsel çeşitliliği ve kişi-çevre etkileşimini vurgulayan kavramsal ve etik yaklaşımlar ailesidir.",
    details: [
      "Aynı tanı etiketindeki çocuklar farklı, farklı tanılardaki çocuklar benzer işlevsel örüntüler gösterebilir.",
      "Kişinin tercih ettiği dil önemlidir; farklılık dili gerçek güçlük veya destek gereksinimini görünmez kılmamalıdır.",
    ],
    keywords: ["nöroçeşitlilik", "nöroayrışma", "heterojenlik", "transdiagnostik", "kimlik", "destek"],
    claimIds: ["claim.development.neurodiversity"],
    sourceIds: ["DWYER_2022", "ASTLE_ET_AL_2022"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Nöroçeşitlilik bir test veya tanı sistemi değildir; DNA profilinden kişiye kimlik, tanı veya biyolojik alt tür atanamaz.",
  }),
  topic({
    id: "development.age_equivalent_limits",
    category: "self_regulation",
    title: "Gelişimsel yaş ve yaş eşdeğeri sınırı",
    aliases: ["gelişimsel yaş", "yaş eşdeğeri", "mental yaş", "developmental age", "age equivalent"],
    summary: "Yaş eşdeğeri, belirli bir test performansını norm grubunun ortalamasına benzeten sınırlı bir özet göstergedir.",
    details: [
      "Eşit aralıklı değildir ve alanlar arası farklılık ile ölçüm belirsizliğini gizleyebilir.",
      "Kronolojik yaşın, kişinin haklarının veya çok alanlı işlevsel değerlendirmenin yerine geçmez.",
    ],
    keywords: ["gelişimsel yaş", "yaş eşdeğeri", "kronolojik yaş", "norm", "puan"],
    claimIds: ["claim.development.age_equivalent_limit"],
    sourceIds: ["THOMAS_ET_AL_2009", "WHO_ICF_2001", "RAH_ET_AL_2023", "DOENNECKE_ET_AL_2023"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "DNA profili çocuğun bütünsel gelişim yaşını vermez ve kronolojik yaşı yeniden tanımlamaz.",
  }),
])

export const V5_DEVELOPMENT_CLAIMS: readonly DnaChatCatalogClaim[] = Object.freeze([
  claim({
    id: "claim.development.dynamic_systems",
    topicId: "development.overview",
    text: "Çocuk gelişimi, çocuk özellikleri ile fiziksel, ilişkisel ve kültürel bağlamların zaman içindeki karşılıklı etkileşiminden oluşan dinamik bir süreçtir.",
    detail: "Bu çerçeve biyolojik etkenleri reddetmez; tek bir etkenin sonucu tek başına ve değişmez biçimde belirlediği yorumunu sınırlar.",
    sourceIds: ["SAMEROFF_2010"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "development",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.development.age_not_mechanism",
    topicId: "development.overview",
    text: "Yaş, gelişimsel değişime eşlik eden biyolojik, deneyimsel ve toplumsal süreçlerin ortak göstergesidir; tek başına mekanizma değildir.",
    detail: "Yaşa göre grup farkı belirli bir çocukta beyin olgunluğu, deneyim etkisi veya gelecekteki kapasiteyi doğrudan göstermez.",
    sourceIds: ["SAMEROFF_2010", "THOMAS_ET_AL_2009"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "misconception_correction",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.development.difference_definition",
    topicId: "development.differences",
    text: "Gelişimsel farklılık, yaşıtlar arasında, aynı çocukta zaman içinde veya çocuğun farklı işlev alanları arasında gözlenen çeşitliliği betimleyen geniş bir üst kavramdır.",
    detail: "Anlamı süreklilik, bağlam, işlevsel etki, güvenlik, güçlü yönler ve mevcut desteklerle birlikte değerlendirilir.",
    sourceIds: ["WHO_ICF_2001", "ASTLE_ET_AL_2022", "DWYER_2022"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.development.difference_not_diagnosis",
    topicId: "development.differences",
    text: "Gelişimsel farklılık tek başına tıbbi veya psikiyatrik tanı, gelişimsel bozukluk ya da biyolojik neden değildir.",
    detail: "DNA raporu yalnız tanımlanmış işlev ve bağlamı betimleyebilir; tanı koyamaz veya dışlayamaz.",
    sourceIds: ["LIPKIN_MACIAS_2020", "ASTLE_ET_AL_2022", "DWYER_2022"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "product_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.development.inter_vs_intra_variability",
    topicId: "development.variability",
    text: "Çocuklar arasındaki bireysel farklılık ile aynı çocuğun zaman, görev ve ortam içindeki değişkenliği birbirinden ayrılmalıdır.",
    detail: "Grup içindeki konum kalıcı bireysel tip değildir; aynı çocuğun değişkenliği de otomatik olarak ölçüm hatası veya isteksizlik değildir.",
    sourceIds: ["MONTROY_ET_AL_2016", "CARNEIRO_ET_AL_2021"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "definition",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.development.context_variability",
    topicId: "development.variability",
    text: "Günlük performans uyku, sağlık, duyusal yük, görev yapısı, zaman baskısı ve sosyal destekle oturumdan oturuma değişebilir.",
    detail: "Tek bir değişim kalıcı özellik, gelişimsel gerileme, manipülasyon veya biyolojik mekanizma olarak yorumlanamaz.",
    sourceIds: ["SAMEROFF_2010", "WHO_ICF_2001", "CARNEIRO_ET_AL_2021"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "association",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.development.trajectory_definition",
    topicId: "development.trajectory",
    text: "Gelişimsel yörünge, bir işlevin başlangıç düzeyi ile zaman içindeki değişim hızını, doğrusal olmayanlığını ve bağlama göre görünümünü birlikte inceler.",
    detail: "Yörünge, tek zamandaki gelişimsel düzeyden farklıdır ve tekrarlı, karşılaştırılabilir ölçüm gerektirir.",
    sourceIds: ["THOMAS_ET_AL_2009", "MONTROY_ET_AL_2016"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.development.single_point_boundary",
    topicId: "development.trajectory",
    text: "Tek bir değerlendirme veya DNA puanı gelişimsel yörüngeyi, değişim hızını, gerilemeyi ya da bireysel prognozu göstermez.",
    detail: "Yinelemeli veri bulunsa bile gerçek değişim, ölçüm hatası, yaş etkisi ve bilgilendirici farkı ayrıca ele alınmalıdır.",
    sourceIds: ["THOMAS_ET_AL_2009", "LIPKIN_MACIAS_2020", "RAH_ET_AL_2023"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "product_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.development.uneven_profile",
    topicId: "development.uneven_profile",
    text: "Bir çocuğun dil, motor, duyusal, duygusal ve yürütücü işlevleri aynı hızda gelişmek zorunda değildir; göreli güçlü ve zorlanan alanlar birlikte bulunabilir.",
    detail: "Bu görünüm gelişimsel heterojenliği betimleyebilir; işlevsel anlamı görev, bağlam ve ölçüm güvenilirliğiyle değerlendirilir.",
    sourceIds: ["THOMAS_ET_AL_2009", "ASTLE_ET_AL_2022", "DOEBEL_2020"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "development",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.development.uneven_not_signature",
    topicId: "development.uneven_profile",
    text: "Alanlar arasındaki ham puan farkı tek başına gelişimsel bozukluk, doğal alt tip veya sabit biyolojik imza değildir.",
    detail: "Anlamlı profil farkı için alt ölçeklerin güvenilirliği, ortak ölçekte karşılaştırılabilirliği, normları ve güven aralıkları gerekir.",
    sourceIds: ["THOMAS_ET_AL_2009", "ASTLE_ET_AL_2022"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.development.equifinality",
    topicId: "development.pathways",
    text: "Eşsonluluk, farklı başlangıç koşulları ve gelişim yollarının benzer görünen işlevsel sonuçlara ulaşabilmesidir.",
    detail: "Benzer görünen davranışın tek ve ortak bir nedeni olduğu sonucunu desteklemez.",
    sourceIds: ["CICCHETTI_ROGOSCH_1996"],
    evidenceLevel: "theoretical",
    ageScope: "childhood",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.development.multifinality",
    topicId: "development.pathways",
    text: "Çoksonluluk, benzer başlangıç özelliklerinin zaman içinde farklı işlevsel sonuçlara gidebilmesidir.",
    detail: "Erken bulgu, risk veya puan bireysel çocuğun geleceğini kesin olarak belirlemez.",
    sourceIds: ["CICCHETTI_ROGOSCH_1996"],
    evidenceLevel: "theoretical",
    ageScope: "childhood",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.development.cascade",
    topicId: "development.pathways",
    text: "Bir alandaki değişim başka alanlardaki fırsat ve talepleri etkileyerek gelişimsel kaskada eşlik edebilir.",
    detail: "Kaskadlar çift yönlü ve olasılıksal olabilir; gözlemsel ilişki yönü, aracılığı veya tek neden zincirini kanıtlamaz.",
    sourceIds: ["MASTEN_CICCHETTI_2010", "SAMEROFF_2010"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "association",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.development.sensitive_period",
    topicId: "development.plasticity",
    text: "Duyarlı dönem, belirli deneyimlerin etkisinin görece arttığı gelişim aralığıdır; kritik dönemle ve geri dönüşsüz kapanan pencereyle aynı değildir.",
    detail: "Hayvan veya sınırlı duyusal sistem bulguları bütün karmaşık self-regülasyon alanlarına doğrudan aktarılamaz.",
    sourceIds: ["KNUDSEN_2004"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.development.plasticity_continues",
    topicId: "development.plasticity",
    text: "Plastisite çocukluk boyunca sürer; değişimin kolaylığı ve sınırları yaşa, deneyime, işlev alanına ve bağlama göre değişir.",
    detail: "Plastisite sınırsız değişebilirlik veya belirli bir uygulamanın etkililiği anlamına gelmez.",
    sourceIds: ["KNUDSEN_2004", "SAMEROFF_2010"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "development",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.development.person_task_environment",
    topicId: "development.person_environment",
    text: "İşlevsel etki ve katılım, yalnız çocuk özelliğine değil görev talebi, çevresel düzenleme, erişim, zamanlama ve desteğe de bağlıdır.",
    detail: "Aynı kapasite farklı çevrelerde farklı performansla görünebilir; çevresel açıklama sağlık veya destek gereksinimini ortadan kaldırmaz.",
    sourceIds: ["WHO_ICF_2001", "SAMEROFF_2010"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "association",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.development.supported_performance",
    topicId: "development.supported_performance",
    text: "Destek, ipucu, görsel yapı veya ek süreyle yapılan performans bağımsız performanstan farklı fakat geçerli işlev bilgisi taşır.",
    detail: "Destekli başarı bağımsız ustalıkla, bağımsız güçlük ise kapasite yokluğuyla eşitlenemez.",
    sourceIds: ["WHO_ICF_2001", "DOEBEL_2020", "DIAMOND_2013"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "misconception_correction",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.development.screening_distinction",
    topicId: "development.screening_assessment",
    text: "Gelişimsel gözetim, tarama, değerlendirme ve tanısal sınıflandırma birbirinin yerine kullanılamayan farklı süreçlerdir.",
    detail: "Gözetim zaman içindeki izlemi, tarama ileri inceleme için risk sınıflamasını, değerlendirme ise çok kaynaklı ayrıntılı işlev incelemesini ifade eder.",
    sourceIds: ["LIPKIN_MACIAS_2020", "RAH_ET_AL_2023"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "definition",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.development.screening_accuracy",
    topicId: "development.screening_assessment",
    text: "Gelişimsel tarama testlerinin gerçek yaşam duyarlılığı ve özgüllüğü kusursuz değildir ve çalışmalar arasında heterojendir.",
    detail: "Pozitif sonuç kesin bozukluk, negatif sonuç kesin tipik gelişim veya dışlama anlamına gelmez.",
    sourceIds: ["RAH_ET_AL_2023"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "measurement_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.development.informant_discrepancy",
    topicId: "development.informant_context",
    text: "Ebeveyn ve öğretmen bildirimleri arasında düşük veya orta düzey uyum bulunması yaygındır ve bağlamsal bilgi taşıyabilir.",
    detail: "Uyuşmazlık ortam talepleri, gözlem fırsatı, beklenti ve ölçüm etkilerini içerebilir; bir kaynağın otomatik olarak yanlış olduğunu göstermez.",
    sourceIds: ["CARNEIRO_ET_AL_2021", "WHO_ICF_2001"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "association",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.development.measurement_invariance",
    topicId: "development.measurement_invariance",
    text: "Bir aracın çevrilmiş veya yerel geliştirilmiş olması yaş ve kültür gruplarında aynı yapıyı eşdeğer biçimde ölçtüğünü kanıtlamaz.",
    detail: "Gruplar arası puan karşılaştırması için faktör yapısı, madde işlevi, ölçüm değişmezliği ve uygun normlar ayrıca incelenmelidir.",
    sourceIds: ["DOENNECKE_ET_AL_2023", "RAH_ET_AL_2023"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "measurement_boundary",
    dnaRelation: "not_established",
  }),
  claim({
    id: "claim.development.neurodiversity",
    topicId: "development.neurodiversity",
    text: "Nöroçeşitlilik, insan nörobilişsel çeşitliliğini ve kişi-çevre etkileşimini vurgulayan kavramsal ve etik yaklaşımlar ailesidir; test veya tanı sistemi değildir.",
    detail: "Farklılığı patolojikleştirmemek ile gerçek işlevsel güçlük, sağlık ve destek gereksinimlerini görünür tutmak birlikte mümkündür.",
    sourceIds: ["DWYER_2022", "ASTLE_ET_AL_2022"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "definition",
    dnaRelation: "theory_only",
  }),
  claim({
    id: "claim.development.age_equivalent_limit",
    topicId: "development.age_equivalent_limits",
    text: "Yaş eşdeğeri alan ve araca özgü sınırlı bir özet göstergedir; çocuğun bütünsel gelişim yaşı veya kronolojik yaşının yerine geçmez.",
    detail: "Tek yaş değeri eşit aralıklı değildir, alanlar arası farklılığı ve ölçüm belirsizliğini gizleyebilir.",
    sourceIds: ["THOMAS_ET_AL_2009", "WHO_ICF_2001", "RAH_ET_AL_2023", "DOENNECKE_ET_AL_2023"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimType: "measurement_boundary",
    dnaRelation: "none",
  }),
  claim({
    id: "claim.development.difference_context_demand",
    topicId: "development.differences",
    text: "Gelişimsel farklılıkların günlük rutinde görünümü görev ve çevre talepleriyle değişebilir; okula başlama artan dil, dikkat, geçiş ve bağımsızlık talepleri nedeniyle daha önce az görünür olan örüntüleri görünür kılabilir.",
    detail: "Bu bağlamsal görünürlük okulun güçlüğün tek nedeni olduğunu veya çocuğun isteksiz davrandığını göstermez.",
    sourceIds: ["WHO_ICF_2001", "SAMEROFF_2010", "DOEBEL_2020"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimType: "association",
    dnaRelation: "conceptual_proximity",
  }),
  claim({
    id: "claim.development.difference_early_childhood_assessment",
    topicId: "development.differences",
    text: "Erken çocuklukta gelişimsel farklılıklar tek gözlemle değil, gelişim dönemi, tekrarlı gözlem, bakımveren bilgisi, görev ve bağlam birlikte ele alınarak değerlendirilmelidir.",
    detail: "0-2 yaş için yetişkin normu, tek alan puanı veya tek oturum kalıcı tip, tanı ya da gelişimsel yörünge göstermez.",
    sourceIds: ["LIPKIN_MACIAS_2020", "WHO_ICF_2001", "SAMEROFF_2010"],
    evidenceLevel: "strong",
    ageScope: "early_childhood",
    claimType: "development",
    dnaRelation: "conceptual_proximity",
  }),
])

export const V5_DEVELOPMENT_RELATIONS: readonly DnaChatCatalogRelation[] = Object.freeze([
  relation({
    id: "relation.development.differences-overview",
    fromTopicId: "development.differences",
    toTopicId: "development.overview",
    predicate: "part_of",
    summary: "Gelişimsel farklılık, çocuk gelişiminin dinamik ve bağlama duyarlı yapısı içinde ele alınan betimleyici bir üst kavramdır.",
    sourceIds: ["SAMEROFF_2010", "WHO_ICF_2001"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "Bu ilişki farklılığı tanı, neden veya değişmez tip yapmaz.",
  }),
  relation({
    id: "relation.development.variability-differences",
    fromTopicId: "development.variability",
    toTopicId: "development.differences",
    predicate: "part_of",
    summary: "Çocuklar arası ve aynı çocuk içindeki değişkenlik, gelişimsel farklılığın birbirinden ayrılması gereken iki görünümüdür.",
    sourceIds: ["MONTROY_ET_AL_2016", "CARNEIRO_ET_AL_2021"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Değişkenlik tek başına bozukluk, gerileme veya ölçüm hatası değildir.",
  }),
  relation({
    id: "relation.development.trajectory-differences",
    fromTopicId: "development.trajectory",
    toTopicId: "development.differences",
    predicate: "conceptually_related_to",
    summary: "Gelişimsel farklılıkların zaman içindeki biçimi yörünge yaklaşımıyla incelenebilir.",
    sourceIds: ["THOMAS_ET_AL_2009", "MONTROY_ET_AL_2016"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "Tek zamanlı fark yörünge veya değişim hızı göstermez.",
  }),
  relation({
    id: "relation.development.trajectory-variability",
    fromTopicId: "development.trajectory",
    toTopicId: "development.variability",
    predicate: "associated_with",
    summary: "Yörüngeyi yorumlamak için gerçek zaman içi değişim ile durum ve ölçüm değişkenliğinin ayrılması gerekir.",
    sourceIds: ["THOMAS_ET_AL_2009", "CARNEIRO_ET_AL_2021"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Bu ayrım tekrarlı ve karşılaştırılabilir veri olmadan bireysel olarak kurulamaz.",
  }),
  relation({
    id: "relation.development.uneven-differences",
    fromTopicId: "development.uneven_profile",
    toTopicId: "development.differences",
    predicate: "conceptually_related_to",
    summary: "Alanlar arası eşzamanlı olmayan gelişim, gelişimsel farklılığın olası görünümlerinden biridir.",
    sourceIds: ["THOMAS_ET_AL_2009", "ASTLE_ET_AL_2022"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Alan farkı tanı, regresyon, doğal alt tip veya biyolojik imza değildir.",
  }),
  relation({
    id: "relation.development.pathways-trajectory",
    fromTopicId: "development.pathways",
    toTopicId: "development.trajectory",
    predicate: "conceptually_related_to",
    summary: "Eşsonluluk, çoksonluluk ve kaskad ilkeleri farklı gelişimsel yörüngelerin olasılıksal niteliğini açıklar.",
    sourceIds: ["CICCHETTI_ROGOSCH_1996", "MASTEN_CICCHETTI_2010", "THOMAS_ET_AL_2009"],
    evidenceLevel: "theoretical",
    ageScope: "childhood",
    claimBoundary: "Kuramsal bağlantı bireysel neden veya prognoz sağlamaz.",
  }),
  relation({
    id: "relation.development.plasticity-trajectory",
    fromTopicId: "development.plasticity",
    toTopicId: "development.trajectory",
    predicate: "conceptually_related_to",
    summary: "Plastisite ve deneyimin zamanlaması gelişimsel değişimin olası zeminlerindendir.",
    sourceIds: ["KNUDSEN_2004", "SAMEROFF_2010"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Bu ilişki belirli bir uygulamanın etkisini veya değişimin zorunlu yönünü göstermez.",
  }),
  relation({
    id: "relation.development.person-environment-differences",
    fromTopicId: "development.person_environment",
    toTopicId: "development.differences",
    predicate: "associated_with",
    summary: "Görev ve çevre talepleri gelişimsel farklılıkların günlük işlevde nasıl göründüğünü etkileyebilir.",
    sourceIds: ["WHO_ICF_2001", "SAMEROFF_2010"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "Bağlamsal ilişki çocuğu veya çevreyi tek neden olarak belirlemez.",
  }),
  relation({
    id: "relation.development.supported-person-environment",
    fromTopicId: "development.supported_performance",
    toTopicId: "development.person_environment",
    predicate: "associated_with",
    summary: "Destekli performans, çevresel düzenleme ile çocuğun işlevi arasındaki uyuma ilişkin bilgi sağlar.",
    sourceIds: ["WHO_ICF_2001", "DOEBEL_2020", "DIAMOND_2013"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Destekli başarı bağımsız ustalık veya belirli bir müdahalenin etkililiği değildir.",
  }),
  relation({
    id: "relation.development.informant-person-environment",
    fromTopicId: "development.informant_context",
    toTopicId: "development.person_environment",
    predicate: "associated_with",
    summary: "Ebeveyn ve öğretmen farklı görev ve çevre koşullarını gözlediği için bildirimler bağlama göre ayrışabilir.",
    sourceIds: ["CARNEIRO_ET_AL_2021", "WHO_ICF_2001"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "Uyuşmazlık tek başına bir bilgilendiricinin yanlış olduğunu göstermez.",
  }),
  relation({
    id: "relation.development.invariance-differences",
    fromTopicId: "development.measurement_invariance",
    toTopicId: "development.differences",
    predicate: "supports",
    summary: "Ölçüm değişmezliği, yaş veya kültür grupları arasındaki puan farklarının karşılaştırılabilir biçimde yorumlanmasını destekler.",
    sourceIds: ["DOENNECKE_ET_AL_2023"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "Genel gereklilik DNA'nın ölçüm değişmezliğini kanıtlamaz.",
  }),
  relation({
    id: "relation.development.screening-trajectory",
    fromTopicId: "development.screening_assessment",
    toTopicId: "development.trajectory",
    predicate: "distinguished_from",
    summary: "Tek bir tarama sonucu zaman içindeki gelişimsel yörüngeden farklı bir bilgi türüdür.",
    sourceIds: ["LIPKIN_MACIAS_2020", "RAH_ET_AL_2023", "THOMAS_ET_AL_2009"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "Tarama sonucu yörünge, tanı veya prognoz değildir.",
  }),
  relation({
    id: "relation.development.age-equivalent-trajectory",
    fromTopicId: "development.age_equivalent_limits",
    toTopicId: "development.trajectory",
    predicate: "distinguished_from",
    summary: "Tek bir yaş eşdeğeri zaman içindeki değişim biçimini ve alanlar arası profili gösteren gelişimsel yörüngeden farklıdır.",
    sourceIds: ["THOMAS_ET_AL_2009", "RAH_ET_AL_2023"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Yaş eşdeğeri bütünsel gelişim yaşı veya bireysel gelecek değildir.",
  }),
  relation({
    id: "relation.development.neurodiversity-differences",
    fromTopicId: "development.neurodiversity",
    toTopicId: "development.differences",
    predicate: "conceptually_related_to",
    summary: "Nöroçeşitlilik gelişimsel farklılıkları insan çeşitliliği, haklar ve kişi-çevre etkileşimi içinde ele alan yaklaşımlar sunar.",
    sourceIds: ["DWYER_2022", "ASTLE_ET_AL_2022"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Kavramsal ilişki tanıyı, güçlüğü veya destek gereksinimini otomatik olarak ortadan kaldırmaz.",
  }),
  relation({
    id: "relation.development.neurodiversity-screening",
    fromTopicId: "development.neurodiversity",
    toTopicId: "development.screening_assessment",
    predicate: "distinguished_from",
    summary: "Nöroçeşitlilik kavramsal ve etik bir çerçevedir; gelişimsel tarama veya değerlendirme yöntemi değildir.",
    sourceIds: ["DWYER_2022", "LIPKIN_MACIAS_2020"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Kişiye DNA profilinden kimlik veya tanı atanamaz.",
  }),
  relation({
    id: "relation.development.differences-sensory-reactivity",
    fromTopicId: "development.differences",
    toTopicId: "selfreg.sensory_modulation",
    predicate: "conceptually_related_to",
    summary: "Duyusal reaktivite gelişimsel farklılıkların günlük işlevdeki olası görünümlerinden biri olabilir; gelişimsel farklılığın tamamı veya tek nedeni değildir.",
    sourceIds: ["WHO_ICF_2001", "WATKYNS_ET_AL_2024", "SAMEROFF_2010"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Duyusal davranıştan tanı, nörolojik eşik veya tek gelişimsel mekanizma çıkarılamaz.",
  }),
  relation({
    id: "relation.development.differences-interoception",
    fromTopicId: "development.differences",
    toTopicId: "ans.interoception",
    predicate: "conceptually_related_to",
    summary: "İç bedensel sinyali fark etme ve kullanma biçimi gelişimsel, dilsel ve bağlamsal farklılıklarla birlikte değişebilir.",
    sourceIds: ["SAMEROFF_2010", "KHALSA_ET_AL_2018", "QUIGLEY_ET_AL_2021"],
    evidenceLevel: "theoretical",
    ageScope: "developmental",
    claimBoundary: "Bu ilişki interoseptif doğruluğu, organ işlevini veya belirli bir gelişimsel tanıyı göstermez.",
  }),
  relation({
    id: "relation.development.differences-dna-physiological",
    fromTopicId: "development.differences",
    toTopicId: "dna.physiological_regulation",
    predicate: "conceptually_related_to",
    summary: "Fizyolojik durum, enerji, uyarılma ve toparlanmanın işlevsel görünümü gelişim dönemi ve bağlamla birlikte değişebilir.",
    sourceIds: ["SAMEROFF_2010", "WHO_ICF_2001", "BLAIR_RAVER_2015"],
    evidenceLevel: "theoretical",
    ageScope: "developmental",
    claimBoundary: "Kavramsal yakınlık DNA alanının biyolojik ölçüm veya doğrulanmış gelişim faktörü olduğu anlamına gelmez.",
  }),
  relation({
    id: "relation.development.differences-dna-sensory",
    fromTopicId: "development.differences",
    toTopicId: "dna.sensory_regulation",
    predicate: "conceptually_related_to",
    summary: "Duyusal örüntülerin işlevsel etkisi yaş, görev ve çevreyle değişebildiği için gelişimsel bağlam DNA duyusal alanının yorum sınırlarından biridir.",
    sourceIds: ["WHO_ICF_2001", "WATKYNS_ET_AL_2024", "SAMEROFF_2010"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "İlişki duyusal alanı tanı, biyolojik eşik veya bağımsız gelişim faktörü yapmaz.",
  }),
  relation({
    id: "relation.development.differences-dna-emotional",
    fromTopicId: "development.differences",
    toTopicId: "dna.emotional_regulation",
    predicate: "conceptually_related_to",
    summary: "Duygusal tepki, strateji ve yeniden katılımın görünümü gelişim düzeyi ve sosyal bağlamla birlikte değişebilir.",
    sourceIds: ["SAMEROFF_2010", "COLE_ET_AL_2004", "WHO_ICF_2001"],
    evidenceLevel: "theoretical",
    ageScope: "developmental",
    claimBoundary: "DNA duygusal alanı gelişimsel tanı, sabit tip veya tek biyolojik mekanizma değildir.",
  }),
  relation({
    id: "relation.development.differences-dna-cognitive",
    fromTopicId: "development.differences",
    toTopicId: "dna.cognitive_regulation",
    predicate: "conceptually_related_to",
    summary: "Dikkat, beklenti ve strateji kullanımının işlevsel görünümü gelişim dönemi, görev ve öğretim bağlamıyla birlikte değişebilir.",
    sourceIds: ["SAMEROFF_2010", "DOEBEL_2020", "WHO_ICF_2001"],
    evidenceLevel: "theoretical",
    ageScope: "developmental",
    claimBoundary: "Kavramsal ilişki bağımsız DNA faktörü, zekâ veya sabit bilişsel kapasite kanıtı değildir.",
  }),
  relation({
    id: "relation.development.differences-dna-executive",
    fromTopicId: "development.differences",
    toTopicId: "dna.executive_function_domain",
    predicate: "conceptually_related_to",
    summary: "Yürütücü işlev talepleri çocukluk boyunca değiştiği için DNA yürütücü alanının görünümü yaş ve görev bağlamına duyarlıdır.",
    sourceIds: ["DIAMOND_2013", "DOEBEL_2020", "SAMEROFF_2010"],
    evidenceLevel: "moderate",
    ageScope: "developmental",
    claimBoundary: "Alan puanı PFC olgunluğunu, tanıyı veya gelişimin tamamlandığı yaşı göstermez.",
  }),
  relation({
    id: "relation.development.differences-dna-interoception",
    fromTopicId: "development.differences",
    toTopicId: "dna.interoception_domain",
    predicate: "conceptually_related_to",
    summary: "İç beden sinyalini fark etme, adlandırma ve eylemle ilişkilendirme becerileri gelişim ve dil bağlamına duyarlıdır.",
    sourceIds: ["KHALSA_ET_AL_2018", "QUIGLEY_ET_AL_2021", "SAMEROFF_2010"],
    evidenceLevel: "theoretical",
    ageScope: "developmental",
    claimBoundary: "DNA interosepsiyon alanı nesnel doğruluk, organ işlevi veya gelişimsel tanı ölçümü değildir.",
  }),
  relation({
    id: "relation.development.person-environment-sleep",
    fromTopicId: "development.person_environment",
    toTopicId: "selfreg.sleep_health",
    predicate: "associated_with",
    summary: "Uyku ve yorgunluk görev talebiyle etkileşerek çocuğun günlük performansının hangi koşullarda sürdürülebildiğini etkileyebilir.",
    sourceIds: ["WHO_ICF_2001", "ASTILL_ET_AL_2012", "SAMEROFF_2010"],
    evidenceLevel: "moderate",
    ageScope: "childhood",
    claimBoundary: "Uyku-performans ilişkisi bireysel neden, tanı veya tek gelişimsel mekanizma değildir.",
  }),
  relation({
    id: "relation.development.screening-case-screening",
    fromTopicId: "development.screening_assessment",
    toTopicId: "case.screening_diagnosis",
    predicate: "conceptually_related_to",
    summary: "Gelişimsel tarama ileri değerlendirme gereksinimini sınıflar; vaka yorumunda tarama sonucu tanısal kararın yerine geçmez.",
    sourceIds: ["LIPKIN_MACIAS_2020", "RAH_ET_AL_2023", "SHELDRICK_ET_AL_2020"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "DNA için tanısal doğruluk veya dışlama olasılığı üretilmez.",
  }),
  relation({
    id: "relation.development.invariance-case-culture",
    fromTopicId: "development.measurement_invariance",
    toTopicId: "case.development_culture",
    predicate: "supports",
    summary: "Kültürel ve dilsel uygunluk için ölçüm değişmezliği, norm, madde işlevi ve yanıt süreçleri hedef grupta ayrıca incelenmelidir.",
    sourceIds: ["DOENNECKE_ET_AL_2023", "PUTNICK_BORNSTEIN_2016"],
    evidenceLevel: "strong",
    ageScope: "childhood",
    claimBoundary: "Genel gereklilik DNA'nın Türkiye'de veya başka bir grupta kültürel geçerli olduğunu kanıtlamaz.",
  }),
])

export const V5_DEVELOPMENT_SAFETY_RULES: readonly DnaChatCatalogSafetyRule[] = Object.freeze([
  safetyRule({
    id: "safety.development.trajectory_from_score",
    patterns: ["DNA puanı gelişimsel yörüngeyi gösterir mi?"],
    response: "Tek zamanlı DNA puanı gelişimsel yörünge, değişim hızı veya prognoz göstermez; yalnız ölçüm anındaki sınırlı işlevsel bilgiyi betimleyebilir.",
    category: "measurement_overreach",
    sourceIds: ["THOMAS_ET_AL_2009", "RAH_ET_AL_2023"],
  }),
  safetyRule({
    id: "safety.development.diagnosis_from_profile",
    patterns: [
      "DNA puanına göre bu çocukta otizm var mı?",
      "Bu profil çocuğun DEHB olduğunu kanıtlıyor mu?",
    ],
    response: "DNA profili tanı koymaz veya tanıyı dışlamaz; yalnız bildirilen işlevleri ve bağlamları betimlemek için kullanılabilir.",
    category: "diagnosis",
    sourceIds: ["LIPKIN_MACIAS_2020", "RAH_ET_AL_2023", "ASTLE_ET_AL_2022"],
  }),
  safetyRule({
    id: "safety.development.biological_damage_from_profile",
    patterns: ["Hangi beyin bölgesi bozuk?", "Sinir sistemi hasarlı mı?"],
    response: "Davranışsal veya DNA profil verisi belirli bir beyin bölgesinin işlevini ya da sinir sistemi hasarını ölçmez ve bu sonuçları dışlayamaz.",
    category: "biological_inference",
    sourceIds: ["POLDRAK_2006", "ASTLE_ET_AL_2022"],
  }),
  safetyRule({
    id: "safety.development.trauma_from_profile",
    patterns: ["Bu çocuk kesin travma yaşamış mı?"],
    response: "Regülasyon ve gelişimsel farklılıklar travmaya özgü değildir; DNA profilinden yaşam öyküsü, travma nedeni veya travma tanısı çıkarılamaz.",
    category: "causality",
    sourceIds: ["SAMEROFF_2010", "SHONKOFF_ET_AL_2012"],
  }),
  safetyRule({
    id: "safety.development.age_from_profile",
    patterns: ["Çocuğun gelişim yaşı tam olarak kaç?"],
    response: "Tek bir DNA profili çocuğun bütünsel gelişim yaşını vermez; yaş eşdeğerleri alan ve araca özgü sınırlı göstergelerdir ve kronolojik yaşın yerine geçmez.",
    category: "measurement_overreach",
    sourceIds: ["THOMAS_ET_AL_2009", "WHO_ICF_2001", "RAH_ET_AL_2023"],
  }),
  safetyRule({
    id: "safety.development.prognosis_from_profile",
    patterns: ["İleride bağımsız olur mu?"],
    response: "Mevcut DNA profili bireysel bağımsızlık veya uzun dönem işlev prognozu vermez; gelişimsel yollar ve çevresel koşullar zaman içinde değişebilir.",
    category: "measurement_overreach",
    sourceIds: ["CICCHETTI_ROGOSCH_1996", "MASTEN_CICCHETTI_2010", "THOMAS_ET_AL_2009"],
  }),
])
