import {
  DNA_CHAT_CATALOG_VERSION,
  type DnaChatCatalogClaim,
  type DnaChatCatalogRelation,
  type DnaChatCatalogSource,
  type DnaChatCatalogTopic,
} from "./types"

export const V6_FOUNDATIONAL_EXPANSION_VERSION =
  "dna-foundational-expansion@1" as const

export type DnaFoundationalPassage = Readonly<{
  id: string
  sourceAssetId: string
  catalogSourceId: string
  page: number | null
  supportingExcerpt: string
  sourceContentSha256: string
  licenseSpdx: "CC-BY-4.0"
  licenseDecision: "licensed_runtime_candidate"
  auditedAt: "2026-08-03"
}>

const SOURCE = Object.freeze({
  neuroscience: "OPEN_NEUROSCIENCE_CANADIAN_2022",
  physiology: "OPEN_PHYSIOLOGY_UW_2023",
  sleep: "OPEN_SCIENCE_OF_SLEEP_2022",
  hrv: "QUIGLEY_ET_AL_2024_HRV_GUIDELINES",
})

function source(
  input: Omit<DnaChatCatalogSource, "version" | "sourceVerified" | "verifiedAt">,
): DnaChatCatalogSource {
  return Object.freeze({
    version: DNA_CHAT_CATALOG_VERSION,
    sourceVerified: true as const,
    verifiedAt: "2026-08-03",
    ...input,
  })
}

export const V6_FOUNDATIONAL_EXPANSION_SOURCES: readonly DnaChatCatalogSource[] =
  Object.freeze([
    source({
      id: SOURCE.neuroscience,
      title: "Neuroscience: Canadian 3rd Edition",
      authors: "Ju, W., Shcherbina, M., Halawa, A., Jarovi, J., & Pilkiw, M.",
      year: 2022,
      publication: "eCampusOntario Pressbooks",
      publicationStatus: "published",
      studyType: "CC BY 4.0 açık nörobilim ders kitabı",
      doi: null,
      pmid: null,
      url: "https://ecampusontario.pressbooks.pub/neurosciencecdn3/",
      evidenceDomain: "foundational_cellular_neuroscience",
      ageScope: "all_ages",
      claimBoundary: "Temel hücresel nörobilim kavramlarını destekler; DNA'ya özgü geçerlik, kişisel beyin işlevi veya klinik sonuç sağlamaz.",
    }),
    source({
      id: SOURCE.physiology,
      title: "Physiology",
      authors: "Asbury, C., Rieke, F., Hille, B., Bothwell, M., Tuthill, J., & Vivas, O.",
      year: 2023,
      publication: "University of Washington Pressbooks",
      publicationStatus: "published",
      studyType: "CC BY 4.0 açık fizyoloji ders kitabı",
      doi: null,
      pmid: null,
      url: "https://uw.pressbooks.pub/physiology/",
      evidenceDomain: "foundational_neurophysiology_and_autonomic_physiology",
      ageScope: "all_ages",
      claimBoundary: "Temel membran, sinaps ve otonom fizyolojiyi destekler; davranıştan fizyoloji, DNA geçerliği veya bireysel klinik mekanizma çıkarmaz.",
    }),
    source({
      id: SOURCE.sleep,
      title: "The Science of Sleep",
      authors: "Shook, S.",
      year: 2022,
      publication: "University of Hawai‘i Open Educational Resource",
      publicationStatus: "published",
      studyType: "CC BY 4.0 giriş düzeyi açık uyku bilimi kitabı",
      doi: null,
      pmid: null,
      url: "https://open.umn.edu/opentextbooks/textbooks/the-science-of-sleep",
      evidenceDomain: "foundational_sleep_and_circadian_science",
      ageScope: "mixed",
      claimBoundary: "Temel uyku eğitimi için kullanılır; uyku bozukluğu, tedavi, kişisel sirkadiyen faz veya klinik ölçüm kararı sağlamaz.",
    }),
    source({
      id: SOURCE.hrv,
      title: "Publication guidelines for human heart rate and heart rate variability studies in psychophysiology—Part 1: Physiological underpinnings and foundations of measurement",
      authors: "Quigley, K. S., Gianaros, P. J., Norman, G. J., Jennings, J. R., Berntson, G. G., & de Geus, E. J. C.",
      year: 2024,
      publication: "Psychophysiology",
      publicationStatus: "consensus",
      studyType: "Komite ölçüm ve yayın kılavuzu",
      doi: "10.1111/psyp.14604",
      pmid: "38873876",
      url: "https://doi.org/10.1111/psyp.14604",
      evidenceDomain: "hrv_measurement_and_interpretation",
      ageScope: "mixed",
      claimBoundary: "HRV edinimi ve yorum sınırlarını destekler; HRV'yi stresin, psikolojik durumun, sempatovagal dengenin veya DNA profilinin doğrudan ölçümü yapmaz.",
    }),
  ])

function passage(
  input: Omit<
    DnaFoundationalPassage,
    "licenseSpdx" | "licenseDecision" | "auditedAt"
  >,
): DnaFoundationalPassage {
  return Object.freeze({
    licenseSpdx: "CC-BY-4.0" as const,
    licenseDecision: "licensed_runtime_candidate" as const,
    auditedAt: "2026-08-03" as const,
    ...input,
  })
}

export const V6_FOUNDATIONAL_EXPANSION_PASSAGES: readonly DnaFoundationalPassage[] =
  Object.freeze([
    passage({ id: "book.passage:book.physiology-uw-2023:0096:008", sourceAssetId: "book.physiology-uw-2023", catalogSourceId: SOURCE.physiology, page: 96, supportingExcerpt: "specific ions can move down their electrochemical gradient", sourceContentSha256: "3823f1968d83b621e50b0a7680fb3b4b3a97c9aa86c595690146aab160e8bb10" }),
    passage({ id: "book.passage:book.neuroscience-canadian-3e:0018:001", sourceAssetId: "book.neuroscience-canadian-3e", catalogSourceId: SOURCE.neuroscience, page: 18, supportingExcerpt: "the Na+/K+ pump", sourceContentSha256: "2f4f03d62d7a333ba9c5920c1f64ed21dbbbc26260f5c16238c323228047bb1c" }),
    passage({ id: "book.passage:book.physiology-uw-2023:0205:002", sourceAssetId: "book.physiology-uw-2023", catalogSourceId: SOURCE.physiology, page: 205, supportingExcerpt: "receptor potentials are graded and are proportional to the strength of the stimulus", sourceContentSha256: "b6c42d2afe9f1944e3a4c6f192bfd6af5ee0de125da9c42628df5eb60011d333" }),
    passage({ id: "book.passage:book.neuroscience-canadian-3e:0024:005", sourceAssetId: "book.neuroscience-canadian-3e", catalogSourceId: SOURCE.neuroscience, page: 24, supportingExcerpt: "This results in a refractory period", sourceContentSha256: "5098e2f1501167f245d31acebd5afa343870bcff6677798722491aa5bc1f4270" }),
    passage({ id: "book.passage:book.neuroscience-canadian-3e:0026:014", sourceAssetId: "book.neuroscience-canadian-3e", catalogSourceId: SOURCE.neuroscience, page: 26, supportingExcerpt: "only at nodes of Ranvier", sourceContentSha256: "ff989b6420c7523164e7f4eb1c20a6518157ccf738a98272bc1d336b4b55c55c" }),
    passage({ id: "book.passage:book.physiology-uw-2023:0141:007", sourceAssetId: "book.physiology-uw-2023", catalogSourceId: SOURCE.physiology, page: 141, supportingExcerpt: "saltatory conduction", sourceContentSha256: "45be4f7688430745ee64e258a81a753eb8c9cfd0ad985295c06e4375ff79ad15" }),
    passage({ id: "book.passage:book.physiology-uw-2023:0160:012", sourceAssetId: "book.physiology-uw-2023", catalogSourceId: SOURCE.physiology, page: 160, supportingExcerpt: "opening of voltage-gated Ca 2+ channels", sourceContentSha256: "41ef519579c40dc39583274ed0dc4782162cd4196e111779b6eca8fe855653c1" }),
    passage({ id: "book.passage:book.physiology-uw-2023:0162:005", sourceAssetId: "book.physiology-uw-2023", catalogSourceId: SOURCE.physiology, page: 162, supportingExcerpt: "release their contents into the synaptic cleft (a process termed exocytosis)", sourceContentSha256: "912ecdfe9285e8c96a6869997778092fc425b6dbd48135ca3ef6c4d319820d5b" }),
    passage({ id: "book.passage:book.physiology-uw-2023:0155:008", sourceAssetId: "book.physiology-uw-2023", catalogSourceId: SOURCE.physiology, page: 155, supportingExcerpt: "Ionotropic receptors are ion channels that open rapidly", sourceContentSha256: "3316f4b1aea816b00c44d36123abb55131d8d9354ddcc9e25716810cbd4fb074" }),
    passage({ id: "book.passage:book.physiology-uw-2023:0155:009", sourceAssetId: "book.physiology-uw-2023", catalogSourceId: SOURCE.physiology, page: 155, supportingExcerpt: "Metabotropic receptors are GPCRs that initiate second messenger signaling", sourceContentSha256: "1f72d5b800572ddab4ff3c3ad0fb4b3867660647c706eeb0be81a4ac5cc014e4" }),
    passage({ id: "book.passage:book.physiology-uw-2023:0163:006", sourceAssetId: "book.physiology-uw-2023", catalogSourceId: SOURCE.physiology, page: 163, supportingExcerpt: "depolarizing (excitatory postsynaptic potentials or EPSPs) or hyperpolarizing (inhibitory postsynaptic potentials or IPSPs)", sourceContentSha256: "e9ef00bfa8e7347a5d1b7bb25f9401a9ef9df51e85277617c804c7bd7d4118d0" }),
    passage({ id: "book.passage:book.physiology-uw-2023:0174:004", sourceAssetId: "book.physiology-uw-2023", catalogSourceId: SOURCE.physiology, page: 174, supportingExcerpt: "multiple excitatory inputs must be summed or integrated", sourceContentSha256: "c372bc23b5f9ea53ccd0c7beeedaf41baad7c6d314814a5ec29dc5de4543f9bd" }),

    passage({ id: "book.passage:book.science-of-sleep:0062:017", sourceAssetId: "book.science-of-sleep", catalogSourceId: SOURCE.sleep, page: 62, supportingExcerpt: "Animal studies have demonstrated that the suprachiasmatic nucleus (SCN)", sourceContentSha256: "87d16de04d63893b7b451fb5cc0cdd83030743e8dbf160ac36937e785f7dda04" }),
    passage({ id: "book.passage:book.science-of-sleep:0045:008", sourceAssetId: "book.science-of-sleep", catalogSourceId: SOURCE.sleep, page: 45, supportingExcerpt: "lightand dark-dependent signals from the eyes are one of the driving forces of the SCN", sourceContentSha256: "c9d0f37be9bed6dad734cb167f8c7606d625ee5abe89361136717de441272f05" }),
    passage({ id: "book.passage:book.science-of-sleep:0060:001", sourceAssetId: "book.science-of-sleep", catalogSourceId: SOURCE.sleep, page: 60, supportingExcerpt: "sleep pressure, the drive to sleep depending on how long you have been awake", sourceContentSha256: "1abbc772d05e068a8411b96853a27d719c17e08f57b663ea9449d027da840a33" }),
    passage({ id: "book.passage:book.science-of-sleep:0060:006", sourceAssetId: "book.science-of-sleep", catalogSourceId: SOURCE.sleep, page: 60, supportingExcerpt: "During sleep, adenosine will get broken down, recycled, and removed from the brain", sourceContentSha256: "7fd7d7da2d02e944ef23322e8780ad680065b1a95df398e459c171f4203e1962" }),
    passage({ id: "book.passage:book.science-of-sleep:0062:011", sourceAssetId: "book.science-of-sleep", catalogSourceId: SOURCE.sleep, page: 62, supportingExcerpt: "These cues are called zeitgebers", sourceContentSha256: "2757b51178362ed27799c8bcbfafe729ff82c2fe544307138a14fdc9c0f3c7de" }),
    passage({ id: "book.passage:book.science-of-sleep:0062:016", sourceAssetId: "book.science-of-sleep", catalogSourceId: SOURCE.sleep, page: 62, supportingExcerpt: "our clock signal is generated inside of us (endogenous)", sourceContentSha256: "6a57a965b661d4f7b33d4903f7e2876081b6c95cb77c15797f908a2fcfe50bef" }),
    passage({ id: "book.passage:book.science-of-sleep:0049:003", sourceAssetId: "book.science-of-sleep", catalogSourceId: SOURCE.sleep, page: 49, supportingExcerpt: "electroencephalogram, electrooculogram, and electromyogram—comprise the polysomnogram", sourceContentSha256: "67260ac1a921c73e9df96358f7fb7563d96cb9bf431956d83fe6e50f855a3137" }),
    passage({ id: "book.passage:book.science-of-sleep:0049:004", sourceAssetId: "book.science-of-sleep", catalogSourceId: SOURCE.sleep, page: 49, supportingExcerpt: "detected by pasting tiny electrodes to the scalp", sourceContentSha256: "209ca87509d8ff8f53f925369ba864bb9132390c5cb0b3dad9c237eb845d182f" }),
    passage({ id: "book.passage:book.science-of-sleep:0057:012", sourceAssetId: "book.science-of-sleep", catalogSourceId: SOURCE.sleep, page: 57, supportingExcerpt: "Polysomnography, with the three physiological measures of EEG, EOG, and EMG, has been used to validate actigraphy", sourceContentSha256: "6b93bacf2ed5d14b5ca2db5987a90fc4dc936945fac9b41ca86b61cb97b8ebd5" }),
    passage({ id: "book.passage:book.science-of-sleep:0054:001", sourceAssetId: "book.science-of-sleep", catalogSourceId: SOURCE.sleep, page: 54, supportingExcerpt: "each with an assortment of characteristics that distinguishes one stage from the other", sourceContentSha256: "de603eb41c6b7a83ee1b074d9d7de508ccd560d45be1cbdf0877618e07a2369f" }),
    passage({ id: "book.passage:book.science-of-sleep:0055:015", sourceAssetId: "book.science-of-sleep", catalogSourceId: SOURCE.sleep, page: 55, supportingExcerpt: "sleep spindles and K-complexes—of NREM 2", sourceContentSha256: "c0e99215844eaa0010dfd02bee62fe96167cf27e01dd4ed0bb906adf2a289d96" }),
    passage({ id: "book.passage:book.science-of-sleep:0054:008", sourceAssetId: "book.science-of-sleep", catalogSourceId: SOURCE.sleep, page: 54, supportingExcerpt: "During REM sleep, we have vivid and emotional dreams while the body is paralyzed", sourceContentSha256: "0b35729e2d90e09de1a0b80ba40ec1cd54c59bd2477a15734125ac6ca2475262" }),

    passage({ id: "book.passage:book.physiology-uw-2023:0213:006", sourceAssetId: "book.physiology-uw-2023", catalogSourceId: SOURCE.physiology, page: 213, supportingExcerpt: "a two-neuron relay: first efferent preganglionic neurons and then peripheral postganglionic neurons", sourceContentSha256: "60ad76c2fc620689e219cdba4d8d411e22ca9091973920e2b6748f824eb2cfea" }),
    passage({ id: "book.passage:book.physiology-uw-2023:0209:004", sourceAssetId: "book.physiology-uw-2023", catalogSourceId: SOURCE.physiology, page: 209, supportingExcerpt: "release acetylcholine (ACh) on postganglionic neurons in autonomic ganglion", sourceContentSha256: "b370e2008beedee6b032eecfa3a91ab08c26e00a02c4934a6a75857877927be1" }),
    passage({ id: "book.passage:book.physiology-uw-2023:0209:005", sourceAssetId: "book.physiology-uw-2023", catalogSourceId: SOURCE.physiology, page: 209, supportingExcerpt: "releases norepinephrine on targets if it is sympathetic, or ACh if it is parasympathetic", sourceContentSha256: "63ddf98250af9321d2fb0fb6e0f7d1d977edd035f68b13874b65fc36e82ffc85" }),
    passage({ id: "book.passage:book.physiology-uw-2023:0211:001", sourceAssetId: "book.physiology-uw-2023", catalogSourceId: SOURCE.physiology, page: 211, supportingExcerpt: "Pressure receptors mount a corrective response called the baroreflex", sourceContentSha256: "7288bacd6f17df16d26995e0fec33e866bf1abd67ea0073bb6c58848abd6965b" }),
    passage({ id: "book.passage:book.physiology-uw-2023:0232:003", sourceAssetId: "book.physiology-uw-2023", catalogSourceId: SOURCE.physiology, page: 232, supportingExcerpt: "restore homeostasis by vasoconstriction in the legs and speeding heart beat", sourceContentSha256: "3fbd7c9dd57515af6500994e136c05eedb02abe1cc9b1a37ead6f6a1e559e0eb" }),
    passage({ id: "evidence.passage:hrv-publication-guidelines-2024:f7e67ae2db:00165", sourceAssetId: "hrv-publication-guidelines-2024", catalogSourceId: SOURCE.hrv, page: null, supportingExcerpt: "The period between any specific voltage deflections in the ECG from two consecutive heartbeats", sourceContentSha256: "97426bb98bdd56c5da4b03d7a55170994cab2c9a25d7753311faad81f4af044c" }),
    passage({ id: "evidence.passage:hrv-publication-guidelines-2024:f7e67ae2db:00032", sourceAssetId: "hrv-publication-guidelines-2024", catalogSourceId: SOURCE.hrv, page: null, supportingExcerpt: "Artifacts due to technical, movement, and other non-physiological sources", sourceContentSha256: "6c1ce4a6b8e8879a321703187251f45fbf9a425aa1e8c56ed52c8d7699837008" }),
    passage({ id: "evidence.passage:hrv-publication-guidelines-2024:f7e67ae2db:00088", sourceAssetId: "hrv-publication-guidelines-2024", catalogSourceId: SOURCE.hrv, page: null, supportingExcerpt: "the standard deviation of all normal heart periods (SDNN) and the root mean square of the successive beat differences (RMSSD)", sourceContentSha256: "353e1a60ec1dbf198560d07545345be6867f897eaabe484376e6dae961293bff" }),
    passage({ id: "evidence.passage:hrv-publication-guidelines-2024:f7e67ae2db:00099", sourceAssetId: "hrv-publication-guidelines-2024", catalogSourceId: SOURCE.hrv, page: null, supportingExcerpt: "standardization of recording lengths used for comparisons", sourceContentSha256: "202096e83fb42b28af590814509be7cc041a04ffed7fd28e0a8be205811add3a" }),
    passage({ id: "candidate.passage:hrv-publication-guidelines-2024:003", sourceAssetId: "hrv-publication-guidelines-2024", catalogSourceId: SOURCE.hrv, page: null, supportingExcerpt: "HF HRV and RSA are not identical", sourceContentSha256: "27704979b9b78c735091b5c77ddfede8ee5ec73c6e969b3a5e11677530e34071" }),
    passage({ id: "candidate.passage:hrv-publication-guidelines-2024:007", sourceAssetId: "hrv-publication-guidelines-2024", catalogSourceId: SOURCE.hrv, page: null, supportingExcerpt: "Changes in respiratory behavior (rate and depth) have a strong impact on HRV measures", sourceContentSha256: "e402ed1a78597eeb91930513ff56ea0076cd124106623a20bd1f32256a51d393" }),
    passage({ id: "candidate.passage:hrv-publication-guidelines-2024:002", sourceAssetId: "hrv-publication-guidelines-2024", catalogSourceId: SOURCE.hrv, page: null, supportingExcerpt: "It is exclusively the phasic modulation of tonic cardiac parasympathetic and sympathetic nerve activity that generates HRV", sourceContentSha256: "42f195ce5b8a5141c73766b88af8196a133e8df395ea57ca24ffb3b08488ece5" }),
    passage({ id: "candidate.passage:hrv-publication-guidelines-2024:018", sourceAssetId: "hrv-publication-guidelines-2024", catalogSourceId: SOURCE.hrv, page: null, supportingExcerpt: "HP and HRV have no one-to-one mapping onto any psychological state", sourceContentSha256: "749c9ae8dd2576a7a8894ca5b3f3a6f4683af7ecf3b422f3630d19eade0280b1" }),
  ])

function claim(
  input: Omit<DnaChatCatalogClaim, "version" | "safetyStatus" | "sourceVerified">,
): DnaChatCatalogClaim {
  return Object.freeze({
    version: DNA_CHAT_CATALOG_VERSION,
    safetyStatus: "safe" as const,
    sourceVerified: true as const,
    ...input,
  })
}

const C = (input: Omit<DnaChatCatalogClaim, "version" | "safetyStatus" | "sourceVerified">) => claim(input)

export const V6_FOUNDATIONAL_EXPANSION_CLAIMS: readonly DnaChatCatalogClaim[] = Object.freeze([
  C({ id: "claim.neuro.membrane.electrochemical_gradient", topicId: "neuro.membrane_potential", text: "İyon-seçici bir kanal açıldığında uygun iyonlar, elektriksel ve yoğunluk bileşenlerinden oluşan elektrokimyasal gradyanları yönünde hareket edebilir.", detail: "Bu, membran potansiyelini açıklayan temel süreçlerden biridir; tek başına bir nöronun bütün durumunu veya davranışı açıklamaz.", sourceIds: [SOURCE.physiology], passageIds: ["book.passage:book.physiology-uw-2023:0096:008"], evidenceLevel: "strong", ageScope: "all_ages", claimType: "mechanism", dnaRelation: "none" }),
  C({ id: "claim.neuro.membrane.sodium_potassium_pump", topicId: "neuro.membrane_potential", text: "Sodyum-potasyum pompası, dinlenim membran potansiyelinin sürdürülmesine etkin biçimde katkı verir.", detail: "Pompa önemli olsa da dinlenim potansiyeli yalnız pompaya indirgenmez; iyon gradyanları ve membran geçirgenliği de gerekir.", sourceIds: [SOURCE.neuroscience], passageIds: ["book.passage:book.neuroscience-canadian-3e:0018:001"], evidenceLevel: "strong", ageScope: "all_ages", claimType: "mechanism", dnaRelation: "none" }),
  C({ id: "claim.neuro.action_potential.graded_distinction", topicId: "neuro.action_potential", text: "Reseptör potansiyelleri derecelidir ve uyaran şiddetiyle değişebilir; aksiyon potansiyeli ise eşik aşıldığında hep-ya-da-hiç biçiminde ilerler.", detail: "Bu ayrım, duyusal girdinin ilk dönüştürülmesi ile akson boyunca iletilen sinyalin aynı şey olmadığını gösterir.", sourceIds: [SOURCE.physiology], passageIds: ["book.passage:book.physiology-uw-2023:0205:002"], evidenceLevel: "strong", ageScope: "all_ages", claimType: "misconception_correction", dnaRelation: "none" }),
  C({ id: "claim.neuro.action_potential.refractory_period", topicId: "neuro.action_potential", text: "Aksiyon potansiyelini izleyen refrakter dönem, hemen yeni bir aksiyon potansiyeli oluşturma olasılığını geçici olarak sınırlar.", detail: "Bu dönem voltaj kapılı sodyum kanallarının durumuyla ilişkilidir ve sinyal zamanlamasının fizyolojik sınırlarından biridir.", sourceIds: [SOURCE.neuroscience], passageIds: ["book.passage:book.neuroscience-canadian-3e:0024:005"], evidenceLevel: "strong", ageScope: "all_ages", claimType: "mechanism", dnaRelation: "none" }),
  C({ id: "claim.neuro.myelin.nodes", topicId: "neuro.myelin_conduction", text: "Miyelinli aksonlarda aksiyon potansiyeli Ranvier düğümlerinde yeniden oluşturulur.", detail: "Miyelinli bölümler ile düğümler aynı elektriksel rolü taşımaz; bu düzen iletimin örgütlenmesine katkı verir.", sourceIds: [SOURCE.neuroscience], passageIds: ["book.passage:book.neuroscience-canadian-3e:0026:014"], evidenceLevel: "strong", ageScope: "all_ages", claimType: "mechanism", dnaRelation: "none" }),
  C({ id: "claim.neuro.myelin.saltatory", topicId: "neuro.myelin_conduction", text: "Saltatorik iletimde aksiyon potansiyeli miyelinsiz düğüm bölgelerinde yeniden üretilirken düğümler arasındaki yayılım pasif ilerler.", detail: "Bu temel iletim düzeni, davranıştan bireysel miyelin durumu veya iletim bozukluğu çıkarılabileceği anlamına gelmez.", sourceIds: [SOURCE.physiology], passageIds: ["book.passage:book.physiology-uw-2023:0141:007"], evidenceLevel: "strong", ageScope: "all_ages", claimType: "mechanism", dnaRelation: "none" }),
  C({ id: "claim.neuro.synapse.calcium_entry", topicId: "neuro.chemical_synapse", text: "Aksiyon potansiyeli sinaptik uca ulaştığında depolarizasyon voltaj kapılı kalsiyum kanallarını açar ve terminale kalsiyum girişi olur.", detail: "Bu olay kimyasal sinaptik iletimin presinaptik basamaklarından biridir.", sourceIds: [SOURCE.physiology], passageIds: ["book.passage:book.physiology-uw-2023:0160:012"], evidenceLevel: "strong", ageScope: "all_ages", claimType: "mechanism", dnaRelation: "none" }),
  C({ id: "claim.neuro.synapse.exocytosis", topicId: "neuro.chemical_synapse", text: "Presinaptik uçtaki kalsiyum artışı, nörotransmiter taşıyan veziküllerin membranla birleşerek içeriklerini sinaptik aralığa bırakmasını tetikler.", detail: "Bu salım ekzositoz olarak adlandırılır; tüm sinapsların etkisi veya davranışsal sonucu yalnız bu basamakla açıklanmaz.", sourceIds: [SOURCE.physiology], passageIds: ["book.passage:book.physiology-uw-2023:0162:005"], evidenceLevel: "strong", ageScope: "all_ages", claimType: "mechanism", dnaRelation: "none" }),
  C({ id: "claim.neuro.receptor.ionotropic", topicId: "neuro.synaptic_receptors", text: "İyonotropik reseptörler hızlı açılan iyon kanallarıdır ve membran potansiyelini doğrudan değiştirebilir.", detail: "Hızlı olmaları her zaman uyarıcı oldukları anlamına gelmez; etki kanalın iyon seçiciliğine ve elektrokimyasal koşullara bağlıdır.", sourceIds: [SOURCE.physiology], passageIds: ["book.passage:book.physiology-uw-2023:0155:008"], evidenceLevel: "strong", ageScope: "all_ages", claimType: "definition", dnaRelation: "none" }),
  C({ id: "claim.neuro.receptor.metabotropic", topicId: "neuro.synaptic_receptors", text: "Metabotropik reseptörler G-protein bağlantılı reseptörlerdir ve ikinci haberci sinyallemesini başlatır.", detail: "İyonotropik reseptörlerle aynı değildir; etkileri hücre içi sinyal yolları üzerinden gelişir.", sourceIds: [SOURCE.physiology], passageIds: ["book.passage:book.physiology-uw-2023:0155:009"], evidenceLevel: "strong", ageScope: "all_ages", claimType: "definition", dnaRelation: "none" }),
  C({ id: "claim.neuro.synaptic_potential.epsp_ipsp", topicId: "neuro.synaptic_potentials", text: "Merkezi sinir sisteminde postsinaptik potansiyeller depolarizan EPSP veya hiperpolarizan IPSP biçiminde olabilir.", detail: "EPSP ve IPSP terimleri tek başına davranış, duygu ya da klinik durum etiketi değildir; hücresel elektriksel etkileri betimler.", sourceIds: [SOURCE.physiology], passageIds: ["book.passage:book.physiology-uw-2023:0163:006"], evidenceLevel: "strong", ageScope: "all_ages", claimType: "definition", dnaRelation: "none" }),
  C({ id: "claim.neuro.synaptic_potential.summation", topicId: "neuro.synaptic_potentials", text: "Tek bir uyarıcı sinaptik girdinin genliği çoğu zaman eşiğe ulaşmadığı için birden çok uyarıcı girdinin toplanması gerekebilir.", detail: "Sinaptik bütünleştirme, nöronun çoklu girdileri birlikte işlemesinin temel örneklerinden biridir; psikolojik bir karar modeli değildir.", sourceIds: [SOURCE.physiology], passageIds: ["book.passage:book.physiology-uw-2023:0174:004"], evidenceLevel: "strong", ageScope: "all_ages", claimType: "mechanism", dnaRelation: "none" }),

  C({ id: "claim.sleep.scn.animal_evidence", topicId: "sleep.scn", text: "Hayvan çalışmalarında suprakiazmatik çekirdeğin çıkarılması sirkadiyen ritmikliğin kaybolmasıyla ilişkilendirilmiştir.", detail: "Bu deneysel kanıt SCN'nin sirkadiyen zamanlamadaki merkezi rolünü destekler; davranıştan bir insanın SCN işlevi çıkarılamaz.", sourceIds: [SOURCE.sleep], passageIds: ["book.passage:book.science-of-sleep:0062:017"], evidenceLevel: "moderate", ageScope: "mixed", claimType: "mechanism", dnaRelation: "none" }),
  C({ id: "claim.sleep.scn.light_melatonin", topicId: "sleep.scn", text: "Gözlerden gelen ışık-karanlık bilgisi SCN'yi etkiler; SCN de pineal bezin melatonin salımının zamanlanmasına katılır.", detail: "Bu genel yolak, yatış saatinden veya davranıştan kişisel melatonin düzeyi ya da SCN işlevi hesaplanabileceği anlamına gelmez.", sourceIds: [SOURCE.sleep], passageIds: ["book.passage:book.science-of-sleep:0045:008"], evidenceLevel: "moderate", ageScope: "mixed", claimType: "mechanism", dnaRelation: "none" }),
  C({ id: "claim.sleep.pressure.time_awake", topicId: "sleep.sleep_pressure", text: "Uyku basıncı, uyanık kalınan süre uzadıkça artan uyuma eğilimini anlatır.", detail: "Uyku basıncı sirkadiyen zamanlamayla etkileşir; yorgunluk gözlemi tek başına bu sürecin doğrudan ölçümü değildir.", sourceIds: [SOURCE.sleep], passageIds: ["book.passage:book.science-of-sleep:0060:001"], evidenceLevel: "moderate", ageScope: "mixed", claimType: "definition", dnaRelation: "theory_only" }),
  C({ id: "claim.sleep.pressure.adenosine_intro", topicId: "sleep.sleep_pressure", text: "Giriş düzeyi uyku fizyolojisinde adenozin birikimi ve uyku sırasında azalması, homeostatik uyku basıncını açıklayan süreçlerden biri olarak ele alınır.", detail: "Bu açıklama kişisel adenozin düzeyinin davranıştan ölçüldüğü veya tek başına uyku sorununu açıkladığı anlamına gelmez.", sourceIds: [SOURCE.sleep], passageIds: ["book.passage:book.science-of-sleep:0060:006"], evidenceLevel: "limited", ageScope: "mixed", claimType: "mechanism", dnaRelation: "none" }),
  C({ id: "claim.sleep.zeitgeber.definition", topicId: "sleep.zeitgeber", text: "Zeitgeber, iç biyolojik saatin çevresel zamana ayarlanmasına yardım eden zaman ipucudur.", detail: "Işık başlıca örnektir; sosyal düzen ve başka çevresel ipuçları da bağlama göre zamanlayıcı rol taşıyabilir.", sourceIds: [SOURCE.sleep], passageIds: ["book.passage:book.science-of-sleep:0062:011"], evidenceLevel: "moderate", ageScope: "mixed", claimType: "definition", dnaRelation: "theory_only" }),
  C({ id: "claim.sleep.zeitgeber.endogenous_clock", topicId: "sleep.zeitgeber", text: "Çevresel zaman ipuçları azaldığında da içsel saat sinyali sürer; bu nedenle sirkadiyen saat yalnız dış rutinin ürünü değildir.", detail: "Dış ipuçlarından bağımsız sürme, çevrenin önemsiz olduğu anlamına gelmez; zeitgeberler saatin çevreyle hizalanmasına yardım eder.", sourceIds: [SOURCE.sleep], passageIds: ["book.passage:book.science-of-sleep:0062:016"], evidenceLevel: "moderate", ageScope: "mixed", claimType: "misconception_correction", dnaRelation: "none" }),
  C({ id: "claim.sleep.psg.components", topicId: "sleep.psg", text: "Polisomnogramın temel bileşenleri elektroensefalogram, elektrookülogram ve elektromiyogram kayıtlarını içerir.", detail: "Bu sinyaller sırasıyla beyin kaynaklı kafa derisi alanlarını, göz hareketlerini ve kas aktivitesini örnekler; tek bir sinyal bütün uyku değerlendirmesi değildir.", sourceIds: [SOURCE.sleep], passageIds: ["book.passage:book.science-of-sleep:0049:003"], evidenceLevel: "moderate", ageScope: "mixed", claimType: "definition", dnaRelation: "none" }),
  C({ id: "claim.sleep.psg.eeg_scalp", topicId: "sleep.psg", text: "Uyku EEG'si, kafa derisine yerleştirilen elektrotlarla kafatası ve dokular üzerinden ulaşan elektriksel alanları kaydeder.", detail: "Bu kayıt tek bir nöronun doğrudan ölçümü veya belirli bir psikolojik durumun özgül göstergesi değildir.", sourceIds: [SOURCE.sleep], passageIds: ["book.passage:book.science-of-sleep:0049:004"], evidenceLevel: "moderate", ageScope: "mixed", claimType: "measurement_boundary", dnaRelation: "none" }),
  C({ id: "claim.sleep.psg.actigraphy_validation", topicId: "sleep.psg", text: "Aktigrafi yöntemleri polisomnografi ölçümleriyle karşılaştırılarak doğrulanabilir; iki yöntem yine de aynı veriyi üretmez.", detail: "Aktigrafi temelde hareketten uyku-uyanıklık tahmini yapar, polisomnografi ise birden çok fizyolojik sinyal kullanır.", sourceIds: [SOURCE.sleep], passageIds: ["book.passage:book.science-of-sleep:0057:012"], evidenceLevel: "moderate", ageScope: "mixed", claimType: "measurement_boundary", dnaRelation: "none" }),
  C({ id: "claim.sleep.stages.distinguishable", topicId: "sleep.sleep_stages", text: "Uyku, ayırt edici özellikleri olan NREM ve REM evreleri halinde sınıflandırılır.", detail: "Evre adları ve puanlama kuralları güncel sınıflandırma standardına göre kullanılmalıdır; giriş kitabındaki tarihsel evre sayısı evrensel sabit kabul edilmez.", sourceIds: [SOURCE.sleep], passageIds: ["book.passage:book.science-of-sleep:0054:001"], evidenceLevel: "moderate", ageScope: "mixed", claimType: "definition", dnaRelation: "none" }),
  C({ id: "claim.sleep.stages.n2_markers", topicId: "sleep.sleep_stages", text: "NREM 2 uykusunda uyku iğcikleri ve K-kompleksleri ayırt edici EEG örüntülerindendir.", detail: "Bu örüntüler eğitimli uyku evreleme bağlamında yorumlanır; tüketici cihazı etiketiyle birebir aynı şey değildir.", sourceIds: [SOURCE.sleep], passageIds: ["book.passage:book.science-of-sleep:0055:015"], evidenceLevel: "moderate", ageScope: "mixed", claimType: "definition", dnaRelation: "none" }),
  C({ id: "claim.sleep.rem.features", topicId: "sleep.rem", text: "REM uykusu canlı ve duygusal rüyalarla ve iskelet kaslarında belirgin atoniyle ilişkilidir.", detail: "Bu genel evre özellikleri, tek bir gece gözleminden rüya içeriği, duygusal durum veya uyku bozukluğu çıkarılabileceği anlamına gelmez.", sourceIds: [SOURCE.sleep], passageIds: ["book.passage:book.science-of-sleep:0054:008"], evidenceLevel: "moderate", ageScope: "mixed", claimType: "association", dnaRelation: "none" }),

  C({ id: "claim.ans.relay.two_neuron", topicId: "ans.autonomic_relay", text: "Sempatik ve parasempatik periferik çıkışın temel örgütlenmesinde preganglionik ve ardından postganglionik nörondan oluşan iki nöronlu bir röle bulunur.", detail: "Bu genel anatomi, bütün otonom kontrolün yalnız iki nörondan ibaret olduğu anlamına gelmez; merkezi ağlar ve organ geri bildirimi de sürece katılır.", sourceIds: [SOURCE.physiology], passageIds: ["book.passage:book.physiology-uw-2023:0213:006"], evidenceLevel: "strong", ageScope: "all_ages", claimType: "definition", dnaRelation: "none" }),
  C({ id: "claim.ans.relay.preganglionic_ach", topicId: "ans.autonomic_relay", text: "Otonom ganglionlarda preganglionik lifler postganglionik nöronlara asetilkolin salar.", detail: "Bu ifade ganglion düzeyindeki ortak aktarımı anlatır; hedef organdaki postganglionik aktarım aynı kalıba indirgenmez.", sourceIds: [SOURCE.physiology], passageIds: ["book.passage:book.physiology-uw-2023:0209:004"], evidenceLevel: "strong", ageScope: "all_ages", claimType: "mechanism", dnaRelation: "none" }),
  C({ id: "claim.ans.relay.postganglionic_pattern", topicId: "ans.autonomic_relay", text: "Yaygın temel örüntüde sempatik postganglionik nöronlar norepinefrin, parasempatik postganglionik nöronlar asetilkolin kullanır.", detail: "Bu sadeleştirilmiş genel kalıbın hedef organa göre istisnaları vardır; kişiyi bütünüyle sempatik veya parasempatik diye sınıflandırmaz.", sourceIds: [SOURCE.physiology], passageIds: ["book.passage:book.physiology-uw-2023:0209:005"], evidenceLevel: "strong", ageScope: "all_ages", claimType: "mechanism", dnaRelation: "none" }),
  C({ id: "claim.ans.baroreflex.corrective", topicId: "ans.baroreflex", text: "Barorefleks, basınç reseptörlerinden gelen bilgiye dayanarak kan basıncındaki değişime karşı düzeltici yanıtlar oluşturan geri bildirim sürecidir.", detail: "Refleks kalp ve damar yanıtlarını koordine eder; tek davranış veya DNA puanı barorefleks ölçümü değildir.", sourceIds: [SOURCE.physiology], passageIds: ["book.passage:book.physiology-uw-2023:0211:001"], evidenceLevel: "strong", ageScope: "all_ages", claimType: "definition", dnaRelation: "none" }),
  C({ id: "claim.ans.baroreflex.response_example", topicId: "ans.baroreflex", text: "Kan basıncının düştüğü bir durumda barorefleks, damar daralması ve kalp hızında artış gibi yanıtlarla basıncı destekleyebilir.", detail: "Bu bir fizyolojik yanıt örneğidir; her kişide her koşulda aynı büyüklükte olacağı veya davranıştan görüleceği anlamına gelmez.", sourceIds: [SOURCE.physiology], passageIds: ["book.passage:book.physiology-uw-2023:0232:003"], evidenceLevel: "strong", ageScope: "all_ages", claimType: "mechanism", dnaRelation: "none" }),
  C({ id: "claim.hrv.signal.interbeat_interval", topicId: "ans.hrv_signal_quality", text: "Atımlar arası aralık, ardışık iki kalp atımındaki eşdeğer zamanlama noktaları arasında geçen süredir.", detail: "HRV ölçütleri bu aralıkların oluşturduğu zaman serisinden hesaplanır; yalnız ortalama kalp hızıyla aynı bilgi değildir.", sourceIds: [SOURCE.hrv], passageIds: ["evidence.passage:hrv-publication-guidelines-2024:f7e67ae2db:00165"], evidenceLevel: "strong", ageScope: "mixed", claimType: "definition", dnaRelation: "none" }),
  C({ id: "claim.hrv.signal.artifact_control", topicId: "ans.hrv_signal_quality", text: "HRV hesabından önce atım algılamasının doğruluğu ve hareket, teknik gürültü, anormal atım gibi artefaktlar denetlenmelidir.", detail: "Otomatik atım algılama yararlı olsa da görsel kalite kontrolünün yerini tamamen almaz; zayıf giriş sinyali güvenilir HRV üretmez.", sourceIds: [SOURCE.hrv], passageIds: ["evidence.passage:hrv-publication-guidelines-2024:f7e67ae2db:00032"], evidenceLevel: "strong", ageScope: "mixed", claimType: "measurement_boundary", dnaRelation: "none" }),
  C({ id: "claim.hrv.time_domain.sdnn_rmssd", topicId: "ans.hrv_time_domain", text: "SDNN normal atım aralıklarının standart sapmasını, RMSSD ise ardışık aralık farklarının kareleri ortalamasının karekökünü özetleyen zaman alanı ölçütleridir.", detail: "İki ölçüt aynı matematiksel özeti vermez ve tek başına psikolojik durum, tanı veya bütün otonom işlev anlamına gelmez.", sourceIds: [SOURCE.hrv], passageIds: ["evidence.passage:hrv-publication-guidelines-2024:f7e67ae2db:00088"], evidenceLevel: "strong", ageScope: "mixed", claimType: "definition", dnaRelation: "none" }),
  C({ id: "claim.hrv.time_domain.recording_duration", topicId: "ans.hrv_time_domain", text: "HRV karşılaştırmalarında analiz edilen kayıt süresinin standartlaştırılması gerekir; ölçütler kayıt uzunluğundan etkilenebilir.", detail: "Frekans alanı tahmini ayrıca incelenen salınımdan yeterli sayıda döngü içermelidir; farklı süreler doğrudan karşılaştırılmamalıdır.", sourceIds: [SOURCE.hrv], passageIds: ["evidence.passage:hrv-publication-guidelines-2024:f7e67ae2db:00099"], evidenceLevel: "strong", ageScope: "mixed", claimType: "measurement_boundary", dnaRelation: "none" }),
  C({ id: "claim.hrv.respiration.hf_rsa_distinction", topicId: "ans.hrv_respiration", text: "Yüksek frekanslı HRV ile respiratuvar sinüs aritmisi ilişkili olsa da özdeş kavramlar değildir.", detail: "Seçilen frekans bandı kişinin gerçek solunum frekansını kapsamıyorsa solunumla ilişkili değişkenliğin bir kısmı HF ölçütünün dışında kalabilir.", sourceIds: [SOURCE.hrv], passageIds: ["candidate.passage:hrv-publication-guidelines-2024:003"], evidenceLevel: "strong", ageScope: "mixed", claimType: "misconception_correction", dnaRelation: "none" }),
  C({ id: "claim.hrv.respiration.rate_depth", topicId: "ans.hrv_respiration", text: "Solunum hızı ve derinliği HRV ve RSA ölçümlerini belirgin biçimde etkileyebilir.", detail: "Koşullar arası vagal yorum yapılırken solunum davranışındaki değişim ölçülmeli veya en azından güvenilir biçimde tahmin edilmelidir.", sourceIds: [SOURCE.hrv], passageIds: ["candidate.passage:hrv-publication-guidelines-2024:007"], evidenceLevel: "strong", ageScope: "mixed", claimType: "measurement_boundary", dnaRelation: "none" }),
  C({ id: "claim.hrv.interpretation.phasic_tonic", topicId: "ans.hrv_interpretation", text: "HRV doğrudan kalbin otonom kontrolündeki atımdan atıma fazik değişimi yansıtır; bundan tonik otonom düzey çıkarmak ek varsayımlara bağlıdır.", detail: "Fazik değişimi tonik vagal veya sempatik düzeyle birebir eşitlemek, başka etkenler HRV'yi etkilediğinde yanıltıcı olabilir.", sourceIds: [SOURCE.hrv], passageIds: ["candidate.passage:hrv-publication-guidelines-2024:002"], evidenceLevel: "strong", ageScope: "mixed", claimType: "measurement_boundary", dnaRelation: "not_established" }),
  C({ id: "claim.hrv.interpretation.no_one_to_one", topicId: "ans.hrv_interpretation", text: "HRV'nin herhangi bir psikolojik durumla değişmez ve birebir eşleşmesi yoktur.", detail: "Bağlam, yöntem ve fizyolojik belirleyiciler hesaba katılmadan HRV'den stres, duygu, öz-düzenleme kapasitesi veya kişilik sonucu çıkarılamaz.", sourceIds: [SOURCE.hrv], passageIds: ["candidate.passage:hrv-publication-guidelines-2024:018"], evidenceLevel: "strong", ageScope: "mixed", claimType: "measurement_boundary", dnaRelation: "not_established" }),
])

function topic(input: Omit<DnaChatCatalogTopic, "version" | "reviewStatus">): DnaChatCatalogTopic {
  return Object.freeze({ version: DNA_CHAT_CATALOG_VERSION, reviewStatus: "source_verified_expert_pending" as const, ...input })
}

const T = (input: Omit<DnaChatCatalogTopic, "version" | "reviewStatus">) => topic(input)

export const V6_FOUNDATIONAL_EXPANSION_TOPICS: readonly DnaChatCatalogTopic[] = Object.freeze([
  T({ id: "neuro.membrane_potential", category: "central_nervous_system", title: "Membran potansiyeli", aliases: ["membrane potential", "dinlenim membran potansiyeli", "resting membrane potential", "elektrokimyasal gradyan", "sodyum potasyum pompası", "na k pump"], summary: "Membran potansiyeli, hücre zarının iki tarafı arasındaki elektriksel potansiyel farkıdır.", details: ["İyon gradyanları, seçici geçirgenlik ve aktif taşıma birlikte katkı verir.", "Tek bir pompaya veya tek bir iyon kanalına indirgenmez."], keywords: ["iyon", "kanal", "gradyan", "dinlenim", "pompa", "membran"], claimIds: ["claim.neuro.membrane.electrochemical_gradient", "claim.neuro.membrane.sodium_potassium_pump"], sourceIds: [SOURCE.physiology, SOURCE.neuroscience], evidenceLevel: "strong", ageScope: "all_ages", claimBoundary: "Davranıştan veya DNA profilinden kişisel membran potansiyeli ya da kanal işlevi çıkarılamaz." }),
  T({ id: "neuro.action_potential", category: "central_nervous_system", title: "Aksiyon potansiyeli", aliases: ["action potential", "aksiyon potansiyeli", "refrakter dönem", "hep ya da hiç", "all or none", "reseptör potansiyeli farkı"], summary: "Aksiyon potansiyeli, eşik aşıldığında akson boyunca yenilenen elektriksel sinyaldir.", details: ["Dereceli reseptör potansiyellerinden ayrılır.", "Refrakter dönem yeni ateşlemenin zamanlamasını sınırlar."], keywords: ["eşik", "akson", "refrakter", "sodyum kanalı", "dereceli"], claimIds: ["claim.neuro.action_potential.graded_distinction", "claim.neuro.action_potential.refractory_period"], sourceIds: [SOURCE.physiology, SOURCE.neuroscience], evidenceLevel: "strong", ageScope: "all_ages", claimBoundary: "Davranış veya klinik gözlem tek bir nöronun aksiyon potansiyelini ölçmez." }),
  T({ id: "neuro.myelin_conduction", category: "central_nervous_system", title: "Miyelin ve saltatorik iletim", aliases: ["myelin", "miyelin", "saltatory conduction", "saltatorik iletim", "Ranvier düğümü", "nodes of Ranvier"], summary: "Miyelinli aksonlarda sinyal Ranvier düğümlerinde yenilenerek saltatorik biçimde iletilir.", details: ["Düğümler arası yayılım pasiftir.", "Aksiyon potansiyeli düğümlerde yeniden oluşturulur."], keywords: ["miyelin", "akson", "ranvier", "iletim", "düğüm"], claimIds: ["claim.neuro.myelin.nodes", "claim.neuro.myelin.saltatory"], sourceIds: [SOURCE.neuroscience, SOURCE.physiology], evidenceLevel: "strong", ageScope: "all_ages", claimBoundary: "Davranıştan miyelin bütünlüğü, iletim hızı veya nörolojik hasar çıkarılamaz." }),
  T({ id: "neuro.chemical_synapse", category: "central_nervous_system", title: "Kimyasal sinaps", aliases: ["chemical synapse", "kimyasal sinaps", "sinaptik uç", "kalsiyum kanalı", "nörotransmiter salımı", "ekzositoz"], summary: "Kimyasal sinapsta presinaptik elektriksel sinyal, kalsiyuma bağlı nörotransmiter salımına dönüştürülür.", details: ["Voltaj kapılı kalsiyum kanalları açılır.", "Veziküller membranla birleşerek içeriklerini sinaptik aralığa bırakır."], keywords: ["sinaps", "kalsiyum", "vezikül", "nörotransmiter", "ekzositoz"], claimIds: ["claim.neuro.synapse.calcium_entry", "claim.neuro.synapse.exocytosis"], sourceIds: [SOURCE.physiology], evidenceLevel: "strong", ageScope: "all_ages", claimBoundary: "Genel sinaptik mekanizma bireysel davranışın veya bir DNA alanının doğrudan açıklaması değildir." }),
  T({ id: "neuro.synaptic_receptors", category: "central_nervous_system", title: "İyonotropik ve metabotropik reseptörler", aliases: ["ionotropic receptor", "iyonotropik reseptör", "metabotropic receptor", "metabotropik reseptör", "gpcr", "ikinci haberci"], summary: "İyonotropik ve metabotropik reseptörler sinaptik sinyali farklı hücresel yollarla işler.", details: ["İyonotropik reseptörler hızlı iyon kanallarıdır.", "Metabotropik reseptörler G-protein ve ikinci haberci yollarını kullanır."], keywords: ["reseptör", "iyonotropik", "metabotropik", "gpcr", "ikinci haberci"], claimIds: ["claim.neuro.receptor.ionotropic", "claim.neuro.receptor.metabotropic"], sourceIds: [SOURCE.physiology], evidenceLevel: "strong", ageScope: "all_ages", claimBoundary: "Reseptör sınıfı tek başına uyarılma, duygu, tanı veya kişisel ilaç yanıtı göstermez." }),
  T({ id: "neuro.synaptic_potentials", category: "central_nervous_system", title: "Postsinaptik potansiyeller ve toplama", aliases: ["postsinaptik potansiyel", "postsynaptic potential", "epsp", "ipsp", "sinaptik toplama", "synaptic summation"], summary: "EPSP ve IPSP'ler nöronun membran potansiyelini farklı yönlerde etkileyen dereceli sinaptik potansiyellerdir.", details: ["Birden çok girdi uzamsal ve zamansal olarak bütünleşebilir.", "Tek bir küçük girdi çoğu zaman ateşleme eşiğine yetmez."], keywords: ["epsp", "ipsp", "uyarıcı", "engelleyici", "toplama", "eşik"], claimIds: ["claim.neuro.synaptic_potential.epsp_ipsp", "claim.neuro.synaptic_potential.summation"], sourceIds: [SOURCE.physiology], evidenceLevel: "strong", ageScope: "all_ages", claimBoundary: "EPSP ve IPSP psikolojik iyi-kötü etiketi veya davranışın tek nedeni değildir." }),

  T({ id: "sleep.scn", category: "self_regulation", title: "Suprakiazmatik çekirdek", aliases: ["suprachiasmatic nucleus", "suprakiazmatik çekirdek", "scn görevi", "scn nedir", "sirkadiyen pacemaker"], summary: "Suprakiazmatik çekirdek, sirkadiyen zamanlamanın merkezi sinir sistemi düğümlerinden biridir.", details: ["Işık bilgisiyle çevresel zamana hizalanır.", "Hayvan lezyon çalışmaları ritim üretimindeki rolünü destekler."], keywords: ["scn", "ışık", "sirkadiyen", "melatonin", "hayvan çalışması"], claimIds: ["claim.sleep.scn.animal_evidence", "claim.sleep.scn.light_melatonin"], sourceIds: [SOURCE.sleep], evidenceLevel: "moderate", ageScope: "mixed", claimBoundary: "Yatış saati, davranış veya DNA profili kişisel SCN işlevini ya da melatonin düzeyini ölçmez." }),
  T({ id: "sleep.sleep_pressure", category: "self_regulation", title: "Homeostatik uyku basıncı", aliases: ["sleep pressure", "uyku basıncı", "uyku baskısı", "process s", "adenozin ve uyku", "ne kadar uyanık kalınca uyku"], summary: "Homeostatik uyku basıncı, uyanıklık süresiyle artan uyuma eğilimini betimler.", details: ["Sirkadiyen zamanlamayla etkileşir.", "Adenozin giriş düzeyi açıklamalarda bu süreçle ilişkilendirilir."], keywords: ["uyku basıncı", "uyanıklık", "adenozin", "homeostatik", "process s"], claimIds: ["claim.sleep.pressure.time_awake", "claim.sleep.pressure.adenosine_intro"], sourceIds: [SOURCE.sleep], evidenceLevel: "moderate", ageScope: "mixed", claimBoundary: "Yorgunluk davranışı kişisel adenozin düzeyi, uyku basıncı değeri veya uyku bozukluğu ölçümü değildir." }),
  T({ id: "sleep.zeitgeber", category: "self_regulation", title: "Zeitgeber", aliases: ["zeitgeber", "zaman verici", "time giver", "sirkadiyen zaman ipucu", "çevresel zamanlayıcı"], summary: "Zeitgeber, iç biyolojik saatin çevresel zamana hizalanmasına yardım eden ipucudur.", details: ["Işık başlıca zamanlayıcılardandır.", "İç saat dış ipucu olmadığında da kendi ritmini sürdürebilir."], keywords: ["ışık", "zamanlayıcı", "çevre", "sirkadiyen", "hizalanma"], claimIds: ["claim.sleep.zeitgeber.definition", "claim.sleep.zeitgeber.endogenous_clock"], sourceIds: [SOURCE.sleep], evidenceLevel: "moderate", ageScope: "mixed", claimBoundary: "Günlük rutin kişisel sirkadiyen fazın veya biyolojik saatin doğrudan ölçümü değildir." }),
  T({ id: "sleep.psg", category: "self_regulation", title: "Polisomnografi ve uyku sinyalleri", aliases: ["polysomnography", "polisomnografi", "psg bileşenleri", "eeg eog emg", "uyku eeg", "aktigrafi ve psg farkı"], summary: "Polisomnografi uyku evrelemesi ve ilgili fizyolojik olaylar için birden çok sinyali birlikte kaydeder.", details: ["Temel bileşenler EEG, EOG ve EMG'yi içerir.", "Aktigrafiyle aynı ölçüm değildir."], keywords: ["psg", "eeg", "eog", "emg", "aktigrafi", "uyku ölçümü"], claimIds: ["claim.sleep.psg.components", "claim.sleep.psg.eeg_scalp", "claim.sleep.psg.actigraphy_validation"], sourceIds: [SOURCE.sleep], evidenceLevel: "moderate", ageScope: "mixed", claimBoundary: "Tek sinyal, tüketici cihazı veya DNA profili polisomnografi ya da klinik uyku değerlendirmesi yerine geçmez." }),
  T({ id: "sleep.sleep_stages", category: "self_regulation", title: "Uyku evreleri", aliases: ["sleep stages", "uyku evreleri", "nrem evreleri", "nrem 2", "n2 uykusu", "uyku iğciği", "k kompleksi"], summary: "Uyku, güncel evreleme kurallarıyla NREM ve REM evrelerine ayrılır.", details: ["Evreler ayırt edici fizyolojik örüntüler taşır.", "N2'de uyku iğcikleri ve K-kompleksleri görülür."], keywords: ["nrem", "rem", "n2", "uyku iğciği", "k kompleksi", "evre"], claimIds: ["claim.sleep.stages.distinguishable", "claim.sleep.stages.n2_markers"], sourceIds: [SOURCE.sleep], evidenceLevel: "moderate", ageScope: "mixed", claimBoundary: "Davranış, akıllı saat etiketi veya tek bir gözlem klinik uyku evrelemesi değildir." }),
  T({ id: "sleep.rem", category: "self_regulation", title: "REM uykusu", aliases: ["rem sleep", "rem uykusu", "hızlı göz hareketi uykusu", "rem atonisi", "rem rüyaları"], summary: "REM, hızlı göz hareketleri, canlı rüyalar ve belirgin iskelet kası atonisiyle ilişkilendirilen uyku evresidir.", details: ["Bir gecenin normal uyku döngüsünde NREM ile dönüşümlü görülür.", "Evre özelliği tek başına klinik tanı değildir."], keywords: ["rem", "rüya", "atoni", "hızlı göz hareketi", "uyku"], claimIds: ["claim.sleep.rem.features"], sourceIds: [SOURCE.sleep], evidenceLevel: "moderate", ageScope: "mixed", claimBoundary: "REM özelliğinden tek başına duygu, travma, rüya içeriği veya uyku bozukluğu çıkarılamaz." }),

  T({ id: "ans.autonomic_relay", category: "autonomic_nervous_system", title: "Otonom ganglion ve iki nöronlu yol", aliases: ["autonomic ganglion", "otonom ganglion", "preganglionik", "postganglionik", "two neuron relay", "asetilkolin norepinefrin"], summary: "Periferik otonom çıkış, genel olarak preganglionik ve postganglionik nöronlardan oluşan iki basamaklı bir yol kullanır.", details: ["Ganglionda preganglionik aktarım asetilkolinerjiktir.", "Hedef organdaki aktarım dal ve organa göre değişir."], keywords: ["ganglion", "preganglionik", "postganglionik", "asetilkolin", "norepinefrin"], claimIds: ["claim.ans.relay.two_neuron", "claim.ans.relay.preganglionic_ach", "claim.ans.relay.postganglionic_pattern"], sourceIds: [SOURCE.physiology], evidenceLevel: "strong", ageScope: "all_ages", claimBoundary: "Bu genel yolak kişiyi sempatik veya parasempatik tip olarak sınıflandırmaz ve davranıştan ölçülmez." }),
  T({ id: "ans.baroreflex", category: "autonomic_nervous_system", title: "Barorefleks", aliases: ["baroreflex", "barorefleks", "baroreceptor reflex", "basınç refleksi", "kan basıncı geri bildirimi"], summary: "Barorefleks, kan basıncındaki kısa süreli değişimlere karşı kalp ve damar yanıtlarını ayarlayan geri bildirim sürecidir.", details: ["Basınç reseptörü bilgisi düzeltici yanıtı başlatır.", "Kalp hızı ve damar tonusu yanıtın parçaları olabilir."], keywords: ["baroreseptör", "kan basıncı", "kalp hızı", "damar", "refleks"], claimIds: ["claim.ans.baroreflex.corrective", "claim.ans.baroreflex.response_example"], sourceIds: [SOURCE.physiology], evidenceLevel: "strong", ageScope: "all_ages", claimBoundary: "Davranış, HRV veya DNA puanı tek başına barorefleks duyarlılığı ölçümü değildir." }),
  T({ id: "ans.hrv_signal_quality", category: "autonomic_nervous_system", title: "HRV sinyal kalitesi", aliases: ["hrv signal quality", "hrv sinyal kalitesi", "atımlar arası aralık", "interbeat interval", "ibi", "hrv artefakt", "ectopic beat"], summary: "HRV'nin güvenilirliği, atımlar arası aralık serisinin doğru oluşturulmasına ve artefakt kontrolüne bağlıdır.", details: ["Atım algılama hataları sonucu bozabilir.", "Hareket, teknik gürültü ve anormal atımlar ele alınmalıdır."], keywords: ["ibi", "artefakt", "ecg", "ppg", "atım algılama", "kalite"], claimIds: ["claim.hrv.signal.interbeat_interval", "claim.hrv.signal.artifact_control"], sourceIds: [SOURCE.hrv], evidenceLevel: "strong", ageScope: "mixed", claimBoundary: "Kalitesiz sinyalden hesaplanan değer psikolojik veya klinik yorum için güvenilir kabul edilemez." }),
  T({ id: "ans.hrv_time_domain", category: "autonomic_nervous_system", title: "HRV zaman alanı ölçütleri", aliases: ["hrv time domain", "zaman alanı hrv", "sdnn", "rmssd", "kayıt süresi hrv", "hrv epoch length"], summary: "SDNN ve RMSSD, atımlar arası aralık değişkenliğini farklı matematiksel biçimlerde özetleyen zaman alanı ölçütleridir.", details: ["Ölçütler aynı değildir.", "Kayıt süresi karşılaştırmalarda standartlaştırılmalıdır."], keywords: ["sdnn", "rmssd", "zaman alanı", "kayıt süresi", "epoch"], claimIds: ["claim.hrv.time_domain.sdnn_rmssd", "claim.hrv.time_domain.recording_duration"], sourceIds: [SOURCE.hrv], evidenceLevel: "strong", ageScope: "mixed", claimBoundary: "Tek HRV ölçütü bütün otonom işlevi, stresi, öz-düzenlemeyi veya tanıyı göstermez." }),
  T({ id: "ans.hrv_respiration", category: "autonomic_nervous_system", title: "HRV ve solunum", aliases: ["hrv respiration", "hrv ve solunum", "rsa", "respiratory sinus arrhythmia", "hf hrv", "solunum hızı hrv"], summary: "Solunum hızı ve derinliği özellikle solunumla ilişkili HRV ölçümlerinin yorumunu etkiler.", details: ["HF-HRV ile RSA özdeş değildir.", "Seçilen frekans bandı gerçek solunumu kapsamayabilir."], keywords: ["solunum", "rsa", "hf hrv", "frekans bandı", "tidal volume"], claimIds: ["claim.hrv.respiration.hf_rsa_distinction", "claim.hrv.respiration.rate_depth"], sourceIds: [SOURCE.hrv], evidenceLevel: "strong", ageScope: "mixed", claimBoundary: "Solunum dikkate alınmadan HF-HRV'den kişisel vagal ton veya psikolojik durum çıkarılamaz." }),
  T({ id: "ans.hrv_interpretation", category: "autonomic_nervous_system", title: "HRV yorum sınırları", aliases: ["hrv interpretation", "hrv yorumlama", "hrv stres gösterir mi", "hrv vagal ton", "phasic tonic hrv", "hrv psikolojik durum"], summary: "HRV bağlama ve yönteme duyarlı bir fizyolojik değişkenlik ölçümüdür; psikolojik durumlarla birebir eşleşmez.", details: ["Fazik değişim ile tonik otonom düzey aynı kavram değildir.", "Yorum, kayıt koşulu ve fizyolojik belirleyicileri gerektirir."], keywords: ["yorum", "fazik", "tonik", "stres", "vagal", "bağlam"], claimIds: ["claim.hrv.interpretation.phasic_tonic", "claim.hrv.interpretation.no_one_to_one"], sourceIds: [SOURCE.hrv], evidenceLevel: "strong", ageScope: "mixed", claimBoundary: "HRV'den tek başına stres, duygu, kişilik, tanı, prognoz veya DNA alanı çıkarılamaz." }),
])

function relation(input: Omit<DnaChatCatalogRelation, "version" | "maxHops">): DnaChatCatalogRelation {
  return Object.freeze({ version: DNA_CHAT_CATALOG_VERSION, maxHops: 1 as const, ...input })
}

const R = (input: Omit<DnaChatCatalogRelation, "version" | "maxHops">) => relation(input)
const boundary = "İlişki yalnız açık tek-adımlı kaynak bağlantısıdır; davranıştan biyolojik mekanizma veya bireysel klinik sonuç çıkarmaz."

export const V6_FOUNDATIONAL_EXPANSION_RELATIONS: readonly DnaChatCatalogRelation[] = Object.freeze([
  R({ id: "relation.neuro.membrane.action-potential", fromTopicId: "neuro.membrane_potential", toTopicId: "neuro.action_potential", predicate: "supports", summary: "Membran iyon gradyanları ve geçirgenliği aksiyon potansiyelinin elektriksel zeminine katkı verir.", sourceIds: [SOURCE.physiology, SOURCE.neuroscience], evidenceLevel: "strong", ageScope: "all_ages", claimBoundary: boundary }),
  R({ id: "relation.neuro.action-potential.myelin", fromTopicId: "neuro.action_potential", toTopicId: "neuro.myelin_conduction", predicate: "conceptually_related_to", summary: "Miyelinli aksonlarda aksiyon potansiyeli Ranvier düğümlerinde yeniden oluşturulur.", sourceIds: [SOURCE.physiology, SOURCE.neuroscience], evidenceLevel: "strong", ageScope: "all_ages", claimBoundary: boundary }),
  R({ id: "relation.neuro.chemical-synapse.receptors", fromTopicId: "neuro.chemical_synapse", toTopicId: "neuro.synaptic_receptors", predicate: "includes", summary: "Salınan nörotransmiterin postsinaptik etkisi iyonotropik veya metabotropik reseptörler üzerinden gelişebilir.", sourceIds: [SOURCE.physiology], evidenceLevel: "strong", ageScope: "all_ages", claimBoundary: boundary }),
  R({ id: "relation.neuro.receptors.potentials", fromTopicId: "neuro.synaptic_receptors", toTopicId: "neuro.synaptic_potentials", predicate: "supports", summary: "Sinaptik reseptör etkinliği postsinaptik membran potansiyelini değiştirebilir.", sourceIds: [SOURCE.physiology], evidenceLevel: "strong", ageScope: "all_ages", claimBoundary: boundary }),
  R({ id: "relation.sleep.scn.circadian", fromTopicId: "sleep.scn", toTopicId: "selfreg.circadian_rhythm", predicate: "part_of", summary: "SCN, sirkadiyen zamanlama sisteminin merkezi düğümlerinden biridir.", sourceIds: [SOURCE.sleep], evidenceLevel: "moderate", ageScope: "mixed", claimBoundary: boundary }),
  R({ id: "relation.sleep.pressure.two-process", fromTopicId: "sleep.sleep_pressure", toTopicId: "selfreg.sleep_regulation", predicate: "part_of", summary: "Homeostatik uyku basıncı iki süreçli uyku modelinin süreçlerinden biridir.", sourceIds: [SOURCE.sleep], evidenceLevel: "moderate", ageScope: "mixed", claimBoundary: boundary }),
  R({ id: "relation.sleep.zeitgeber.circadian", fromTopicId: "sleep.zeitgeber", toTopicId: "selfreg.circadian_rhythm", predicate: "supports", summary: "Zeitgeberler iç saatin çevresel zamanla hizalanmasına yardım eder.", sourceIds: [SOURCE.sleep], evidenceLevel: "moderate", ageScope: "mixed", claimBoundary: boundary }),
  R({ id: "relation.sleep.psg.measurement", fromTopicId: "sleep.psg", toTopicId: "selfreg.sleep_measurement", predicate: "part_of", summary: "Polisomnografi uyku ölçüm yöntemlerinden biridir ve birden çok fizyolojik sinyal kullanır.", sourceIds: [SOURCE.sleep], evidenceLevel: "moderate", ageScope: "mixed", claimBoundary: boundary }),
  R({ id: "relation.sleep.stages.psg", fromTopicId: "sleep.sleep_stages", toTopicId: "sleep.psg", predicate: "measured_indirectly_by", summary: "Uyku evreleri EEG, EOG ve EMG örüntülerinin birlikte değerlendirilmesiyle sınıflandırılır.", sourceIds: [SOURCE.sleep], evidenceLevel: "moderate", ageScope: "mixed", claimBoundary: boundary }),
  R({ id: "relation.sleep.rem.stages", fromTopicId: "sleep.rem", toTopicId: "sleep.sleep_stages", predicate: "part_of", summary: "REM, NREM evrelerinden ayırt edilen temel uyku evrelerinden biridir.", sourceIds: [SOURCE.sleep], evidenceLevel: "moderate", ageScope: "mixed", claimBoundary: boundary }),
  R({ id: "relation.ans.relay.overview", fromTopicId: "ans.autonomic_relay", toTopicId: "ans.overview", predicate: "part_of", summary: "Preganglionik ve postganglionik yol periferik otonom çıkışın temel örgütlenmesidir.", sourceIds: [SOURCE.physiology], evidenceLevel: "strong", ageScope: "all_ages", claimBoundary: boundary }),
  R({ id: "relation.ans.baroreflex.overview", fromTopicId: "ans.baroreflex", toTopicId: "ans.overview", predicate: "part_of", summary: "Barorefleks kısa süreli kardiyovasküler otonom düzenlemenin geri bildirim örneğidir.", sourceIds: [SOURCE.physiology], evidenceLevel: "strong", ageScope: "all_ages", claimBoundary: boundary }),
  R({ id: "relation.hrv.signal-quality.hrv", fromTopicId: "ans.hrv_signal_quality", toTopicId: "ans.hrv", predicate: "supports", summary: "HRV ölçümünün güvenilirliği doğru atım serisi ve artefakt kontrolüne bağlıdır.", sourceIds: [SOURCE.hrv], evidenceLevel: "strong", ageScope: "mixed", claimBoundary: boundary }),
  R({ id: "relation.hrv.time-domain.hrv", fromTopicId: "ans.hrv_time_domain", toTopicId: "ans.hrv", predicate: "part_of", summary: "SDNN ve RMSSD HRV'nin zaman alanı ölçütleri arasındadır.", sourceIds: [SOURCE.hrv], evidenceLevel: "strong", ageScope: "mixed", claimBoundary: boundary }),
  R({ id: "relation.hrv.respiration.hrv", fromTopicId: "ans.hrv_respiration", toTopicId: "ans.hrv", predicate: "associated_with", summary: "Solunum hızı ve derinliği bazı HRV ölçümlerini belirgin biçimde etkiler.", sourceIds: [SOURCE.hrv], evidenceLevel: "strong", ageScope: "mixed", claimBoundary: boundary }),
  R({ id: "relation.hrv.interpretation.hrv", fromTopicId: "ans.hrv_interpretation", toTopicId: "ans.hrv", predicate: "conceptually_related_to", summary: "HRV yorumu ölçümün fizyolojik belirleyicileri ve bağlamıyla sınırlandırılmalıdır.", sourceIds: [SOURCE.hrv], evidenceLevel: "strong", ageScope: "mixed", claimBoundary: boundary }),
])
